### ISSUE TITLE
FreeMarker template error: Edit version history page

### ISSUE THREAD

**Issue by kbraak** [gbif/ipt#1161]
```
This bug affects any public resources already published

What steps will reproduce the problem?
1. Upgrade an IPT to v2.2
2. Open the homepage for one of the public & published resources, and try to edit the
change summary for the first version in its version history table 

What version of the provider software are you using?
v2.2.1

Please provide any additional information below.

Reproduced using http://ipt.gbif.org/resource?r=cabin

The following has evaluated to null or missing:
==> history.status  [in template "WEB-INF/pages/manage/version_history.ftl" at line
42, column 32]
```

Original issue reported on code.google.com by `kyle.braak` on 2015-05-05 14:41:38
<hr>
 * *Attachment: Screen Shot 2015-05-05 at 16.32.15.png<br>![Screen Shot 2015-05-05 at 16.32.15.png](https://storage.googleapis.com/google-code-attachments/gbif-providertoolkit/issue-1161/comment-0/Screen Shot 2015-05-05 at 16.32.15.png)*

**Comment by natyoliveira** [comment]
Hello kbrak any news about this issue? I'm facing the same problem

**Comment by kbraak** [comment]
@natyoliveira this issue has been fixed. If needed, you could apply this simple fix locally. Otherwise the fix will be included in the next release.
