### ISSUE TITLE
User context switching when concurrent administrators logged in

### ISSUE THREAD

**Issue by kbraak** [gbif/ipt#1167]
What steps will reproduce the problem?
1.  Administrator 1 logs into IPT 
2.  Second administrator logs in from a different computer
3.  Context (user name) for both users will vary between Admin 1 and Admin 2
(we haven't worked it out completely but it seems to depend on which user performed an action last, certainly an admin logging in will change the context for any other admin's when they next move between pages.)

What version of the provider software are you using? 

version 2.1.1-r4640 

What browser are you using?
Firefox 37.0.2  

Please provide any additional information below.

IPT instance installed on:
Apache Tomcat 7.00.55
JVM 1.8.0_20-b26
OS Windows Server 2012 version 6.2 (amd64)

**Comment by kbraak** [comment]
I was unable to reproduce this error using the steps you described, accessing ipt.gbif.org from two different computers as Admins through Firefox. 

The environment ipt.gbif.org runs on is a bit different though: 

IPT v2.2.1
Apache Tomcat 6.0.24
CentOS release 6.6 (Final)
java version "1.7.0_75"
OpenJDK Runtime Environment (rhel-2.5.4.0.el6_6-x86_64 u75-b13)
OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)

Please, can you try clearing your browser caches (on both computers) before trying to reproduce this error  again? Maybe it's worthwhile cleaning Tomcat's cache/work directory also while you're at it. Thanks.

**Comment by AaronWilton** [comment]
Hi Kyle
We just restarted tomcat and cleared our browser histories.  We were able to repeat it. 

For example, if first admin goes to then Manage Page, then when Admin 2 goes there the Page displays the Admin 1 as logged in, but if you force a refresh in the browser it reverts to the correct login.  We were able to repeat this several times.
cheers
Aaron

**Comment by kbraak** [comment]
Thanks Aaron,
It's good to know you have found out how to reliably reproduce the bug at least.

What is the URL of your IPT, and are you using a reverse proxy such as Apache? If it's not too much trouble, would it be possible for you to try and reproduce this using the latest IPT version 2.2.1 please? 
Kyle

**Comment by AaronWilton** [comment]
Hi Kyle
Our production instance is ipt.landcareresearch.co.nz 
Just checked with our Network admin - our access from inside the network to that server is going through proxy.  External access is not via proxy.  So we tested this behaviour when logging in from outside our network and problem behaviour was not repeated.  (Something with our proxy caching?)

We plan to update our test instance of IPT soon, so will be able to test if it also occurs on the new version (our test instance of IPT also has the same issue).
cheers
Aaron

**Comment by AaronWilton** [comment]
Hi Kyle
We have updated to version 2.2.1 which appears to have improved things.

Firstly, this only appears to effect users within our network (proxy caching).

If an Admin is logged in (from within our network), and a second user from within the network visits the server they are able to see the Admin's user name at the top.  The unauthenticated user can also visit the high level pages (home, Manage, Admin, About).  However if they try to perform an action on any of the pages (e.g., go into a resource, user settings) they are challenged for their credentials.  Also if they force a page refresh in their browser they lose the Admin context.

So perhaps not too much of an issue?
cheers
Aaron

**Comment by kbraak** [comment]
Thanks Aaron, 

I'm glad no serious security issue exists. It does expose unwanted proxy caching though as you point out. Commit [d5e114](https://github.com/gbif/ipt/commit/d25e11452543005a06cd5c9bf3908326baea83a0) should fix this, ultimately preventing stale or sensitive data from ever being cached by the browser or proxy caches. 

To confirm this fixes the problem on your side, would you be able to test this latest build please?  https://dl.dropboxusercontent.com/u/4552753/ipt-2.3-SNAPSHOT.war Thanks

**Comment by kbraak** [comment]
Aaron, if you get the chance to verify this issue is fixed, please use [IPT 2.3 RC1](https://dl.dropboxusercontent.com/u/4552753/ipt-2.3-rc1.war). Due to vacations, and further testing the release date has moved to August so you have plenty of additional time for testing. Thanks

**Comment by kbraak** [comment]
Any luck testing verifying my fix for this issue @AaronWilton? I'd like to close this issue for inclusion in the 2.3 release.

**Comment by AaronWilton** [comment]
Hi Kyle
We managed to test today!  All looks good
cheers
Aaron

**Comment by kbraak** [comment]
Glad to hear! Thanks for verifying it.
