### ISSUE TITLE
Allow IPT to be installed without an organization

### ISSUE THREAD

**Issue by timrobertson100** [gbif/ipt#1179]
The IPT should not need an organization to be installed.

Several people have come forward complaining about this, and have been using it to generate archives for exchange within networks but without any intention or need to publish to GBIF.  Most recently the iDigBio folks have raised it as confusing and a regression.

The option to use the test mode is not ideal, as it both puts "TEST MODE" on the site which is a nuisance and will not use production level standards and vocabularies.

**Comment by laurarussell** [comment]
VertNet uses the IPT this way as well for our own internal purposes when we need to break resources apart for just Verts (like Smithsonian) or to publish post-migration on resources that came from self-hosted institutions or from non-IPT generated DwCA (like OZCAM resources).  We have not upgraded yet, but we currently have 29 resources that we harvest for VertNet this way.

**Comment by debpaul** [comment]
Hi All, Tim, this also poses a problem for us at iDigBio when we want to do a workshop and give people Test Mode instances. Do we also need to "register" 30 instances of test mode versions, for a workshop?

**Comment by dshorthouse** [comment]
+1

**Comment by laurarussell** [comment]
In answer to Deb's question, the 2.2.1 in Test Mode also requires you to register the IPT.  

I was working with DataOne and Colorado State last week.  They called because they wanted to evaluate IPT and were having difficulty because they couldn't do anything without registering.  I ended up helping them to install 2.1.1 in test mode so they could evaluate the parts and I explained what features/differences are in 2.2.1.

**Comment by JoannaMcCaffrey** [comment]
This new feature in 2.2.1 is impeding our progress. Could it be assigned to someone to work on soon?

**Comment by timrobertson100** [comment]
Thanks everyone for the feedback.  @kbraak - please can you make sure the IPT does not require an organization to install in either test or production mode for the imminent 2.3 release.  
To install an IPT should not require any organization - in production or test mode.

**Comment by timrobertson100** [comment]
Looking through comms New Zealand (Land care) also have asked for this to be removed

**Comment by peterdesmet** [comment]
Once implemented, we'll have to test this for the new [DCAT feed feature](https://github.com/gbif/ipt/pull/1185). I think the code will still work fine, even without a registered organization, but the feed won't be valid anymore. Note that this is also the case if no datasets have been published yet, so this is not without precedent.

@simon-vc @amenai

**Comment by kbraak** [comment]
This issue has been fixed. Installing IPT 2.3 will no longer require any organisation - in production or test mode.

Please note that in the meantime, IPT admins can work around this requirement by registering their test IPTs against "Test Organisation # 1" with password=password. 

The reason for requiring the IPT to be installed with an organisation, was that the publishing organisation became a mandatory metadata field in IPT 2.2. In addition to being required for registration with GBIF, the publishing organisation is mandatory for minting DOIs with DataCite/EZID, and enables auto-generating a resource citation.

Anyways, this requirement will be dropped in IPT 2.3 by simply making it possible to publish a resource without any publishing organisation. Of course this means users can't register their dataset with GBIF, and a warning explaining this consequence will be shown to users. 

I should also point out, that an IPT in test mode gets registered in the GBIF Sandbox Registry (not the live GBIF Registry), allowing its registered resources to be indexed into the GBIF Sandbox/UAT Portal available online at www.gbif-uat.org. This allows trainees at workshops to experience the complete publishing lifecycle. No doubt there is a huge amount of work required to setup up a room of IPTs for a workshop, so hopefully more progress can be made on automating IPT deployments in the future. 

@peterdesmet thanks for the reminder, we will test this new functionality thoroughly after merging this pull request in.

**Comment by debpaul** [comment]
Looking forward to trying it out. Thanks @kbraak

**Comment by kbraak** [comment]
Great to hear @debpaul - I look forward to your feedback on this issue. 

Now that all work (including translations) has been completed, I'm closing the issue.

**Comment by debpaul** [comment]
@kbraak I'm going to be testing the newer RC release where the missing drop-down menus issue has been fixed.
