### ISSUE TITLE
Mapping preview shows more rows than records (see screenshot)

### ISSUE THREAD

**Issue by LarissaS** [gbif/ipt#1182]
![screenshot_ipt](https://cloud.githubusercontent.com/assets/949726/8931439/97e8c940-3536-11e5-9e8e-90356886a21a.png)

**Comment by kbraak** [comment]
Thanks for reporting this issue Larissa. I cannot reproduce it, however, and suspect it might have to do with empty lines at the bottom of your source file. Can you please check if this is the case? Feel free to email me the source file if you like at kbraak at gbif dot org

**Comment by DanBIF** [comment]
Hi, I have had the same issue with the previous version of the IPT if the sourcefile came from excel. I did not manage to identify how the error occured, only how to solve it: There where somehow hidden rows that were set by excel to be defined as rows to be imported (maybe defined by a print area set larger than the number of lines with data). I deleted apparently empty rows in excel source file and repeated the upload in IPT and the error disappeared end the corect number of rows were imported by the IPT.

**Comment by kbraak** [comment]
Thank you for the extra information DanBIF, which allowed me to reproduce this issue and make a fix for it.

The fix/commit above will ensure that the IPT skips empty lines during mapping preview and DwC-A generation. Plus, log messages alert the user how many empty lines were encountered (including their line numbers) so the user can go back and fix their data at source.
