### ISSUE TITLE
Identifiers Changed for Unregistered Datasets in IPT 2.2

### ISSUE THREAD

**Issue by godfoder** [gbif/ipt#1184]
iDigBio ran into this when consuming the RSS feeds from a recently updated IPT.

Old Format:
http://ipt.flmnh.ufl.edu:8080/ipt/resource.do?id=herbarium

New Format:
http://ipt.flmnh.ufl.edu:8080/ipt/resource?id=herbarium

That cat is kind of out of the bag here, I'm not sure if there is much point in patching this at this point. I just want to make you guys aware that people do consume those as identifiers, they are the guid value in the RSS feed when a dataset is unregistered, and that changing them is problematic.

**Comment by kbraak** [comment]
Thank you for this information and sorry for the inconvenience. You can expect the new format to remain stable now.
