### ISSUE TITLE
Building 2.3-SNAPSHOT errors out with  package com.lowagie.text does not exist

### ISSUE THREAD

**Issue by dshorthouse** [gbif/ipt#1190]
As in the subject. Either com.lowagie dependency needs to be replaced with com.itextpdf or I'm lost.

**Comment by kbraak** [comment]
Please refer to this answer posted by Tim on the IPT mailing list and let us know if it works for you:

http://lists.gbif.org/pipermail/ipt/2015-August/000623.html

**Comment by dshorthouse** [comment]
That worked. Thanks for this.

**Comment by kbraak** [comment]
Good to know, thanks!
