### ISSUE TITLE
Add a list of allowed extensions to create a new resource.

### ISSUE THREAD

**Issue by santiagomtzdelariva** [gbif/ipt#1191]
In the context:

![image](https://cloud.githubusercontent.com/assets/3853645/9597987/5b7b3b0c-5087-11e5-9308-d1581692ba24.png)

Sometimes the users try to upload files like a .xls or .mdb to create a new resource . 
This action causes that the IPT doesn't work correctly. In this moment, when someone try to upload a wrong file, the users loose the metadata information that they write in their resources. 
For This reason I think that could be a good solution, add the list of allowed extensions the IPT can use to create a new resource .

Thanks in advance.

**Comment by santiagomtzdelariva** [comment]
The same idea could be applied to add a source data file.
Maybe an easy solution could be, include a help panel with the information of the right files, a little schema of this information:
https://github.com/gbif/ipt/wiki/IPT2ManualNotes.wiki#create-a-new-resource, https://github.com/gbif/ipt/wiki/IPT2ManualNotes.wiki#source-data

**Comment by kbraak** [comment]
Thanks for opening this issue. 

The latest commit fixes the root of the problem, which is that a resource directory with invalid eml.xml file is left over when creating a new resource using an invalid imported file such as an .mdb file.  

Would you have time to help test this fix? If yes, you can download a .war file with this fix here: https://dl.dropboxusercontent.com/u/4552753/ipt-2.3-rc2.war Thanks

**Comment by santiagomtzdelariva** [comment]
Ive uploaded one resource to this new reléase and Ive obtained this
exception:

 

FreeMarker template error (HTML_DEBUG mode; use RETHROW in production!)

 

Java method "org.gbif.metadata.eml.Eml.parseLicenseUrl()" threw an exception
when invoked on org.gbif.metadata.eml.Eml object "Eml{description=[El Banco
de Germoplasma de la URJC se fundó en 2008



 

----
FTL stack trace ("~" means nesting-related):
         - Failed at: @shortLicense resource.getEml().parse...  [in template
"WEB-INF/pages/manage/overview.ftl" at line 327, column 222]
----
 
Java stack trace (for programmers):
----
freemarker.core._TemplateModelException: [... Exception message was already
printed; see it above ...]
         at
freemarker.ext.beans._MethodUtil.newInvocationTemplateModelException(_Method
Util.java:311)
         at
freemarker.ext.beans._MethodUtil.newInvocationTemplateModelException(_Method
Util.java:275)
         at
freemarker.ext.beans.SimpleMethodModel.exec(SimpleMethodModel.java:80)



Caused by: java.lang.OutOfMemoryError: PermGen space
 

In other hand, in the question that we are talking, Ive tested that and now
I can see the new message: 

 

·         Error importing file - are you sure this is a Darwin Core archive?
Try the Archive Validator http://tools.gbif.org/dwca-validator/.

 

But It would be cool that this happen also in the Source Data section. What
do you think?? I mean in this section, Its only allowed delimited files and
database connections and not excel files. We have this problem with our
users in this sections.

 

De: kbraak [mailto:notifications@github.com] 
Enviado el: martes, 01 de septiembre de 2015 13:09
Para: gbif/ipt
CC: Santiago Martinez de la Riva
Asunto: Re: [ipt] Add a list of allowed extensions to create a new resource.
(#1191)

 

Thanks for opening this issue. 

The latest commit fixes the root of the problem, which is that a resource
directory with invalid eml.xml file is left over when creating a new
resource using an invalid imported file such as an .mdb file. 

Would you have time to help test this fix? If yes, you can download a .war
file with this fix here:
https://dl.dropboxusercontent.com/u/4552753/ipt-2.3-rc2.war Thanks


Reply to this email directly or view it on GitHub
<https://github.com/gbif/ipt/issues/1191#issuecomment-136676249> .
<https://github.com/notifications/beacon/ADrNTQqlMCSB104y1u-NIxj-PokkyBgEks5
otX62gaJpZM4F1jHH.gif>

**Comment by kbraak** [comment]
I noticed your error was "Caused by: java.lang.OutOfMemoryError: PermGen space"

Could you please try and test using a smaller file, or increase the heap size of Perm space and try your test again?
