### ISSUE TITLE
Duplication of "Darwin Core Identification History" extension in Darwin Core Mappings drop-down

### ISSUE THREAD

**Issue by dshorthouse** [gbif/ipt#1195]
As in the subject line, v2.3 release.

**Comment by kbraak** [comment]
Is this a new or existing installation that was upgraded? Is it in test mode or production? 

Please go to the Core Types and Extensions page, and ensure only a single version of the Darwin Core Identification History is installed. If this was an existing installation that was upgraded to v2.3, you should have been alerted that the extension is out of date, and that a new version exists to update to.

**Comment by dshorthouse** [comment]
This is a new installation in production mode. I disabled the extension, it disappears from the drop-down as expected but when I re-enable it, two instances re-appear in the drop-down anew.

**Comment by kbraak** [comment]
Thanks. I can confirm it also happens in test mode too. 

The duplication appears confined to extensions loaded by keyword (e.g. dwc:Occurrence).

**Comment by kbraak** [comment]
Please note that 2.3.1 fixes this issue and is available for download [here](http://repository.gbif.org/content/groups/gbif/org/gbif/ipt/2.3.1/ipt-2.3.1.war).
