### ISSUE TITLE
De-emphasize upload of DwC-A as first step in creation of resource

### ISSUE THREAD

**Issue by dshorthouse** [gbif/ipt#1198]
This is a common issue in many workshops conducted. In fact, I often fall into the same trap. The file upload feature as the very first step of resource creation requires a DwC-A file, but this is not immediately apparent, especially when working too quickly without paying attention. The natural tendency is to attempt upload of a text/Excel file at this step. Although there is ample warning when one attempts to do this, it is still confusing for users new to the concept of a DwC-A file. Perhaps a collapsed fieldset for the file upload form element would be appropriate.

**Comment by atalavan** [comment]
I am also guilty of that! +1

**Comment by kbraak** [comment]
Thanks for the feedback. 

Similar feedback has also been provided in issue #1191 and issue #1133. 

Resource creation obviously needs to be made more user friendly. We'll aim to fix this in the next major version.

**Comment by DanBIF** [comment]
Tadaa, I too attempted excel/CSV as well when trying the test-version before release: didn't read the intro because my normal workflow with the IPT is with excel - so reintroducing this feature will be much appreciated.

**Comment by debpaul** [comment]
+1

Sent from my iPhone

On Sep 17, 2015, at 11:59 PM, David Shorthouse <notifications@github.com<mailto:notifications@github.com>> wrote:


This is a common issue in many workshops conducted. In fact, I often fall into the same trap. The file upload feature as the very first step of resource creation requires a DwC-A file, but this is not immediately apparent, especially when working too quickly without paying attention. The natural tendency is to attempt upload of a text/Excel file at this step. Although there is ample warning when one attempts to do this, it is still confusing for users new to the concept of a DwC-A file. Perhaps a collapsed fieldset for the file upload form element would be appropriate.

**Comment by niconoe** [comment]
In Manila for a BIFA workshop, and I can confirm this upload creates a lot of confusion around newcomers :)

So, +1 too!

Thanks
