### ISSUE TITLE
Error processing SQL result sets with null table column values

### ISSUE THREAD

**Issue by kbraak** [gbif/ipt#1205]
This error causes mapping previews and publishing to fail with an error such as:
```
Generating mapping preview failed: Error writing data file for mapping Darwin Core Occurrence in source watervogels-occurrences, line 25 
```
Affects version 2.3.1

**Note**: A temporary work around is to update your SQL query so that 'null' values aren't returned in the result set. 

In PostgreSQL for example, you could replace the null values with an empty string using COALESCE: 

SELECT COALESCE(column, '') AS column ...

**Comment by timrobertson100** [comment]
Note for this workaround to work with non String types such as numeric or boolean types, you will likely also need to CAST too.  

```
  SELECT COALESCE(CAST(decimalLatitude AS VARCHAR), '') AS decimalLatitude FROM...
```

**Comment by JoannaMcCaffrey** [comment]
Do you have a release date for 2.3.2?

**Comment by kbraak** [comment]
Dear Joanna, 2.3.2 was released on October 13th. Notice of the release was sent to the IPT mailing list: http://lists.gbif.org/pipermail/ipt/2015-October/000631.html I can see that you are signed up to the list using your flmnh.ufl.edu email address.

**Comment by JoannaMcCaffrey** [comment]
Thanks Kyle, I was confused by this page: http://www.gbif.org/ipt/releases - if only says 2.3.
