### ISSUE TITLE
Building new archive makes EML errors - missing eml.ftl

### ISSUE THREAD

**Issue by JoannaMcCaffrey** [gbif/ipt#1207]
Using IPT VERSION: IPT Version 2.3.1-rb916964
When building a new archive, we are getting an EML file error. Please advise.
---------------------------
ERROR java.io.FileNotFoundException: Template "eml.ftl" not found. The quoted name was interpreted by this template loader: ClassTemplateLoader(baseClass=org.gbif.file.FreemarkerWriter, packagePath="/templates/").
ERROR Publishing version #11.14of resource but_herbfailed:IO exception when writing eml for Resource but_herb
org.gbif.ipt.service.InvalidConfigException: IO exception when writing eml for Resource but_herb
    at org.gbif.ipt.utils.EmlUtils.writeWithLocale(EmlUtils.java:106)
    at org.gbif.ipt.service.manage.impl.ResourceManagerImpl.saveEml(ResourceManagerImpl.java:1976)
    at org.gbif.ipt.service.manage.impl.ResourceManagerImpl.updateAlternateIdentifierForIPTURLToResource(ResourceManagerImpl.java:1600)
    at org.gbif.ipt.service.manage.impl.ResourceManagerImpl.publishEml(ResourceManagerImpl.java:1639)
    at org.gbif.ipt.service.manage.impl.ResourceManagerImpl.publish(ResourceManagerImpl.java:1215)
    at org.gbif.ipt.config.PublishingMonitor$QueueMonitor.run(PublishingMonitor.java:95)
    at java.lang.Thread.run(Thread.java:745)
ERROR java.io.FileNotFoundException: Template "eml.ftl" not found. The quoted name was interpreted by this template loader: ClassTemplateLoader(baseClass=org.gbif.file.FreemarkerWriter, packagePath="/templates/").
ERROR Publishing version #7.14of resource usf_herbfailed:IO exception when writing eml for Resource usf_herb
org.gbif.ipt.service.InvalidConfigException: IO exception when writing eml for Resource usf_herb
    at org.gbif.ipt.utils.EmlUtils.writeWithLocale(EmlUtils.java:106)
    at org.gbif.ipt.service.manage.impl.ResourceManagerImpl.saveEml(ResourceManagerImpl.java:1976)
    at org.gbif.ipt.service.manage.impl.ResourceManagerImpl.updateAlternateIdentifierForIPTURLToResource(ResourceManagerImpl.java:1600)
    at org.gbif.ipt.service.manage.impl.ResourceManagerImpl.publishEml(ResourceManagerImpl.java:1639)
    at org.gbif.ipt.service.manage.impl.ResourceManagerImpl.publish(ResourceManagerImpl.java:1215)
    at org.gbif.ipt.config.PublishingMonitor$QueueMonitor.run(PublishingMonitor.java:95)
    at java.lang.Thread.run(Thread.java:745)

**Comment by godfoder** [comment]
It should be noted that this installation was upgraded from version 2.2 to 2.3 on September 21st, and the archive hasn't built successfully since September 15th. The archive was probably last configured on version 2.1 however.

**Comment by kbraak** [comment]
Thanks for reporting this issue Joanna. I see two resources in the logs: but_herb and usf_herb. What kind of resources are these? Can you successfully edit/save their metadata? 

Can you please describe the steps you took to (re)produce this error? Did you press the publish all button for example?

**Comment by JoannaMcCaffrey** [comment]
Hi Kyle - I've asked Andrea to reply if she has time. If she is not able, I'll get back to you after my next trip (beginning tomorrow), after I've tried to re-construct the path to the errors. Note: a couple of other achieves have been built since the update and they are fine.

**Comment by JoannaMcCaffrey** [comment]
It also looks like the date are out of kilter. The Friesner Herbarium's next publish date is earlier than the actual 'Last Modified' and 'Last Publication' dates. It is likely that I don't understand the sequence of the the dates.

**Comment by ammatsun** [comment]
Kyle, these resources are connecting directly to a MSSQL database, and mappings exist for both specimen occurrences and simple multimedia extension. Thus, they have been configured to be auto-published on a weekly basis, and we did not have any problems with the auto-publish until the upgrade. In the first upgrade, the auto-publishing continued to work, but I was not able to change any metadata (since IPT required the instance to be registered, and our IPT is not registered). After the latest upgrade to an IPT version that would remove this constraint, we found that the auto-publishing stopped working with the error above. I experimented changing the name of the resource and it succeeded. So, I'm able to save/edit metadata.

**Comment by kbraak** [comment]
Thanks for the additional information. 

Next, can you please try to re-publish "but_herb" by itself (not using auto-publishing) and confirm that you get the same error? Afterwards, can you locate its resource directory ($IPT data directory/resources/but_herb) and ensure the user running Tomcat has permissions to write to this directory? Easiest is probably to compare its permissions with the directory of another resource that re-publishes successfully for example.

**Comment by godfoder** [comment]
It looks like the above error messages were caused by not having restarted Tomcat after the upgrade. Now we're running into #1205, but it looks like we can workaround that until the fix is released.

**Comment by kbraak** [comment]
Thanks for reporting back.

Please note a new minor release 2.3.2 including the fix for #1205 will be made available shortly.
