### ISSUE TITLE
DCAT displays metadata from preview and not last published version

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#1209]
The DCAT feed uses updated but not yet published metadata from a resource, instead of the metadata from the last published version of a resource. These updated metadata are available as a preview to logged-in users at e.g. http://data.inbo.be/ipt/resource/preview?r=kevers-grensmaas-occurrences, but should not be available to others (until published).

E.g. I gave [this dataset](http://data.inbo.be/ipt/resource?r=kevers-grensmaas-occurrences) a new title (which is available in the preview of 9.3), but have not republished yet (version is still 9.2). This new title, as well as updates to the abstract and keywords, are already available however in [our DCAT feed](http://data.inbo.be/ipt/dcat).

It would be better if the DCAT feed only used metadata of the (latest) published version of a resource.

*Note: This only affects published datasets. Private datasets are not included in the feed.*

**Comment by peterdesmet** [comment]
Fixed = awesome. Will this be included in 2.3.2?

**Comment by kbraak** [comment]
It will be included in 2.3.2 yes. 

I'd kindly ask that you help test the 2.3.2 SNAPSHOT version now (not in production please) to ensure the DCAT feed is fixed now, and that the NULL issue #1212 is fixed. Would this be possible? Thanks

**Comment by peterdesmet** [comment]
Where can I download snapshot version? I'll try to test on Tuesday, but since I encountered these issues on our production server, I might not be able to repeat them on our QA server, where I would install the snapshot.

**Comment by kbraak** [comment]
You can download it from [here](https://dl.dropboxusercontent.com/u/4552753/ipt-2.3.2-SNAPSHOT-r6eaa448.war). Thank you very much for all your help Peter.

**Comment by peterdesmet** [comment]
Confirmed fixed in `2.3.2 SNAPSHOT`: title remains last published one.
