### ISSUE TITLE
Resource overview uses updated title, not last published title

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#1213]
I've updated the title of [one of our datasets](http://data.inbo.be/ipt/resource?r=kevers-grensmaas-occurrences), but have not republished yet.

On the resource page, the last published title is shown (as expected):

> Loopkevers Grensmaas - **Carabid** beetles near the river Meuse in Flanders, Belgium

On the [public resource overview page](http://data.inbo.be/ipt/) however, the updated title is already shown:

> Loopkevers Grensmaas - **Ground** beetles near the river Meuse in Flanders, Belgium

**Comment by peterdesmet** [comment]
Not yet fixed in `2.3.2 SNAPSHOT`.

**Comment by kbraak** [comment]
Issue verified.
