### ISSUE TITLE
DCAT feed broken

### ISSUE THREAD

**Issue by kbraak** [gbif/ipt#1217]
Affects version 2.3.2

Error appears as either a Freemarker template error as the following stacktrace: java.lang.NullPointerException
    com.google.common.base.Preconditions.checkNotNull(Preconditions.java:210)
    org.gbif.ipt.task.GenerateDCAT.createDCATDistributionInformation(GenerateDCAT.java:665)
    org.gbif.ipt.task.GenerateDCAT.createDCATFeed(GenerateDCAT.java:181)

**Comment by kbraak** [comment]
@peterdesmet to work around this issue, ensure that all public published resources have been assigned a license. That's how I got http://ipt.gbif.org/dcat to work again.

**Comment by peterdesmet** [comment]
Thanks @kbraak, the workaround worked. But just to be sure: this is a bug in the code right?

**Comment by kbraak** [comment]
Confirmed it is a bug in the code.

**Comment by kbraak** [comment]
Issue fixed. It will be included in 2.3.3 release. Closing issue.
