### ISSUE TITLE
Minor issue: Link to github IPT user manual would be nice, especially for new users of the IPT

### ISSUE THREAD

**Issue by DanBIF** [gbif/ipt#1219]
Change the old link at bottom of IPT UI (http://code.google.com/p/gbif-providertoolkit/wiki/IPT2ManualNotes) to the valid one https://github.com/gbif/ipt/wiki

**Comment by kbraak** [comment]
Fixed in following commit: https://github.com/gbif/ipt/commit/ad53401ca8d3b7cabe09cb859d442c8722c20c86 Closing issue.

**Comment by kbraak** [comment]
Duplicate of #1279
