### ISSUE TITLE
Prevent duplicate IPT registrations

### ISSUE THREAD

**Issue by kbraak** [gbif/ipt#1220]
Publishers often register an IPT, take it offline, and then register a brand new IPT. Therefore there are a lot of duplicate or dead IPT registrations in the GBIF Registry. 

Only in rare cases does an organisation need to host more than one IPT. Therefore to prevent duplicate IPT registrations, the IPT should add the following safeguards:
- Check if the hosting organisation has already registered an IPT
  - If multiple IPTs per organisation are NOT allowed, the administrator can choose to update their existing registration (using the organisation and IPT passwords for example).
  - If multiple IPTs per organisation ARE allowed, a check should ensure it has a different URL from its other IPTs 

Note: to add these safeguards requires use of the new GBIF web services (see issue #1021).

**Comment by mike-podolskiy90** [comment]
Having this may cause confusion and possible mix-ups, and cases are quite rare so it's easier just to remove dead/duplicate installation. Closing after internal discussion.
