### ISSUE TITLE
Move to Java 8

### ISSUE THREAD

**Issue by cgendreau** [gbif/ipt#1222]
Since Java 6 reached its End Of Life in February 2013 and Java 7 in April 2015 (source http://www.oracle.com/technetwork/java/eol-135779.html) the IPT should now be released as a Java 8 product.

**Comment by cgendreau** [comment]
gbif-api moved to Java 8.
Last Java 6 tag here: https://github.com/gbif/gbif-api/releases/tag/gbif-api-last-j6-release

**Comment by timrobertson100** [comment]
Fixed with 2.3.4

**Comment by mdoering** [comment]
should we not set sources to java 8 properly and use java 8 dependencies e.g. for postgresql & mysql when moving to java8? https://github.com/gbif/ipt/blob/master/pom.xml#L40

**Comment by mdoering** [comment]
updated to java8 in https://github.com/gbif/ipt/commit/5af9c655e1e7f1deab7bfc0b6170615ae1e697c4
