### ISSUE TITLE
Catch JsonSyntaxException when processing JSON from the registry

### ISSUE THREAD

**Issue by silenius** [gbif/ipt#1235]
Hello,

We upgraded our IPT to Version 2.3.2-rea67259 and since then we have a stacktrace when clicking on "Core Types and Extensions". I've put IPT in debug mode and in the logs I have:

```
WARN  02-Dec-2015 16:29:09 [org.apache.struts2.components.ServletUrlRenderer] - No configuration found for the specified action: 'publishAll.do' in namespace: ''. Form action defaulting to 'action' attribute's literal value.
WARN  02-Dec-2015 16:29:09 [org.apache.struts2.components.ServletUrlRenderer] - No configuration found for the specified action: 'publishAll.do' in namespace: ''. Form action defaulting to 'action' attribute's literal value.
DEBUG 02-Dec-2015 16:29:10 [org.gbif.utils.PreemptiveAuthenticationInterceptor] - GET /registry/extensions.json HTTP/1.1
WARN  02-Dec-2015 16:29:15 [org.apache.struts2.components.ServletUrlRenderer] - No configuration found for the specified action: 'publishAll.do' in namespace: ''. Form action defaulting to 'action' attribute's literal value.
WARN  02-Dec-2015 16:29:15 [org.apache.struts2.components.ServletUrlRenderer] - No configuration found for the specified action: 'publishAll.do' in namespace: ''. Form action defaulting to 'action' attribute's literal value.
```

Here is a screenshot:

![firefox_screenshot_2015-12-02t15-27-33 764z](https://cloud.githubusercontent.com/assets/1225348/11535023/43abedb8-9912-11e5-993a-d55b4818d16f.png)

Thanks!

**Comment by silenius** [comment]
It seems to work now..! Was it an issue with the returned JSON from GBIF servers ?

**Comment by kbraak** [comment]
Thanks for reporting this. Your guess looks right and it would be nice to handle this more gracefully in the future. I'll try to include it for 2.4.

**Comment by kbraak** [comment]
Another similar case reported by JBRJ when trying to edit an organisation

![image](https://cloud.githubusercontent.com/assets/5981100/23750264/66935538-04cc-11e7-85b1-36135dd9d65b.png)
