### ISSUE TITLE
Random refresh loses unsaved changes

### ISSUE THREAD

**Issue by vickerss-landcare** [gbif/ipt#1237]
While editing Darwin Core Mappings, the page refreshed several times without me doing anything and I lost the changes I had made since last saving.

**Comment by kbraak** [comment]
Thanks for reporting this issue. Can you please describe what browser and OS you were using, including their version numbers please? Any additional information that could help reproduce this would be greatly appreciated also. 

A quick search found Chrome users experienced random refreshes - see [here](https://productforums.google.com/forum/#!topic/chrome/zMSHB4WBaXs). They were recommended to upgrade their version of Chrome, and clear their cache to make the problem go away.

**Comment by vickerss-landcare** [comment]
Hi
I am using Chrome  version 47.02526.73, Windows 7 Enterprise service pack 1. Chrome says it is up-to-date.
I’ll try clearing the cache.

Thanks, Shirley Vickers

**Comment by kbraak** [comment]
Closing issue, as this problem was isolated to Chrome and presumably solved by upgrading the version of Chrome and clearing the cache.
