### ISSUE TITLE
Adding or deleting fields in source data affects mapping even for columns which do not change

### ISSUE THREAD

**Issue by vickerss-landcare** [gbif/ipt#1238]
It appears that mappings are stored using column positions within the source data rather than column names. (Eg when I added a column in source data then all following columns in the mapping were changed, making them incorrect). This is very annoying and I would say dangerous because someone could adjust the view in the database without realising that IPT will be affected.

**Comment by kbraak** [comment]
Thanks for reporting this issue. I agree this is dangerous. 

The IPT needs to make users aware of the consequences of changing the columns of a source that has already been mapped:
- If the number of columns changes, users should receive a warning explaining that they *have to* update its corresponding mappings.
- If the SQL statement changes but the number of columns stays the same, users should receive a warning that they *may* need to update its corresponding mappings.

**Comment by kbraak** [comment]
Now when the IPT detects the number of columns in a mapped data source has changed, the user is warned that they should update its mappings.

**Comment by kbraak** [comment]
A warning can also be added to the user manual in the following the sections: 
* https://github.com/gbif/ipt/wiki/IPT2ManualNotes.wiki#file-as-data-source
* https://github.com/gbif/ipt/wiki/IPT2ManualNotes.wiki#database-as-data-source

**Comment by kbraak** [comment]
Issue verified.

**Comment by kbraak** [comment]
Changes to user manual completed. The following sections have been updated: 
* https://github.com/gbif/ipt/wiki/IPT2ManualNotes.wiki#file-as-data-source
* https://github.com/gbif/ipt/wiki/IPT2ManualNotes.wiki#database-as-data-source
