### ISSUE TITLE
Add hover over text to DwC-A validator button

### ISSUE THREAD

**Issue by meliezer** [gbif/ipt#1247]
As per title

**Comment by kbraak** [comment]
The IPT already makes this easy for publishers - note the green checkmark next to the current published version. 
![screen shot 2015-12-16 at 13 28 43](https://cloud.githubusercontent.com/assets/5981100/11840801/fe39a0da-a3f8-11e5-9cd2-cfd42527e70e.png)

**Comment by meliezer** [comment]
I've never hovered over this icon for finding out thsi hidden feature.
At least you can add  to the html code something like 'title="Validate with GBIF Darwin Core Archive Validator"'.

**Comment by kbraak** [comment]
The screenshot below illustrates how this will look in v2.3.3:

![screen shot 2016-11-01 at 14 00 55](https://cloud.githubusercontent.com/assets/5981100/19890538/b14c0110-a03b-11e6-8208-f3e0a36a5edb.png)

**Comment by kbraak** [comment]
Issue verified.
