### ISSUE TITLE
Resource gets added to RSS on PUBLIC, not on published

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#1248]
Steps:

1. I add a new resource to our IPT
2. The to-be-published version 1.0 of the resource will be public, so I set visibility to `PUBLIC`. Since I haven't finished writing the metadata or uploading the data yet, I'm not yet publishing the dataset.
3. The status `PUBLIC` triggers the IPT to include the resource in the RSS.
4. Via IFTTT a tweet is sent with the link to the not-yet-published dataset.
5. Visitors of the link see an `Not authorized` page

Solution: Setting a dataset to `PUBLIC` should not trigger the IPT to update the RSS. Only **publishing** a resource should trigger this.

Note: the not-yet-published resource is NOT included in the DCAT feed, which is the correct behaviour.

**Comment by kbraak** [comment]
Thanks for reporting this issue Peter. It should be possible to fix in the next minor release (2.3.3).

**Comment by kbraak** [comment]
Confirmed working, closing issue.

**Comment by kbraak** [comment]
Issue verified.
