### ISSUE TITLE
Error trying to edit metadata for resource

### ISSUE THREAD

**Issue by jfong** [gbif/ipt#1250]
Clicking Metadata edit button produces following error:

java.lang.NullPointerException at
org.gbif.ipt.action.manage.MetadataAction.loadOrganisations(MetadataAction.java:877) at
org.gbif.ipt.action.manage.MetadataAction.prepare(MetadataAction.java:302) at
com.opensymphony.xwork2.interceptor.PrepareInterceptor.doIntercept(PrepareInterceptor.java:167) at
com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98) at
com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:215) at
com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:244) at
org.apache.struts2.interceptor.ServletConfigInterceptor.intercept(ServletConfigInterceptor.java:164) at
com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:215) at
com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:244) at
com.opensymphony.xwork2.interceptor.ExceptionMappingInterceptor.intercept(ExceptionMappingInterceptor.java:189) at
com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:215) at
com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:244) at
com.opensymphony.xwork2.interceptor.I18nInterceptor.intercept(I18nInterceptor.java:139) at
com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:215) at
com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:244) at
org.gbif.ipt.struts2.RedirectMessageInterceptor.doIntercept(RedirectMessageInterceptor.java:120) at
com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98) at
com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:215) at
com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:244) at
org.gbif.ipt.struts2.RequireManagerInterceptor.intercept(RequireManagerInterceptor.java:91) at
com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:215) at
com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:244) at
org.gbif.ipt.struts2.SetupAndCancelInterceptor.intercept(SetupAndCancelInterceptor.java:84) at
com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:215) at
com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:244) at
org.gbif.ipt.struts2.ResourceSessionInterceptor.intercept(ResourceSessionInterceptor.java:41) at
com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:215) at
com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:244) at
org.apache.struts2.impl.StrutsActionProxy.execute(StrutsActionProxy.java:54) at
org.apache.struts2.dispatcher.Dispatcher.serviceAction(Dispatcher.java:564) at
org.apache.struts2.dispatcher.ng.ExecuteOperations.executeAction(ExecuteOperations.java:81) at
org.apache.struts2.dispatcher.ng.filter.StrutsPrepareAndExecuteFilter.doFilter(StrutsPrepareAndExecuteFilter.java:99) at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235) at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) at
org.gbif.ipt.struts2.ResponseHeaderFilter.doFilter(ResponseHeaderFilter.java:53) at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235) at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) at
com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:66) at
org.gbif.ipt.xss.XSSFilter.doFilter(XSSFilter.java:57) at
com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163) at
com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) at
org.gbif.ipt.struts2.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:43) at
com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163) at
com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) at
com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118) at
com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113) at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235) at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) at
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233) at
org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191) at
org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127) at
org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102) at
org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109) at
org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298) at
org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:857) at
org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:588) at
org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489) at
java.lang.Thread.run(Thread.java:745)

**Comment by kbraak** [comment]
Thank you for reporting this issue Jon, 

This issue indicates your upgrade didn't proceed normally, and that you bypassed the third setup page. Maybe the IPT complained about your baseURL and didn't allow you to finish the upgrade? 

Anyways, to fix the problem just bring up the third setup page (by appending "/setup3.do" to your IPT base URL), and then press "continue". Please report back if it works. Thanks.

**Comment by jfong** [comment]
It worked! Thank you very much.

Jon
