### ISSUE TITLE
Adding Admin as Resource Manager

### ISSUE THREAD

**Issue by bbrunet** [gbif/ipt#1251]
Shouldn't you be able to add Admins as Resource Managers? 

I recently discovered that I'm unable to add Resource Managers to our IPT resources unless users specifically have Manager roles. I suppose it is easy enough just to change one's role, but if a user really should retain an Admin role then there is no way to add them as a Resource Manager. 

This issue has recently come to light since the contract of one of our prior Admins has ended, and I wanted to delete their user account. However, since the user created the Resource in question I am unable to delete their user account unless I add another Resource Manager. We only have a three Admins registered as users on our IPT so I am unable to add a second Resource Manager.

Thanks,
Bryan

**Comment by DanBIF** [comment]
Hi, I had exactly the same problem not long ago. I too think it would be great if an Admin could be added as resource manager.

**Comment by kbraak** [comment]
Thank you Bryan and Isabel for this feedback. Issue #687 will improve handling for expired user accounts and solve the problem you experienced. The plan is to add these enhancements in the next major version (2.4).
