### ISSUE TITLE
Shortname permit only ASCII characters?

### ISSUE THREAD

**Issue by dvdscripter** [gbif/ipt#1253]
When trying to use "ç" or any letter like "á" at shortname IPT return:
`Invalid name. Use at least 3 Latin characters, numbers, hyphens, or underscores with no whitespace.`
These letters are valid latin characters at UTF-8 and charset="UTF-8" is set on HTML source.

> IPT Version 2.3.1-rb916964

**Comment by kbraak** [comment]
Thanks for this feedback David. 

Indeed only English characters A-Z, numbers 0-9, hyphens (-) or underscores (_) are can be used in the resource shortname. 

We'll clear this up the confusion in the next major release (2.4) to make this clearer in the form validation, user interface, help text, and user manual. 

This will be part of the larger issue #1198 that aims to simplify resource creation.

**Comment by MattBlissett** [comment]
@mike-podolskiy90, I've changed the documentation and the UI string; if it's easy to do there could be a pattern applied to the HTML element too (i.e. `pattern="[A-Za-z0-9_-]{3,}"`).

**Comment by mike-podolskiy90** [comment]
Thank you for updating documentation @MattBlissett 
Closing this
