### ISSUE TITLE
Partial ISO 8601 dates are incorrectly flagged

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#1254]
Sometimes the day or month of an event is not known. ISO 8601 allows to write such dates with reduced precision as `YYYY-MM` or `YYYY` (see https://en.wikipedia.org/wiki/ISO_8601#Calendar_dates).

When mapping a file with such dates to an Occurrence core, Event core or Occurrence extension in the IPT however, a warning message is shown:

> eventDate is mapped to values with the wrong data type.

As this is a warning and not an error, this doesn't stop the publication of the dataset, but it would be good that the IPT recognizes these dates as valid. Curiously, ISO 8601 date ranges (even partial ones) are accepted by the IPT, such as:

```
2014-02-01/2014-02-02
2014-02/2014-03
```

_Note that date ranges cannot be processed correctly by the occurrence store for the moment: http://dev.gbif.org/issues/browse/POR-2277_
## Test file

```
id  eventDate   remark
1   2014-02-01  accepted
2   2014-02 throws warning
3   2014-02-01/2014-02-02   accepted
4   2014-02/2014-03 accepted
```

**Comment by kbraak** [comment]
Thanks for the thorough report Peter, and for highlighting that the IPT's ISO date validation should accept the YYYY-MM format. 

In the future the IPT's date validation behavior will change. As per issue #745, the IPT will allow the date format to be specified for each source. The validation would therefore use the format specified, defaulting to ISO 8601. Then during publication the IPT would convert/standardize all dates to use the ISO 8601 format.
