### ISSUE TITLE
Deleting unregistered resource says resource is registered in dialog box

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#1255]
When I want to delete an **un**registered resource, I get:

![ipt](https://cloud.githubusercontent.com/assets/600993/12320390/bced1320-baa8-11e5-93b6-495685eeffe2.png)

Seems like the dialog box doesn't make a distinction between registered and unregistered, but mentions `registered` anyway?

**Comment by kbraak** [comment]
Thanks Peter, this will be fixed in the next minor release (2.3.3).

**Comment by kbraak** [comment]
Issue verified.
