### ISSUE TITLE
Why is institutionCode no part of the Event core

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#1256]
Not sure where to ask this question exactly (GBIF issue, DwC issue, IPT issue?), but I noticed that some `record` terms of Darwin Core are not available in the Event core defined [here](http://rs.gbif.org/core/dwc_event_2015_05_29.xml) and used by the IPT. Those terms are:

1. collectionID
2. institutionCode
3. collectionCode
4. basisOfRecord

I understand why the collection/specimen related terms 1, 3 and 4 are not part of the Event core, but [institutionCode](http://rs.tdwg.org/dwc/terms/index.htm#institutionCode) is applicable for non-collection related datasets too. Besides, the corresponding term `institutionID` is part of the Event core.

Can `institutionCode` be added to the Event core?

/cc @tucotuco @mdoering @dimevil

**Comment by mdoering** [comment]
agree with you Peter, at least institutionCode and institutionID should be together. It would probably not harm to even have collectionID/Code and the other record level terms in the core. At least for GBIF it would not matter as we override any value found in the extension record (e.g. Occurrence) with values found in the core. The core basically just sets defaults that are inherited by the extension

**Comment by peterdesmet** [comment]
Ha, I would have assumed otherwise: take values from event core as default and overwrite with extension data if available. That would make sense if you add `basisOfRecord` for example.

**Comment by mdoering** [comment]
Ah, my bad. I mixed it up. We do it like you say, the defaults come from the core and the final word has the extension record

**Comment by peterdesmet** [comment]
Can you let me know when institionCode is part of the extension again?

**Comment by mdoering** [comment]
@kbraak, any reasons to not change this rather soon?

**Comment by dvdscripter** [comment]
I would like to see justification for "core" division on IPT.

**Comment by kbraak** [comment]
New version of event core including institutionCode has now been released: http://rs.gbif.org/core/dwc_event_2016_06_21.xml
