### ISSUE TITLE
EML file version #126.5 for resource orn couldn't be parsed

### ISSUE THREAD

**Issue by jfong** [gbif/ipt#1259]
Error above for all archives. Log file attached. Might it have something to do with the fact that I updated licenses recently?
[logfile.txt](https://github.com/gbif/ipt/files/95166/logfile.txt)

**Comment by kbraak** [comment]
Thanks Jon,

Please try restarting Tomcat.

If the error doesn't go away, please investigate the eml.xml file for each resource (located in $IPT_DATA_DIR/resources/shortname/eml.xml).

Specifically, check the content inside ```<intellectualRights>```. Below is an example of valid content for the CC-BY license:

```
  <intellectualRights>
    <para>This work is licensed under a <ulink url="http://creativecommons.org/licenses/by/4.0/legalcode"><citetitle>Creative Commons Attribution (CC-BY) 4.0 License</citetitle></ulink>.</para>
  </intellectualRights>

```
Next, can you please answer the following questions: 

* Is the content inside ```<intellectualRights>``` empty or invalid for any of your resources? 
* What are the exact steps you took when updating the licenses? 
* What OS version do you run? 
* What version of the IPT do you run? 
* What version of Tomcat do you run?
* What version of Java do you run?

Thanks,
Kyle

**Comment by jfong** [comment]
Hi Kyle,

Restarting Tomcat did the trick, thanks.

As for your questions:

- Is the content inside <intellectualRights> empty or invalid for any of
your resources? *No*.
- What are the exact steps you took when updating the licenses? *Used the
IPT to edit the metadata and selected the license from the drop-down box.*
- What OS version do you run? *CentOS 6.6*
- What version of the IPT do you run? *2.3.2-rea67259*
- What version of Tomcat do you run? *Apache Tomcat/6.0.24*
- What version of Java do you run? *1.7.0_79-mockbuild_2015_05_14_07_23-b00*

Thanks much,
Jon

**Comment by kbraak** [comment]
Great news! And thank you very much for this extra information, it's certainly valuable.
