### ISSUE TITLE
Occurrence_COre vs Event_COre validation

### ISSUE THREAD

**Issue by DimEvil** [gbif/ipt#1260]
This validation should be in two ways.

Validating the ID field eventID is always present in extension data file. --> but also the eventID's in the occurrence extension should always be present in the event_Core

As far as I see, this is not the case and I'm publishing Occurrences which are not linked with an event...

I don't know how GBIF will interpret this, but when downloading DwC-A from the IPT I have much more occurrences than I should have.

This would be certainly helpful when after the dataset validation some sample events had to be removed from the original data before publishing.

**Comment by kbraak** [comment]
Thank you for reporting this issue Dimitry. Issue #1246 already captures this enhancement request, due to be implemented in the next major version (2.4).
