### ISSUE TITLE
Extend and improve RSS feed

### ISSUE THREAD

**Issue by kbraak** [gbif/ipt#1261]
* Expose IPT UUID in channel. This will help differentiate between multiple registered IPTs at the same URL
* Expose feed's own address in channel. This will make the feed easier to cache, etc.
* Fix elements having email addresses. The format used is currently invalid. 
* Ensure pubDate is RFC822 compliant. For more information please refer to https://validator.w3.org/feed/docs/error/InvalidRFC2822Date.html

An example feed with all changes proposed above is attached. Please use https://validator.w3.org/feed/ to ensure feed is valid. 

[feed.xml.zip](https://github.com/gbif/ipt/files/99235/feed.xml.zip)

**Comment by peterdesmet** [comment]
Also: make sure the RSS is refreshed on every republication (e.g. by using version number). From my experience, sometimes a republication triggers an update, sometimes it does not (not tested). I think it has something to do with what items were changed, e.g. if title was updated -> triggers an update (again not tested).

**Comment by kbraak** [comment]
Further verification of fix needed using https://validator.w3.org/feed/

**Comment by kbraak** [comment]
Issue verified - feed is valid according to [W3C Feed Validation Service](https://validator.w3.org/feed/).
