### ISSUE TITLE
Outdated license information in case of "No license"

### ISSUE THREAD

**Issue by meliezer** [gbif/ipt#1262]
Hello,
metadata-basic.do, no license selected, resulted in
"This work is licensed under a Creative Commons Attribution 3.0 License (CC-BY): http://creativecommons.org/licenses/by/3.0/deed.en"
Instead of version 4.0

IPT Version 2.3.2-rea67259
--
Menashè

**Comment by kbraak** [comment]
Menashè, I'm assuming this a resource you created using an earlier version of the IPT, and that this is the rights statement assigned to it. Until a new license is selected, the former rights statement remains.

**Comment by meliezer** [comment]
Right, so it's not a default message. Good to know.
However, just as in case of no publisher, you may want tell users that an old statement is being used. I've assumed the system will use ver. 4.0 automatically, and I've discovered by pure lack the license is not updated. Anyway, it's not so important.
