### ISSUE TITLE
invalid pubDate format in IPT-generated RSS feed

### ISSUE THREAD

**Issue by danstoner** [gbif/ipt#1264]
It appears that the IPT RSS feed sometimes includes internationalized / localized version of pubDate instead of RFC-822 compliant "english" datetime.

At the time of this post...

http://ipt.jbrj.gov.br/jbrj/rss.do

fails validation due to pubDate issue.  

Instead of Mon, Tue, Wed the feed includes Seg, Ter, Qua (Portuguese). 

Validation report viewable:

https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fipt.jbrj.gov.br%2Fjbrj%2Frss.do

I tried to contact the provider to find out if they know "what they changed on the server" to introduce the invalid pubDate format and will update here if I learn anything.

**Comment by godfoder** [comment]
Workaround found via changing the request language via the IPT UI. The same parameter effects the RSS feed apparently.

http://ipt.jbrj.gov.br/jbrj/rss.do?request_locale=en

**Comment by danstoner** [comment]
The issue was noticed in IPT version 2.2.1-r5193.


I am guessing that following this FAQ:

https://github.com/gbif/ipt/wiki/FAQ.wiki#5-how-can-i-change-the-ipts-default-language

leads to "inappropriate application of locale to some fields in the RSS feed".


I notice there is an existing issue for other RSS feed improvements: #1261

**Comment by kbraak** [comment]
Thanks for reporting this issue Dan. And thanks for suggesting the workaround Alex.

I have included this improvement to the catch all issue #1261. 

I believe the hosts of http://ipt.jbrj.gov.br/jbrj set their locale locale to Portugues - see https://github.com/gbif/ipt/issues/1149#issuecomment-100218916
