### ISSUE TITLE
New line character replaced by a space not documented/reported

### ISSUE THREAD

**Issue by erudas-SiBBr** [gbif/ipt#1267]
If data is coming from a database and if a field in a record have a new line character (\r\n), that character is replaced by a space in the resulting DwC-A occurence.txt file. This change is not reported in the publication logs and it's not specifically documented.

How to reproduce this issue:
- Add sqlite support to IPT, following the instructions here: https://github.com/gbif/ipt/wiki/IPT2DatabaseConnection.wiki
- Create a resource and point the data source to [occurrence.sqlite.zip](https://github.com/gbif/ipt/files/151465/occurrence.sqlite.zip).  The field with \r\n is "locality"
- Create the mappings and the basic metadata
- Publish the resource
- The field "locality" will have the new line character replaced by an space in the resulting DwC-A occurence.txt file without reporting.

**Comment by kbraak** [comment]
The documentation has been updated to make clearer what happens to line breaking characters during publishing, see: https://github.com/gbif/ipt/wiki/IPT2ManualNotes.wiki#data-validation 

The java documentation has also been improved to make this behavior clearer: https://github.com/gbif/ipt/commit/7894bcc5858df99ee0851f41541ff7067ef48573 

Closing issue.
