### ISSUE TITLE
eventDate element format

### ISSUE THREAD

**Issue by vdean26** [gbif/ipt#1269]
Darwin Core Mapping is not working according to the date format ISO 8601:2004(E) found in the definition of the element eventDate. Data with only year and month (AAAA-MM) is not being accepted and cannot be mapped. The following message appears:

![image](https://cloud.githubusercontent.com/assets/13892476/14114193/bb7ea430-f59b-11e5-9147-75e8fadd84f1.png)

**Comment by kbraak** [comment]
Thanks for taking the time to report this issue. Please refer to issue #1254 for work on fixing this issue.

**Comment by vdean26** [comment]
Perfect! Thank you
