### ISSUE TITLE
When metadata edit occured error, after IPT upgraded from 2.1 to 2.3

### ISSUE THREAD

**Issue by kimhojin75** [gbif/ipt#1271]
Hi, Developer Team!

I have upgraded recently IPT from 2.1 to 2.3 .
And then at Admin mode,
whenever I have clicked  'metadata edit' button in "Manage Resources" tab, 
It has occurred NullPointerException error.

My site url is http://data.kbif.re.kr/ipt/

Please answer me about this error.
I need your help...:(...please...

Thanks!!

<img width="1280" alt="2016-04-12 2 49 36" src="https://cloud.githubusercontent.com/assets/4167759/14450969/e719f338-00bd-11e6-8a13-1553fbaab6bb.png">

**Comment by kbraak** [comment]
Thank you for reporting this issue Kim. Please try the solution proposed [here](https://github.com/gbif/ipt/issues/1250#issuecomment-169664487). Thanks.
