### ISSUE TITLE
Install MaterialSample GGBN core on ipt

### ISSUE THREAD

**Issue by natyoliveira** [gbif/ipt#1272]
Hi,

We are facing a issue trying to install the MaterialSample GGBN core on our JBRJ ipt.

Following the instructions:  http://wiki.ggbn.org/ggbn/DwC

It says to add the core lines on $IPT_DATA_DIR/config/ipt.properties.

We did it but the core isn't showing, can you help us?

Regards,

**Comment by kbraak** [comment]
Thank you for reporting this issue. The GGBN instructions link to an out of date set of instructions. Please follow the instructions [here](https://github.com/gbif/ipt/wiki/IPT2Core.wiki) and please be sure to restart Tomcat and install the core, as mentioned at the end.

**Comment by natyoliveira** [comment]
Hello Kyle, thank for your answer.

I did the steps, but it is still now working..

Any idea?

**Comment by kbraak** [comment]
I suspect you are trying to install a test extension in your production instance, is that true? 

For your convenience, this is the [list of extensions available in test mode](http://gbrdsdev.gbif.org/registry/extensions.json) and this is the [list of extensions available in production mode](http://gbrds.gbif.org/registry/extensions.json)

**Comment by natyoliveira** [comment]
Hi Kyle, yes I'm trying to install it in production instance. Is that
possible?


On Mon, Apr 25, 2016 at 9:25 AM, kbraak <notifications@github.com> wrote:

> I suspect you are trying to install a test extension in your production
> instance, is that true?
>
> For your convenience, this is the list of extensions available in test
> mode <http://gbrdsdev.gbif.org/registry/extensions.json> and this is the list
> of extensions available in production mode
> <http://gbrds.gbif.org/registry/extensions.json>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/gbif/ipt/issues/1272#issuecomment-214293183>
>



-- 


Natália Oliveira

**Comment by kbraak** [comment]
No sorry. As per the [documentation](https://github.com/gbif/ipt/wiki/IPT2Core.wiki#introduction), adding custom cores is for communities trying to prototype new data standards. In production mode, all core types need to be supported by GBIF.org.

**Comment by dshorthouse** [comment]
It's been nearly two years now that the MaterialSample core has been under development. Any update to when this might be available as a core in the IPT?
