### ISSUE TITLE
Link to IPT user manual in page footer

### ISSUE THREAD

**Issue by dagendresen** [gbif/ipt#1279]
The link at the bottom footer of the most recent IPT Version 2.3.2-rea67259 ([User manual](https://code.google.com/archive/p/gbif-providertoolkit/wikis/IPT2ManualNotes.wiki) v2.2) is to the now obsolete Google Code manual and not to the most recent GitHub manual ([User manual](https://github.com/gbif/ipt/wiki/IPT2ManualNotes.wiki) v2.3).

Fix: Update link for User manual in the IPT footer.

**Comment by kbraak** [comment]
Thank you for reporting this issue. It has now been fixed and including in the next release (2.3.3).
