### ISSUE TITLE
IPT rejects Bonjour/zeroconf Base URLs

### ISSUE THREAD

**Issue by niconoe** [gbif/ipt#1282]
Hi,

I was trying to install the IPT on a machine using zeroconf, but during the configuration, the base URL is rejected with the IPT. Such an address seems correct to me, and works with other web apps. The URL is:

http://raspberrypi.local:8080/ipt

Thanks!

**Comment by dshorthouse** [comment]
It's the "local" top level domain. The workaround for me is to use a registered top level domain and add an entry in /etc/hosts.

**Comment by kbraak** [comment]
Thanks @dshorthouse for providing this solution. 

Closing issue.
