### ISSUE TITLE
Address iText issue

### ISSUE THREAD

**Issue by timrobertson100** [gbif/ipt#1288]
From @helpdesk we received:

> Our maven build of your code fails, we are getting the below error.
> /src/main/java/org/gbif/ipt/task/Eml2Rtf.java:[54,24] package com.lowagie.text does not exist
>  
> Related warning before the build:
> [WARNING] While downloading com.lowagie:itext:4.2.1
> This artifact has been relocated to com.itextpdf:itextpdf:5.5.6.
> After release 2.1.7, iText moved from the MPLicense to the AGPLicense.
> The groupId changed from com.lowagie to com.itextpdf and the artifactId from itext to itextpdf.
> See http://itextpdf.com/functionalitycomparison for more information.
>  
> Currently we found a few blogs on how to build your code, we are using mvn eclipse:eclipse, also tried mvn clean install…
> Looks like there are some issues with the lowagie package, is it possible to update your code or provide us with the correct maven build parameters ?
 
While this issue remains open, as a workaround can you please add this to the `pom.xml`?  
```
    <repository>
      <id>gbif-central</id>
      <url>http://repository.gbif.org/content/repositories/central</url>
    </repository>
```

**Comment by kbraak** [comment]
Issue fixed by reverting com.lowagie:itext to v2.1.7. Unfortunately RTF writing is no longer supported in itext v5. That means itext v4 can't be used either because it has a distribution relocation to v5 in its POM.
