### ISSUE TITLE
Project data are not saved

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#1290]
Odd that I never noticed, but **project data has been removed** for all datasets where we populated this.

## Example: http://dataset.inbo.be/bird-tracking-gull-occurrences

* We definitely added project data to this dataset. We have a record of it in the [dataset metadata we maintain on GitHub](https://github.com/inbo/data-publication/blob/master/datasets/bird-tracking-gull-occurrences/metadata.md#project-data)
* All fields for project data are empty in the metadata editor
* No project information appears on the dataset page on [IPT](http://dataset.inbo.be/bird-tracking-gull-occurrences) nor [GBIF](http://www.gbif.org/dataset/83e20573-f7dd-4852-9159-21566e1e691e)

Oddly though, if I re-add project metadata in the editor (title & funding), that information is saved, but:

* Does not appear on the dataset preview page (http://data.inbo.be/ipt/resource/preview?r=bird-tracking-gull-occurrences)
* Is apparently lost on publication (i.e. all project data fields are empty again).

Does this bug only affects us? If not, since when do republication empty project information? Has project information ever appeared on GBIF?

**Comment by kbraak** [comment]
Project information does appear on the IPT and GBIF. As an example: http://cloud.gbif.org/eubon/resource?r=butterflies-monitoring-scheme-il#project, which gets displayed here: http://www.gbif.org/dataset/647ae6f8-8e26-4189-b448-02b45b7ad884#project 

Here is another example from Canadensys: http://data.canadensys.net/ipt/resource?r=vascan#project, which gets displayed here: http://www.gbif.org/dataset/3f8a1297-3259-4700-91fc-acc4170b27ce#project

I'd recommend trying to find evidence that the `<project>` section inside your published EML files was ever populated. Is there a chance that it was never entered manually into the IPT, despite being in your [metadata.md](https://github.com/inbo/data-publication/blob/master/datasets/bird-tracking-gull-occurrences/metadata.md#project-data)?

**Comment by DanBIF** [comment]
Maybe a wild shot, but I seem to remember having a similar problem and Kyle and I found out it might occur if I had not entered text in all the fields of the project data tab.

**Comment by peterdesmet** [comment]
Good to know, but according to the * indication of the fields, only title is required + the IPT does not complain if the other fields are not populated.

I'm not arguing all fields should be mandatory: in fact, I would like to have all optional, so I can populate the funding of the publication of the dataset only. Let me know if there is a better field for this.

**Comment by kbraak** [comment]
At least one project personnel is required according to the GBIF Metadata Profile, however, the metadata form wasn't enforcing this. 

Therefore if no project personnel was filled in, the IPT wouldn't populate/show project metadata. 

The above commit fixes this problem. To work around this problem until 2.3.3 is released always ensure project personnel are filled in.

**Comment by peterdesmet** [comment]
Too bad project personnel is mandatory: it's often the same people as the contributors and a lot of work to populate these unless #1166 is implemented

**Comment by kbraak** [comment]
Issue verified.
