### ISSUE TITLE
fixed values not updated when remapped to database 

### ISSUE THREAD

**Issue by abubelinha** [gbif/ipt#1296]
IPT Version 2.3.2-rea67259

In mapping.do, I mapped a certain DwC term to a fixed value:
informationWithheld = "some info restricted for endangered species"
Most of the other terms are mapped to a mysql query.

After saving the changes and going back to resource.do , the fixed value is shown when I click on the "eye" icon of the mapped data (which links to mappingPeek.do)
The other non-fixed values are taken from the database as expected.

OK. Later on, I re-mapped some concepts, and informationWithheld was not coming from a fixed value anymore. I mapped it to a field of my mysql query.

But when going back to mappingPeek.do, the preview still shows the fixed value for all the records.
I tried this many times, no way to preview the data from the database for this particular field.

I only could solve that doing it this way:

1) First I un-map the concept informationWithheld
2) Save changes and see the preview: the concept is not shown
3) Re-edit mapping and map the concept to the database
4) Save changes and see the preview: now informationWithheld shows info from the database

I don't know if this is the expected behaviour but it took me a while to figure this out.

**Comment by kbraak** [comment]
Dear @abubelinha Thank you for reporting this issue. Unfortunately I was not able to reproduce it. After mapping informationWitheld to a field in the source data, the fixed value will automatically be cleared. Then as long as you remember to save the mapping, the preview will no longer show the fixed value. 

Additionally, please remember to always recheck your source's mappings when updating its MySQL query. Thanks to the improvement made in issue https://github.com/gbif/ipt/issues/1238, v2.3.3 will  automatically warn the user to update a source's mappings each time the its number of columns changes.
