### ISSUE TITLE
Map on Geographic Coverage page doesn't work

### ISSUE THREAD

**Issue by kbraak** [gbif/ipt#1302]
The IPT uses Google Maps JavaScript API to render the map on the Geographic Coverage page. It uses a keyless request meaning it doesn't include an API key.

Unfortunately as of June 22, 2016 Google Maps JavaScript API no longer support keyless access. More information about this change can be found in [this blog post](http://googlegeodevelopers.blogspot.com.au/2016/06/building-for-scale-updates-to-google.html). 

Fortunately Google has grandfathered all previously active domains for keyless usage. This means that IPTs setup before June 22, 2016 will "continue to function both now and in the future".

This change will require the next version of the IPT to either a) use a new map vendor (e.g. Leaflet, OpenStreetMap, GBIF, etc) or b) be configured with its own API key.  

**** 

Note: On localhost domain a `NoApiKeys` warning appears but doesn't prevent the map from rendering. Otherwise a `MissingKeyMapError` appears, which does prevent the map from rendering. More information about these errors can be found [here](https://developers.google.com/maps/documentation/javascript/error-messages). The screenshots below demonstrate them:

![screen shot 2016-11-15 at 19 24 23](https://cloud.githubusercontent.com/assets/5981100/20318174/810a2502-ab69-11e6-8e4f-c30caf72fd4c.png)

![screen shot 2016-11-15 at 19 23 46](https://cloud.githubusercontent.com/assets/5981100/20318180/8448cbc4-ab69-11e6-8d04-6d1b1802f90c.png)

**Comment by peterdesmet** [comment]
I'd vote for using an open source base layer, such as OpenStreetMap or the nice terrain layer used on the new GBIF portal (http://demo.gbif.org/occurrence/1258202889), which is based on OpenStreetMap.

**Comment by kbraak** [comment]
The IPT's maps (on geographic coverage page and IPT settings page) have now been updated to use the OSM-based 'terrain' tile set from [Stamen Design](http://maps.stamen.com/), rendered using [Leaflet](http://leafletjs.com/). This tile set is available for free and unlimited use under the CC BY 3.0 license and is compatible with Leaflet. It features hill shading, natural vegetation colors, advanced labeling, etc. 

To draw the bounding box, the [leaflet-locationFilter](https://github.com/kajic/leaflet-locationfilter/) library is used. A screenshot showing how the geographic coverage map appears following the change can be found below. For those interested, it is possible to tryout the 'terrain' tile set [here](http://maps.stamen.com/#terrain). 

![screen shot 2016-12-09 at 19 38 32](https://cloud.githubusercontent.com/assets/5981100/21060374/4c6e7154-be47-11e6-92c5-1dc7379a6007.png)

**Comment by kbraak** [comment]
User manual change required in [geographic coverage section](https://github.com/gbif/ipt/wiki/IPT2ManualNotes.wiki#geographic-coverage) to reflect recent changes.

**Comment by kbraak** [comment]
Changes to user manual completed. Changes applied to the following sections:
* https://github.com/gbif/ipt/wiki/IPT2ManualNotes.wiki#geographic-coverage
* https://github.com/gbif/ipt/wiki/IPT2ManualNotes.wiki#configure-ipt-settings
