### ISSUE TITLE
Make IPT package for CentOS

### ISSUE THREAD

**Issue by kbraak** [gbif/ipt#1304]
Simplify installing and updating the IPT by making a package for the IPT and including it in the GBIF package repository for CentOS. 

To work, the GBIF package repository would first have to be added: 

`yum-config-manager --add-repo repository_url`

The IPT could be installed and started in just two commands: 

`#yum install ipt`
`#systemctl start ipt`

The package will instruct Jetty to deploy the .war file as follows:

`/usr/bin/java -jar /usr/share/java/jetty/jetty-runner.jar /usr/share/java/gbif/ipt.war`

The IPT data directory will be pre-configured to `/var/lib/ipt` and its port will be pre-configured to `8080`. Both will be possible to reconfigure though.  

Each time a new version of the IPT is released, a new corresponding IPT package will be added to the package repository. This will allow the IPT to be upgraded with a single command:

`#yum upgrade ipt`

_Additional information:_

Testing can start on the latest version of CentOS. One scenario that needs to be tested, is how to replace an existing IPT installation (i.e. how to reuse an existing IPT data directory with proper permissions).

**Comment by MattBlissett** [comment]
The first public test of this is ready:

```
yum-config-manager --add-repo http://packages.gbif.org/gbif.repo
yum install ipt
systemctl start ipt
```

Then view port 8080 in a browser.  Once installed, `man ipt` shows some information.

So far, I've tested it using our minimal CentOS 7 VM installs, and a Vagrant CentOS 7 image.
