### ISSUE TITLE
Search for data publishers listed as international organizations

### ISSUE THREAD

**Issue by siro1** [gbif/ipt#1305]
The current search for data publishers based on country of origin leaves out data publishers listed as international organizations since they are not assigned country codes. It would be very helpful to be able to filter all data publishers based in a particular country including international organizations. I understand that in computing data stats for publishing activity within countries, records are assigned based on the country where a data publisher is based. Assigning country codes to international organizations might break this formula. To avoid breaking this formula, it might be useful to have a filter for "international organizations" in addition to "country" here  http://demo.gbif.org/publisher/search
This should be able to give me all international organizations but thereafter, I still would want to filter based on the country where the international organization is based if it has a physical address.

**Comment by kbraak** [comment]
Thank you @siro1. Because this issue is related to the new portal, can you please create the issue here instead: https://github.com/gbif/portal16/ Thanks.
