### ISSUE TITLE
Registry ws call on organisation page broken when IPT served with HTTPS

### ISSUE THREAD

**Issue by kbraak** [gbif/ipt#1307]
After the user selects an organization from the drop down on the organization page, a call is made to the Registry web service requesting more information about the organization. This information is used to populate an email template for the user, should they want to send a request to the primary contact of the organization asking for the password. 

Unfortunately when the IPT is served with HTTPS, a `Blocked loading mixed content` error occurs because the call to the Registry web service is with HTTP (see screenshot below). 

![screen shot 2016-12-19 at 15 51 09](https://cloud.githubusercontent.com/assets/5981100/21318284/d4302704-c608-11e6-99d4-23931c2567c3.png)

**Comment by MattBlissett** [comment]
Is it straightforward to change to the hostname `gbrds.gbif-uat.org` while updating to use HTTPS? That would be consistent with other GBIF services, and make the configuration considerably easier (i.e. it already works).

`gbrdsdev.gbif.org` can remain as an alias indefinitely, but it will give a certificate warning if accessed using HTTPS.  The server only has the `*.gbif-uat.org` certificate.

`gbrds.gbif-dev.org` also exists, and works with HTTPS, should you find it useful for internal testing.

**Comment by kbraak** [comment]
Change https://github.com/gbif/ipt/commit/7cfea60265bb3290ddffd76c11cf5a3e586d4a9a ensures that the IPT now uses HTTPS when calling gbrds.gbif.org (production mode), gbrds.gbif-uat.org (test mode), tools.gbif.org/validurl-ws, tools.gbif.org/dwca-validator. This has been tested and confirmed working on HTTPS.
