### ISSUE TITLE
Create new IPT servers for GBIF

### ISSUE THREAD

**Issue by MattBlissett** [gbif/ipt#1310]
As mentioned in #1298, we should update the servers the IPTs are running on.

At the moment we have:
* b7g1.gbif.org, running Tomcat 6 and Java 8, hosting eubon-ipt.gbif.org, ipt.gbif.org, which are both in test mode
* uatapps-vh, running Tomcat 7 and Java 8, hosting ipt.gbif-uat.org in test mode
* cloudipt-vh, running Tomcat 7 and Java 8, hosting giasip.gbif.org, cloud.gbif.org (/eubon, /agedi, /bid) in production mode

And the new:
* devtomcat-vh, running Tomcat 7, Java 7 (oops), hosting ipt.gbif-dev.org
which I will update to Java 8 (since 7 no longer has public security updates, #1222).

I want to remove b7g1, since it is an old OS and Tomcat.  I want to replace uatapps-vh, since it hosts too many things, is a mess, and is too powerful.

**So...**

I assume devtomcat-vh / ipt.gbif-dev.org should be (or already is) the Jenkins deploy target.

I will:
-  [x] make uattomcat-vh / ipt.gbif-uat.org for testing releases
   - [x] create new VM
   - [x] switch DNS for ipt.gbif-uat.org
   - [x] remove IPT from uatapps-vh
-  [x] make prodtomcat-vh / ipt.gbif.org for people to fiddle about with in test mode.
   - [x] create new VM
   - [x] switch DNS for ipt.gbif.org
   - [x] remove IPT from b7g1
-  [x] question — is eubon-ipt.gbif.org required?
    * need to decide where it belongs.
- [x] leave cloudipt-vh as it is

**Comment by kbraak** [comment]
eubon-ipt.gbif.org is needed because it is embedded in the EU BON Portal here: http://biodiversity.eubon.eu/eubon-ipt 

How about just moving eubon-ipt.gbif.org and ipt.gbif.org to cloudipt-vh, which is already setup with a large amount of disk space? The IPT on uatapps is only needed when testing new releases.

**Comment by MattBlissett** [comment]
I've moved ipt.gbif-uat.org and ipt.gbif.org, including their data, to new servers.

I set up prodtomcat-vh (automatically), but I think I agree that that, plus cloudipt-vh, is overkill.  Tomorrow I'll move everything to a single production Tomcat server; cloudipt-vh if it's in a decent state regarding patches and custom config, including validurl-ws etc.

**Comment by kbraak** [comment]
Thanks Matt, unfortunately I'm experiencing some undesired redirects. For example, while on the basic metadata page for a given resource (e.g. http://ipt.gbif.org/manage/metadata-basic.do?r=bfast2&edit=Edit) when I click the "cancel" button I get redirected to the following page: http://ipt.gbif.org/ipt//ipt.gbif.org/manage/resource.do Can you please help fix this? Thanks.

**Comment by MattBlissett** [comment]
I've removed the change I made to the baseUrl to try and support both HTTP and HTTPS, it should be back to normal now.

Does eubon-ipt.gbif.org belong on the UAT server or the production server? I don't know how it relates to cloud.gbif.org/eubon

**Comment by kbraak** [comment]
Many thanks. 

Good question. In my opinion eubon-ipt.gbif.org belongs on the UAT server and cloud.gbif.org/eubon belongs on the production server. The former is the Test EU BON IPT used in prototyping, albeit integrated into the EU BON Portal. The latter is used to publish real datasets that came out of the EU BON project through the GBIF network.

**Comment by MattBlissett** [comment]
eubon-ipt.gbif.org is now on the UAT server.

Final state of the new Tomcat servers:

### devtomcat-vh
* ipt.gbif-dev.org

### uattomcat-vh
* ipt.gbif-uat.org
* eubon-ipt.gbif.org (aka eubon-ipt.gbif-uat.org, which you'd need to use to access over HTTPS)

### prodtomcat-vh
* ipt.gbif.org
* cloud.gbif.org ( /eubon, /agedi, /bid )
* giasip.gbif.org
* tools.gbif.org (including /ws-validurl)

Everything is ready for HTTPS, but the IPTs need their baseUrl's updating, and perhaps logo locations for resources etc. I'll leave this to you, if you wish to move them to HTTPS.

**Comment by kbraak** [comment]
All IPTs are now on HTTPS, with the exception of eubon-ipt.gbif.org because this is embedded in the EU BON Portal and will require some coordination to change. Thanks for all your assistance @MattBlissett with this reorganization and HTTPS setup.
