### ISSUE TITLE
Manage resource table broken after uploading zipped resource folder 

### ISSUE THREAD

**Issue by kbraak** [gbif/ipt#1313]
As per title. Likely result of importing without having made subsequent modifications immediately afterwards such as editing the metadata.

The following fix can be applied in the meantime, until v2.4 is released including the fix:

1. Manually add the following line to the resource.xml of the resource that was just uploaded:
`<modified>2016-12-23 10:43:51.975 UTC</modified>`
2. Restart Tomcat

![screen shot 2017-01-11 at 12 33 37](https://cloud.githubusercontent.com/assets/5981100/21847151/9b564f72-d7fa-11e6-8f8c-362585017c6d.png)

**Comment by mike-podolskiy90** [comment]
Not applicable for the datatables backend processing
