### ISSUE TITLE
Incorrect character escaping in DCAT?

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#1316]
I noticed incorrectly escaped characters in the DCAT feed: http://data.inbo.be/ipt/dcat:

```
1972â€“2004
University of LiÃ¨ge
4 x 4 kmÂ² IFBL grid cells
```

Is this just my browser or are characters not correctly escaped when generating the feed?

**Comment by MattBlissett** [comment]
The output *is* UTF-8 encoded, but the HTTP content type is `Content-Type: text;charset=ISO-8859-1`

Adding `<param name="contentCharSet">UTF-8</param>` to https://github.com/gbif/ipt/blob/master/src/main/resources/struts-portal.xml#L91 didn't help, the content type then becomes `Content-Type: text;charset=UTF-8;charset=ISO-8859-1` (!?).

CC @dagendresen.
