### ISSUE TITLE
Newline character in change summary breaks versions table

### ISSUE THREAD

**Issue by kbraak** [gbif/ipt#1320]
As per title.

Affects version 2.3.3.

![screen shot 2017-02-17 at 14 58 28](https://cloud.githubusercontent.com/assets/5981100/23068297/6a05dbf4-f523-11e6-9eff-e5d558140bf7.png)

**Comment by dgasl** [comment]
I actually realized we can put html tags (br, li) to get the same multiline effect inside version table (this is also useful for font styling, or hyperlinking to further explanations of issues and changes).

It would be great if this "html-way" of describing versions keeps also working (after your upcoming correction of the actual breakline parsing bug).

**Comment by kbraak** [comment]
Thanks @dgasl for your feedback. 

Turns out newline characters were also responsible for breaking the home page in issue https://github.com/gbif/ipt/issues/1322. I agree @simoncha that some additional work is needed to ensure these types of characters are sanitized properly before persisting. Thanks.
