### ISSUE TITLE
Add possibility to reorder items in lists (e.g. contacts, taxa, citations)

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#1325]
Issue #1324 reminds me of what I find the most frustrating missing feature in the IPT 😄 : the possibility to reorder items in lists. Currently, the order in which you add contacts, taxa or citations is also the order in which they are displayed. I like that, because it allows you to define that order yourself.

It becomes frustrating when you want to **insert something at a specific place in those lists or reorder items**. The only option you currently have is to create an empty item at the bottom and copy all information (field by field) one item down, so you can create an free slot at the place you intended.

The best way to solve this would be to allow users to grab and reorder items in the list. Note that having the option to create an empty form at a specific place would only solve the **insert** use case, not the one where you want to reorder things.

This applies to:

* **Description** (in basic metadata)
* **Contacts** (in basic metadata, 3 lists): order is important here, as it - at least for resource creators - defines the order of the authors in the citation. Note that for adding contact information, there is still room for improvement (see #1166)
* **Taxa** (in taxonomic coverage): one could opt to remove the possibility to let the user define the order here and automatically reorder on rank once you save (important to also show the new order in the metadata editor, not only on the dataset page). The user can then still create subsets by adding another taxonomic coverage list.
* **Taxonomic coverages** (in taxonomic coverage)
* **Temporal coverages** (in temporal coverage): the user defines in which order to add temporal coverages (e.g. first a general date range and then e.g. breeding seasons as [here](http://data.inbo.be/ipt/resource?r=bird-tracking-gull-occurrences#temporal)), but cannot reorder these.
* **Keyword lists** (in keywords): Keywords themselves are just comma separated and can be reorder in the field, but keyword lists cannot.
* **Associated parties** (in associated parties)
* **Step descriptions** (in sampling methods): order is definitely of importance here, but steps cannot be reordered.
* **Bibliographic citations** (in citations): one could opt to remove the possibility to let the user define the order and automatically reorder alphabetically once you save. That way it is no longer possible to highlight e.g. the data paper as the first citation, but maybe that should be a separate citation anyway.
* **Collections** (in collection data)
* **Specimen preservation methods** (in collection data)
* **Curatorial Units** (in collection data)
* **External links/Other Data Formats** (in external links)
* **Alternative identifiers** (in additional metadata)

Full list:
- [x]   Description
- [x]   Contacts
- [x]   Creators
- [x]   Metadata providers
- [x]   Taxa
- [x]   Taxonomic coverages
- [x]   Temporal coverages
- [x]   Keyword lists
- [x]   Associated parties
- [x]   Project personnel
- [x]   Step descriptions
- [x]   Bibliographic citations
- [x]   Collections
- [x]   Specimen preservation methods
- [x]   Curatorial units
- [x]   External links
- [x]   Alternative identifiers

**Comment by kbraak** [comment]
Thank you for these additional ideas related to improving the IPT's user interface and in particular its metadata editor. 

This is a good opportunity to repost the following job announcement for a Web Developer position open at the GBIF Secretariat, as advertised by @fmendezh:

> The GBIF Secretariat is currently seeking applications for a Web Developer, see complete details here: 
> 
> http://www.gbif.org/newsroom/news/web-developer-job-2017
> 
> Deadline for applications is Monday, 20 March 2017. Please be aware that the successful candidate will be locally recruited (no-relocation involved), according to the GBIF Staff Rules
> 
> Please feel free to share this position with your own networks and contacts.
> 
> Thanks, 
> 
> Federico Mendez
> 
> fmendez@gbif.org
> skype: fede.mendez
> Lead Software Developer
>

**Comment by abubelinha** [comment]
> Currently, **the order in which you add contacts**, taxa or citations is also the **order in which they are displayed**. I like that, because it allows you to define that order yourself.

@peterdesmet I guess you meant the order in which they are displayed **in GBIF portal/api**.

**In IPT**, I noticed contacts displayed in section `/resource.do?r=resourceId#anchor-contacts`
do _**not**_ match the order I added them in section `/manage/metadata-parties.do?r=resourceId`

I guess they follow some other sorting pattern but I couldn't figure it out.
Have you noticed this too? 

I suppose it is not as important as the order in GBIF portal page, but I still would like to control contacts order in IPT interface.

**Comment by peterdesmet** [comment]
Yes, order matters. The scope of this issue is that it should be easier to change that order in the basic metadata editor (e.g. dragging up/down).

**Comment by abubelinha** [comment]
Thanks @peterdesmet (I understood and opened #1874 after my comment).

As for your reordering issue, a very useful workaround is the @sylmorin-gbif approach in https://github.com/gbif/ipt/issues/1480#issuecomment-720369009 
You could manage your lists in a spreadsheet, dataframe or whatever ... and then (re)populate IPT forms (lists) from a script.

The problem with that is your script could break at anytime if forms design is modified.
That's why having an api alternative would be so convenient, specially for those providers with hundreds or thousands of datasets.

**Comment by peterdesmet** [comment]
Yeah, for some datasets I externally maintain an EML file that I upload. Still, reordering contacts with drag and drop in the interface would be useful, cf. Zenodo:

<img width="970" alt="Screenshot 2022-11-17 at 11 56 02" src="https://user-images.githubusercontent.com/600993/202428416-1c786376-a6cc-45f1-983a-d955395e58ef.png">

**Comment by mike-podolskiy90** [comment]
Thank you for the comments @peterdesmet @abubelinha 
I was recently exploring different implementations for this, but didn't manage to find a proper solution. I may find something in the future if I happen to have more time to play with this

**Comment by peterdesmet** [comment]
I'm actually curious how Zenodo does it. 😄

**Comment by abubelinha** [comment]
> I'm actually curious how Zenodo does it. 😄

As per the underlying css classes names, I guess it's a [jquery ui.sortable](https://angular-ui.github.io/ui-sortable/) implementation or something similar.
