### ISSUE TITLE
figures in metdata

### ISSUE THREAD

**Issue by DimEvil** [gbif/ipt#1326]
What would it be nice to have (or to be able to have) figures in the metadata.

**Comment by dschigel** [comment]
Like figures illustrating sampling methods? Note that licenses and rights for images are different from those for text bits @ahahn-gbif

**Comment by ahahn-gbif** [comment]
Could you be a bit more specific, @DimEvil? Figures as in numbers, or as in images? Documenting / indicating what?

**Comment by kbraak** [comment]
Closing as duplicate of reopened issue https://github.com/gbif/ipt/issues/971, which has more details and rationale behind this proposed enhancement.
