### ISSUE TITLE
Change DOI display according to new guidelines

### ISSUE THREAD

**Issue by dshorthouse** [gbif/ipt#1333]
The DOI display guidelines now urge publishers to use https and to drop the dx: https://www.crossref.org/blog/revised-crossref-doi-display-guidelines-are-now-active/

**Comment by kbraak** [comment]
Thanks @dshorthouse 

The IPT follows the DOI display guidelines in the DOI Handbook. [Section 2.5.2.2](https://www.doi.org/doi_handbook/2_Numbering.html#htmlencoding) is in line with CrossRef, stating "https is preferred over http, and that dx.doi.org, an earlier syntax, will remain fully supported but is no longer preferred". 

In case you weren't aware, several changes went into [v2.3.3](https://github.com/gbif/ipt/projects/1) and [v2.3.4](https://github.com/gbif/ipt/projects/3) to support the IPT being configured over HTTPS. We'll ensure the next version ([v.2.4](https://github.com/gbif/ipt/projects/2)) displays DOIs using HTTPS to better enable secure browsing for users.

**Comment by MattBlissett** [comment]
I'm not quite sure what the IPT showed in 2017, but I think the display is reasonable now.
