### ISSUE TITLE
How are several source files concatenated?

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#1339]
I'm trying to upload a data file that exceeds the 100MB limit, so I've split it up in different files. I was wondering though in what order these are concatenated, so I tested with smaller files.

The order in which files are uploaded doesn't seem to matter, as they are displayed in alphabetical order:

<img width="643" alt="screen shot 2017-04-26 at 10 40 37" src="https://cloud.githubusercontent.com/assets/600993/25425639/d3a2738c-2a6c-11e7-833a-13d38f5f036b.png">

The order in which files are mapped to Darwin Core does seem to matter:

<img width="629" alt="screen shot 2017-04-26 at 09 39 43" src="https://cloud.githubusercontent.com/assets/600993/25425611/bd135730-2a6c-11e7-95c5-6fa189b3d862.png">

And that order is also how they seem to be concatenated in the final data file in the DwC-A. Is that assumption correct? If so, I think it would be good to add to the manual: https://github.com/gbif/ipt/wiki/IPT2ManualNotes.wiki#file-upload

> * compressing the file (with zip or gzip)
> * loading the data into one of the many databases supported by the IPT
> * splitting the file up **(the IPT will concatenate the files in the order they are mapped upon publication)**

I think I might end up using [this approach](https://github.com/gbif/ipt/issues/1300) for my data file, but it would be good to know none the less.

**Comment by MattBlissett** [comment]
Thanks Peter -- documentation fixed.
