### ISSUE TITLE
Validation should alert in case of column names duplicates

### ISSUE THREAD

**Issue by meliezer** [gbif/ipt#1340]
Hello,
Both IPT validator and the web validator should detect as errors duplicated column names.
Such error would be rare, but it should be detected sooner or later.
--
Menashè

**Comment by kbraak** [comment]
Thanks @meliezer,

The IPT doesn't let you publish files with duplicated column names. https://github.com/gbif/gbif-data-validator serves as a replacement for the [GBIF Darwin Core validator](http://tools.gbif.org/dwca-validator) (web validator) so please feel free to submit this enhancement idea to this project.

**Comment by meliezer** [comment]
Thanks. I've used the web validator with the DwC-A where there were no duplicated column names inside occurrence.txt, however IPT Version 2.3.2-rea67259  (Yes, I should update...) has published the resource without problems/alerts even though I had eventDate column also as a last column of the csv source file. Should I submit a new issue?

**Comment by kbraak** [comment]
Please upgrade to 2.3.4 and then if the problem persists, submit a detailed issue describing how the problem can be reproduced, thanks.
