### ISSUE TITLE
IPT2ManualNotes.wiki

### ISSUE THREAD

**Issue by johntorgersen** [gbif/ipt#1341]
Hello,

None of the image links on the 

https://code.google.com/archive/p/gbif-providertoolkit/wikis/IPT2ManualNotes.wiki

page seem to be working.

Thank you.

**Comment by kbraak** [comment]
Thanks @johntorgersen,

Please note the IPT source code and wiki was migrated to GitHub a couple of years ago. You can find the latest version of the IPT User Manual here: 

https://github.com/gbif/ipt/wiki/IPT2ManualNotes.wiki

Thank you

**Comment by johntorgersen** [comment]
Hi Kyle,

https://code.google.com/archive/p/gbif-providertoolkit/wikis/IPT2ManualNotes.wiki 
is the one linked from the bottom of the ipt installation page.



Thank you for the current URL, though, as the images help a lot.

- John

**Comment by kbraak** [comment]
@johntorgersen, please install the latest version v2.3.4. 

The link in the footer was changed as of v2.3.3 (see https://github.com/gbif/ipt/issues/1279). Thanks.
