### ISSUE TITLE
Make metadata downloadable in standard bibliographic file formats

### ISSUE THREAD

**Issue by kbraak** [gbif/ipt#1342]
Make metadata downloadable in standard bibliographic file formats on the landing page of the dataset. 
As per [A Data Citation Roadmap for Scholarly Data Repositories](http://dx.doi.org/10.1101/097196), this will further improve the IPT's data citation support. Specifically, this roadmap recommends two common bibliographic formats: .bib (BibTex file format) and/or .ris (RIS file format). Examples of these file formats are provided in section 11 of the roadmap.

**Comment by MattBlissett** [comment]
This is now more relevant in the GBIF portal:

https://github.com/gbif/portal-feedback/issues/2027
https://github.com/gbif/portal-feedback/issues/33
https://github.com/gbif/portal16/issues/277
