### ISSUE TITLE
replace itext-rtf

### ISSUE THREAD

**Issue by mdoering** [gbif/ipt#1346]
itext-rtf is dead and stuck in version 2.1.7 since 2009. This brings in lots of outdated dependencies.
It should be replaced by something modern. As RTF is a text based format the simplest would be to use a freemarker template for the Eml2Rtf conversion. Freemarker supports escaping for the [RTF output format](http://freemarker.org/docs/ref_directive_outputformat.html#autoid_123).

**Comment by MattBlissett** [comment]
https://github.com/LibrePDF/OpenRTF is the successor (has the same package names) but still has a fair few dependencies.

https://xmlgraphics.apache.org/fop/dev/rtflib.html might be better, its dependencies are other bits of xmlgraphics.

Writing it by hand/Freemarker doesn't seem fun once you read about the Unicode "support": https://en.wikipedia.org/wiki/Rich_Text_Format#Character_encoding

I don't know what the RTF export is used for. OpenDocument Text format might be fine as a replacement?

**Comment by mike-podolskiy90** [comment]
I tried manually with Freemarker, it's huge pain

**Comment by mike-podolskiy90** [comment]
Let's use openRTF library
