### ISSUE TITLE
Change the order of licenses in the dropdown at basic metadata

### ISSUE THREAD

**Issue by Daniel-Mietchen** [gbif/ipt#1349]
Right now, it is listed at the end of the list, which leads to fewer people picking it.

**Comment by peterdesmet** [comment]
@Daniel-Mietchen interpreting here: the goal is to list the licenses from fewer to more conditions (as below), not to have the default value be `Public Domain (CC0 1.0)` over `No license selected`?

> No licence selected
> Public Domain (CC0 1.0)
> Creative Commons Attribution (CC-BY 4.0)
> Creative Commons Attribution Non Commercial (CC-BY-NC 4.0)

Note that I consistently put the version number _in_ the parenthesis (currently not the case in IPT).

While we're at it, should `Data Licence` be renamed to `Data License` and `No licence selected` to `No license selected`? American spelling seem to be used for Organization, so good to be consistent and use American spelling for license. I notice it's also spelled as `Licence` on gbif.org so maybe this is a wider discussion.

**Comment by MattBlissett** [comment]
GBIF follows the UN style guide, which is British spelling with the Oxford dictionary.

https://www.un.org/dgacm/en/content/editorial-manual

https://www.un.org/dgacm/en/content/editorial-manual/spelling#l

I wouldn't want to trick people into publishing with the most permissive licence, so the default should still be "No licence selected", but reordering the options would be fine.

**Comment by peterdesmet** [comment]
@mike-podolskiy90 three potential tasks were discussed in this issue:

- [ ] change order licenses from fewer to more restrictions
- [ ] write license names consistency
- [ ] update spelling from `licence` to `license`

@MattBlissett indicated that the last should not be done, but the other two would still be useful.

**Comment by dbloom** [comment]
I appreciate and support these updates. Thanks for the work.

**Comment by mike-podolskiy90** [comment]
Thank you @peterdesmet

**Comment by mike-podolskiy90** [comment]
Fix bc45d34881a47d1238d7c7b7dc4e01dbb42d32ea
