### ISSUE TITLE
The base URL is not valid

### ISSUE THREAD

**Issue by wbloos** [gbif/ipt#1351]
I've installed a new IPT (2.3.4) under tomcat8 with a reverse proxy in apache2.
The reverse proxy works well both wit port 80 and 443, but regardless I get the following error when validating the base URL.
"The base URL is not valid. Please check the IPT is publicly accessible at this base URL. Since this IPT is being run in test mode, however, the form for registration below will be activated anyway."
That occurs in http://<my-ipt>/admin/registration.do (or https, respectively).

**Comment by kbraak** [comment]
@wbloos thank you for reporting your issue.  

In the IPT wiki, there is a helpful section with guidance on how to configure Apache Reverse Proxy for an IPT https://github.com/gbif/ipt/wiki/IPTServerPreparation.wiki#configure-apache-reverse-proxy 

In addition, please ensure your IPT server can make the necessary outbound connections as described in this FAQ: https://github.com/gbif/ipt/wiki/FAQ.wiki#7-what-outgoing-connections-does-the-ipt-make Take note of the differences depending on whether your IPT is running in test or production mode. 

During IPT registration, the IPT calls http://tools.gbif.org/ws-validurl to validate its base URL. Therefore you always can try testing your base URL making the following call replacing the URL being tested with your own of course: http://tools.gbif.org/ws-validurl/?url=https://ipt.gbif.org

Please reopen another issue if your problem persists after doing the necessary setup and checks detailed above, thanks.
