### ISSUE TITLE
IPT installation must have internet connection

### ISSUE THREAD

**Issue by dvdscripter** [gbif/ipt#1355]
Hi, I was just editing our forked version of [docker-ipt](https://github.com/sibbr/docker-ipt) and when running without internet found the ipt don't really start. Later I found connection is required to access some information at gbif.org.

Isn't possible to have this information shipped with ipt.war? Sadly I was trying to have a IPT installation at my laptop for when internet connectivity isn't that good (happens very often).

**Comment by kbraak** [comment]
Thanks @dvdscripter 

I'm afraid not. This section of the IPT User Manual explains the IPT's Internet Connectivity requirements: https://github.com/gbif/ipt/wiki/IPT2ManualNotes.wiki#internet-connectivity

This FAQ explains the specific outgoing (HTTPS) connections the current version makes: https://github.com/gbif/ipt/wiki/FAQ.wiki#7-what-outgoing-connections-does-the-ipt-make 

I'd also like to take this opportunity to point out a little known feature, that allows the IPT to keep up-to-date with the latest version of Darwin Core. This is its ability to synchronise with the latest versions of cores/extensions and vocabularies as soon as they get released. For this to work, the IPT must remain connected to the Internet. More about this feature can be found in this section of the IPT User Manual in case you're interested: https://github.com/gbif/ipt/wiki/IPT2ManualNotes.wiki#synchronise-extensions-and-vocabularies
