### ISSUE TITLE
IPT says organisation is not registered while it is in administration tab

### ISSUE THREAD

**Issue by datameister-NL** [gbif/ipt#1358]
![gbif_not_registered](https://user-images.githubusercontent.com/30290633/30022141-570df02a-916a-11e7-95c2-b164b2db3cd9.jpg)

Both our organisation (https://www.gbif.org/publisher/6fbb8fe2-66e2-4a9e-bb39-b84665571f1c) as our ipt (https://www.gbif.org/installation/c4195389-aa85-42ab-a264-bf5e3b3c2966) are registered.

Why is there still 'not registered' at my resources tab. Please resolve this, I am working on publishing over a hundred datasets, this is not encouraging.

**Comment by kbraak** [comment]
The resource manager, not GBIF, decides when to register their resource with GBIF and which organisation gets credited as the owner. For more information about the various resource visibility states supported by the IPT, you can refer to the [Visibilty section](https://github.com/gbif/ipt/wiki/IPT2ManualNotes.wiki#visibility) of the IPT User Manaual. Thanks.
