### ISSUE TITLE
Phase out support for EZID

### ISSUE THREAD

**Issue by kbraak** [gbif/ipt#1361]
[Since v2.2](http://gbif.blogspot.dk/2015/03/ipt-v22.html ), the IPT has been capable of automatically connecting with either DataCite or EZID to assign DOIs to datasets.

Note EZID is being phased out over the next two years according to a [press release by the California Digital Library (CDL) on August 4, 2017](http://www.cdlib.org/cdlinfo/2017/08/04/ezid-doi-service-is-evolving/):

> Over the course of the next two years, EZID DOI services will be phased out for users outside of the University of California. CDL, Purdue and Datacite will work together to support EZID users in joining and migrating their service to use DataCite directly or to help them evaluate other options.

The University of California doesn't publish any datasets using an IPT configured with an EZID account. Therefore it makes sense to phase out the IPT's support for EZID, thereby simplifying the tool. IPT users should be informed about this change periodically over the next couple of years.

**Comment by MattBlissett** [comment]
For Thomas and anyone else subscribed to notifications on this issue, please see this message to the mailing list about likely phasing out support for EZID: https://lists.gbif.org/pipermail/ipt/2019-June/000723.html

**Comment by timrobertson100** [comment]
A mail was sent to the IPT list, and some one to one discussions followed.

We are aware that EZID and ARK are used heavily by e.g. Smithsonian but that is upstream of the IPT. 

The IPT connection to EZID was originally intended for DOI for the dataset and not for ARKs. Those who use ARK are really creating record level identifiers in their data management systems.

I don't believe anyone is using EZID connection directly from their IPT and it should be removed for IPT 2.4 unless new information comes to light.

This does not mean the IPT can't be used for passing through records with ARK (as the Smithsonian do for example)
