### ISSUE TITLE
404 in wiki

### ISSUE THREAD

**Issue by jar398** [gbif/ipt#1363]
The wiki home page links to
http://www.gbif.org/ipt/releases
which is 404.

**Comment by kbraak** [comment]
Thanks for reporting this issue @jar398 

Content from the previously existing page on GBIF.org (http://www.gbif.org/ipt/releases) has been transferred to https://github.com/gbif/ipt/wiki/Releases and https://github.com/gbif/ipt/wiki/Roadmap both appearing in the sidebar on the wiki
