### ISSUE TITLE
Fix XSS issues 

### ISSUE THREAD

**Issue by timrobertson100** [gbif/ipt#1364]
The security scanner run by Smithsonian has found XSS issues to address.  Liaise in private with those developers and ensure the issues are addressed.

**Comment by timrobertson100** [comment]
Fixed with https://github.com/gbif/ipt/commit/bed9f2e461df3c05764e5f661306e61e8e794de0

**Comment by mdoering** [comment]
Passes all xss tests from AppSpider and https://detectify.com/

**Comment by kbraak** [comment]
Great @mdoering, thanks. But the above commit https://github.com/gbif/ipt/commit/bed9f2e461df3c05764e5f661306e61e8e794de0 broke other parts of the IPT's functionality that still require fixing.

**Comment by mdoering** [comment]
excluded /manage and /admin from firing the filter: https://github.com/gbif/ipt/commit/3ce4adbd9103ce38617695b44d75746e93620235
