### ISSUE TITLE
Prevent DOM XSS vulnerability setting the language flag

### ISSUE THREAD

**Issue by mdoering** [gbif/ipt#1367]
A potential DOM XSS vulnerability exists when setting the language flag in the IPT via jquery (ranked HIGH by Burp security scanner) in global.js:

```
The application may be vulnerable to DOM-based cross-site scripting. Data is read from location and passed to the 'append()' function of JQuery via the following statement:
$("#languages").append('<li><a href="'+location+request+'='+this+'"><img src="'+baseUrl+'/images/flags/flag_'+this+'.png"/></a></li>');
```

**Comment by mdoering** [comment]
An easy fix would be to remove the use of location and link back to the home page of the application. It is not as comfortable as it currently is, but then again people do not switch the locale often

**Comment by timrobertson100** [comment]
I wonder if @MortenHofft knows of an alternative solution for this?

**Comment by mdoering** [comment]
The simplest I can think of would be server side rendering. I am actually surprised to see this being done with jquery in a struts2 freemarker project
