### ISSUE TITLE
Unforeseen Error

### ISSUE THREAD

**Issue by zacheous** [gbif/ipt#1369]
we have encountered the following error installing IPT

It seems you have discovered an unforeseen error:

gbrds.gbif-uat.org
If you think this shouldn't have happened, would you mind helping us to improve the IPT and file a small bug report for this exception?

Thanks a million, the IPT development team.

The install can't proceed beyond this point.

Regards,

Zack.

**Comment by MattBlissett** [comment]
This is only part of an error (perhaps the IPT didn't show all of the error), but a typical cause is when a firewall or proxy blocks the IPT from accessing gbrds.gbif-uat.org.

**Comment by MattBlissett** [comment]
Please let us know if there's still an issue; hopefully configuring the firewall (or similar) resolved the problem.
