### ISSUE TITLE
Error while trying to save edits on metadata dataset or launching preview

### ISSUE THREAD

**Issue by datameister-NL** [gbif/ipt#1370]
IO exception when writing eml for Resource 1_201_monitoring_amfibieen_nl_2001

Hitting preview, ipt can't find the resource anymore, in editing mode everything is there, but can't save any edits. Publishing gives also same error. Please advise!

[GBIF_error_1_201.txt](https://github.com/gbif/ipt/files/1431322/GBIF_error_1_201.txt)

**Comment by kbraak** [comment]
To help diagnose the error, please provide more detailed information including the exact sequence of events leading to the error (perhaps you can even try to reproduce it with a new resource?), the IPT version you are running, the browser you are using, your server's operating system your IP, etc. Also, if you have access to your IPT Data Directory, try looking at $IPT_Data_Directory/resources/1_201_monitoring_amfibieen_nl_2001/eml.xml - is it corrupt? What's different in comparison to the latest version of the eml.xml file?
