### ISSUE TITLE
繁體中文翻譯：元數據中「引用文獻」第一項建議修改為「引用方式」

### ISSUE THREAD

**Issue by jerome-cjko** [gbif/ipt#1373]
![image](https://user-images.githubusercontent.com/31880136/33050867-24503074-cea2-11e7-93ff-8ab802f8217a.png)

**Comment by kbraak** [comment]
謝謝。 此翻譯已被驗證。 原來的英文意思就像引用。

**Comment by jerome-cjko** [comment]
Please note that "引用文獻" means "Cited References", and "引用方式" means "How to cite", both have the same two leading words "引用" but the last two words make the term to very different meanings.
