### ISSUE TITLE
Missing CORS headers

### ISSUE THREAD

**Issue by MortenHofft** [gbif/ipt#1374]
inventory URLs (such as https://ipt.gbif.org/inventory/dataset) cannot be used from webbrowsers due to missing CORS headers

blocks https://github.com/gbif/management-tools/issues/2

**Comment by thomasstjerne** [comment]
@mdoering can I ask you to review this [code](https://github.com/gbif/ipt/commit/b4fef661cfd33a4d5fa1896a44a29a531f029f73) ?
