### ISSUE TITLE
Create new version of Country Codes vocabulary used by IPT

### ISSUE THREAD

**Issue by kbraak** [gbif/ipt#1376]
The [ISO 3166-1 Alpha2 Country Codes vocabulary](http://rs.gbif.org/vocabulary/iso/3166-1_alpha2.xml) has 246 country codes, which is out of date. 

The [Wikipedia page for the ISO 3166-1 Alpha2 Country Codes](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) lists 249 current officially assigned ISO 3166-1 alpha-2 codes. 

Please release a new version of this IPT vocabulary in sync with the latest version of the ISO 3166-1 Alpha2 Country Codes, by following [these instructions](https://github.com/gbif/rs.gbif.org/blob/master/versioning.md).  The IPT will automatically pick up the new version following a restart. 

Note this is needed for a BID project, currently unable to fill in the desired country in the contact metadata form.

**Comment by laurarussell** [comment]
One of the BID Participants is from South Sudan and that is one of the
missing countries. So a fix on this sooner rather than later would be
appreciated. Thanks!

Laura Russell
+01 785.766.4713 <(785)%20766-4713>
Facetime: pagodarose@gmail.com
Skype: laura.anne.russell
email: laura.anne.russell@gmail.com

**Comment by MattBlissett** [comment]
Hmm, I didn't follow those instructions properly. But I did update the list. I don't see anyone using the AN Netherlands Antilles or YU Yugoslavia (!), which are the codes I removed.

I added BQ Bonaire, Sint Eustatius and Saba, CW Curaçao, MF Saint Martin, SS South Sudan, SX Sint Maarten, XK Kosovo.

I also updated some English and Spanish names in line with the GBIF API list.
