### ISSUE TITLE
Auto-populate geographic and temporal range metadata sections for uploaded occurrence datasets?

### ISSUE THREAD

**Issue by esellers-usgs** [gbif/ipt#1377]
Hi Folks,

Would it be possible to make the IPT capable of automatically defining/filling the geographic and temporal range sections of the metadata for an occurrence dataset after it is uploaded and mapped to DwC? A simple machine examination of the eventDate field values would easily indicate the temporal range; and the same would go for an examination of the decimalLatitude and decimalLongitude field values (of course with the assumption that those fields are populated and formatted correctly in the uploaded dataset).... with the option for the user to choose the option to either keep the auto-populated values or to manually overwrite/define them.

Cheers, Liz

**Comment by mike-podolskiy90** [comment]
Implemented here https://github.com/gbif/ipt/issues/1803
Closing this
