### ISSUE TITLE
Possible backup file was detected

### ISSUE THREAD

**Issue by fmendezh** [gbif/ipt#1380]
IPT 2.3.6-SNAPSHOT has a medium vulnerability: "a possible backup file was detected: struts/webconsole~"

Reported by Ivan Fetch fetch@usgs.gov

**Comment by mdoering** [comment]
Similar to #1381 this only happens in snapshots on purpose

**Comment by mdoering** [comment]
struts2 devMode activates the debuggingInterceptor:
http://struts.apache.org/getting-started/debugging-struts.html
