### ISSUE TITLE
Struts 2 development mode being enabled

### ISSUE THREAD

**Issue by fmendezh** [gbif/ipt#1381]
IPT 2.3.6-SNAPSHOT has a high vulnerability for Struts 2 development mode being enabled.

Reported by Ivan Fetch ifetch@usgs.gov

**Comment by mdoering** [comment]
This is on purpose during developments and struts dev mode is active by default in our snapshots.
It is disabled during a release build by using the release maven profile, triggered by jenkins: 

https://github.com/gbif/ipt/blob/master/pom.xml#L634
https://github.com/gbif/ipt/blob/master/src/main/resources/struts.properties#L7

**Comment by mdoering** [comment]
Changed the default to be production and created a new "dev" maven profile:
https://github.com/gbif/ipt/commit/f25cea33b7899deebe596a428e029ff10515d456

Snapshots should now also pass security tests
