### ISSUE TITLE
Using dockerized IPT v 2.3.5 - cannot add resources in Test Mode

### ISSUE THREAD

**Issue by mskyttner** [gbif/ipt#1386]
The use case is to run a local IPT instance to test uploading of "sampling event" datasets.

For this purpose, we dockerize v 2.3.5 of the IPT and launch it locally. 

When attempting to create a resource for "sampling event" data, we discover that we cannot use "Create" button until an Organization has been setup in the IPT. 

Trying to setup the Organization, since it is a test IPT node, only for testing and development purposes, we don't want to use an Organization from the list. 

We also cannot add a new Organization.'

So we try to look for a Test Organization, and we find the Test Organization Nr 1. We try to use this, but we don't know the password or the other way around. So we cannot proceed. The Test Organization lists kbraak as the contact person. Is it still valid?

How can we proceed with our test installation of IPT on our local machine?

**Comment by mskyttner** [comment]
I tried the 2.4.0 version now with some pre-configured settings from here mounted into the container at build time (I added COPY ./config/ /srv/ipt/config/ in the Dockerfile) to append the ipt config from here: https://github.com/bioatlas/ipt-docker/tree/master/bin/config but after the first login and when trying to set an organization as an ipt admin user, it still looks disabled or greyed out in the UI.

![grayed-out-organization-ui](https://user-images.githubusercontent.com/1715840/91745071-b0bf6880-ebba-11ea-8f0c-213f2cb92474.png)

It may be something wrong with the ipt config or (not unlikely) operator error?

**Comment by mskyttner** [comment]
This was an operator error, it seems like I can choose "No organization" and proceed.

![ipt_no_org](https://user-images.githubusercontent.com/1715840/91755183-fa17b400-ebca-11ea-8b3d-4acb5d1f3b97.png)

So I guess it confirms that this is no longer an issue.

I can enumerate the dataset with curl/(http)[https://httpie.org/] from the rss feed:

```bash
http [servername]/rss.do
```
But it does not turn up in the /inventory/dataset endpoint, which I guess is by design:

```bash
http $IPT_NAME/inventory/dataset
```

**Comment by MattBlissett** [comment]
Thanks Markus.  I think that is probably by design.
