### ISSUE TITLE
reset password fails

### ISSUE THREAD

**Issue by Antonarctica** [gbif/ipt#1389]
For 1 admin without registration right I cannot rest the password. This person cannot login anymore either....

**Comment by MattBlissett** [comment]
Hi Anton,

I've added an FAQ entry on resetting a lost admin password, which might help you.  If not, I'll need to see logs from the IPT. (But probably you found a solution long ago...)

https://github.com/gbif/ipt/wiki/FAQ.wiki#8-how-do-i-reset-the-admin-password
