### ISSUE TITLE
Java error after initial IPT configuration

### ISSUE THREAD

**Issue by nhmk** [gbif/ipt#1391]
After ipt-2.3.5 initial configuration at 3rd step of setup, got the error bellow.
I am running ipt-2.3.5 on tomcat 8.0.5
With JAVA:
openjdk version "1.8.0_161"
OpenJDK Runtime Environment (build 1.8.0_161-b14)
OpenJDK 64-Bit Server VM (build 25.161-b14, mixed mode)

Error text:

Oops

It seems you have discovered an unforeseen error:

java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

View IPT logs

If you think this shouldn't have happened, would you mind helping us to improve the IPT and file a small bug report for this exception?

Thanks a million, the IPT development team.
Technical Details

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $ at com.google.gson.Gson.fromJson(Gson.java:900) at com.google.gson.Gson.fromJson(Gson.java:853) at com.google.gson.Gson.fromJson(Gson.java:802) at org.gbif.ipt.service.registry.impl.RegistryManagerImpl.getVocabularies(RegistryManagerImpl.java:440) at org.gbif.ipt.service.admin.impl.VocabulariesManagerImpl.getFileNameToVocabularyMap(VocabulariesManagerImpl.java:310) at org.gbif.ipt.service.admin.impl.VocabulariesManagerImpl.load(VocabulariesManagerImpl.java:265) at org.gbif.ipt.config.ConfigManagerImpl.loadDataDirConfig(ConfigManagerImpl.java:175) at org.gbif.ipt.config.SetupAction.setup3(SetupAction.java:328) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at ognl.OgnlRuntime.invokeMethod(OgnlRuntime.java:897) at ognl.OgnlRuntime.callAppropriateMethod(OgnlRuntime.java:1299) at ognl.ObjectMethodAccessor.callMethod(ObjectMethodAccessor.java:68) at com.opensymphony.xwork2.ognl.accessor.XWorkMethodAccessor.callMethodWithDebugInfo(XWorkMethodAccessor.java:117) at com.opensymphony.xwork2.ognl.accessor.XWorkMethodAccessor.callMethod(XWorkMethodAccessor.java:108) at ognl.OgnlRuntime.callMethod(OgnlRuntime.java:1375) at ognl.ASTMethod.getValueBody(ASTMethod.java:91) at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212) at ognl.SimpleNode.getValue(SimpleNode.java:258) at ognl.Ognl.getValue(Ognl.java:470) at ognl.Ognl.getValue(Ognl.java:434) at com.opensymphony.xwork2.ognl.OgnlUtil$3.execute(OgnlUtil.java:362) at com.opensymphony.xwork2.ognl.OgnlUtil.compileAndExecuteMethod(OgnlUtil.java:414) at com.opensymphony.xwork2.ognl.OgnlUtil.callMethod(OgnlUtil.java:360) at com.opensymphony.xwork2.DefaultActionInvocation.invokeAction(DefaultActionInvocation.java:430) at com.opensymphony.xwork2.DefaultActionInvocation.invokeActionOnly(DefaultActionInvocation.java:290) at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:251) at com.opensymphony.xwork2.interceptor.DefaultWorkflowInterceptor.doIntercept(DefaultWorkflowInterceptor.java:168) at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98) at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216) at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) at org.gbif.ipt.struts2.CsrfLoginInterceptor.intercept(CsrfLoginInterceptor.java:68) at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216) at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) at com.opensymphony.xwork2.validator.ValidationInterceptor.doIntercept(ValidationInterceptor.java:265) at org.apache.struts2.interceptor.validation.AnnotationValidationInterceptor.doIntercept(AnnotationValidationInterceptor.java:76) at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98) at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216) at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) at org.apache.struts2.interceptor.DeprecationInterceptor.intercept(DeprecationInterceptor.java:41) at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216) at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) at com.opensymphony.xwork2.interceptor.ConversionErrorInterceptor.intercept(ConversionErrorInterceptor.java:138) at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216) at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) at com.opensymphony.xwork2.interceptor.ParametersInterceptor.doIntercept(ParametersInterceptor.java:229) at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98) at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216) at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) at com.opensymphony.xwork2.interceptor.ParametersInterceptor.doIntercept(ParametersInterceptor.java:229) at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98) at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216) at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) at org.apache.struts2.interceptor.MultiselectInterceptor.intercept(MultiselectInterceptor.java:73) at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216) at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) at org.apache.struts2.interceptor.DateTextFieldInterceptor.intercept(DateTextFieldInterceptor.java:125) at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216) at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) at org.apache.struts2.interceptor.CheckboxInterceptor.intercept(CheckboxInterceptor.java:91) at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216) at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) at com.opensymphony.xwork2.interceptor.PrepareInterceptor.doIntercept(PrepareInterceptor.java:171) at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98) at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216) at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) at org.apache.struts2.interceptor.ServletConfigInterceptor.intercept(ServletConfigInterceptor.java:164) at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216) at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) at com.opensymphony.xwork2.interceptor.ExceptionMappingInterceptor.intercept(ExceptionMappingInterceptor.java:189) at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216) at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) at com.opensymphony.xwork2.interceptor.I18nInterceptor.intercept(I18nInterceptor.java:140) at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216) at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) at org.gbif.ipt.struts2.RedirectMessageInterceptor.doIntercept(RedirectMessageInterceptor.java:119) at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98) at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216) at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) at org.gbif.ipt.struts2.PrivateDeletedResourceInterceptor.intercept(PrivateDeletedResourceInterceptor.java:82) at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216) at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) at org.gbif.ipt.struts2.SetupAndCancelInterceptor.intercept(SetupAndCancelInterceptor.java:84) at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216) at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) at org.gbif.ipt.struts2.ResourceSessionInterceptor.intercept(ResourceSessionInterceptor.java:41) at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216) at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245) at org.apache.struts2.impl.StrutsActionProxy.execute(StrutsActionProxy.java:54) at org.apache.struts2.dispatcher.Dispatcher.serviceAction(Dispatcher.java:575) at org.apache.struts2.dispatcher.ng.ExecuteOperations.executeAction(ExecuteOperations.java:81) at org.apache.struts2.dispatcher.ng.filter.StrutsPrepareAndExecuteFilter.doFilter(StrutsPrepareAndExecuteFilter.java:99) at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120) at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502) at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1132) at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1539) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1495) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.lang.Thread.run(Thread.java:748) Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $ at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385) at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183) at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) at com.google.gson.Gson.fromJson(Gson.java:888) ... 113 more

**Comment by pdelong42** [comment]
I am also having this error.  Any advice would be appreciated (e.g., is it safe to ignore...).

It doesn't seem to be a fatal error so far, but I haven't started using the IPT in earnest yet.  The error does make me slightly nervous, in case it should have any adverse affects on subsequent operation.

I'm still just running the IPT in test mode, while waiting to hear back from the stakeholder regarding which of the three CC licenses they want to apply to their data (I'm the sysadmin, not the end user).

Here are the versions of the bits I'm running:

IPT Version 2.3.5-rb9b0544

$ rpm -qa tomcat\* java-\*-openjdk\* centos-release | sort
centos-release-7-5.1804.el7.centos.2.x86_64
java-1.8.0-openjdk-1.8.0.171-8.b10.el7_5.x86_64
java-1.8.0-openjdk-headless-1.8.0.171-8.b10.el7_5.x86_64
tomcat-7.0.76-6.el7.noarch
tomcat-admin-webapps-7.0.76-6.el7.noarch
tomcat-el-2.2-api-7.0.76-6.el7.noarch
tomcat-jsp-2.2-api-7.0.76-6.el7.noarch
tomcat-lib-7.0.76-6.el7.noarch
tomcat-servlet-3.0-api-7.0.76-6.el7.noarch
tomcat-webapps-7.0.76-6.el7.noarch

**Comment by MattBlissett** [comment]
During initial setup, and thereafter during startup or when using the /admin/extensions.do page, the IPT retrieves a list of vocabularies from https://gbrds.gbif.org/registry/thesauri.json and a list of data standards from https://gbrds.gbif.org/registry/extensions.json (or gbrds.gbif-uat.org if using test mode).

The standards themselves are retrieved from http://rs.gbif.org.

gbrds.gbif.org (or gbrds.gbif-uat.org) is also used when registering a dataset with GBIF.

Do you have a firewall preventing access? It's easiest to allow access on ports 80 and 443 to 130.225.43.0/24; alternatively a proxy can be set within the IPT's setup pages or config file.

I'll try and make a better error message when the IPT can't connect to these servers.

**Comment by pdelong42** [comment]
Well, there doesn't seem to be any obstacle to reaching any of those endpoints from the server on which I've installed the IPT.  I'm able to get a response when I hit each URL from that server (using curl from the shell).

I guess I could do a packet capture or an strace, to see what the IPT is attempting to do when it returns that error.  But long-term, my vote is on a more informative error message, which reports the URL it's having trouble reaching.

But in case that turns-up nothing: is there any other possible cause for this type of error?

**Comment by pdelong42** [comment]
Here are some more data points...

It looks like it's at-least able to retrieve the data for the vocabularies, judging by the presence of files in the data directory (see output below).  Is there an way in the admin UI to test reachability of external resources?

Incidentally, when I went looking for that in the UI, I tried "GBIF registration options", and clicking on it reproduces the error.  This is at the URL `http://localhost:8080/ipt-2.3.5/admin/registration.do` (previously, it was `http://localhost:8080/ipt-2.3.5/setup3.do`).

```
$ find /var/lib/tomcat/data/ipt
/var/lib/tomcat/data/ipt
/var/lib/tomcat/data/ipt/tmp
/var/lib/tomcat/data/ipt/resources
/var/lib/tomcat/data/ipt/config
/var/lib/tomcat/data/ipt/config/registration2.xml
/var/lib/tomcat/data/ipt/config/ipt.properties
/var/lib/tomcat/data/ipt/config/.vocabularies
/var/lib/tomcat/data/ipt/config/.vocabularies/http_rs_gbif_org_vocabulary_iso_3166-1_alpha2_xml.vocab
/var/lib/tomcat/data/ipt/config/.vocabularies/http_rs_gbif_org_vocabulary_gbif_preservation_method_xml.vocab
/var/lib/tomcat/data/ipt/config/.vocabularies/http_rs_gbif_org_vocabulary_gbif_dataset_subtype_xml.vocab
/var/lib/tomcat/data/ipt/config/.vocabularies/http_rs_gbif_org_vocabulary_gbif_agent_role_xml.vocab
/var/lib/tomcat/data/ipt/config/.vocabularies/http_rs_gbif_org_vocabulary_iso_639-2_xml.vocab
/var/lib/tomcat/data/ipt/config/.vocabularies/http_rs_gbif_org_vocabulary_gbif_dataset_type_2015-07-10_xml.vocab
/var/lib/tomcat/data/ipt/config/.vocabularies/http_rs_gbif_org_vocabulary_gbif_rank_2015-04-24_xml.vocab
/var/lib/tomcat/data/ipt/config/.vocabularies/http_rs_gbif_org_vocabulary_eml_update_frequency_xml.vocab
/var/lib/tomcat/data/ipt/config/users.xml
/var/lib/tomcat/data/ipt/config/about.ftl
/var/lib/tomcat/data/ipt/config/.gbifreg
/var/lib/tomcat/data/ipt/logs
/var/lib/tomcat/data/ipt/logs/debug.log
/var/lib/tomcat/data/ipt/logs/admin.log

```

**Comment by MattBlissett** [comment]
@nhmk, this error seems to be caused by having an incorrect proxy server configuration. I've improved the error message around this.

@pdelong42, this is the sequence from a new install of the IPT:

After accepting the notice on setup.do and giving a data directory, the IPT retrieves https://gbrds.gbif-uat.org/registry/thesauri.json, which gives the URLs from which to download the vocabularies. Eight vocabularies are retrieved from rs.gbif.org. This step seems to have worked for you. This step doesn't use a proxy, as it's not configured yet. If it fails, it's repeated in the next step.

Completing setup2.do and selecting "Test mode" causes https://gbrds.gbif-uat.org/registry/extensions.json to be retrieved, which gives the URL from which to retrieve each extension, e.g. http://rs.gbif.org/core/dwc_event_2016_06_21.xml.  Three extensions and some additional vocabularies are downloaded from rs.gbif.org.

Selecting "Production mode" retrieves https://gbrds.gbif.org/registry/extensions.json, then the extensions and vocabularies as for test mode.

The result should be this structure:

```
...
├── config
│   ├── about.ftl
│   ├── .extensions
│   │   ├── http_rs_tdwg_org_dwc_terms_Event.xml
│   │   ├── http_rs_tdwg_org_dwc_terms_Occurrence.xml
│   │   └── http_rs_tdwg_org_dwc_terms_Taxon.xml
│   ├── .gbifreg
│   ├── ipt.properties
│   ├── registration2.xml
│   ├── users.xml
│   └── .vocabularies
│       ├── http_rs_gbif_org_vocabulary_dcterms_type_xml.vocab
│       ├── http_rs_gbif_org_vocabulary_dwc_basis_of_record_xml.vocab
│       ├── http_rs_gbif_org_vocabulary_eml_update_frequency_xml.vocab
│       ├── http_rs_gbif_org_vocabulary_gbif_agent_role_xml.vocab
│       ├── http_rs_gbif_org_vocabulary_gbif_dataset_subtype_xml.vocab
│       ├── http_rs_gbif_org_vocabulary_gbif_dataset_type_2015-07-10_xml.vocab
│       ├── http_rs_gbif_org_vocabulary_gbif_nomenclatural_code_xml.vocab
│       ├── http_rs_gbif_org_vocabulary_gbif_preservation_method_xml.vocab
│       ├── http_rs_gbif_org_vocabulary_gbif_quantity_type_2015-07-10_xml.vocab
│       ├── http_rs_gbif_org_vocabulary_gbif_rank_2015-04-24_xml.vocab
│       ├── http_rs_gbif_org_vocabulary_gbif_unit_of_measurement_2015-07-10_xml.vocab
│       ├── http_rs_gbif_org_vocabulary_iso_3166-1_alpha2_xml.vocab
│       └── http_rs_gbif_org_vocabulary_iso_639-2_xml.vocab
├── logs
│   ├── admin.log
│   └── debug.log
├── resources
└── tmp
```

Visiting /admin/extensions.do will perform the gbrds query, and clicking "Synchronize" will do the queries to rs.gbif.org for the standards that have been added.

**Comment by pdelong42** [comment]
Thanks, I'm running a snapshot of 2.3.6, and it seems to have fixed the issue.
