### ISSUE TITLE
Task: Release 2.3.6

### ISSUE THREAD

**Issue by timrobertson100** [gbif/ipt#1393]
It has been requested this be done by a user before some major upgrades end April.

- [x] Review commit history
- [x] Run user testing
- [x] Run security scanning
- [x] Release and communicate

**Comment by ivanfetch** [comment]
We've had a few delays, but now could use this version RE: [this JQuery issue](https://github.com/gbif/ipt/issues/1378). IPT 2.3.6 was slated for mid April according to an email from Tim on March 21st. Is there an ETA for 2.3.6?

**Comment by MattBlissett** [comment]
2.3.6 was released last July, but we forgot to close this issue.
