### ISSUE TITLE
ipt installation problems

### ISSUE THREAD

**Issue by nereydafl** [gbif/ipt#1396]
I got this error when trying to open the IPT in Tomat. Did not give me  any other problems, it was deployed correctly.

<img width="1510" alt="screen shot 2018-04-10 at 6 22 55 pm" src="https://user-images.githubusercontent.com/38265530/38586575-4740c5b8-3cec-11e8-99cd-707477b69d67.png">

**Comment by MattBlissett** [comment]
Thanks. I'm working on an update of the IPT, so I will ask you to test.

The very latest test versions are in http://repository.gbif.org/content/repositories/gbif/org/gbif/ipt/ , but I think they will give the same problem.

**Comment by MattBlissett** [comment]
From https://issues.apache.org/jira/browse/WW-4869 the issue is Struts and Java 9.

**Comment by nereydafl** [comment]
Thanks for your help. The problem seems like was in java but since no don't know java coding I install everything and re installed everything including java.

Not sure was was but it worked

**Comment by MattBlissett** [comment]
To make this easier to search, I'm copying the error into a message:

```
.nio.file.InvalidPathException: Illegal char <:> at index 3: jar:file:\C:\myWebProject\tomcat\webapps\ipt1\WEB-INF\lib\struts2-core-2.3.34.jar
```
