### ISSUE TITLE
base URL Validation failed!

### ISSUE THREAD

**Issue by nereydafl** [gbif/ipt#1397]
I installed the IPT but when i tried to validate my Base URL gave me this: Validation failed! Please check your Internet connection. If connected, check the Base URL and the Proxy URL (if needed on this server).

Internet is not the problem but for some reason it is my URL
http://128.119.112.251:8088/ipt 

I tried to use a nicer URL such as http://eco.umass/ipt orhttp://eco.umass:8088/ipt 
and it did not worked.

So, my next question will be how to chance the url. 
I tried what the guide says: change the ipt document in the config folder in an editor and modify the URL but did not worked.

**Comment by MattBlissett** [comment]
This validation is checking the URL can be accessed from the public internet (you could also test using a mobile phone's web browser, so long as it's not on university wifi).

Public access to http://128.119.112.251:8088/ipt is probably blocked by your university's firewall, you'll need to ask the IT / network administrators to open the port.

Also eco.umass isn't a public domain name, you could ask the university to assign one, and set the baseURL accordingly.
