### ISSUE TITLE
Date created problematic

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#1405]
The `additional metadata > date created` field is automatically populated based on when a resource was first created. That date is then used to build the year in the automatic citation. It is not possible for the user to update this field.

<img width="377" alt="date-created" src="https://user-images.githubusercontent.com/600993/40163343-d1f573f2-59b6-11e8-86b6-e4596893198c.png">

That implementation is problematic however:

1. A resource is often created many months before it is actually published, so the year might be off (like [here](https://ipt.inbo.be/resource?r=hemiptera-natuurpunt-occurrences#citation))
2. The definition (blue box above) states it is the date the resource was `published/made publicly available` (which makes perfect sense for the citation), but that is not how it is implemented.

Suggest to:

1. Update label to `Date first published` (fits quite nicely with `Date last published` field)
2. Populate field with date when resource was first made public/published, rather than created

**Comment by mike-podolskiy90** [comment]
Thank you @peterdesmet for the suggestions.
Will be added in version 2.5.0
Closing this
