### ISSUE TITLE
IPT manual page won't render

### ISSUE THREAD

**Issue by jlegind** [gbif/ipt#1406]
Displays this warning:

**The wiki page took too long to render.
This wiki page’s content is too large to render on this page.**

Claims the 'content is too large' to render.

The first time I have seen this behavior was today 13-06-2018

**Comment by MattBlissett** [comment]
The wiki can be edited by checking out the repo:

`git clone git@github.com:gbif/ipt.wiki.git`

**Comment by peterdesmet** [comment]
Once you are able to edit, it might be useful to break the user manual up in different pages per section.

**Comment by jlegind** [comment]
It might be easier to break up the manual, rather than try to edit it down to a size that github can render.
