### ISSUE TITLE
Importing EML metadata into occurence resource

### ISSUE THREAD

**Issue by tvandenberghe** [gbif/ipt#1409]
Never mind. Issue can be disregarded.

**Comment by peterdesmet** [comment]
How did you solve it? I’d very much like it too if EML could be imported or updated remotely.

**Comment by tvandenberghe** [comment]
Hi Peter,

I saw on https://github.com/gbif/ipt/issues/955 that the resource can be created as a "metadata-only" one from an existing EML file, then 'cast' into a occurence dataset from the basic metadata/Type dropdown.

Cheers, Thomas

**Comment by MattBlissett** [comment]
Thanks both.

Another option (the worst option, probably) is to copy the EML file directly into the IPT's data directory, and restart. That's probably only appropriate if the EML is based on an existing, known-good file.

Some code around this approach is in these repositories:
* https://github.com/MattBlissett/ipt-batch-import
* https://github.com/gbif/watchdog
