### ISSUE TITLE
EML file version #unspecified for resource surveillance-exotic-mosquitoes-belgium couldn't be parsed

### ISSUE THREAD

**Issue by DimEvil** [gbif/ipt#1413]
Parsing of text copied from certain .pdf format can't be parsed, it seems....

workaround, copy to text editor first and re-copy into IPT.....

**Comment by DimEvil** [comment]
I just did everything again from scratch and it still fails... (strange)

**Comment by DimEvil** [comment]
Just tried with minimal metadata and that works...

**Comment by DimEvil** [comment]
It is somewhere in the `description` field....

**Comment by MattBlissett** [comment]
Do you remember more details about this issue?  Thanks.

**Comment by peterdesmet** [comment]
@DimEvil is about this dataset: https://doi.org/10.15468/df1mwn The described issue sounds like there was an unreadable character copied into the metadata, which then failed the EML creation?

**Comment by DimEvil** [comment]
2018... I don't really recall.  But I guess @peterdesmet is right, or it sounds like that. I might try to create the issue again, if you want.

**Comment by MattBlissett** [comment]
If it's something that's worth fixing, we'll need to know what the problem was.  If it was a minor annoyance which we can live with, we can just close the issue.

**Comment by peterdesmet** [comment]
@MattBlissett I think we can close this. We'll see if it ever comes up again.
