### ISSUE TITLE
login problem IPT Version 2.3.5

### ISSUE THREAD

**Issue by jeroencreuwels** [gbif/ipt#1417]
I am writing on behalf of the  IPT administrator of IPT.ravon.nl

Each time a new page is opened the user is logged oud and a message appears:  "Not Authorised | You are not authorised to view the requested page. | Please login with a suitable account." Also when logging in for the first time in the box in the right upper corner, you need to enter the password again in the user login page.
 I have the same problems when logging in but do not encounter these problems in other IPT installations (e.g. ipt.nlbif.nl which is the exactly the same version).

**Comment by MattBlissett** [comment]
This will be tricky to track down.

Does the same happen if the IPT is opened in a private browser tab?

**Comment by jeroencreuwels** [comment]
No difference. But I see that two of five datasets are not registered with GBIF anymore, whereas before all five were registered.

**Comment by RicardoOrtizG** [comment]
We are having the same problem in SiB Colombia's IPT in 2.3.6 version. As @jeroencreuwels said, it doesn't happen in all installations.

**Comment by jeroencreuwels** [comment]
We have been able to track down the problems at the RAVON IPT. It appears that when updating the IPT version, the link to the new version on the virtual server had not been updated. It still directed to the older version, and after adjusting this, the IPT worked fine again.

**Comment by SCozijnsen** [comment]
Were you still using the template changes I made for you for the 2.3 version? I think there was a wrong redirect in the header version of the login box. If you go to ipt.ravon.nl/login.do it would have probably worked. This was because of some template changes in the newer version. I'm, planning to make a new version for the 2.3.6. I will let you know when it is finished!
