### ISSUE TITLE
automatic user logout causes loss of input

### ISSUE THREAD

**Issue by jatuloom** [gbif/ipt#1419]
New user entering meta data on /manage/metadata-basic.do?r={resource_name}&edit=Edit is automatically logged-out despite typing continuously.

ipt v2.3.5

**Comment by MattBlissett** [comment]
This was answered by email by the helpdesk; I'm abbreviating and their reply in case others come across it.

> Please try editing session-config in the web.xml file and restart Tomcat.
>
> If you want no timeouts at all, set the number to -1 .
