### ISSUE TITLE
All fields of Basic metadata is filled but error "Basic Metadata section was not validated! This needs to be fixed before all sections can save successfully." occur

### ISSUE THREAD

**Issue by chadinkomi** [gbif/ipt#1420]
http://ib.komisc.ru:8088/ipt

Trying to publish new Checklist. All fields of Basic metadata is filled but error "Basic Metadata section was not validated! This needs to be fixed before all sections can save successfully." occur.

![02](https://user-images.githubusercontent.com/9402875/46332202-16e48f00-c624-11e8-81a8-9398b499b5d0.png)
![01](https://user-images.githubusercontent.com/9402875/46332203-16e48f00-c624-11e8-955a-04ec36c8763b.png)

**Comment by peterdesmet** [comment]
Have had that too and it’s easy too miss, but a personnel id without a personnel directory generates an error. I think the personnel identifier directory for Tatiana Shubina is missing

**Comment by MattBlissett** [comment]
@mike-podolskiy90, this looks relevant to the Bootstrap UI; the validation error isn't clear at present.

**Comment by mike-podolskiy90** [comment]
Thank you @chadinkomi @peterdesmet 
We now highlight the error 

![Screenshot 2021-06-11 at 11 36 21](https://user-images.githubusercontent.com/24795387/121667395-846e3c00-caaa-11eb-8003-d9c07dd43fb7.png)

I hope that is enough. Closing this.

**Comment by peterdesmet** [comment]
Probably something for a different issue, but it would be good if ORCIDs are the default.
