### ISSUE TITLE
making a pending version public also exposes the current private version

### ISSUE THREAD

**Issue by pieterprovoost** [gbif/ipt#1425]
When making a private resource public without republishing, the archive for the current (private) version can be downloaded without logging into IPT. This is unexpected behaviour, as the UI still marks the current version as private and only the pending version as public.

In the case of the resource below, version 1.4 was publicly available at `/archive.do?r=mydataset` (but not at `/archive.do?r=mydataset&v=1.4`).

This affects IPT 2.3.4.

![screen shot 2018-10-25 at 12 34 33](https://user-images.githubusercontent.com/490041/47494883-099d7780-d853-11e8-9acc-df227d5d5742.png)

**Comment by MattBlissett** [comment]
This bug isn't present in the current development version, and I believe also not in v2.3.6.

I think fa6c8e6fed7f8a23eb5018932285c97e5e26e81c fixed the problem.
