### ISSUE TITLE
expected http status 404 on missing dataset, but got 302 (temporary moved) or 200 (ok) instead.

### ISSUE THREAD

**Issue by jhpoelen** [gbif/ipt#1427]
When attempting to retrieve a GBIF registered dataset at http://bim-mirror.aseanbiodiversity.org:8080/ipt/archive.do?r=flora_of_agusanmarsh , it appears that the dataset no longer exists or accessible. 

expected: an expected error code 404 (not found) or 403 (forbidden)

actual: a 302 (found) was observed, with a re-direct to a setup page. Please see attached screenshot and curl results. 

```
$ curl --verbose "http://bim-mirror.aseanbiodiversity.org:8080/ipt/archive.do?r=flora_of_agusanmarsh"
*   Trying 160.20.43.236...
* TCP_NODELAY set
* Connected to bim-mirror.aseanbiodiversity.org (160.20.43.236) port 8080 (#0)
> GET /ipt/archive.do?r=flora_of_agusanmarsh HTTP/1.1
> Host: bim-mirror.aseanbiodiversity.org:8080
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 302 Found
< Server: Apache-Coyote/1.1
< Set-Cookie: JSESSIONID=791C114757D4A4DB96A8AC5C4DAD8D7F; Path=/ipt/; HttpOnly
< Location: http://bim-mirror.aseanbiodiversity.org:8080/ipt/setup.do;jsessionid=791C114757D4A4DB96A8AC5C4DAD8D7F
< Content-Language: en-US
< Content-Length: 0
< Date: Tue, 30 Oct 2018 17:28:25 GMT
< 
* Connection #0 to host bim-mirror.aseanbiodiversity.org left intact
```

![screenshot from 2018-10-29 10-26-41](https://user-images.githubusercontent.com/1084872/47668270-36100700-db65-11e8-9820-2aad32aabe26.png)

**Comment by MattBlissett** [comment]
I think this is likely to have been a temporary problem with that IPT (restarted without a data directory for example).

**Comment by jhpoelen** [comment]
@MattBlissett Thanks for responding to this issue. 

On reproducing the original observation of getting an unexpected 302 error code requesting a non-existent error code, I got a 200 OK response with an html error page saying that the resource does not exist (see below). I would expect a 404 error code along with a html error, regardless of whether the IPT was configured properly or not .

Suggest to re-open this issue and address it, or close with status "will not fix". 

```
$ curl --verbose "http://bim-mirror.aseanbiodiversity.org:8080/ipt/archive.do?r=flora_of_agusanmarsh"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 160.20.43.236...
* TCP_NODELAY set
* Connected to bim-mirror.aseanbiodiversity.org (160.20.43.236) port 8080 (#0)
> GET /ipt/archive.do?r=flora_of_agusanmarsh HTTP/1.1
> Host: bim-mirror.aseanbiodiversity.org:8080
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: Apache-Coyote/1.1
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET, OPTIONS, HEAD
< Set-Cookie: JSESSIONID=9810CFBEADBC9B2B77D51BA9EF31770A; Path=/ipt/; HttpOnly
< Content-Type: text/html;charset=UTF-8
< Content-Language: en-US
< Transfer-Encoding: chunked
< Date: Mon, 21 Sep 2020 17:36:42 GMT
```

![Screenshot from 2020-09-20 10-25-08](https://user-images.githubusercontent.com/1084872/93717584-9dede300-fb2b-11ea-98e7-f17e96806570.png)

**Comment by MattBlissett** [comment]
Ah, yes, you are quite correct.  I didn't think to check that the "Resource Does Not Exist" page returns 404.

**Comment by MattBlissett** [comment]
This should be easy then.

`curl -I https://ipt.gbif.org/resource?r=should_be_404`

currently returns HTTP 200, but should return 404.

**Comment by jhpoelen** [comment]
@MattBlissett Thanks!
