### ISSUE TITLE
Resources xml transfer from 2.3.4 -> 2.3.6

### ISSUE THREAD

**Issue by esko-piirainen** [gbif/ipt#1430]
Hi,

I tried to update our IPT from 2.3.4 to 2.3.6.

I provided the same data folder as before. On the admin side, manage resources said when processing .ftl file that "r.organisation" was null/undefined. As a result the UI was not functional.

I didn't copy the exact stacktrace, sorry.

**Comment by timrobertson100** [comment]
I have seen this when people move resources on the file system but not when an entire data directory is used.

Can you please check your Admin > Organisations and verify that they are all as you would expect?

Failing that, can you please share your data folder with informatics@gbif.org and we will be able to diagnose the problem properly.

**Comment by MattBlissett** [comment]
Hi @esko-piirainen, @timrobertson100; do you know if this issue was resolved, or (if not) if it's still useful? (i.e. do we have data we could use to reproduce it.)

**Comment by esko-piirainen** [comment]
Hi, I'll try updating to the latest version again in the next couple of weeks and then I'll see if the problem still exists. If so, I'll send you the data

**Comment by timrobertson100** [comment]
@esko-piirainen , can you please tell us if this is still and issue or if this can be closed?

**Comment by esko-piirainen** [comment]
I updated to 2.4.2 - no problems. 
Closing this

**Comment by esko-piirainen** [comment]
Well there was no problems in earlier stage - concerning r.organization but there is a problem with parsing  sqlsource when editing a source. I'll open a different issue for that
