### ISSUE TITLE
Potential security issue - restart of tomcat required after IPT install

### ISSUE THREAD

**Issue by jdpye** [gbif/ipt#1431]
Environment details:
IPT Version 2.3.6-r3985b6a
Server version: Apache Tomcat/7.0.73
Server number:  7.0.73.0
OS Name:        Linux
OS Version:     3.10.0-862.11.6.el7.x86_64
Architecture:   amd64
JVM Version:    1.8.0_181-b13

After installing and configuring an IPT instance via Tomcat, anyone can visit the $IPT_URL/setup.do form, click the Continue button, and be automatically logged in as the default administrator without any password challenge. A restart of the Tomcat service removes this capability/behaviour.

I looked through the install instructions and video to see if this was intended behaviour, some artifact of configuring the IPT for the first time, but was unable to find reference to it. In the meantime I'll make the Tomcat restart part of my deployment strategy going forward.

**Comment by MattBlissett** [comment]
Thanks Jon.

This is a limitation with the installation procedure, but from version 2.5.0 it will at least be possible to (re)set the data directory for the initial installation, or future upgrades.  That removes most of the risk.
