### ISSUE TITLE
ipt - Cannot connect to proxy host

### ISSUE THREAD

**Issue by atur** [gbif/ipt#1432]
Hi,
Our ipt (2.3.6) is accessible on the url http://gbif.mnhn.lu:8080/ipt-2.3.5
We have setup a proxy url http://gbif.mnhn.lu/ipt based on nginx which pass this url to the ipt url above.
When we try try to set the proxy url in the ipt settings, the ipt says "Cannot connect to proxy host http://gbif.mnhn.lu/ipt"

What is going wrong?

**Comment by MattBlissett** [comment]
Hi
The proxy URL in the IPT settings is necessary when there is an institutional proxy — when all requests for web pages must go through a proxy, e.g. to filter what employees can see.

You probably want to leave that setting empty.

(http://gbif.mnhn.lu/ipt is working, so you must have worked this out, but I've written this in case someone else finds it.)
