### ISSUE TITLE
Missing created resource 

### ISSUE THREAD

**Issue by RicardoOrtizG** [gbif/ipt#1435]
I'm having an issue with the creation of resources in the IPT's 2.3.6 version. I created the next resource:
https://ipt.biodiversidad.co/sib/manage/resource?r=fedena-mamiferos-001
But a week later the resource disappeared from the IPT and datadir (Log message: The resource doesn't exist). I created the resource again with the same name, and it happens again. At the moment it disappears the data and metadata had not loaded yet. ¿Can you help me to understand what could happened?

**Comment by RicardoOrtizG** [comment]
Searching in the Administrator logs, I found this message: Cleaning up invalid resource directory pruebairaida with single file: resource.xml, where pruebairaida is a prove dataset I created to see if it disappear again.

Searching in the IPT's GitHub, we found this code that maybe explain what happened, apparently, the IPT delete the resource if it's found empty. I just want to know if I'm right, what is the trigger to initialize this IPT clean up, and how much time the resource remains in the IPT, before it is deleted.

          if (resourceDirFiles == null) {
            log.error("Resource directory " + resourceDir.getName() + " could not be read. Please verify its content");
          } else if (resourceDirFiles.length == 0) {
            log.warn("Cleaning up empty resource directory " + resourceDir.getName());
            FileUtils.deleteQuietly(resourceDir);
            counterDeleted++;
          } else if (resourceDirFiles.length == 1) {
            log.warn("Cleaning up invalid resource directory " + resourceDir.getName() + " with single file: " + resourceDirFiles[0].getName());
            FileUtils.deleteQuietly(resourceDir);
            counterDeleted++;
          } else {
            try {
              log.debug("Loading resource from directory " + resourceDir.getName());
              addResource(loadFromDir(resourceDir, creator));
              counter++;
            } catch (InvalidConfigException e) {
              log.error("Can't load resource " + resourceDir.getName(), e);
            }
          }
        }
      }
      log.info("Loaded " + counter + " resources into memory altogether.");
      log.info("Cleaned up " + counterDeleted + " resources altogether.");
    } else {
      log.info("Data directory does not hold a resources directory: " + dataDir.dataFile(""));
    }
    return counter;
  }

**Comment by RicardoOrtizG** [comment]
The problem also occurs when metadata is documented but the data file is not loaded yet. We had 2 resources in the process to be published that has been deleted with documented metadata. I answer to the technology team and they told me that they don't clean up the resources in the IPT.

**Comment by vjrj** [comment]
Some of our IPT users complained about this. As a temporally workaround we create a second file (empty) to prevent the clean process.

**Comment by EstebanMH-SiB** [comment]
We too have this problem in the IPT's 2.4.0 version. With the suggestion of vjrj, the clean process in prevented, but we should like to know if there is a permanent solution to this problem. 
Also, we want to know what is the time frame for the auto cleaning process in the IPT?

**Comment by mike-podolskiy90** [comment]
Thank you for reporting the issue.
Will be fixed in the 2.5.0 release
