### ISSUE TITLE
Resource changed from Public to Private after publishing

### ISSUE THREAD

**Issue by RicardoOrtizG** [gbif/ipt#1436]
When I tried to publish a new resource in the IPT, it had an abnormal behavior. It showed the publishing page as successful, then, when I tried to register the resource in GBIF it appears as private with a public version pending to publish. It makes no sense because the resource was set to 'Public' before publishing the resource, and even a Doi was assigned, but the Doi remains in the pending public version.

![image](https://user-images.githubusercontent.com/15789737/50913397-4f092400-1402-11e9-9a20-7ece5a1863fc.png)

As you can see in the image, I can not publish the public version again because of the buttons of Publishing and Register are disable. I tried to modify the metadata to activate the publishing buttons, but it does not work.

Now, when I look for the resource in the IPT's Manage Resource, it has a Public visibility

![image](https://user-images.githubusercontent.com/15789737/50913624-c048d700-1402-11e9-82f6-9c7e314104cd.png)

We are trying to find the cause of his error, but we are not succeeded yet. Can you help us to understand what happens and what we can do to solve it ?.

Thanks!

By the way, we are working with 2.3.6 IPT's version

**Comment by JeGoi** [comment]
We had the same issue (same IPT version 2.3.6). To bypass that problem (buttons of Publishing and Register are disable), you can remove the class that block the click on that buttons then used them. (It is only a css class that block it)

How to do it:
First, compare the class associated with the button that doesn't work (publish), and the class associated with a button that you can click on it (like "Edit" for Metadata). To do it you can use "inspect element" on Firefox (or "inspect" with Chrome) with a click right on the button (publishing or register). Then on the inspector you should be able to find the "class" associated with that button. It looks like `<a class="something_that_block_and_need_to_be_removed" >Publish</a>`
Select and remove that class. It will looks like  `<a class="" >Publish</a>`. Click somewhere else on the page but do not refresh the page (this fix is only temporary on the current page). The button will be available. Click on it then the button "Publish".
To help you: https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_and_edit_HTML

It solved the issue temporarily but not the problem on the IPT itself.

**Comment by mike-podolskiy90** [comment]
@RicardoOrtizG Could you check is this still an issue for the IPT 2.5.1 or higher?

**Comment by RicardoOrtizG** [comment]
Hi, the issues looks like was solved, it doesn´t appear anymore since 2.4 version
