### ISSUE TITLE
Data file empty (UCDavis - Western USA - Monarch Butterflies - 1892-2005)

### ISSUE THREAD

**Issue by apdrp** [gbif/ipt#1438]
Hi there, 

When I try to download the data as a DwC-A file on this page, I get an empty empty .zip file.
Where are the data?

https://bison.usgs.gov/ipt/resource?r=ucdavis_western_usa_monarchs

Thanks.
apdrp

**Comment by MattBlissett** [comment]
Hi,

Thanks for your question. The download works for me, but it's not a system we at GBIF maintain.  You could try asking Hugh Dingle (listed on that page).

The data is published to GBIF, so it is also available here: https://www.gbif.org/dataset/fab6edb3-9311-4219-9d32-6114125f86a1 — if you have problems downloading data through GBIF, then we are the ones who can help.

**Comment by MattBlissett** [comment]
The data are back! (I have no idea what might have caused this.)
