### ISSUE TITLE
Darwin Core Measurement Or Facts does not display on Event GBIF web page

### ISSUE THREAD

**Issue by rukayaj** [gbif/ipt#1441]
Hello,

I have a sampling event dataset which has been published through the GBIF norway IPT. It has some additional Measurement Or Facts records linked to the sampling event (number of traps set, etc). When I download the dwc archive for that dataset from GBIF I can see the measurementorfact.txt with the correct data and the correct event IDs, but the GBIF web UI is not displaying anything on the sampling event page. Please help!

Here's an example of an event page which should have measurement or facts : https://www.gbif.org/dataset/2f2c251e-a69f-444b-af7e-6b7ad808f74f/event/urn:uuid:f047efff-d5f1-4599-a695-e5763ad3f653 

Thanks
Rukaya

**Comment by ManonGros** [comment]
Replied by email.
