### ISSUE TITLE
Deleting admin user fails

### ISSUE THREAD

**Issue by andrejjh** [gbif/ipt#1442]
When my old email address became invalid, I did created a new admin user with new email address.
Then, I tried to remove the user with the invalid email, but got this error:
The User cannot be deleted as it is the only manager for the following resources: [...].
If I understand well, I have to add new managers to all the resources created by old user...not very intuitive...
Is there another way to replace email address of an existing IPT user?

**Comment by JeGoi** [comment]
I guess you could change it directly in /config/users.xml
Make a backup before. Change the email. Restart tomcat. Test it.
If it is not working, use your backup and restart tomcat.
(Not so sure about restarting tomcat, but sometimes, it looks that ipt needs it)

**Comment by mike-podolskiy90** [comment]
Yes, it's possible to change in internal IPT files (but not recommended though).
There is no another way I'm afraid. We can consider implementing that functionality in the future
