### ISSUE TITLE
Why do only datasets with extensions include a link on the number of records

### ISSUE THREAD

**Issue by rukayaj** [gbif/ipt#1447]
Hi,

I was wondering why rows on the the IPT resource table (on home and /manage) sometimes shows a link to the /resource?r=resource-name#dataRecords and sometimes not. It looks like the link isn't included if the dataset doesn't have any extensions, in the code here:
https://github.com/gbif/ipt/blob/680c6c93e2d707dfb64a951739bf22b328cd296a/src/main/webapp/WEB-INF/pages/macros/resourcesTable.ftl#L45

It seems to work fine without this check (if you just display the link regardless).

Rukaya

**Comment by MattBlissett** [comment]
Thanks for the pull request Rukaya, I will merge this into the master branch.
