### ISSUE TITLE
dataset shortname (=identifier) allow colon and dot?

### ISSUE THREAD

**Issue by tvandenberghe** [gbif/ipt#1452]
Is it possible in the foreseeable future that the datasets get a shortname allowing characters other than hyphen, underscore and alphanumerical? We're looking into recuperating identifiers from external systems into the IPT. We would like to use ':' and '.' fe. bmdc.be:dataset:3213.

Also it's a bit confusing for novice users in the interface that the shortname ends up being the identifier (it's only apparent if you hover over the '?' icon).

The reason being that we can then merge identical metadata records with different provenances as they are talking about the same resource anyway (i.e. the same dataset might be represented by DwC via and O&M via another system).

https://github.com/gbif/ipt/issues/544
https://github.com/gbif/ipt/issues/1253

**Comment by MattBlissett** [comment]
The short name is used as the name of the directory. On Windows, filenames can't contain `:`, so implementing this isn't a simple fix.

Possibly it could be allowed on Linux (and Mac), although that could be a bit confusing.

The IPT supports alternative identifiers in the dataset metadata section, that could be a better place to store the identifiers from your external systems.
