### ISSUE TITLE
Update gbif-doi to version 2

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/ipt#1453]
gbif-doi version 2 stopped supporting mds and ezid services(It's using DataCite REST JSON API now). Check what changes are needed.

**Comment by mike-podolskiy90** [comment]
Use gbif-doi 2.1 or higher, API should be the same

**Comment by mike-podolskiy90** [comment]
To create a new instance of DoiService CommonBuilder#createRestJsonApiDataCiteService should be used instead of CommondBuilder#createDataCiteService

**Comment by MattBlissett** [comment]
Relevant to #1361 .

**Comment by MattBlissett** [comment]
I have tested this, and it seems to be working fine — thanks!
