### ISSUE TITLE
Audubon Core mapping

### ISSUE THREAD

**Issue by AMNHcjohnson** [gbif/ipt#1456]
Hi, I am new to this and I am trying to map my image file, however I am unable to see and select either the Simple Multimedia Extension or Audubon Media Description. Is it me or is there a bug?
Chris

**Comment by ManonGros** [comment]
Hi @AMNHcjohnson, could you or your IPT administrator check if the extensions have been installed?

On the administration menu, click on "Core Types and Extensions", then look for the Simple Multimedia Extension or Audubon Media Description. If they are not installed, click on the install button.

If they are already installed but you still can't find them, please let us know. Thanks!

**Comment by MattBlissett** [comment]
Hi @AMNHcjohnson, did Marie's suggestion solve your problem?

**Comment by debpaul** [comment]
Stepping in here - in case @AMNHcjohnson isn't looking at github stuff right now. I spoke with her and walked through her level of access to IPT functions. She realized she doesn't have Admin level permissions and was going to have to wait for her tech to go in and add the needed extension.

To @AMNHcjohnson: did the tech add it for you? Were you successful in using the Media extension?

**Comment by AMNHcjohnson** [comment]
Hi Debbie,
Yes, our IT dept. did install the media extension. Thanks.
Best,
Chris
