### ISSUE TITLE
Passwords are encrypted rather than hashed

### ISSUE THREAD

**Issue by MattBlissett** [gbif/ipt#1460]
IPT user passwords (including for the admin) can be recovered by anyone who gains access to the cyphertext (i.e. users.xml).

The same salt is used for all passwords.

This should be changed to hashed passwords using a per-user salt.

Note: needs to have a upgrade for existing installations

**Comment by MattBlissett** [comment]
See https://github.com/gbif/ipt/wiki/FAQ.wiki#8-how-do-i-reset-the-admin-password for using this to reset a lost password.

**Comment by raffael-mnhn** [comment]
This is really bad practice. An attacker getting access to the data directory can trivially recover all the users' passwords and use them in other places. This is bad as people often re-use their passwords in many services (yeah, it's not a good idea either). On top of this, the crypto implementation is pretty lowlevel so also prone to errors.

https://github.com/patrickfav/bcrypt or something similar should probably be used. This enhances security dramatically while also reducing code complexity. I might look into creating a PR implementing these changes if gbif is interested.

**Comment by timrobertson100** [comment]
This presumably means the IPT needs to re-store all user passwords. It would be useful to hear from IPT operators how they'd like this rolled out. Two scenarios could be:

1. All passwords are invalidated on upgrade and the administrator needs to distribute new passwords to users
2. As users log in they are required to change their password which is then encrypted using the chosen approach

While the first may be a nuisance it is the safest as some users may rarely log in, if ever.

**Comment by peterdesmet** [comment]
The issue with option 1 is that administers might give everyone the same password and users don’t update the one assigned, which isn’t great either.

What about an option 3 where no one can login using the old passwords, but on login attempt the user can reset their password with:
1. send code to registered email
2. enter code received by email
3. create new password
4. login using new password

**Comment by MattBlissett** [comment]
There's a 3rd option: when upgrading, decrypt all the passwords, hash them, and store the hashes.

It leaves it to the administrator to decide whether to reset all the passwords or not, but protects them from the moment of upgrade.

**Comment by timrobertson100** [comment]
My apologies - I misunderstood the issue, even though it is in the title and that they are currently encrypted and not hashed.

@MattBlissett is correct, that during the update process the passwords can be decrypted and then securely hashed and restored. Optionally, an admin may wish to invalidate them all.

**Comment by MattBlissett** [comment]
> https://github.com/patrickfav/bcrypt or something similar should probably be used.

Bcrypt was also my first thought, but I decided to read up on it.  There are several people recommending Argon2, including the [Open Web Application Security Project](https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html), but this seems to be [a misunderstanding](https://www.reddit.com/r/crypto/comments/hvbgt7/alternatives_to_bcrypt/fytf0yc/?context=3) -- Argon2 is better for key derivation (generating a key for use in an encryption process), but Bcrypt is better for web application password hashing.

Check the number of rounds is appropriate; aiming for about 250ms of CPU time to calculate the hash seems common.
