### ISSUE TITLE
migrating and deleting resource from one IPT to another

### ISSUE THREAD

**Issue by ManonGros** [gbif/ipt#1461]
When migrating a resource from one IPT to an other, and deleting this resource from the old IPT, the resource is also deleted on GBIF.
Would it be possible to add in the documentation how to safely delete the resource from the old IPT? (If I missed it could you let me know where to find it?)
```
Stop IPT
Delete resource from data directory
Restart IPT
```
Even better, would it be possible  to have the IPT check if an endpoint has changed before deleting a resource?

**Comment by MattBlissett** [comment]
There's no way to delete a resource from the IPT but keep it in GBIF.org; see https://github.com/gbif/ipt/wiki/IPT2ManualManageResources.wiki#delete-a-resource for a workaround (deleting the resource directory and restarting the IPT).

I agree it would be useful to change the single "Delete" button into "Delete from the IPT and GBIF.org" and "Delete from the IPT only (orphan)", or similar.
