### ISSUE TITLE
Classpath error in DataCite client

### ISSUE THREAD

**Issue by MattBlissett** [gbif/ipt#1462]
Colombia report an error when publishing/updating a dataset. The relevant part of the stack trace:

```
java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/JsonNode
	org.gbif.datacite.rest.client.configuration.RetrofitClientFactory.createRetrofitClient(RetrofitClientFactory.java:79)
	org.gbif.datacite.rest.client.retrofit.DataCiteRetrofitSyncClient.<init>(DataCiteRetrofitSyncClient.java:33)
```

This is odd, the DataCite client shades jackson-databind to hidden.com.fasterxml.jackson.databind, and the compiled classes use this, and we don't see a problem with our own IPT running on Tomcat.

**Comment by MattBlissett** [comment]
Probably related to #1463

**Comment by mike-podolskiy90** [comment]
I could not reproduce this. But we can fix this by adding jackson dependencies? What do you think @MattBlissett ?

**Comment by MattBlissett** [comment]
I was able to reproduce this in Docker and in Tomcat (without Docker) in version 2.4.2, but not in 2.5.0-snapshot. It should be fine in the next release.

(Reproduce just by adding a Datacite account to an organization.)
