### ISSUE TITLE
java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/JsonNode and java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/TreeNode

### ISSUE THREAD

**Issue by jsrfntd** [gbif/ipt#1463]
I have installed the ipt with docker. Alll works fine until i want to assign a DOI to a Resource. The error is the following:

java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/TreeNode
    org.gbif.datacite.rest.client.configuration.RetrofitClientFactory.createRetrofitClient(RetrofitClientFactory.java:79)
    org.gbif.datacite.rest.client.retrofit.DataCiteRetrofitSyncClient.<init>(DataCiteRetrofitSyncClient.java:33)

java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/JsonNode
    org.gbif.datacite.rest.client.configuration.RetrofitClientFactory.createRetrofitClient(RetrofitClientFactory.java:79)
    org.gbif.datacite.rest.client.retrofit.DataCiteRetrofitSyncClient.<init>(DataCiteRetrofitSyncClient.java:33)

**Comment by timrobertson100** [comment]
@MattBlissett 
Can this be closed? Is the issue with the docker container documented?

**Comment by MattBlissett** [comment]
I was able to reproduce this in Docker and in Tomcat (without Docker) in version 2.4.2, but not in 2.5.0-snapshot.  It should be fine in the next release.

(Reproduce just by adding a Datacite account to an organization.)
