### ISSUE TITLE
Automated mapping to Darwin Core terms - bug report and suggestion

### ISSUE THREAD

**Issue by ManonGros** [gbif/ipt#1466]
Today we received this email on Helpdesk.

> Hi,
> 
> I am testing data mapping at https://ipt-test.gbif.no/manage/mapping.do.
> 
> This is just to let you know about two things which I have noticed: one error and a couple of suggestions.
> 
> 1. Auto mapping
> Most of the columns I’ve imported with names which match the core occurrence terms are automatically selected for mapping (eg materialSampleID). However, I have a column of data with the heading dcterms:type and it is not recognised as matching the term listed in the Record-level section. It works if I change the column name to type, without the prefix. Since it’s potentially a pretty generic term, and it could be handy to have them named this way in the original data, I thought it would be useful if the system was able to recognise and map columns named dcterms:type (or even dcterms.type). (There is such flexibility in recognition of the occurrenceID field: imported columns named occurrence.occurrenceID and firstTable.occurrenceID are both auto mapped ok).
> 
> 2. Error when cancelling a Mapping
> A couple of times I clicked Add with the wrong core/extension selected, or I did it just as a way to read the descriptions of extension types (eg trying to review the difference between MoF and eMoF). In each case I clicked the Cancel button on the Mapping page, but the system goes ahead and creates and saves a Mapping anyway, even if you just click on the Resource Title at the top to escape back to the Overview page. This isn’t so bad if you notice and delete it while still in the Mapping page, but if you just click the Resource Title it will remain as part of the resource and could be a source of error if published without noticing.
> 
> One way to allow access to the core/extension descriptions, without going into the Administration section (if you have access), could be to list the core/extension names as a radio button list, instead of a dropdown list. Each item could then have an info link beside it with a popup box displaying the description. I have attached a doc with images of how this could look, and code to reproduce the layout mockup. (Please excuse my unsolicited suggestions; I spent years working as a web developer and it’s kind of second nature to look for improvements 😊).
>  
> I hope that is of some use. Feel free to ignore the suggestions; I realise there are many other factors to take into account.
>  
> Best,
> Gavin Alexander

EDIT: here is the document Gavin sent: 
[Alternative Darwin Core Mappings form in IPT.docx](https://github.com/gbif/ipt/files/4128838/Alternative.Darwin.Core.Mappings.form.in.IPT.docx)

**Comment by mike-podolskiy90** [comment]
This is fixed. Related issues https://github.com/gbif/ipt/issues/1739 and https://github.com/gbif/ipt/issues/1806
