### ISSUE TITLE
Give an error message when occurrenceIDs are missing

### ISSUE THREAD

**Issue by ManonGros** [gbif/ipt#1468]
Right now, publishers can generate Darwin Core Archive and register occurrence datasets even when occurrenceIDs are missing. The problem is that they might not realise that the data cannot be indexed on GBIF.

I suggest to give an error message for occurrence datasets that are missing occurrenceIDs.

**Comment by MattBlissett** [comment]
This should be a warning rather than an error, to allow older datasets with the DWC triple.

**Comment by mike-podolskiy90** [comment]
@ManonGros Where\when do you think this error\warning should be displayed please?

**Comment by ManonGros** [comment]
Maybe during the Archive validation? in the validation report?

**Comment by mike-podolskiy90** [comment]
I've added a warning for this but we can change it to an error if needed.
Closing this.
