### ISSUE TITLE
IPT crashes with "OutOfMemory" error on Postgresql

### ISSUE THREAD

**Issue by jlegind** [gbif/ipt#1474]
The Pl@ntNet team has tried mapping a large dataset in the IPT, but the installation crashes when clicking the preview icon.

This is what helpdesk received on April 24, 2020:

>>We have a large dataset (6 millions occurrences). When I connect to the database (Manage Resources > Create New Resource > Source Data), I can see the first records by clicking the "eye" icon. When I do the mapping between the database columns and DarwinCore fields, if I click the "eye" icon, the IPT crashes after a few seconds with an "OutOfMemory" error.

>> I have read that the IPT installation required 256 MB RAM (https://github.com/gbif/ipt/wiki/IPT2ManualNotes.wiki#getting-started-guide), and I have allocated 4 GB RAM to this process but it still crashes.

>> Is it a bug in the visualization tool ("eye" icon) or will it do the same when publishing the data (and therefore the mapping)? Could you tell me if you have an estimate of the RAM needed for large datasets?

**Comment by timrobertson100** [comment]
This seems unusual and I'd expect 2GB to be plenty. 

That "eye" should read only a small number of records (20?) and show them and we're not aware of anyone reporting issues on this before. The only time the IPT should use _some_ memory is when publishing, and only then if running on windows (linux will use the native `sort` command).

What database (or file type) are you using, please? Could you perhaps make an admin user for trobertson@gbif.org and mail me the credentials and URL so I can help diagnose this?

**Comment by jlegind** [comment]
From Antoine:

>> About the "out of memory" error: I created a single PostgreSQL table that contains all the data for one of our datasets (6 millions rows, no "join" statements, just a "select * from table"). if I do the process on a subset (100 rows), it works.


>> With the "test mode" registration, I was able to test to publish the dataset. I got the same "out of memory" errors.


>> For your information, I deployed the ipt-2.4.0.war and I also tested the Docker version, with the same result.

    publication.log:

    Archive generation started for version #1.0
    Start writing data file for Darwin Core Occurrence

    Tomcat9:

    tomcat9[22426]: Exception: java.lang.OutOfMemoryError thrown from the                         
    UncaughtExceptionHandler in thread "http-nio-8080-ClientPoller-1"
    tomcat9[22426]: Exception: java.lang.OutOfMemoryError thrown from the 
    UncaughtExceptionHandler in thread "http-nio-8080-ClientPoller-0"
    tomcat9[22426]: Exception: java.lang.OutOfMemoryError thrown from the 
    UncaughtExceptionHandler in thread "AsyncFileHandlerWriter-1828972342"
    tomcat9[22426]: Exception: java.lang.OutOfMemoryError thrown from the                         
    UncaughtExceptionHandler in thread "http-nio-8080-exec-10"
    tomcat9[22426]: Exception: java.lang.OutOfMemoryError thrown from the 
    UncaughtExceptionHandler in thread "Catalina-utility-1"
    tomcat9[22426]: Exception: java.lang.OutOfMemoryError thrown from the 
    UncaughtExceptionHandler in thread "Catalina-utility-2"

**Comment by AntoineAA** [comment]
Hello,

@jlegind, Thanks for the issue!

I confirm that the "eye" (the one associated with "mapping", not the one in the database source config page) results in an Out Of Memory error.

We are using PostgreSQL and we deployed the ipt-2.4.0.war and we also tried the Docker version, with the same result.

I created a single PostgreSQL table that contains all the data for one of our datasets (6 millions rows, no "join" statements, just a "select * from table"). if I do the process on a subset (100 rows), it works.

With the "test mode" registration, I was able to test to publish the dataset. I got the same "out of memory" errors.

@timrobertson100, i'll send you an email with the credentials.

Best regards

**Comment by timrobertson100** [comment]
It looks like scrolling cursors on PostgreSQL does not work, requiring the IPT to load the full dataset into memory when publishing. Two things are noteworthy here:

  1. The jdbc.properties has `pgsql.url=jdbc:postgresql://{host}/{database}?compatible=7.2` but [the PG docs](https://jdbc.postgresql.org/documentation/head/query.html) say that cursors only work on 7.4 and later
  2. There is no explicit turning off of  `auto-commit` which is said to be required in the PG [JDBC docs](https://jdbc.postgresql.org/documentation/head/query.html#fetchsize-example)

**Comment by MattBlissett** [comment]
Tested using Postgres:

```
pgsql.url=jdbc:postgresql://{host}/{database}
conn.setAutoCommit(false);
```

This works, and I think turning off Auto Commit should be fine, but it deserves a bit more testing, especially on other databases.
