### ISSUE TITLE
USGS IPT return basis-of-record error for HumanObservation

### ISSUE THREAD

**Issue by jlegind** [gbif/ipt#1475]
Abby wrote that when she tries generating a new dataset on their IPT an error comes up:
`basisOfRecord doesn't match the DwC Type Vocabulary   `

Line 1 has basisOfRecord ["HumanObservation"] that does not match the Darwin Core Type Vocabulary
Line 2 has basisOfRecord ["HumanObservation"] that does not match the Darwin Core Type Vocabulary
Line 3 has basisOfRecord ["HumanObservation"] that does not match the Darwin Core Type Vocabulary
...

The IPT is not the newest version. it is  2.3.6

**Comment by MattBlissett** [comment]
I think this would have been caused by the basis of record field including quote characters, i.e. `"HumanObservation"` rather than `HumanObservation`.
