### ISSUE TITLE
Startup warning on IPT in test mode: Test Organization #1 on gbrds.gbif-uat.org has been removed

### ISSUE THREAD

**Issue by bart-v** [gbif/ipt#1476]
IPT version 2.3.4 (and up?)
Now produces this startup warning:

`IPT startup warnings. For additional help diagnosing the problem(s), please see logs. After fixing the problem(s), please restart your web server.
Couldn't load registered organisation 625a5522-1886-4998-be46-52c66dd566c9 from Registry: https://gbrds.gbif-uat.org.`

This is due to the fact that the default "Test Organization #1" has been removed from gbrds.gbif-uat.org
https://gbrds.gbif-uat.org/registry/organisation/625a5522-1886-4998-be46-52c66dd566c9

Somebody created a new, similar one
https://registry.gbif-uat.org/organization/296de24e-25b2-454c-a178-bc7d3a88a73e

**Comment by MattBlissett** [comment]
@asturcon, @fmendezh -- have the IPT test entries not been imported?

**Comment by MattBlissett** [comment]
The test entries were already imported, but this is the IPT's "No organisation" organization.  "Installed by default, used to indicate resource is not published by any organisation".

The new registry (just released into testing) has different behaviour with this organization key on the IPT's API.  Possibly it has different behaviour on all error responses.

http://gbrds.gbif-uat.org/registry/organisation/625a5522-1886-4998-be46-52c66dd566c9.json -- 200, and an error message.

http://gbrds.gbif.org/registry/organisation/625a5522-1886-4998-be46-52c66dd566c9.json -- just a plain 404.

**Comment by bart-v** [comment]
The warning has now disappeared although nothing has changes to the behavior of the IPT's "No organisation" organization in the GBRDS

**Comment by bart-v** [comment]
This is happening again, see
https://lists.gbif.org/pipermail/ipt/2020-June/000740.html
Reopening...

**Comment by MattBlissett** [comment]
Thanks @bart-v, but I think we [just fixed it](https://github.com/gbif/registry/commit/ea9b5351553d96d36a96ffae7c5b40d9047ed9b3) -- we were waiting for confirmation from Beth before replying to the list.  Unless you've seen this since?

Production IPTs restarted since 9:56 UTC today shouldn't show the problem.

**Comment by bart-v** [comment]
Indeed.
I just restarted all of our IPTs and it's working fine
Thanks
