### ISSUE TITLE
updating IPT contact informations

### ISSUE THREAD

**Issue by silenius** [gbif/ipt#1478]
Hello,

Updating the Contact information for an IPT results in a 401:

![Firefox_Screenshot_2020-06-04T08-18-07 859Z](https://user-images.githubusercontent.com/1225348/83732994-2fa11580-a64d-11ea-996e-9070e0313384.png)

This is with IPT Version 2.4.0-r315faa5

**Comment by MattBlissett** [comment]
Hi

Sorry for the delay here.  If this wasn't resolved some other way (e.g. the helpdesk), would you let me know if you still have this issue?

**Comment by MattBlissett** [comment]
CC @silenius 

@mike-podolskiy90 — Please just check this works in the normal case, and otherwise we can assume this was an incorrect password or other temporary issue.

**Comment by mike-podolskiy90** [comment]
It still happens when trying to update the contact name or email.

**Comment by mike-podolskiy90** [comment]
@MattBlissett close this?

**Comment by MattBlissett** [comment]
> It was failing on ipt.gbif.org due to an invalid password, and is now failing due to missing (on gbif-uat) resources. These can probably just be removed, let's check with the helpdesk.

I removed the old and dead resources from ipt.gbif.org (now in ../archived-resources in case anyone needs them back).

The update then worked, so I don't think there's a bug.

----

```shell
for i in *; do
   echo $i
   key=$(xmllint --xpath "/resource/key/text()" $i/resource.xml 2> /dev/null)
   echo $key
   if [[ -n $key ]]; then
      curl --fail http://api.gbif-uat.org/v1/dataset/$key &> /dev/null || \
         mv -v $i ../archived-resources/
   fi
done

for i in $(find */resource.xml -mtime +365); do
   mv -v $(dirname $i) ../archived-resources/
done
```
