### ISSUE TITLE
IPT admin UI improvement - allow download of source files from admin menu

### ISSUE THREAD

**Issue by rukayaj** [gbif/ipt#1488]
I have inherited an IPT with many datasets, quite a few of which have xlsx spreadsheet data sources. Those spreadsheets are only available through the IPT, and it's a bit of a pain not to have an easy way of downloading them. I imagine this is a fairly common scenario for others too.

I can understand that the source files might potentially contain sensitive data which isn't published. So it doesn't make sense to have a link to the source files on the dataset page where you can download the DwCA etc, but wouldn't it make sense to have a download button from the admin interface (e.g. on http://localhost:8080/manage/source.do?r=test&id=test)?

**Comment by rukayaj** [comment]
Looks like it's related to #1008

**Comment by ahahn-gbif** [comment]
Hi @ rukayaj, thank you for the suggestion. At this time, there is no active development on the IPT, but we will keep your suggestion in mind when this picks up again.

**Comment by sylmorin-gbif** [comment]
Implemented in https://github.com/gbif/ipt/pull/1537

**Comment by sylmorin-gbif** [comment]
Hello @rukayaj ,

I'm sorry (and a bit shameful) I didn't see you also did the implementation, not just created the issue!
I totally write the same feature on my side without noticing your PR....

The good news: it has been merged and should be available in the next release.

Regards,
Sylvain
GBIF France

**Comment by mike-podolskiy90** [comment]
Thank you @rukayaj @sylmorin-gbif 
I close this
