### ISSUE TITLE
Update documentation and FAQ to reflect Debian SystemD default security settings

### ISSUE THREAD

**Issue by abubelinha** [gbif/ipt#1489]
### can't configure ipt data directory:

I am following these instructions to install a test ipt:
https://github.com/gbif/ipt/wiki/IPT2ManualNotes.wiki#set-up-the-ipt-for-the-first-time

I have already performed these steps:
https://lists.gbif.org/pipermail/ipt/2011-April/000328.html
https://github.com/gbif/ipt/wiki/FAQ.wiki#4-i-get-the-following-error-the-data-directory-directory-is-not-writable-what-should-i-do

In my case (Ubuntu 18 server, Tomcat 9), this is what I did (logged in as root):
```
# mkdir /mnt/iptestdata
# chmod 777 /mnt/iptestdata
# chown -R tomcat:tomcat /mnt/iptestdata
# ls -la /mnt
drwxr-xr-x  6 root   root   4096 jul 13 17:53 .
drwxr-xr-x 24 root   root   4096 jul  3 06:32 ..
drwxrwxrwx  2 tomcat tomcat 4096 jul 13 17:53 iptestdata
...
```
I restarted tomcat, just in case.

Then I browsed to ipt server:
http://10.10.10.10:8080/ipt-2.4.0/setup.do

But I still keep getting this message when trying to use "/mnt/iptestdata" as ipt data directory:

`The data directory "/mnt/iptestdata" is not writable
`

**Comment by abubelinha** [comment]
It would be good to add this explanation either to IPT installation instructions ([IPT setup I: data directory configuration](https://github.com/gbif/ipt/wiki/IPT2ManualNotes.wiki#ipt-setup)), or to FAQs point 4 ([data directory is not writable](https://github.com/gbif/ipt/wiki/FAQ.wiki#4-i-get-the-following-error-the-data-directory-directory-is-not-writable-what-should-i-do)):

https://stackoverflow.com/questions/56827735/how-to-allow-tomcat-war-app-to-write-in-folder/56835997#56835997

That was exactly my problem

**Comment by MattBlissett** [comment]
Thanks @abubelinha, I've reopened this to remind us to update the documentation.  It's not something I was aware of, since we are using CentOS 7 at GBIF. Debian looks to have introduced this less than a year ago.

**Comment by MattBlissett** [comment]
The FAQ item is now updated.
