### ISSUE TITLE
mapped concepts appear duplicated in some resources published to gbif test registry

### ISSUE THREAD

**Issue by abubelinha** [gbif/ipt#1491]
I am playing with a fresh IPT server in "test mode".
I had never played with the gbif-uat registry, so I have some questions about it:

**(1) What resources should I expect to find in gbif-uat.org portal?**

I was expecting to see only those resources served by "test mode" IPT servers, but that is not the case.

Some datasets I see here, are served from production IPT servers.
So I understand the gbif-uat.org portal is serving datasets from testing IPT servers, plus live-production IPT servers.

But in that case, shouldn't gbif-uat.org portal be serving more datasets than gbif.org portal?
I guess that's not true. If I search datasets, this is what I see:

[gbif-uat.org](https://www.gbif-uat.org/dataset/search): 48387 results
[gbif.org](https://www.gbif.org/dataset/search):        53799 results

Why does gbif-uat show less datasets?

**(2). Why do I see differences when I browse the same "real" occurrence dataset, in both portals?**

The same occurrence looks different:

https://www.gbif.org/occurrence/1265799898
Normal view

https://www.gbif-uat.org/occurrence/1265799898
All darwincore concepts are repeated (shown twice)

I tested with some other occurrenceIDs and it happens the same.
Isn't this a bug?

Not sure if this could happen in other kind of resources, but at least this is happening to **occurrence datasets**.
No matter if they are test datasets (published through IPTs in test mode) or normal datasets (IPTs in production mode).

**Comment by MattBlissett** [comment]
> (1) What resources should I expect to find in gbif-uat.org portal?

GBIF-UAT.org is a partial copy of GBIF.org, with enough data for us to test and demonstrate proposed changes to publishing, ingestion, processing and download processes, but not all the data as we do not maintain enough server capacity for that.

Since it starts as a copy of GBIF's Registry, it includes publishing organizations and datasets as they are in production, plus any additional ones created/published by users and developers in their own tests, training workshops and so on.  

> Why does gbif-uat show less datasets?

We occasionally reset GBIF-UAT, wiping out all the occurrences, setting the Registry to be a fresh copy from production, and losing all information of test datasets.  Since the last time this was done (fairly recently), the number of new, real datasets (on GBIF) is greater than the number of test datasets on GBIF-UAT.

> (2). Why do I see differences when I browse the same "real" occurrence dataset, in both portals?

Thanks for reporting this, it was a new bug, and it's been fixed.

**Comment by abubelinha** [comment]
Thanks for fixing it so quickly @MattBlissett 

Regarding my first question (resources available in gbif-uat portal), I have some related doubts.

I was planning to use gbif-uat for testing some new resources using cores and extensions I never used before (regional checklist and some other related stuff).
At the same time, I plan to consume those new resources from a gbif-api-based webapp. 
But for now, this should be done using the api against gbif-uat. 

Questions:

(1) Are all api calls used in gbif.org valid for gbif-uat.org, so I can safely tell people they can already use this webapp even if data are still coming from a provisional resource (test-mode IPT)?

(2) Are there any huge performance differences when using api against gbif-uat.org, compared to gbif.org?

(3) When you occasionally reset gbif-uat, how quickly can I put our webapp live again?
  Is gbif-uat registry affected by those resets? (resource ids deleted, or something like that)
  If not, I guess it does not affect my webapp because I can just publish a new resource version in the IPT and the webapp should go back to life.

**Comment by MattBlissett** [comment]
You can use GBIF-UAT for testing and development.

The API calls are the same, but the two systems (GBIF.org and GBIF-UAT.org) are independent.  Identifiers (datasetKey, occurrenceKey and so on) can be different, and will change if UAT is reset.  You can develop a system using test data on GBIF-UAT.org while you are preparing the real data for GBIF.org, but:

* we don't make any guarantee that GBIF-UAT.org will remain available -- if something goes wrong, fixing it is not the highest priority.
* it runs on older hardware with less capacity, but has much less data.  Performance varies accordingly. The biggest difference will be occurrence search, which I expect to be significantly slower on UAT.
* resetting the database takes less than an hour, but would probably be followed by many datasets being reprocessed.  When a dataset is re-submitted, it will get a new datasetKey (UUID), and the identifiers for occurrences and checklist records will be regenerated.

**Comment by abubelinha** [comment]
Thanks @MattBlissett, all that sounds reasonable.

One thing I forgot to ask: how often are gbif-uat resets?
(i.e when did gbif-uat start, and how many resets since that moment)
