### ISSUE TITLE
Upgrade GBIF dependencies

### ISSUE THREAD

**Issue by MattBlissett** [gbif/ipt#1496]
With significant work on Pipelines, the Registry etc, the IPT is now using fairly old versions of GBIF API, DWC API, GBIF Common etc.

Upgrade these to current versions.

**Comment by MattBlissett** [comment]
See #1533 for an upgrade of dwca-io.

**Comment by MattBlissett** [comment]
Solving #1346 first might help remove some of the old dependencies.

**Comment by mike-podolskiy90** [comment]
Motherpom should be updated too
