### ISSUE TITLE
Copyright notice in footer should be updated to 2020

### ISSUE THREAD

**Issue by ainsofs** [gbif/ipt#1501]
Similar to this issue -https://github.com/gbif/ipt/issues/602

The footer says © 2018, but should be 2020.  Or maybe 2010-2020?  I don't know the legalities.

What steps will reproduce the problem?
1. Browse any page

What version of the provider software are you using? The version should be
displayed in the footer of any page.
Version 2.4.2

What browser are you using?
ff

**Comment by MattBlissett** [comment]
Thanks -- it will be updated in the next release.

**Comment by ainsofs** [comment]
Great stuff and thanks for quick response
