### ISSUE TITLE
Problem with "Collector" + "Identified by" field types in Scratchpads

### ISSUE THREAD

**Issue by Archilegt** [gbif/ipt#1503]
Those fields correspond to the current "recordedBy" and "identifiedBy". See problem documentation at https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6169
Issue opened here following the suggestion of Peter Desmet, during TDWG 2020 session "Capturing Ideas for the Future of BioCASe Provider Software and the GBIF Integrated Publishing Toolkit (IPT)".
Can edit further if necessary.

**Comment by timrobertson100** [comment]
Thanks @Archilegt 

If I understand correctly from the discussion on that thread this is a Scratchpad issue, where they aren't letting a curator enter `recordedBy` and `identifiedBy` fields but instead internally SP is tying it to another content model.

Is there a specific concern you have on the IPT, or are you raising this as an example to make sure the IPT doesn't impose incorrect limitations on data mapping?
