### ISSUE TITLE
Cannot change auto-publish settings or turn it off without publishing a version

### ISSUE THREAD

**Issue by sylmorin-gbif** [gbif/ipt#1505]
If we want to change the auto-publish settings (change the frequency) or just turn it off, we have to click on the "Publish" button.
A new version is then published.

Example of issue: 
We had trouble with our DB used to generate the resource.
We wanted to turn off the auto-publish, to avoid publishing an incorrect version in a few days.
It was not possible since we had to click on "Publish and turn off"
To avoid publishing a corrupted version, we had to stop the IPT!

**Comment by sylmorin-gbif** [comment]
Here is the PR:
https://github.com/gbif/ipt/pull/1509

**Comment by MattBlissett** [comment]
Also merged, thanks!
