### ISSUE TITLE
Add options in auto-publish to define the next published date more precisely

### ISSUE THREAD

**Issue by sylmorin-gbif** [gbif/ipt#1506]
Currently, the next published date is calculated from the last publication date, by adding a number of days.
If we activate the auto-publish, with a "Monthly" frequency, on the 5th of March at 10am, the next publication will be on the 5th of April at 10am.

We would the following auto-publish options:
Annually: Month, Day of month, Hour, Minute
BiAnnually: 2 Months, Day of month, Hour, Minute
Monthly: Day of month, Hour, Minute
Weekly: Day in week, Hour, Minute
Daily: Hour, Minute

With these options, it would be possible to configure a "Monthly" frequency like these:
- Day of Month: every 1st day of month
- Hour/Minute: at 5pm

**Comment by sylmorin-gbif** [comment]
Here is the PR:
https://github.com/gbif/ipt/pull/1509

**Comment by MattBlissett** [comment]
Thanks, this looks good. I've merged the PR.
