### ISSUE TITLE
Define number of archives to keep

### ISSUE THREAD

**Issue by sylmorin-gbif** [gbif/ipt#1507]
When the archive mode is activated, we would like to configure how many archives will be kept on the IPT.

Ex: keep the 10 last versions of each resource

**Comment by timrobertson100** [comment]
This seems very sensible.

As a workaround, I wonder if a periodic, manual process that removed historical versions and restarted the IPT would simply remove them. If anyone gets a chance to test it, please post the results here.

**Comment by timrobertson100** [comment]
For a manual procedure (advanced users only):

**Be aware this has potential for unrecoverable data loss, and should only be attempted by someone familiar with the consequences**

- remove the versions from the resource.xml as described in [this issue comment](https://github.com/gbif/ipt/issues/1508#issuecomment-725512896)
- locate the associated files to remove and delete them from the file system. e.g. to remove version 1.1 of resource you delete:
    - `aaa-1.1.rtf`
    - `dwca-1.1.zip`
    - `eml-1.1.xml`
- restart the IPT

**Comment by sylmorin-gbif** [comment]
Like #1508 , it's sensible, indeed, but there is a problem to fix: how to avoid too much disk consumption, when auto publish is used.

And again, a manual process could be the solution - even if I trust more java code with unit testing than manual operations :) 

Here is the PR: https://github.com/gbif/ipt/pull/1514

**Comment by MattBlissett** [comment]
Thanks for working on this. I've merged it into the master branch, and tested it on UAT.
