### ISSUE TITLE
Problems to load registered vocabularies and extensions - IPT GBIF Peru

### ISSUE THREAD

**Issue by leo-buitrago** [gbif/ipt#1510]
The registered extensions and vocabularies from Registry: https://gbrds.gbif.org can't be loaded in this IPT https://ipt.minam.gob.pe/ipt/, so the datasets can not be updated or published properly and is not possible to manage the extensions y in the Administration IPT section.
<img width="982" alt="Screen Shot 2020-10-21 at 4 47 45 PM" src="https://user-images.githubusercontent.com/61566113/96791427-114e7300-13be-11eb-8dd8-dcb8a5bfa3bc.png">

I attached the log file from the IPT too ;)
[logfile.pdf](https://github.com/gbif/ipt/files/5418877/logfile.pdf)

**Comment by MattBlissett** [comment]
Problems like this are typically firewalls preventing the IPT server from contacting http://gbrds.gbif.org, https://gbrds.gbif.org, and http://rs.gbif.org / https://rs.gbif.org 

First check the server has access to the internet, or at least to 130.225.43.0/24 (GBIF's IPs).

(That English+French error is strange, I haven't seen that before.)

**Comment by MattBlissett** [comment]
@leo-buitrago, did you fix this with changes to the firewall etc?

Please reopen if it's still a problem.
