### ISSUE TITLE
Improve error reporting when the IPT does not have write permission to the data directory.

### ISSUE THREAD

**Issue by MattBlissett** [gbif/ipt#1511]
Many of the support requests to the helpdesk are straightforward permission errors -- Linux or Windows systems where basic filesystem permissions or more advanced security roles (SELinux etc) prevent the IPT from writing to the configured data directory.

Test this on Windows and Linux, and improve the error messages.

Remember some edge cases, e.g. Linux will remount a disk read-only if it has detected a failing drive; the IPT user may exceed a disk quota.

**Comment by sylmorin-gbif** [comment]
Hi,

When the access rights are not correct on the ipt/resources folder:

At **IPT startup**, we have the following message in debug.log:

`INFO  02-Nov-2020 10:26:16 [org.gbif.ipt.service.manage.impl.ResourceManagerImpl] - Data directory does not hold a resources directory: /tmp/ipt
`

In the UI, the list of resources is empty.

When we **create a resource**, we get the following error in the UI:

![image](https://user-images.githubusercontent.com/56630013/97850626-96a62180-1cf4-11eb-940f-879446e4393b.png)

In the debug.log, we have:

```
ERROR 02-Nov-2020 10:14:46 [org.gbif.ipt.service.manage.impl.ResourceManagerImpl] - java.io.IOException: Unable to create directory /tmp/ipt/resources/c02
ERROR 02-Nov-2020 10:14:46 [org.gbif.ipt.service.manage.impl.ResourceManagerImpl] - Error creating resource
org.gbif.ipt.service.InvalidConfigException: Can't write mapping configuration
	at org.gbif.ipt.service.manage.impl.ResourceManagerImpl.save(ResourceManagerImpl.java:2118) ~[classes/:?]
	at org.gbif.ipt.service.manage.impl.ResourceManagerImpl.create(ResourceManagerImpl.java:477) [classes/:?]
	at org.gbif.ipt.action.manage.CreateResourceAction.save(CreateResourceAction.java:91) [classes/:?]
	at org.gbif.ipt.action.POSTAction.execute(POSTAction.java:39) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]

```

**Comment by sylmorin-gbif** [comment]
What are the planned improvements for this ticket?

- displaying a warning message at the top of the IPT landing page?

![image](https://user-images.githubusercontent.com/56630013/97853500-78dabb80-1cf8-11eb-9d3d-ac734ab9178a.png)

- improving the error message when creating a resource? to give the reason why the resource creation failed

- improving the log message in debug.log? (ERROR instead of INFO at startup, ...)

**Comment by sylmorin-gbif** [comment]
Implemented here: https://github.com/gbif/ipt/pull/1536

**Comment by mike-podolskiy90** [comment]
Thanks @sylmorin-gbif . PR merged, I close this
