### ISSUE TITLE
UAT organisation missing UUID

### ISSUE THREAD

**Issue by JimCircadian** [gbif/ipt#1517]
Hello

I've noticed a selection of issues (one in particular #1483) in UAT/test mode, that might be affected by the following: 

When registering a GBIF with an organisation, the UAT list contains a record without UUID. This will obviously have the affect of triggering NullPointerExceptions in functions that don't have the correct handling for invalidly instantiated objects.

```
<select name="organisation.key" size="15" id="organisation.key" class="e1">
    <option value=""></option>
    <option value="...">&quot;	 Compensation International Progress S.A. -Ciprogress Greenlife-&quot;</option>
    <option value="...">A Rocha Ghana</option>
    <option value="...">A Rocha Kenya</option>
```

Would it be possible to correct the records in UAT/reseed the DB from live, as appropriate? This is obviously causing others issues, looking at the list. How a null object was created is the root issue to be solved, so happy to feed back an analysis if it helps.

**Comment by timrobertson100** [comment]
Thanks @JimCircadian 

It is the case that UAT is periodically refreshed, and test installations may need to be recreated as they are not intended to be long term installations. We'll schedule a reseeding for live, but that may be after Christmas now.

Can you help me understand which organisations you have in that snippet that have null keys? Does it really have `value="..."` or did you remove those for the paste, please?

Perhaps you could create me an account on the test IPT so I could explore it? (trobertson@gbif.org)

**Comment by JimCircadian** [comment]
Hello @timrobertson100 

Thanks for getting back to me. The null organisation is actually in the whole list of organisations returned from the UAT GBIF registry, so that first organisation is exactly as it appears, as `value=""`, it had no UUID associated with it (the `value="..."` have been redacted rather than being empty).

Absolutely understood that UAT is not a long term/reliable source of truth. Problem was that functionality seemed to be triggering NullPointerExceptions that fit with there being a null entry in the organisation list. How or why this is, I can't say, but I thought it interesting as something has managed to create this in UAT (unless it's also the case in production!) 

Interestingly, reinstalling the whole IPT instance cleared the issue for us, so our users are now happily evaluating in test mode. There also appears to be a fix for the NPE in the next release, but it'd be good to track this down (and I hope to get a dev setup going myself in the New Year if I've got time...)

All the best
