### ISSUE TITLE
Unable to load RSS feed containing the tags pubdate and lastBuildDate

### ISSUE THREAD

**Issue by susan1637** [gbif/ipt#1521]
I've installed the IPT server(2.4.2) under tomcat8 with a reverse proxy in apache2.4.6 (CentOS7). When I try to access its RSS feed through the browser, the request keeps pending and not responding. Also, there are no error messages in the apache error log. The RSS link is https://bgnn.tulane.edu/ipt/rss.do

See the screenshots below:

![{}C$Q`N%6_~M%9RJ`{1)QDD](https://user-images.githubusercontent.com/48254997/101171109-f1d57780-3604-11eb-950e-d901d098e656.png)
![RWH2(M6 @}5TFLV4Q{4$TV1](https://user-images.githubusercontent.com/48254997/101171127-f732c200-3604-11eb-97e6-210930c3f5ea.png)

I commented out pubDate and latePubDate in rss.ftl file when I was looking through all of the lines, and it didn't work.  However, the browser was able to load the RSS feed on my IPT server only if I removed both the pubDate and latePubDate lines. 

I'm not sure why these two tags lead to this problem. Could you help me with this?
![2M3AT $L BQ)CL7C(Y J`U](https://user-images.githubusercontent.com/48254997/101171612-9f488b00-3605-11eb-94a8-5f147b24f33a.png)

**Comment by MattBlissett** [comment]
Hi @susan1637,

The RSS at https://bgnn.tulane.edu/ipt/rss.do now includes `<lastBuildDate>` at the top, but doesn't have `<pubDate>`.  Did you find out what was wrong?

Were there any error messages in the IPT's logs, or the Tomcat logs?

**Comment by mike-podolskiy90** [comment]
@susan1637 Please reopen the issue if this problem is still present. Closing this
