### ISSUE TITLE
csrf token refreshes with requests to 'logo.do' and breaks the top login form

### ISSUE THREAD

**Issue by joshbeard** [gbif/ipt#1527]
Hello,
The login form at the top of the main IPT page does not function when the CSRF token doesn't match, as intended. However, requests to `/ipt/logo.do` cause IPT to generate a new CSRF token with every request and the login form doesn't get updated accordingly, causing logins to fail due to the mismatched token. The workaround is to login via `/ipt/login.do`

This was confirmed by blocking requests to `/ipt/logo.do`, which resulted in the top login form working as expected.

### Reproducing

To reproduce this, load IPT without being logged in with a page that has a resource with a logo (making a request to "login.do") and observe the `CSRFtoken` change while the login form's token does not. When logging in, a log message will look like:

```
WARN  13-Jan-2021 07:26:59 [org.gbif.ipt.action.AccountAction] - CSRF login token wrong! A potential malicious attack.
```

**Comment by sylmorin-gbif** [comment]
See PR https://github.com/gbif/ipt/pull/1535
Should do the trick by automatically refreshing the page (every 10 minutes - when not logged yet) before the CSRF token expires (every 15 minutes).

**Comment by joshbeard** [comment]
Thanks for the updates, @sylmorin-gbif!

**Comment by mike-podolskiy90** [comment]
Merged https://github.com/gbif/ipt/pull/1547
