### ISSUE TITLE
Error trying to reserve dois from IPT

### ISSUE THREAD

**Issue by RicardoOrtizG** [gbif/ipt#1528]
Hello!, 

The process to reserve dois from IPTs is showing this error.

![image](https://user-images.githubusercontent.com/15789737/105405470-2fb04e80-5bf9-11eb-975c-d0109b8464cb.png)

This is happening in all our IPT installations. ¿Do you know the cause of this or how can we fix it?

Thanks in advance for any help!

**Comment by mike-podolskiy90** [comment]
Thank you @RicardoOrtizG.

I think that might be wrong username or password of the DataCite account. Could you check those are correct please?

**Comment by RicardoOrtizG** [comment]
Exactly, the problem is already solved.  There was a change in the Datacite password that has to be changed in the IPT installations, it was the step we missed and the cause of the problem.

Thanks in advance
