### ISSUE TITLE
broken link in DwCAHowToGuide.md

### ISSUE THREAD

**Issue by abubelinha** [gbif/ipt#1531]
See this sentence in last section of the document ([DwC-A Examples](https://github.com/gbif/ipt/wiki/DwCAHowToGuide#dwc-a-examples)):

> The guide [How to publish biodiversity data through GBIF.org](https://github.com/gbif/ipt/wiki/howToPublishHow-To) ...

... is not available in the provided link.

I [annotated that](https://github.com/gbif/ipt/wiki/DwCAHowToGuide/_compare/bb2c3d1f7f6d7614c1252b374dbecaf750973edf), but I don't know what the correct link should be:

**Comment by sylmorin-gbif** [comment]
Hi,

I guess it should be: https://github.com/gbif/ipt/wiki/howToPublish

**Comment by MattBlissett** [comment]
Thanks both, I've updated that link and several others that were not working.

**Comment by damianooldoni** [comment]
@MattBlissett: I would like to report a new broken link I found at the very beginning of the [DwCA How To Guide](https://github.com/gbif/ipt/wiki/DwCAHowToGuide).

> This IPT wiki is no longer maintained. Please refer to this page in the [IPT User Manual](https://ipt.gbif.org/manual/dwca-guide).

**Comment by MattBlissett** [comment]
Thanks, Damiano, I've fixed these broken links.
