### ISSUE TITLE
add newly adopted DwC terms to GBIF's IPT as core terms of Occurrences

### ISSUE THREAD

**Issue by asimpson-usgs** [gbif/ipt#1532]
Last year TDWG accepted additional terms and new definitions for old terms to DwC's Occurrence group of terms. They now appear on the [quick reference guide](https://dwc.tdwg.org/terms/).
Specifically, **establishmentMeans**, **degreeOfEstablishment**, **pathway**, and **occurrenceStatus**.

**_I request these four terms be added to the GBIF IPT's Occurrence group of terms as soon as possible._** 
Their quick reference guide urls:
https://dwc.tdwg.org/terms/#dwc:establishmentMeans
https://dwc.tdwg.org/terms/#dwc:degreeOfestablishment
https://dwc.tdwg.org/terms/#dwc:pathway
https://dwc.tdwg.org/terms/#dwc:occurrenceStatus

**NOTE: none of the following URL anchor tags are currently resolving properly:**
https://dwc.tdwg.org/list/#dwc_establishmentMeans
https://dwc.tdwg.org/list/#dwc_degreeOfEstablishment
https://dwc.tdwg.org/list/#dwc_pathway
https://dwc.tdwg.org/list/#dwc_occurrenceStatus

**Comment by peterdesmet** [comment]
@asimpson-usgs

1. I have made a pull request to add/update these terms in the Distribution extension (used for checklists): https://github.com/gbif/rs.gbif.org/pull/66
2. Introducing these terms in the Occurrence core will likely take longer, as we want to combine the introduction of these terms with the upcoming Darwin Core changes that are currently under review.
3. The anchors now resolve

**Comment by MattBlissett** [comment]
The new terms and associated vocabularies are now in the "sandbox", and can be used by IPTs in test mode.  If you would assist by upgrading any test IPTs you use, and checking the mappings are fine, we'll be able to move them to production fairly quickly.

We do need to check the recordedByID/identifiedByID terms work properly with our system.  These were created as GBIF terms, but have now been adopted by DWC, which I think is a new situation.

**Comment by rukayaj** [comment]
@MattBlissett I've checked these on the GBIF Norway test IPT and the mapping is working fine (occurrence core) when I download the dwca directly from the test IPT, but the terms are not appearing on the GBIF UAT portal. Should they be? It would be super if we could publish our data with these terms soon.

**Comment by qgroom** [comment]
Yes, just as encouragement we also have a bunch of datasets and initiatives pending on these terms.

**Comment by MattBlissett** [comment]
Thanks Quentin, could you link a couple here? We can test them as we implement interpretation on gbif-uat.org.

**Comment by qgroom** [comment]
These are a couple of datasets that could be updated quickly

Verloove F, Groom Q, Brosens D, Desmet P, Reyserhove L (2020). Manual of the Alien Plants of Belgium. Version 1.10. Meise Botanic Garden. Checklist dataset https://doi.org/10.15468/wtda1m accessed via GBIF.org on 2021-12-11.

Reyserhove L, Groom Q, Adriaens T, Desmet P, Dekoninck W, Van Keer K, Lock K (2020). Ad hoc checklist of alien species in Belgium. Version 1.7. Research Institute for Nature and Forest (INBO). Checklist dataset https://doi.org/10.15468/3pmlxs accessed via GBIF.org on 2021-12-11.

**Comment by rukayaj** [comment]
Thanks for your work on this, guys!

**Comment by qgroom** [comment]
> Thanks for your work on this, guys!

Seconded!
