### ISSUE TITLE
Slow Darwin Core mapping page

### ISSUE THREAD

**Issue by niconoe** [gbif/ipt#1542]
Hi,

We (INBO, @DimEvil) are having some Darwin core mapping pages that are quite slow (sometimes lead to timeouts) on our IPT instance. I'd like to understand a bit more what's happening behind the scenes to see if I should just throw more RAM/CPU at the machine, or if there's something else happening. Unfortunately I can't easily understand and navigate the struts code :/

So I'd like to know:

- what is the typically most intensive task when displaying the mapping page? Should that need a lot of RAM? CPU cycles?
- in our cases, the data source is a database. Maybe the IPT is creating SQL queries for each mapped field (to show the sample values)? If so, I might also investigate if the database (network access, table structure, ...) is not the root cause. Is there an easy way to ask the IPT to log/show all executed queries, ideally with their response time?

Thanks a lot, any guidance would help!

**Comment by mike-podolskiy90** [comment]
Thank you @niconoe for reporting the issue.
I can't say for sure but I suspect that might be a slow connection to the database. 
You can enable SQL logging in the IPT debug mode in the current snapshot 2.5.0 version. Could you try this?

**Comment by mike-podolskiy90** [comment]
closing this
