### ISSUE TITLE
Cannot upload logo

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#1544]
I'm not sure this is just on our IPT (IPT Version 2.4.2-rd9bfb4b) or a new bug, but I **cannot upload a resource logo** anymore. Pointing to an existing logo URL still works.

## Steps

1. Go to `Additional metadata`
2. Under logo `Choose file` to add a logo from local computer
3. Click `Upload`
4. Page goes to `Basic Metadata` and indicates: Additional Metadata section successfully saved!
5. Navigate back to `Additional metadata`
6. No logo was uploaded.

## Expected (and previous) behaviour

Clicking `Upload` uploads the logo and does not navigate away to `Basis Metadata`

**Comment by mike-podolskiy90** [comment]
Fixed. Will be included in the 2.5.0 release
