### ISSUE TITLE
make admin contact configurable

### ISSUE THREAD

**Issue by pieterprovoost** [gbif/ipt#1552]
It seems that the admin contact currently corresponds to the first admin user in `users.xml`, see https://github.com/gbif/ipt/blob/master/src/main/java/org/gbif/ipt/action/LoginAction.java#L48

In some cases we would like to be able to configure the preferred admin contact, for example by tagging an admin user as the preferred contact, or by making the contact email address a configuration option.

**Comment by mike-podolskiy90** [comment]
Thank you @pieterprovoost

@timrobertson100 there are quite a few solutions to this. We could add a marker field at the "Edit User Account" page or add a email\user select to the IPT settings. What do you think?

**Comment by mike-podolskiy90** [comment]
CC @MattBlissett

**Comment by MattBlissett** [comment]
The page https://ipt.gbif-uat.org/admin/registration.do already has two fields for email/user, and these are sent to the GBIF registry: https://www.gbif-uat.org/installation/8949a635-0eb0-4bf1-aaf9-9af97a0ea949

I might be missing what has been requested here.  Where is the first admin contact used?

**Comment by bart-v** [comment]
For password reset request!

**Comment by MattBlissett** [comment]
Ah, thanks.

I suggest allowing an administrator to choose one of the administrators to be the one to receive password resets etc, i.e. the marker field.

**Comment by mike-podolskiy90** [comment]
New text box "IPT administrator email" added to Administration -> IPT settings.
Deployed to UAT.
