### ISSUE TITLE
IPT setup part II error

### ISSUE THREAD

**Issue by zhoufeiyu** [gbif/ipt#1555]
When I set up IPT for the first time, I filled in the information in the second step without any error. I clicked save, but I couldn't jump to the normal page, as shown in the screenshot, how can I solve it, thank you.
![image](https://user-images.githubusercontent.com/16423139/115350879-39415680-a1e8-11eb-9a11-44194cde9070.png)

**Comment by ManonGros** [comment]
Hi @zhoufeiyu
I have seen this type of issue before when someone tries to run the IPT in production mode with a localhost URL.
Could it be the case for you?

If you want to run your IPT in **production** mode, you will need to use a URL accessible from the internet. The IPT in production mode, functions as a publicly accessible website. GBIF (and in practice, anyone) should be able to access it and harvest the datasets published. So it requires a web server to be set up and the firewall settings to be adjusted accordingly.
You can run your IPT on a localhost URL in **test** mode. This won’t allow you to publish data on GBIF, but it will allow you to work in an enclosed, test environment.

If you think the issue could be somewhere else, could you give us some more details? Thanks!

**Comment by zhoufeiyu** [comment]
After I choose the test environment and click Save, I can't jump to the correct page. How can I configure the base URL?
![image](https://user-images.githubusercontent.com/16423139/115804083-cd900100-a414-11eb-95fa-e1016fec9abe.png)

**Comment by MattBlissett** [comment]
Hi,

On the first screenshot, you are accessing your IPT at http://localhost:8080/ipt/..., so the Base URL should be http://localhost:8080/ipt/

Note that using "localhost" will only allow access from your computer, _not_ the internet.  You'll need to use a public hostname (ipt.genomics.cn or similar) for the IPT to be accessible to the internet.  Usually, someone in the IT department needs to help set this part up.

**Comment by zhoufeiyu** [comment]
Thank you very much. I think I understand.

**Comment by zhoufeiyu** [comment]
> 你好，
> 
> 在第一个屏幕截图中，您正在通过[http：// localhost：8080 / ipt /](http://localhost:8080/ipt/) ...访问IPT ，因此基本URL应该为[http：// localhost：8080 / ipt /](http://localhost:8080/ipt/)
> 
> 请注意，使用“本地主机”将仅允许从您的计算机进行访问，_而不能_访问Internet。您需要使用IPT的公共主机名（ipt.genomics.cn或类似名称）才能通过互联网访问。通常，IT部门的某人需要帮助设置这一部分。



> Hi,
> 
> On the first screenshot, you are accessing your IPT at http://localhost:8080/ipt/..., so the Base URL should be http://localhost:8080/ipt/
> 
> Note that using "localhost" will only allow access from your computer, _not_ the internet. You'll need to use a public hostname (ipt.genomics.cn or similar) for the IPT to be accessible to the internet. Usually, someone in the IT department needs to help set this part up.

Thank you very much, I think I understand.

**Comment by zhoufeiyu** [comment]
> Hi,
> 
> On the first screenshot, you are accessing your IPT at http://localhost:8080/ipt/..., so the Base URL should be http://localhost:8080/ipt/
> 
> Note that using "localhost" will only allow access from your computer, _not_ the internet. You'll need to use a public hostname (ipt.genomics.cn or similar) for the IPT to be accessible to the internet. Usually, someone in the IT department needs to help set this part up.

Thank you very much, I think I understand.
