### ISSUE TITLE
During Set up - Make error message more explicit if the base URL is incorrect

### ISSUE THREAD

**Issue by ManonGros** [gbif/ipt#1556]
This happened to at least one of our users on helpdesk:
1. They install the IPT
2. On the Set up II page, they didn't understand that they couldn't use a localhost URL with the IPT set up in production mode
3. They saw the error message (and might have changed a bit the URL but still kept localhost) and clicked on save.
4. They got back to the set up page but with a broken layout (like in this issue: https://github.com/gbif/ipt/issues/1555) and couldn't do anything else.

I think ending up on a page that looks "different" can be distracting these users from the real issue. It would be good to have a way to be more explicit at that point. Or maybe prevent saving a localhost base URL in production mode?

**Comment by MattBlissett** [comment]
> Or maybe prevent saving a localhost base URL in production mode?

I think that is a good solution.

**Comment by mike-podolskiy90** [comment]
I've fixed a broken layout for the setup2 page.
![Screenshot 2021-05-27 at 15 25 41](https://user-images.githubusercontent.com/24795387/119834039-e4d47980-beff-11eb-9b4e-80bfd284d1db.png)
@MattBlissett @ManonGros is the current message fine?

**Comment by mike-podolskiy90** [comment]
Thank you, I changed the error message. Close this
