### ISSUE TITLE
citation identifier only accepts up to 100 characters

### ISSUE THREAD

**Issue by ManonGros** [gbif/ipt#1559]
One of our users found that this restriction didn't allow him to share the URL for the resource associated with the citation.
Would it be possible to allow longer strings in the next IPT version?

**Comment by mike-podolskiy90** [comment]
How many characters would we like to have please? max 150?

**Comment by ManonGros** [comment]
I am not sure, but the particular URL that triggered this issue is 114 characters. I think 150 or even 200 characters should be ok.

**Comment by mike-podolskiy90** [comment]
Thank you, let's increase to 200 characters then.
