### ISSUE TITLE
[EML edition] Generate temporal coverage

### ISSUE THREAD

**Issue by sylmorin-gbif** [gbif/ipt#1565]
During the EML edition, we could offer to generate the temporal coverage by analyzing the source data.

If the source data is already mapped, we could use the eventDate column.

**Comment by peterdesmet** [comment]
I like this idea. Ideally this (and other) generators should support:

1. Empty temporal coverage page > Click button to populate it > User can adapt > Save page or cancel.
2. Filled out temporal coverage page > Click button to populate it (replacing old content) > User can adapt > Save page or cancel.
3. Maybe: use auto-setting to generate the content on each republication.

**Comment by sylmorin-gbif** [comment]
Thanks for this very important comment: what do we do when we update the source file and re-publish? (I totally forget this part)

We can let the user go back to EML edition and click on "populate" again.
But it could be forgotten (like I did....)

So we should add an option, along with the populate button, if we want to automacilly re-populate this coverage when publish is triggered.

**Comment by peterdesmet** [comment]
Yes, I consider it similar to the citation auto-generate option:

<img width="259" alt="Screenshot 2021-04-28 at 12 05 29" src="https://user-images.githubusercontent.com/600993/116386431-0b789500-a81a-11eb-94e5-9fb6d2af89dd.png">

**Comment by sylmorin-gbif** [comment]
![Peek 2021-07-22 17-03](https://user-images.githubusercontent.com/56630013/126663567-733f4bb3-4988-4bf0-89f8-712a23fb9294.gif)

**Comment by sylmorin-gbif** [comment]
(similar to https://github.com/gbif/ipt/issues/1566)

When activated (like on the video), the temporal coverage will be automatically inferred, everytime we publish.

A new JSON service has been developped to produce these inferred data, from the sources data (the mapping is required first):
http://localhost:8080/api/metadata/coverage?r=coverage_test
{"data":{"eastBoundingCoordinate":1.71635,"maxDate":"2020-09-09T02:00:00","minDate":"2016-10-06T02:00:00","northBoundingCoordinate":50.02353,"southBoundingCoordinate":49.86935,"westBoundingCoordinate":1.488591}}

I started with a basic implementation, and then, I moved to a more robust one, by re-using GBIF code:
https://github.com/gbif/pipelines/blob/dev/sdks/core/src/main/java/org/gbif/pipelines/core/parsers/temporal/TemporalParser.java

I did not duplicate this code, but added the maven dependency:

<groupId>org.gbif.pipelines</groupId>
<artifactId>core</artifactId>

What do you think about this @mike-podolskiy90 , @MattBlissett , @timrobertson100 ? (especially the IPT --> GBIF-pipeline-core dependency)

**Comment by mike-podolskiy90** [comment]
Thanks @sylmorin-gbif 
I do not support the idea of having a pipelines dependency in the IPT

**Comment by MattBlissett** [comment]
We shouldn't have pipelines as a dependency, but it is good to use the same parser.

We can either use the parsers project which is already a dependency (e.g. https://github.com/gbif/parsers/blob/master/src/main/java/org/gbif/common/parsers/date/TemporalParser.java though I think it's been changed since being copied into pipelines), or [split the pipelines parsers into a submodule](https://github.com/gbif/pipelines/issues/579).

**Comment by sylmorin-gbif** [comment]
Hi @MattBlissett and @mike-podolskiy90 
Totally agree that adding a dependency to pipelines was weird, but still better than duplicating the code :) 
I will rather use the parsers project I haven't noticed !
