### ISSUE TITLE
Resource creator and citation generation

### ISSUE THREAD

**Issue by heidivanvliet** [gbif/ipt#1570]
Hello,

Are we able to have more flexibility in the resource creator section where the auto-generation comes from to have an institution/division or organization as the contact name instead of an individual's name (e.g., "Stock Assessment and Research Division (2021) …" rather than "van Vliet H (2021) …")? We have worked around this for now by using a period as the first name and the division/section/institution as the last name (if first name is blank, the last name will not show up in the citation). 

Second request for citation generation - the year that is auto-generated appears to be when the resource was first created but it is the latest publication date on GBIF - can we make it the latest publication date for IPT/OBIS as well instead of when the resource was created? 

Thanks!

Heidi van Vliet
Fisheries and Oceans Canada
OBIS Canada node

**Comment by ahahn-gbif** [comment]
In the present setup, contacts are indeed expected to be persons, and the auto-generated citation is following bibliographic practice. There is no plan so far to add institutional entities as an alternative to that role in the citation generation, so your current work-around would be the option of choice to achieve that. The date is intended to be that of the dataset publication, though the version number of subsequent updates should be part of the citation.

Could I ask - is this in the context of making datasets available through GBIF.org, or within an OBIS setup? When accessed through GBIF.org, the case of citing a whole source dataset and only that is relatively rare. Most users would cite combined downloads with the contribution of multiple sources, identified by a citable download DOI. Datasets accessed directly through their IPT endpoint at source can still be issued a custom citation string. This is overruled in the GBIF metadata update procedures; I am not sure about OBIS central procedures on that.

**Comment by mike-podolskiy90** [comment]
I'm closing this. Please reopen it if it's still relevant
