### ISSUE TITLE
Support Markdown (or HTML) in EML

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#1571]
Dataset metadata could be made more readable if it supports Markdown/HTML, allowing e.g. named links, lists and `code` (for fieldnames). Zenodo (example: https://doi.org/10.5281/zenodo.3540799) supports this by being able to switch the editor between text and html view, but Markdown would be much more convenient. When I type HTML code in the IPT metadata editor however, it is all escaped to HTML-save characters, e.g. `&lt;`.

I haven’t tried myself, but handcrafted EML already seems to support HTML. See e.g. the paragraphs and list of sources in https://www.gbif.org/dataset/d7dddbf4-2cf0-4f39-9b2a-bb099caae36c

**Comment by abubelinha** [comment]
I also find this very convenient.

**Comment by MattBlissett** [comment]
Typing HTML into the dataset description produces escaped output in the IPT, but it is sent unescaped to the GBIF registry.  The registry accepts HTML elements according to this sanitizer policy: https://github.com/gbif/registry/blob/cdb1358a56438de71eaf652223a3a0225fdb0c55/registry-service/src/main/java/org/gbif/registry/service/RegistryDatasetServiceImpl.java#L68-L77

The IPT should probably allow the same HTML elements.

I do not like it, since it seems very strange to embed non-XML syntax into an XML document when XHTML already exists, but EML 2.2 supports Markdown in text elements: https://eml.ecoinformatics.org/whats-new-in-eml-2-2-0.html#markdown-support — that will need wider changes.

**Comment by abubelinha** [comment]
@MattBlissett not sure if I understood you.

When you say "The registry accepts HTML elemets" you mean so it is already possible to create html lists, titles, font styles and things like that ... in a GBIF dataset homepage?

How should we type them in the IPT metadata editor, so?
Can you provide an example?

**Comment by MattBlissett** [comment]
Hi @abubelinha,

HTML can be written directly into the metadata boxes within the IPT:

![image](https://user-images.githubusercontent.com/583320/127644655-e41d9a2a-1a2c-4046-8b1e-c693739f8599.png)

It then shows on the dataset page:

![image](https://user-images.githubusercontent.com/583320/127644745-ffa954aa-943c-488a-bbc6-bcce79cf9075.png)

The description on the IPTs own page is ugly: https://ipt.gbif.org/resource?r=test_nina but I think this is fixed in the upcoming version 2.5.0.

**Comment by abubelinha** [comment]
Great! 
I never got that working, but I guess it was because the ugly IPT visualization made me believe it was not going to work in gbif portal either.

**Comment by peterdesmet** [comment]
Nice! I had the same impression as @abubelinha: since it looked ugly in the IPT, I thought it wouldn't work in the GBIF portal. So, I guess this issue could be scoped to supporting HTML rendering in the IPT as well?

It would be nice if users could type Markdown and it gets immediately translated to HTML behind the scenes, but that might be too much for this issue.

**Comment by mike-podolskiy90** [comment]
In the 2.5.0 IPT it's still the same. We can start supporting HTML there, but we automatically convert URLs in the description to HTML links so this functionality may stop working. I mean if someone wants a URL to be displayed as a link at the resource page one should write it explicitly:
`<a href="http://somelink">somelink</a>`

**Comment by peterdesmet** [comment]
@mike-podolskiy90 the GBIF portal renders HTML formatting _and_ parses raw links, see https://www.gbif-uat.org/dataset/5f1893ae-e0ed-4129-9ef4-2e7562f2cc7b#description Can't the IPT do the same?

Note that the GBIF portal renders raw links slightly better than the [IPT](https://ipt.gbif.org/resource?r=test_nina):

> January 2019 (<https://sisu.ut.ee/publish-sequence-datasets/avaleht>).

vs IPT:

> January 2019 [(https://sisu.ut.ee/publish-sequence-datasets/avaleht).](https://sisu.ut.ee/publish-sequence-datasets/avaleht)

**Comment by mike-podolskiy90** [comment]
GBIF portal calls internal API which provides ready-to-go data:
https://www.gbif-uat.org/api/dataset/5f1893ae-e0ed-4129-9ef4-2e7562f2cc7b

We may find a way how to deal with links in the future. For now IPT will render HTML without wrapping links.

**Comment by abubelinha** [comment]
Is HTML supposed to be rendered now in IPT 2.6.0?

I still see sections where it works and sections where it does not.

**Comment by mike-podolskiy90** [comment]
@abubelinha could you please be more specific

**Comment by abubelinha** [comment]
Sorry, clicked _comment_ by accident, before finished:
- In the [GBIF portal](https://www.gbif-uat.org/dataset/89782cd1-871e-42ed-98a0-90c1117532ab) , bibliography section italics (on 1st title) are rendered as raw html.
- In the [IPT interface](http://193.144.34.193/iptest/resource?r=fake-test), almost every section shows raw html (except description, I think).

**Comment by mike-podolskiy90** [comment]
@abubelinha Thank you for clarification. Yes indeed, it works only for the main description.
I'll add for the rest of metadata too

**Comment by abubelinha** [comment]
Thanks.
I never had the impression that this issue was limited to the main description.
(I thought comments and examples above were supposed to be valid for every metadata section).

**Comment by abubelinha** [comment]
@MattBlissett 
> Typing HTML into the dataset description produces escaped output in the IPT, but it is sent unescaped to the GBIF registry. The registry accepts HTML elements according to this sanitizer policy ...

I have noticed "project" section in portal page does still not support HTML:
https://www.gbif-uat.org/dataset/2adad0d3-6150-4eb7-ac89-b59b71833045/project

Same thing happens to bibliography section:
https://www.gbif-uat.org/dataset/2adad0d3-6150-4eb7-ac89-b59b71833045#bibliography

So it looks like IPT is now better than portal in HTML-rendering.
Should I open a new issue in portal-feedback?

**Comment by mike-podolskiy90** [comment]
@abubelinha Yes please
