### ISSUE TITLE
Extra "</div>" shown in publication-with-DOI confirmation box

### ISSUE THREAD

**Issue by MattBlissett** [gbif/ipt#1572]
![image](https://user-images.githubusercontent.com/583320/118523981-fb2f4800-b73d-11eb-9831-857c95814042.png)

This is the box shown when publishing a minor version of a dataset with a DOI. The similar box for a major version has the same problem.

https://ipt.gbif-uat.org/manage/resource.do?r=gb22s8uc3-andre can be used to test this, it has a test DOI.

**Comment by mike-podolskiy90** [comment]
Thank you for spotting this. I've fixed that and deployed to UAT
