### ISSUE TITLE
Redundant Term Classes - cannot map terms to Extension 

### ISSUE THREAD

**Issue by thomasstjerne** [gbif/ipt#1579]
The [DNA derived data extension](https://rs.gbif.org/sandbox/extension/dna_derived_data_2021-05-14.xml) has some terms (e.g. `concentration` and `concentrationUnit`) placed in the group `MaterialSample `.
When mapping data to the extension, it is not possible to map those terms, the UI shows this "Redundant Term Classes":

<img width="700" alt="Screenshot at May 26 13-42-54" src="https://user-images.githubusercontent.com/1666484/119658721-c43bef00-be2d-11eb-94ee-46209b00e1c7.png">

**Comment by mike-podolskiy90** [comment]
Thanks for spotting this @thomasstjerne.

That's [ExtensionManager](https://github.com/gbif/ipt/blob/master/src/main/java/org/gbif/ipt/service/admin/impl/ExtensionManagerImpl.java#L654) functionality. We probably have to change somehow.

**Comment by mike-podolskiy90** [comment]
Redundant classes can be shown and mapped if press `Show all classes` link in the side navigation. 

![Screenshot 2022-05-31 at 14 16 58](https://user-images.githubusercontent.com/24795387/171171457-88524cc2-b76d-4d26-a756-0912cc30ca6f.png)

I changed an intro there to point out that it's still possible:
![Screenshot 2022-05-31 at 14 16 17](https://user-images.githubusercontent.com/24795387/171171543-ae63feea-2335-4462-8f88-d0c7b9d8aa70.png)

**Comment by mike-podolskiy90** [comment]
a6314dd346a4eadb0d56e4e7f59752fa7cca6403
