### ISSUE TITLE
Strange encoding corruption on Tomcat 9 on Windows

### ISSUE THREAD

**Issue by MattBlissett** [gbif/ipt#1582]
I installed Tomcat 9 using the Windows installer, and deployed the IPT.

The file `/ipt/styles/bootstrap/bootstrap-5.0.0-beta3.min.css` is corrupted, `content:"— "` has become `content:"â€” "` (which messes up the icons on the main resource table).

The file bootstrap-5.0.0-beta3.min.css on disk is 154875 bytes, on both Linux and Windows.  Downloading with 'curl' from the Linux IPT gives an identical 154875B file, but downloading from the Windows IPT gives a corrupt 154880 byte file.

I think we should investigate this, rather than making a workaround (e.g. replacing — with \u8212 in the CSS) since the same issue might corrupt EML etc.

(Around 10% of up-to-date-ish IPTs are running on Windows, 5% on FreeBSD, the rest on Linux.)

**Comment by mike-podolskiy90** [comment]
@MattBlissett Could you investigate this please?

**Comment by MattBlissett** [comment]
This was due to the default servlet (which serves static resources) using the system encoding for files, and recoding them for HTTP requests.

I've added BOMs to the CSS and JS which was not ASCII, which Tomcat detects. It doesn't try and re-encode these files.
