### ISSUE TITLE
IPT uses non https URLs for Javascript libraries even when X-Forwarded-Proto: https; passed

### ISSUE THREAD

**Issue by vollmerk** [gbif/ipt#1589]
Using NGINX proxy with the following configuration
```
  location /ipt {
    proxy_pass            http://127.0.0.1:8082/ipt;
    proxy_read_timeout    90s;
    proxy_connect_timeout 90s;
    proxy_send_timeout    90s;
    proxy_set_header      Host $host;
    proxy_set_header      X-Real-IP $remote_addr;
    proxy_set_header      X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header      X-Forwarded-Proto: https;
    proxy_set_header      Proxy "";
  }
```
IPT writes it's urls with http:// on the setup2.do page. Data directory is defined and the following settings are in the ipt.properies file
```
ipt.baseURL=https\://{EXTERNAL DOMAIN}/ipt
```

Expectation is that when `X-Forwarded-Proto: https` is set or based on the currently browser location IPT should write urls with the relevant protocol, `https`.

**Comment by MattBlissett** [comment]
Thanks for the report.  This will be fixed in the next test release, i.e. version 2.5.0-RC2.
