### ISSUE TITLE
docker ipt - azure sql database

### ISSUE THREAD

**Issue by steinho** [gbif/ipt#1590]
Hi

Trying to connect to azure sql database and get the following error: Error: Reason: Login failed due to client TLS version being less than minimal TLS version allowed by the server.

I do not want to lower TLS requirements (now 1.2), not very experienced with java/tomcat .....
Found some hints googling: https://stackoverflow.com/questions/48464863/java-1-8-0-enable-tls1-2-in-jdbc-connection

Any way to handle/fix this?

Stein

**Comment by steinho** [comment]
I've tried modifying jdbc.properties inside docker image and can tell from error message that changes are being picked up after image restart - but still complaining with reason: Login failed due to client TLS version being less than minimal TLS version allowed by the server.
![image](https://user-images.githubusercontent.com/3253353/121850454-15ccf080-cced-11eb-9e14-4e50cc933145.png)

**Comment by steinho** [comment]
Answering my own issue: 

Dropping mssql-jdbc-9.2.1.jre8.jar from microsoft inside the docker image -at  /usr/local/tomcat/webapps/ROOT/WEB-INF/lib
and change jdbc.properties to 
# Microsoft SQL Server
mssql.title=Microsoft SQL Server
mssql.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
mssql.url=jdbc:sqlserver://{host};databaseName={database}
mssql.limitType=TOP

Seems to fix issue

Is there any reason why microsoft own lib is not included - should be the most compatible?
License is pretty open.... https://github.com/microsoft/mssql-jdbc

**Comment by MattBlissett** [comment]
Thanks, @steinho, you are ahead of us.  

I think the third party MS SQL driver is from long ago, when there was no freely-licensed Microsoft version available.  We can now include this, although we'll need to consider if we replace the `mssql` driver, or add a new entry.

**Comment by steinho** [comment]
I't might require some testing - but functionally I would think it replaces it.
