### ISSUE TITLE
Show "Integrated Publishing Toolkit" in the header

### ISSUE THREAD

**Issue by MattBlissett** [gbif/ipt#1604]
...or something similar. V2.4 has this:

![image](https://user-images.githubusercontent.com/583320/123670044-10b78780-d83d-11eb-9623-fb5c1167c5f0.png)

But v2.5.0-RC1 only has the GBIF logo:

![image](https://user-images.githubusercontent.com/583320/123670088-2167fd80-d83d-11eb-982f-62f0184d5c1e.png)

**Comment by mike-podolskiy90** [comment]
We discussed that with Tim and Kyle, and decided to get rid of any text there. Unless something changed we can close this

**Comment by timrobertson100** [comment]
What's the motivation for this Matt, please? 
We modelled it following GBIF.org style where only the configured logo would appear, and with each page having a title to give context. This can of course be revisited if people think it doesn't work.

**Comment by MattBlissett** [comment]
The gbif.org homepage has "GBIF | Global Biodiversity Information Facility" on the homepage.  The domain name of the site is also our name.

It seemed like an oversight not to have "Integrated Publishing Toolkit" visible anywhere on the IPT, other than the page footer.

If it's intentional then there's no issue.

**Comment by mike-podolskiy90** [comment]
We could probably add that to the login page somehow. I don't think we should add that to every single page header

**Comment by MattBlissett** [comment]
Tim said it was a conscious decision, so it should stay as it is.
