### ISSUE TITLE
More useful header for Resource overview page

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#1605]
I notice the overview page has a title and then an explanation repeating the title (this was also the case in the older version of the IPT):

<img width="713" alt="Screenshot 2021-07-09 at 15 12 13" src="https://user-images.githubusercontent.com/600993/125084073-686db280-e0c9-11eb-852d-a46aed146d53.png">

Can I suggest to replace this with instructions:

<img width="712" alt="Screenshot 2021-07-09 at 15 18 51" src="https://user-images.githubusercontent.com/600993/125084133-7ae7ec00-e0c9-11eb-8b3c-e16404bb6099.png">

Note:

- I removed the `i` button next to the title. I think that content is now partly replaced by the instructions. The text regarding DOI assignment should go into the registration section imo.
- I removed `Overview:` from the title. I find the title of the dataset a better title for this page. In the sentence below it is indicated this is an overview page for the resource.

**Comment by MattBlissett** [comment]
Good idea. I've change the subtitle, but left "Overview" as it distinguishes it from the published page and keeps it consistent with all the other editing pages.

![image](https://user-images.githubusercontent.com/583320/125096471-788b8f00-e0d5-11eb-84ab-185d55322ade.png)

**Comment by mike-podolskiy90** [comment]
@MattBlissett can we close this please?

**Comment by MattBlissett** [comment]
Yes, thanks.
