### ISSUE TITLE
Incorrect warning indicating IPT runs in Test mode

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#1606]
After updating to 2.5-RC1 I noticed a warning on the resource overview page:

<img width="542" alt="Screenshot 2021-07-09 at 15 27 22" src="https://user-images.githubusercontent.com/600993/125085051-753ed600-e0ca-11eb-9cbe-5ee949b049dc.png">

This is incorrect, our IPT is running in production and the resource has been registered already: https://ipt.inbo.be/resource?r=dieren-exoten-natuurpunt-occurrences

**Comment by mike-podolskiy90** [comment]
Thank for reporting this @peterdesmet 
This fix will be included in the next release (2.5.0-RC2)
