### ISSUE TITLE
Broken link in GMPHowToGuide

### ISSUE THREAD

**Issue by Jegelewicz** [gbif/ipt#1607]
![image](https://user-images.githubusercontent.com/5725767/125663587-dee5b163-6858-476f-bf44-4abd4ec8381d.png)

The link to organizationName in the [GMPHowToGuide](https://github.com/gbif/ipt/wiki/GMPHowToGuide#people-and-organisations) does not appear to be working.

**Comment by MattBlissett** [comment]
Thanks; I've fixed it on the new documentation site: https://ipt.gbif.org/manual/en/ipt/2.4/gbif-metadata-profile#people-and-organizations

I've also updated more of the links on the wiki site to go to the new site.
