### ISSUE TITLE
Make the text clickable on Administration page

### ISSUE THREAD

**Issue by sylmorin-gbif** [gbif/ipt#1608]
On Administration page, only the icons are clickable (IPT settings, Bulk publication, ...)

It would be nice if the text also (or the whole row) was clickable.

![image](https://user-images.githubusercontent.com/56630013/125771216-4fce8249-f23f-4037-be4e-261df54bb8f8.png)

**Comment by mike-podolskiy90** [comment]
Thank you for the suggestion. I'm planning to redesign the admin page a little bit.

![Screenshot 2021-07-16 at 10 40 33](https://user-images.githubusercontent.com/24795387/125919479-b99aeaea-446b-4553-a44c-cccdc56823f3.png)

Those will be fully clickable.
