### ISSUE TITLE
Open TDWG mapping links in new tab

### ISSUE THREAD

**Issue by sylmorin-gbif** [gbif/ipt#1609]
On the Mapping page, there are some documentation in tooltip.
If we click on links in these tooltips (like a TDWG link) it's opening in the current tab, loosing the current mapping.

It would be better if these links were opened in a new tab.

![image](https://user-images.githubusercontent.com/56630013/125771446-664f5528-a4df-4995-b20d-29f7a1142a36.png)

**Comment by sylmorin-gbif** [comment]
See PR: https://github.com/gbif/ipt/pull/1611

**Comment by mike-podolskiy90** [comment]
Thank you. PR merged, closing this
