### ISSUE TITLE
Add source / links in tooltip do not work in 2.5.0-RC1

### ISSUE THREAD

**Issue by sylmorin-gbif** [gbif/ipt#1610]
On the Add source page, there are tooltips for fields: Number of Header Rows, Field Quotes, ...
In the tooltip description, there are links that can be clicked to automatically fill the related input.

It does not work anymore in 2.5.0-RC1 (tested with Chrome): clicking on the links has no effect - no javascript error

**Comment by sylmorin-gbif** [comment]
![Peek 2021-07-15 15-13](https://user-images.githubusercontent.com/56630013/125794355-a7d6aa50-7bd1-41bf-aee4-c84c1dd012b5.gif)

**Comment by mike-podolskiy90** [comment]
Thank you for the bug report. JS does not work properly there. I'll fix
