### ISSUE TITLE
ManagerFactory [org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory@2587760f] unable to create manager for [/srv/datadir/logs/debug.log] with data...

### ISSUE THREAD

**Issue by alegnaaived** [gbif/ipt#1616]
Hi everybody,

I would like to get your help to understand why I am getting this error.

I am working on updating the IPT for our organization and I am migrating our data to the new version (v2.5). When I selected the folder with the current folders in the versión we have been working (v2.1.1), I get this error:

### ManagerFactory [org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory@2587760f] unable to create manager for [/srv/datadir/logs/debug.log] with data [org.apache.logging.log4j.core.appender.rolling.RollingFileManager$FactoryData@724add7b[pattern=/srv/datadir/logs/debug.log.%i, append=false, bufferedIO=true, bufferSize=8192, policy=SizeBasedTriggeringPolicy(size=10485760), strategy=DefaultRolloverStrategy(min=1, max=7, useMax=true), advertiseURI=null, layout=%-5p %d{dd-MMM-yyyy HH:mm:ss} [%c] - %m%n, filePermissions=null, fileOwner=null]] 

This is a screenshot with the error:
![image](https://user-images.githubusercontent.com/15584917/126549252-7c7e3bc3-273d-4672-894a-49be6300b2d8.png)

The console does not show any error, and I can use the IPT just to change the current page. But I would like to understand if this error means something to pay attention to.

Thanks a lot in advance for your support.

**Comment by sylmorin-gbif** [comment]
Hi,

Could you please go to the (new :) Health page, to see if there is no problem with your log folder?

![image](https://user-images.githubusercontent.com/56630013/126665422-cabde606-9b39-4d75-aa36-4037ce28db52.png)
(left icon, at the top right corner)

The File Permissions panel will show you if your IPT can use the log folder.
![image](https://user-images.githubusercontent.com/56630013/126665815-57701a4d-8420-4e28-9c6b-81b5e0ca0da4.png)


Thanks

**Comment by mike-podolskiy90** [comment]
@alegnaaived is this still an issue please?

**Comment by mike-podolskiy90** [comment]
Closing this, feel free to reopen it if it's still an issue
