### ISSUE TITLE
how to revert back to a previous resource version

### ISSUE THREAD

**Issue by abubelinha** [gbif/ipt#1618]
I am trying a [quick python-non-official way](https://github.com/gbif/ipt/issues/1480#issuecomment-720369009) (thanks @sylmorin-gbif) to speed-up resource metadata updates using a test IPT installation. 
After several successful small updates, my last try somehow corrupted the resource and now I can't modify it using the IPT web interface anymore.

This testing IPT is configured to keep all versions, so I have a bunch of `resourcename-X.Y.rtf`, `eml-X.Y.xml` and `dwca-X.Y.zip` files stored in my `iptestdatafolder/resources/resourcename/` path.

Can I somehow revert to one of the previous versions by touching the xml files, like it is suggested as a workaround for other issues ([#1223](https://github.com/gbif/ipt/issues/1223#issuecomment-152476525), [#1507](https://github.com/gbif/ipt/issues/1507#issuecomment-725515650), [#1508](https://github.com/gbif/ipt/issues/1508#issuecomment-725512896) ...)

- Which steps should I follow to go from my current 1.29 version back to for example 1.25 version?
- After doing that, I guess the portal page could be linking to a version which does not exist anymore in my IPT (i.e., 1.27). 
Can I solve this just republishing the resource?

I couldn't find anything about this in previous issues or in the [ipt FAQs](https://ipt.gbif.org/manual/en/ipt/2.5/faq).
Thanks a lot in advance for your answers

**Comment by mike-podolskiy90** [comment]
Thank you @abubelinha for contacting us.
You mentioned you can't modify the resource via UI, what exception you have please?
Maybe we can fix that

**Comment by abubelinha** [comment]
Thanks for your prompt reply @mike-podolskiy90 
I probably missed some mandatory form elements in metadata-basic.do IPT page, but I can't tell: I didn't play attention to the exception because I was not interested in fixing that version of the resource (it was not important at all).  

As I am just playing with a test IPT I moved forward and deleted the resource and created a new one.
But this happened to me several times so I would prefer to have a way to delete only the erroneous version (quick way to go back to my previous resource state) ... instead of having to create the resource again.

I guess this could be useful for other non-testing scenarios as well.
For example, if somebody by mistake publishes a version with sensible data which shouldn't be published.
Asumming the errors are noticed immediately, it would be better to go back in time to the previous version, just like if the erroneus version had never existed. And then, we can republish a new version without errors.

That way we avoid having a missing version number or failing links (because the zipped DwCa with sensible data would certainly have been deleted).

**Comment by abubelinha** [comment]
For metadata-only resources, I think this can solve the issue (in this example, I went back from v.1.12 to v.1.9):
Resource name: my-metadata-only-resource
1. Stop tomcat
2. Go to iptdata/resources/my-metadata-only-resource
3. Copy eml-1.9.xml to eml.xml
4. Delete eml.xml files from versions 1.10 to 1.12
5. Delete .rtf files from versions 1.10 to 1.12
6. Edit resource.xml and modified these entries at the top:
    Change `<emlVersion></emlVersion>` from 1.12 to 1.9
    Change `<replacedEmlVersion></replacedEmlVersion>` from 1.11 to 1.8
    Perhaps we could also edit `<modified>date/time</modified>` or `<changeSummary></changeSummary>`
7. Also in resource.xml, remove `<versionHistory></versionHistory>` entries from versions 1.10 to 1.12 
8. Start tomcat

After these changes, I was able to edit my resource again (it was broken after adding associated parties in a wrong way, I guess).

Please correct me if I am wrong.
The point is, would these changes be enough for a occurrence or checklist resource?
I guess those need some more things to change.

**Comment by mike-podolskiy90** [comment]
I can't say for sure. I can only recommend to try to play with those in a test IPT. You can publish a new version, compare "before" and "after" files, and see what changed.

**Comment by MattBlissett** [comment]
> Please correct me if I am wrong.
> For metadata-only resources, I think this recipe might solve the issue

I agree that this looks like it should solve your issue.

We can't support fixing problems like this, so I don't want to add the procedure to the user manual.  Using scripts, manually editing XML etc is best left to users (like you) willing to read the source code, these issues and so on.
