### ISSUE TITLE
Number of occurences records appear in IPT but not on GBIF

### ISSUE THREAD

**Issue by gerlienv** [gbif/ipt#1622]
Dear all,

I encountered an issue while uploading data to GBIF using the ITP tool. I uploaded the following data:
http://ipt.pensoft.net/resource?r=life_beneath_the_ice-jellyfish_and_ctenophores_from_the_ross_sea_antarctica&amp

It has 30 records, but when I go on GBIF, I only see 0 occurrences, not 30: https://www.gbif.org/dataset/5b38d2d1-4aca-46ba-889e-e6e4fe4c39f4

Any ideas how to fix this error?

**Comment by muttcg** [comment]
Dear @gerlienv 
Looks like **http://rs.tdwg.org/dwc/terms/occurrenceID** is missed in your mapping, please try to add occurrenceID

**Comment by gerlienv** [comment]
Der @muttcg,
You were right, it worked now. Many thanks!
