### ISSUE TITLE
how to install new ipt and keep old running (serve identical copies of all resources from both of them)

### ISSUE THREAD

**Issue by abubelinha** [gbif/ipt#1623]
I wonder if the following is possible:

We have a running test-mode IPT 2.4.0, and we want to keep it running
We want to test the new IPT 2.5.0, 
But we would like to recycle all current resources/mappings and users/passwords from the IPT 2.4.0.
I guess the main problem would be to avoid conflicts with things which are already registered to gbif-uat.

This is my guess:

1- Stop tomcat9, and download IPT 2.5.0 war file to tomcat9 webapp folder 
2- Copy the `iptdata240` folder to a new `iptdata250` folder, and make it writable by tomcat.
In Ubuntu/Debian, not to forget [#1489](https://github.com/gbif/ipt/issues/1489#issuecomment-658396948), since there is an extra step: 
Add these lines to `/etc/systemd/system/tomcat9.service.d/override.conf` to let the `iptdata250` folder be writable by tomcat:
```
[Service]
ReadWritePaths=/path/to/iptdata250/
```
3- In that new folder, edit `iptdata250/config/ipt.properties` file, so `ipt.baseURL` points to the correct url
**4- What else should we touch/edit to avoid future conflicts with gbif registry (ipt server and  resources ids)**
5- Restart tomcat9, and point to our `iptdata250` folder
6- Register the new IPT 2.5.0 server, and register all its resources with new ids

How to success in step 4, so the only thing we need to do after 5 is to register our new IPT server with a new ID, and register each of its resources? (without having to reenter their metadata and mappings again, and without having to stop our running IPT 2.4.0 ... so we keep two copies of each resource, one being served from 2.4.0 and the other from 2.5.0)

**Comment by abubelinha** [comment]
ALTERNATIVE (perhaps easier):

Is it possible to somehow backup everything from our 2.4.0 server (both data and config), then upgrade the server to 2.5.0 so everything runs exactly as in 2.4.0 (we keep the url, all resources registered, all their versions, all users, roles and passwords ... everything).

Figure out something fails. 

How could we to go back to 2.4.0 again?
(and of course, having again everything running exactly like it is right now)

**Comment by mike-podolskiy90** [comment]
Thanks for contacting us @abubelinha 

you have already installed the IPT 2.5.0 and it fails, right?

**Comment by mike-podolskiy90** [comment]
I believe two IPTs of different versions running on the same tomcat may cause some collisions. Although we haven't tested that. We would recommend to use only one instance of the most recent one.

**Comment by mike-podolskiy90** [comment]
Upgrading from 2.4 to 2.5 must be safe and cause no errors, but we strongly recommend to backup IPT data directory. 
What's your error please?

**Comment by abubelinha** [comment]
Still not tried.
We just want to know how to try 2.5.0 but being fully sure that we can go back to 2.4.0

So we stick to my second message:
Is it possible to fully-backup a running IPT 2.4.0 installation (i.e. to a couple of zip files), and then remove 2.4.0 from Tomcat, in order to install 2.5.0 ... but being safe that we can go back to 2.4.0?

We use Ubuntu 18.
I understand we just need to do this in order to go back and forward from 2.4.0 to 2.5.0 or vice-versa?

1. Stop Tomcat
2. Save a zip copy of iptdata folder
3. Delete /var/lib/tomcat9/webapps/ipt folder
4. Download ipt.war (either 2.4.0 or 2.5.0) to /var/lib/tomcat9/webapps
5. Restart Tomcat

This way we can restore everyting using either 2.4 or 2.5 version, and keep all resources registered, all dois, all versions history ...?

**Comment by mike-podolskiy90** [comment]
Yes, that's right. As long as you have an iptdata folder backup you are safe to upgrade to the 2.5.0 or downgrade to the 2.4.0

**Comment by abubelinha** [comment]
Sounds like something we can try.

One related question about backwards compatibility.

Let's say we successfully upgrade to 2.5.0, and some users play around, modify their registered resources (maybe publish a new version), or even create new resources.

OK. But finally, after playing around a couple of weeks, they prefer to go back to 2.4.0 for whatever reason (I know of some really-old browsers in this lab, which are not 2.5.0 compatible).

All changes made from 2.5.0 will be fully-backwards-compatible with 2.4.0, so we still can backup the changed iptdata folder, reinstall 2.4.0 and have all modified or new resources available from 2.4.0 ?

**Comment by mike-podolskiy90** [comment]
All must be fine since we haven't changed iptdata folder structure and its files.

**Comment by abubelinha** [comment]
OK, I tried this but I am facing a problem.

After restarting Tomcat9, I was asked for the iptdata folder, as expected.
Once I entered its path, no more questions.  All resources seem to be there.

The problem came when I tried to login.  At a first try, the passwords were not working (nor admin, neither other users). 
After a few minutes (the time I spent looking for similar issues and found  #587 or #495 ) ... the login system "resurrected" and now it works again.  What could be causing this issue?  

Anyway. I take the opportunity to ask a related question:  
I am writing a bash script to automate the [steps I described above](https://github.com/gbif/ipt/issues/1623#issuecomment-893392085), so I just call `install-IPT.sh "2.4.1"` and it makes everything (stops tomcat, deletes current webapp folder, downloads war file and restarts tomcat). 
Is it possible to improve this in order to avoid the initial web interface step where IPT asks me for the iptdata folder?
I suppose IPT looks for that info somewhere, so it only asks for it the first time if it's not available.
But perhaps the script could also write the info to the correct place in advance, before restarting Tomcat. Do you think so?

So, my question is: **Where does IPT store the info about iptdata folder path?**

**Comment by mike-podolskiy90** [comment]
That log-in issue sounds odd, I suspect the IPT did not manage to read files properly or something.

> So, my question is: Where does IPT store the info about iptdata folder path?

https://ipt.gbif.org/manual/en/ipt/2.5/installation#tomcat

**Comment by mike-podolskiy90** [comment]
Just in case, there is also manual about IPT upgrade https://ipt.gbif.org/manual/en/ipt/2.4/release-notes

**Comment by abubelinha** [comment]
I guess I had forgotten my own recommendations in [#1489](https://github.com/gbif/ipt/issues/1489#issuecomment-658396948)
(see [step 2 comments above](https://github.com/gbif/ipt/issues/1623#issue-961609238))

Now it works. Thanks!!

**Comment by abubelinha** [comment]
Hi again @mike-podolskiy90 
I reopen this issue because I would like to clarify [one of your comments above.](https://github.com/gbif/ipt/issues/1623#issuecomment-893374415):

> I believe two IPTs of different versions running on the same tomcat may cause some collisions. Although we haven't tested that. We would recommend to use only one instance of the most recent one.

But that is not what [the IPT 2.5 manual says about Tomcat](https://ipt.gbif.org/manual/en/ipt/2.5/installation#tomcat):

> **Tomcat**:
> The IPT has been tested and works well with Tomcat 7, 8 or 9. 

... and at the top botom, just after the Tomcat installation video: 

> Multiple IPTs can be installed on the same server with a small variation to this process. Rather than (or in addition to) using ipt.xml and ipt.war, use different names and change the files accordingly: on cloud.gbif.org we have africa.xml and africa.war, bid.xml and bid.war etc.
> 
It says "_multiple IPTs_", but nothing is said about "_multiple versions_".

From your comment above you somehow clarify that it is not possible to run IPT 2.4 and 2.5 under the same Tomcat. Could you update the Tomcat section of the manual accordingly?

But, at least, can we install several IPTs, provided all of them are the same version?
For example, one `/ipt` for production and the other `/iptest` one for testing, both under the same Tomcat webapp folder.

Thanks

**Comment by MattBlissett** [comment]
Hi @abubelinha,

I've made some small changes to the manual, which will be visible with the 2.5.2 release.  Running different versions of the IPT within Tomcat should work, but we don't test this. We encourage everyone to use the latest IPT version.

Downgrading the IPT isn't supported, though it may work between some versions, or it might work if some new features aren't used -- for example, v2.5.1 has a new feature for URL based data sources, so I don't think an IPT using this can be downgraded to v2.5.0.  The recommended upgrade process is to back up the data directory, perform the upgrade, then test.  If necessary, the IPT can be downgraded at this point, possibly using the data directory backup.
