### ISSUE TITLE
Support compressed text files for URL source

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/ipt#1632]
related #790

**Comment by peterdesmet** [comment]
Today I was looking for this feature 😄 , good to see it is already recorded as a feature request. Supporting this would improve the read speed of source files dramatically.

**Comment by mike-podolskiy90** [comment]
Thanks Peter. We'll try to add this in one of the next 2.6 releases

**Comment by abubelinha** [comment]
I support this too 👍👍 
Also related #1294 (in my case the remote URL could also point to a pandas-generated file).
Thanks!
@abubelinha
