### ISSUE TITLE
custom.css is no longer included

### ISSUE THREAD

**Issue by MattBlissett** [gbif/ipt#1634]
Simple customization using custom.css does not work with version 2.5.0.  `main.css` can be modified instead.  The example also needs to be updated for the new UI.

It would be good to restore this, ideally with an improvement to aid upgrades and allow use with Linux packages / Docker: include `config/custom.css` from the data directory, if it exists.

Something like https://training-ipt-a.gbif.org/resource?r=koura_invasive_species is then easy to achieve.

**Comment by mike-podolskiy90** [comment]
I added a custom blue theme for the IPT

**Comment by rukayaj** [comment]
I just want to check, so it's not possible for users to have a customisation in e.g. datadir/config/custom.css which persists after IPT upgrades I guess? Seeing as @mike-podolskiy90 's commit has custom.css in the same dir as main.css?

**Comment by mike-podolskiy90** [comment]
Thank you for the question @rukayaj 
Unfortunately, it's not currently supported
