### ISSUE TITLE
Cannot see Darwin core taxon option in Darwin core mappings

### ISSUE THREAD

**Issue by yashsondhi** [gbif/ipt#1639]
Cannot see Darwin core taxon option in Darwin core mappings

**Comment by mike-podolskiy90** [comment]
Thank you for contacting us @yashsondhi 
We need some more details please. What version of the IPT do you use?

**Comment by yashsondhi** [comment]
Hi,
Thanks, I figured it out, IPT asked me to create a Darwin core occurrence
or taxon when I created the dataset, I was trying to change it.
Cheers
