### ISSUE TITLE
Unable to Connect to MySQL Database using Existing Connections

### ISSUE THREAD

**Issue by ben-norton** [gbif/ipt#1640]
Hello,
I reported a problem connecting to MySQL Databases from the VertNET IPT a few months ago. Is there an update on when the problem may be fixed? Publishing activity is currently on hold until a fix is in place. 
The connection file has worked in the past. At some point, it stopped working. 
Thanks!
- Ben Norton

**Comment by MattBlissett** [comment]
Hi Ben,

IPT version 2.5.0 was released last week, and it has the fix (#1594) that should have solved your issue.  Have you tried installing this new version?

In case you didn't know the release was made, announcements of new releases are made to the mailing list: https://lists.gbif.org/pipermail/ipt/2021-August/000764.html and on this repository (Watch → Custom → Releases).

Cheers,

Matt

**Comment by ben-norton** [comment]
Thanks Matt.
I'm using the IPT on VertNET (http://ipt.vertnet.org:8080/ipt/). I'll contact them regarding the update.
(p.s. See you October!)

**Comment by mbnorton** [comment]
It worked perfectly. Sorry for the delayed response.

**Comment by mbnorton** [comment]
I can't figure out how to close it. Please close it.
