### ISSUE TITLE
Package the IPT for CentOS 8 / Rocky Linux 8

### ISSUE THREAD

**Issue by MattBlissett** [gbif/ipt#1646]
(Via helpdesk.)

We have a request to produce an RPM for CentOS 8 / Rocky Linux 8.

**Comment by MattBlissett** [comment]
When installed using the RPM package, the IPT runs using Jetty rather than Tomcat.  This makes for a simple, standalone deployment (see [systemd config](https://github.com/gbif/ipt/blob/master/package/rpm/SOURCES/ipt.service)), although it does prevent customization (changed colours/styles).

I've updated the package build to create an EL8 RPM, but I still need to test it — probably tomorrow.

**Comment by MattBlissett** [comment]
This is not as simple as I thought, as the jetty-runner package which we used in CentOS 7 [is not present in CentOS 8](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/considerations_in_adopting_rhel_8/index#removed-packages_changes-to-packages).

**Comment by FedorSteeman** [comment]
We're having issues installing the IPT on a RHEL8 server right now. Is the solution mentioned by @dipohl  viable or do we need to find another workaround, perhaps even going down to using a RHEL7 server???

**Comment by MattBlissett** [comment]
I have made test packages for the IPT on CentOS 8 Stream and (so far untested) CentOS 9. That should be equivalent to RHEL8 and 9.

To achieve that, I also made a [Jetty Runner package](https://github.com/gbif/jetty-runner-rpm), and I'm running the IPT with Java 11.

The installation instructions are similar to the [manual](https://ipt.gbif.org/manual/en/ipt/2.5/installation#installation-from-linux-packages):

```
yum-config-manager --add-repo https://packages.gbif.org/gbif.repo
yum --enablerepo=gbif-testing install ipt
```

Some basic testing shows #1853, I haven't yet done more testing than that.

**Comment by MattBlissett** [comment]
I think the EL8 / EL9 packages are now working (and have been for a while).

**Comment by FedorSteeman** [comment]
Is there any particular reason we still cannot do the upgrade then? 

> [root@danbifapp02fl config]# yum upgrade ipt
> Updating Subscription Management repositories.
> zabbix-64_el9_x86_64                                                                                                                                                                                    87 kB/s | 2.9 kB     00:00
> epel_el9_x86_64                                                                                                                                                                                         73 kB/s | 2.3 kB     00:00
> gbif_el9_x86_64                                                                                                                                                                                         60 kB/s | 2.0 kB     00:00
> Red Hat Satellite Client 6 for RHEL 9 x86_64 (RPMs)                                                                                                                                                     94 kB/s | 3.8 kB     00:00
> Red Hat Enterprise Linux 9 for x86_64 - BaseOS (RPMs)                                                                                                                                                  100 kB/s | 4.1 kB     00:00
> Red Hat Enterprise Linux 9 for x86_64 - AppStream (RPMs)                                                                                                                                               113 kB/s | 4.5 kB     00:00
> Dependencies resolved.
> Nothing to do.
> Complete!

**Comment by MattBlissett** [comment]
Apologies, there is an error due to a change between CentOS 7 and CentOS 8/9, which shows with an upgrade.

It's now fixed, but you will probably need to remove the old IPT package using this command:

```
# Version 8
rpm -e --nopreun --nopostun ipt-3.0.2-1.el8.noarch

# Version 9
rpm -e --nopreun --nopostun ipt-3.0.2-1.el9.noarch
```

**Comment by FedorSteeman** [comment]
Thank you for your quick response! I was able to remove the older version's packages, but still 3.0.2 is the highest version that is offered to our yum: 

```
[root@danbifapp02fl vsb582]# rpm -e --nopreun --nopostun ipt-3.0.2-1.el9.noarch
[root@danbifapp02fl vsb582]# yum upgrade ipt
Updating Subscription Management repositories.
zabbix-64_el9_x86_64                                                                                                                          69 kB/s | 2.9 kB     00:00
epel_el9_x86_64                                                                                                                               68 kB/s | 2.3 kB     00:00
gbif_el9_x86_64                                                                                                                               41 kB/s | 2.0 kB     00:00
Red Hat Satellite Client 6 for RHEL 9 x86_64 (RPMs)                                                                                           93 kB/s | 3.8 kB     00:00
Red Hat Enterprise Linux 9 for x86_64 - BaseOS (RPMs)                                                                                         97 kB/s | 4.1 kB     00:00
Red Hat Enterprise Linux 9 for x86_64 - AppStream (RPMs)                                                                                      93 kB/s | 4.5 kB     00:00
Dependencies resolved.
=============================================================================================================================================================================
 Package                      Architecture                    Version                               Repository                                                          Size
=============================================================================================================================================================================
Upgrading:
 ipt                          noarch                          3.0.2-1.el9                           Default_Organization_gbif_gbif_el9_x86_64                           80 M

Transaction Summary
=============================================================================================================================================================================
Upgrade  1 Package

Total download size: 80 M
Is this ok [y/N]: N
```

**Comment by FedorSteeman** [comment]
Ah! Never mind! I just needed to refresh the repo: 

```
[root@danbifapp02fl vsb582]# yum-config-manager --add-repo https://packages.gbif.org/gbif.repo
Updating Subscription Management repositories.
Adding repo from: https://packages.gbif.org/gbif.repo
[root@danbifapp02fl vsb582]# yum upgrade ipt
Updating Subscription Management repositories.
GBIF RPM Packages                                                                                                                             71 kB/s | 2.9 kB     00:00
GBIF RPM Packages                                                                                                                             25 kB/s | 2.9 kB     00:00
zabbix-64_el9_x86_64                                                                                                                          85 kB/s | 2.9 kB     00:00
epel_el9_x86_64                                                                                                                               58 kB/s | 2.3 kB     00:00
gbif_el9_x86_64                                                                                                                               40 kB/s | 2.0 kB     00:00
Red Hat Satellite Client 6 for RHEL 9 x86_64 (RPMs)                                                                                           59 kB/s | 3.8 kB     00:00
Red Hat Enterprise Linux 9 for x86_64 - BaseOS (RPMs)                                                                                         57 kB/s | 4.1 kB     00:00
Red Hat Enterprise Linux 9 for x86_64 - AppStream (RPMs)                                                                                      59 kB/s | 4.5 kB     00:00
Dependencies resolved.
=============================================================================================================================================================================
 Package                               Architecture                             Version                                         Repository                              Size
=============================================================================================================================================================================
Upgrading:
 ipt                                   noarch                                   3.0.6-0.3.el9                                   gbif                                    81 M

Transaction Summary
=============================================================================================================================================================================
Upgrade  1 Package

Total download size: 81 M
Is this ok [y/N]: y
```
