### ISSUE TITLE
unabel to use "materialCitation" in basisOfRecord field of IPT

### ISSUE THREAD

**Issue by ninacourlee** [gbif/ipt#1653]
Please, could you answer the issue with the "basisOfRecord" vocabulary in IPT:
according to DwC it currently includes 10 terms (https://dwc.tdwg.org/terms/#dwc:basisOfRecord): 
PreservedSpecimen, FossilSpecimen, LivingSpecimen, MaterialSample, Event, HumanObservation, MachineObservation, Taxon, Occurrence, MaterialCitation. But when uploading data to IPT, there is no "materialCitation" in the picklist.

**Comment by MattBlissett** [comment]
Hi Nina,

MaterialSample and several other terms were recently added to Darwin Core.  We want to add support for them on GBIF.org before encouraging publication of datasets using the new terms.

Meanwhile, they are available in "Test Mode" IPTs, which can publish data to gbif-uat.org -- though a MaterialSample basis of record would probably just show as "Unknown".

https://github.com/gbif/rs.gbif.org/issues/21#issuecomment-908530989 is the main issue for the work.

**Comment by ahahn-gbif** [comment]
The same question arises through helpdesk for a BID project grant deliverable, mobilizing data from literature. To date, the "literature" basisOfRecord in GBIF.org is predominantly available from publishers using the ABCD/BioCASe data publishing pathway. Once MaterialCitation (NB: different from MaterialSample) is integrated, it should map to the "literature" vocabulary concept used in other places, or vice versa. Darwin core quick reference guide link: https://dwc.tdwg.org/terms/#materialcitation. 

This change touches on several different components (vocabulary server work, IPT, API, GBIF.org user interface - see link in the comment above).
