### ISSUE TITLE
Load eml.xml created outside of the IPT

### ISSUE THREAD

**Issue by albenson-usgs** [gbif/ipt#1654]
While most data providers do not create eml.xml files themselves, I do have some that do and it would be ideal if I could load their carefully crafted EML directly into the IPT instead of having to copy it over manually. When I'm first creating a resource I do opt to use the "Import from archived resource" option but when they send me updates I cannot load those updated EML files (and I will note this is not really the intended use of that option since it states "This option is for importing from an exported Darwin Core archive or IPT resource"). It would be nice to be able to load files from the [ezEML tool](https://ezeml.edirepository.org/eml/about).

**Comment by mike-podolskiy90** [comment]
Thank you for contacting us @albenson-usgs 
This feature has already been implemented in the new 2.5.1 version. So if you'd like to use it you just need to upgrade to this version

**Comment by mike-podolskiy90** [comment]
Issue https://github.com/gbif/ipt/issues/955

**Comment by albenson-usgs** [comment]
Ah! Great news. Thanks @mike-podolskiy90 !
