### ISSUE TITLE
Link to "trusted data hosting centre" resource in README is broken

### ISSUE THREAD

**Issue by jocelynpender** [gbif/ipt#1656]
README bullet #4 under Resources "You may request a free account on an IPT from a trusted data hosting centre" links to https://ipt.gbif.org/manual/en/ipt/2.5/data-hosting-centres/ which returns an error "Not Found
The requested URL /manual/en/ipt/2.5/data-hosting-centres.html/ was not found on this server."

**Comment by MattBlissett** [comment]
Thanks, I've fixed the links in the readme.
