### ISSUE TITLE
basisOfRecord [PreservedSpecimen] that does not match the Darwin Core Type Vocabulary

### ISSUE THREAD

**Issue by sylmorin-gbif** [gbif/ipt#1664]
Hello,

On a fresh new 2.5.1 (docker) installation, we have the following error when we try to publish an occurrence dataset

Line #1 has basisOfRecord [PreservedSpecimen] that does not match the Darwin Core Type Vocabulary
Line #2 has basisOfRecord [PreservedSpecimen] that does not match the Darwin Core Type Vocabulary
...

It's really similar to https://github.com/gbif/ipt/issues/1615
Except that the proposed workaround is not helping.

We try:
1) the Synchronize button in Core Types and Extension page
2) manually deleting the config/.vocabularies folder, restarting the IPT

We don't get the http_rs_gbif_org_vocabulary_dwc_basis_of_record_xml.vocab file, like in my other working installations.

In the debug.log, when we click Synchronize, we only have successful messages:
 `INFO  13-Oct-2021 16:19:30 [org.gbif.ipt.service.admin.impl.VocabulariesManagerImpl] - Successfully loaded vocabulary: http://rs.gbif.org/vocabulary/gbif/quantityType
INFO  13-Oct-2021 16:19:30 [org.gbif.ipt.service.admin.impl.VocabulariesManagerImpl] - Successfully loaded vocabulary: http://rs.gbif.org/vocabulary/gbif/unitOfMeasurement
INFO  13-Oct-2021 16:19:30 [org.gbif.ipt.service.admin.impl.VocabulariesManagerImpl] - Successfully loaded vocabulary: http://rs.gbif.org/vocabulary/dwc/pathway/
INFO  13-Oct-2021 16:19:30 [org.gbif.ipt.service.admin.impl.VocabulariesManagerImpl] - Successfully loaded vocabulary: http://rs.gbif.org/vocabulary/gbif/occurrence_status/
INFO  13-Oct-2021 16:19:30 [org.gbif.ipt.service.admin.impl.VocabulariesManagerImpl] - Successfully loaded vocabulary: http://rs.gbif.org/vocabulary/gbif/preservation_method
INFO  13-Oct-2021 16:19:30 [org.gbif.ipt.service.admin.impl.VocabulariesManagerImpl] - Successfully loaded vocabulary: http://rs.gbif.org/vocabulary/gbif/datasetType
INFO  13-Oct-2021 16:19:30 [org.gbif.ipt.service.admin.impl.VocabulariesManagerImpl] - Successfully loaded vocabulary: http://rs.gbif.org/vocabulary/dwc/basis_of_record/
INFO  13-Oct-2021 16:19:30 [org.gbif.ipt.service.admin.impl.VocabulariesManagerImpl] - Successfully loaded vocabulary: http://rs.gbif.org/vocabulary/dwc/degree_of_establishment/
INFO  13-Oct-2021 16:19:30 [org.gbif.ipt.service.admin.impl.VocabulariesManagerImpl] - Successfully loaded vocabulary: http://rs.gbif.org/vocabulary/gbif/rank
INFO  13-Oct-2021 16:19:30 [org.gbif.ipt.service.admin.impl.VocabulariesManagerImpl] - Successfully loaded vocabulary: http://dublincore.org/documents/dcmi-type-vocabulary/
INFO  13-Oct-2021 16:19:31 [org.gbif.ipt.service.admin.impl.VocabulariesManagerImpl] - Successfully loaded vocabulary: http://iso.org/iso3166-1/alpha2
INFO  13-Oct-2021 16:19:31 [org.gbif.ipt.service.admin.impl.VocabulariesManagerImpl] - Successfully loaded vocabulary: http://iso.org/639-2
INFO  13-Oct-2021 16:19:31 [org.gbif.ipt.service.admin.impl.VocabulariesManagerImpl] - Successfully loaded vocabulary: http://rs.gbif.org/vocabulary/eml/updateFrequency
INFO  13-Oct-2021 16:19:31 [org.gbif.ipt.service.admin.impl.VocabulariesManagerImpl] - Successfully loaded vocabulary: http://rs.gbif.org/vocabulary/dwc/establishment_means/
INFO  13-Oct-2021 16:19:31 [org.gbif.ipt.service.admin.impl.VocabulariesManagerImpl] - Successfully loaded vocabulary: http://rs.gbif.org/vocabulary/gbif/agentRole
INFO  13-Oct-2021 16:19:31 [org.gbif.ipt.service.admin.impl.VocabulariesManagerImpl] - Successfully loaded vocabulary: http://rs.gbif.org/vocabulary/gbif/datasetSubtype`

I don't get how it can be successful, since most of the links are broken for me....

http://rs.gbif.org/vocabulary/gbif/quantityType ==> 404
http://rs.gbif.org/vocabulary/gbif/unitOfMeasurement ==> 404
http://rs.gbif.org/vocabulary/gbif/occurrence_status/ ==> OK
http://rs.gbif.org/vocabulary/dwc/basis_of_record/ ==> 404

**Comment by mike-podolskiy90** [comment]
I guess that occurrence extension at your IPT points to `http_rs_gbif_org_vocabulary_dwc_basis_of_record_xml.vocab` which is absent (for some reason). If it's following it should be fine:
```
<property group='Record-level' name='basisOfRecord' thesaurus='http://rs.gbif.org/sandbox/vocabulary/dwc/basis_of_record_2021-08-22.xml' namespace='http://rs.tdwg.org/dwc/terms/' qualName='http://rs.tdwg.org/dwc/terms/basisOfRecord' dc:relation='https://dwc.tdwg.org/terms/#dwc:basisOfRecord' dc:description='The specific nature of the data record.' comments='Recommended best practice is to use the standard label of one of the Darwin Core classes.' examples='`PreservedSpecimen`, `FossilSpecimen`, `LivingSpecimen`, `MaterialSample`, `Event`, `HumanObservation`, `MachineObservation`, `Taxon`, `Occurrence`, `MaterialCitation`' required='true'/>
```

**Comment by wyldsoul** [comment]
Greetings,
  I am getting the same exact error on 2.5.3 docker and older versions :
Line #1 has basisOfRecord [PreservedSpecimen] that does not match the Darwin Core Type Vocabulary
Line #2 has basisOfRecord [PreservedSpecimen] that does not match the Darwin Core Type Vocabulary
...
I have tried all the workarounds that I've reviewed in the basisOfRecord issues, as well as other attempts:
Synchronize Vocabulary
Installed extensions the added the http_rs_gbif_org_vocabulary_dwc_basis_of_record_xml.vocab
Moved the http_rs_gbif_org_vocabulary_dwc_basis_of_record_xml.vocab instal the config/.vocabularies folder.  
Edited the http_rs_tdwg_org_dwc_terms_Occurrence.xml extension to disable the basisOfRerord requirement
Deployed every version of the docker from current(2.5.3) to 2.4.2. on a Local dockers deployed on Mac OS and on Dockers I built on a Linux VM.

Any suggestions would be appreciated.

**Comment by sylmorin-gbif** [comment]
Hi,

I did some debugging since I still have the issue on a new 2.5.5 instance in TEST mode (connected to GBIF UAT)

Here is what I found.

The "basis of record" vocab is initialiazed [here](https://github.com/gbif/ipt/blob/master/src/main/java/org/gbif/ipt/task/GenerateDwca.java#L464), using the key Constants.VOCAB_URI_BASIS_OF_RECORDS whose value is "**http://rs.tdwg.org/dwc/dwctype/**"

In [VocabulariesManagerImpl](https://github.com/gbif/ipt/blob/master/src/main/java/org/gbif/ipt/service/admin/impl/VocabulariesManagerImpl.java#L77), the map has the following content:

![image](https://user-images.githubusercontent.com/56630013/148070335-991695d3-941a-4582-823e-e2e3b2819a2f.png)

As we can see, we don't have "**http://rs.tdwg.org/dwc/dwctype/**", but instead "**http://rs.gbif.org/vocabulary/dwc/basis_of_record/**"

As a result, the basis of record vocab is empty, and we have the reported errors 
>  [PreservedSpecimen] that does not match the Darwin Core Type Vocabulary

For me, **the code is compliant** with the PROD vocab:
https://gbrds.gbif.org/registry/thesauri.json ==> "identifier": "http://rs.tdwg.org/dwc/dwctype/"
but not the UAT vocab:
https://gbrds.gbif-uat.org/registry/thesauri.json ==> "identifier": "http://rs.gbif.org/vocabulary/dwc/basis_of_record/"

I'm not used to all the vocab stuff, so I don't know how to fix it... (don't think it's a code issue)

Thanks,
Sylvain

**Comment by mike-podolskiy90** [comment]
Thank you for your time testing this @sylmorin-gbif 
Yes, it was switched to tdwg term instead of gbif one recently. I'm not sure what we can do with this right now, but we'll get back to this very soon, since we already started adopting new Darwin Core stuff.

**Comment by MattBlissett** [comment]
With https://github.com/gbif/rs.gbif.org/commit/6ac1902c93ef0238def343cbc37371ab5e750a09 I've changed the dc:URIs back to the original values, so this should now be working again.
