### ISSUE TITLE
data source csv files from Google Drive public urls: no way to edit/delete them

### ISSUE THREAD

**Issue by abubelinha** [gbif/ipt#1673]
IPT manual v.2.5 [Source Data section](https://ipt.gbif.org/manual/en/ipt/2.5/manage-resources#source-data) offers now a new [URL](https://ipt.gbif.org/manual/en/ipt/2.5/manage-resources#url-as-data-source) option:

> _**URL as data source**_
> _The IPT can import uncompressed delimited text files (CSV, tab, and files using any other delimiter) directly from a URL. Select "URL" from the source data type dropdown list under "Source Data", then type or copy and paste the full URL (including http:// or https://) into the box below._
> 

I was trying to use a public Google Drive csv file as the source url.
The url I use has this structure (just replaced Google Drive file UUID with [gdFile_UUID]):   
https://drive.google.com/uc?id=[gdFile_UUID]&export=download

At a first glance, the IPT can read it (it correctly shows the number of bytes, rows and columns). And it shows the green circle of "readable".

But when I click the "edit" button on the right side, in the new page opened I get this error message:

`The source ucid=[gdFile_UUID] cannot be loaded. Please ask an administrator to investigate the IPT's logs to find out why.`

This is the log:
`ERROR 29-oct.-2021 10:34:57 [org.gbif.ipt.action.manage.SourceAction] - No source with id ucid=[gdFile_UUID] found!
`

I suppose this can be related to the presence of `=` `&` or `?` symbols in the url.
But **the big issue is** that in this new page, there is **no option to delete the data source**.

Nevertheless, the file has been correctly parsed and **the mapping section works OK**.  But if something was wrong (i.e. a missing field), the data source can't be removed once the url has been added to the IPT resource.

**The same file linked from github shows no issues.** 
I used this url structure:
https://raw.githubusercontent.com/username/projectname/main/filename.csv
The edit button works and in the edition page there are options to edit encoding, headers, delimiters ... save/cancel changes and also deleting the data source.

The point is I want to map csv files that other people is sharing through Google Drive.
Can this be fixed?
 
I tried this in IPT Version 2.5.0-r236903d

**Comment by mike-podolskiy90** [comment]
Thank you for reporting this
I think it's because URL sources reuse file sources functionality and populate a resource name automatically. We will look into that to fix this.
Looks like the only way to delete it in your case is to do it manually from the IPT data directory.

**Comment by mike-podolskiy90** [comment]
I have added a few fixes to the URL sources. Now you need to provide the source name in addition to the URL when creating a new source. Will be included in the next release, closing this.
