### ISSUE TITLE
Login redirection doesn't return to IPT

### ISSUE THREAD

**Issue by joshbeard** [gbif/ipt#1682]
When successfully authenticating on the IPT login via `login.do`, we are redirected back to the root URL of the hosted domain. Our deployment of IPT is served from an /ipt/ path. Navigating back to the IPT URL, we have a logged in session.

From https://github.com/gbif/ipt/blob/b6a4c2c26486763d03507da8589bba2c33f2a563/src/main/java/org/gbif/ipt/action/LoginAction.java#L114, it looks like the `Referer` is evaluated to determine a redirection URL, but excludes Referers ending with `login.do` and defaults to '/'.

I presume if we were serving from a subdomain out of the root context, this behavior wouldn't be noticed. Is this possibly a bug that presents to users that serve IPT from a path? I'm wondering if setting the redirect URL to the IPT base URL is a viable option?

To work around this I have manually set a `Referer` header to the IPT base URL on the reverse proxy.

**Comment by mike-podolskiy90** [comment]
Thank you for contacting us @joshbeard 
We recently changed that, and now it redirects to the IPT base URL
https://github.com/gbif/ipt/blob/b6a4c2c26486763d03507da8589bba2c33f2a563/src/main/java/org/gbif/ipt/action/LoginAction.java#L109
