### ISSUE TITLE
Records filter fails in spanish version

### ISSUE THREAD

**Issue by camiplata** [gbif/ipt#1683]
When the record filter is aplied on the spanish verssion, the resurces are not organized as expected from larger to smaller (or smaller to larger) see:

<img width="1325" alt="Captura de Pantalla 2021-11-16 a la(s) 4 40 12 p  m" src="https://user-images.githubusercontent.com/5700527/142070424-258267e9-4362-415d-85b4-87abcbfe923d.png">

You can see the expected behavior on the english version

<img width="1406" alt="Captura de Pantalla 2021-11-16 a la(s) 4 39 52 p  m" src="https://user-images.githubusercontent.com/5700527/142070492-4b4f8721-a98d-4748-b845-3f99e9042d73.png">

You can replicate this issue on the test IPT

**Comment by mike-podolskiy90** [comment]
Thank you for spotting this bug @camiplata 
That happens with several other languages too (fr, pt, ru). We'll figure out why
