### ISSUE TITLE
Citation metadata section is broken on IPT version 2.5.1-r8cce947

### ISSUE THREAD

**Issue by camiplata** [gbif/ipt#1684]
We recently made the migration to the latest IPT versión (2.5.1-r8cce947 ) and we found for both new an old datasets on edition mode the metadata section is broken see:

<img width="1677" alt="Captura de Pantalla 2021-11-17 a la(s) 12 23 50 p  m" src="https://user-images.githubusercontent.com/5700527/142250484-012208f2-5d1f-4cdf-9593-ad98d90032f3.png">

We found this error that was also [reported by Rui Figueira on the mailing list](https://www.mail-archive.com/ipt@lists.gbif.org/msg00070.html) a work around emerged,  but republishing has not worked for us.

We want to know if this is an issue of the IPT itself and if it will be fixed soon, or if we should stay with previous versions? Is there another fix so we can keep this IPT version ? or it is a problem with the installation?

@RicardoOrtizG

**Comment by camiplata** [comment]
A few new datasets do work, but for the great majority it does not work.

**Comment by mike-podolskiy90** [comment]
Thank you for contacting us @camiplata 
I'm looking into that

**Comment by mike-podolskiy90** [comment]
Sorry, I answered your email at helpdesk, but made a typo in my email address. It's mpodolskiy@gbif.org

**Comment by mike-podolskiy90** [comment]
Thank you for the account. Could you please send me a couple of resources which have issues, and describe what actions cause those. I checked several resources (took them from logs, including ciat_001), but they seem fine - I can edit metadata including citations.

**Comment by camiplata** [comment]
The error happens when going to the citation section when editing the metadata see the following gif:

![ETScBNZAzp](https://user-images.githubusercontent.com/5700527/142434849-9f9d5517-fd95-4cae-b153-b23de874155a.gif)


I have found the error in 90% of the datasets I have checked, see some examples:

Datasets that existed before updating to the new IPT version:

- https://ipt.biodiversidad.co/sib/resource?r=ciat_001
- https://ipt.biodiversidad.co/iavh/resource?r=santurban_plantas_2013

Datasets created after updating the IPT:

- https://ipt.biodiversidad.co/sib/manage/resource.do?r=ullanos_mhnu_coleccion-entomologia
- https://ipt.biodiversidad.co/sib/manage/resource?r=002_bio-le_sc_202018

**Comment by mike-podolskiy90** [comment]
I got it, it does not happen for page in english for some reason

**Comment by mike-podolskiy90** [comment]
We found the issue. We are going to release a new version of the IPT soon (this or next week) until then you can access the citations section in English as a workaround. Sorry for the inconvenience
Let me know if you have any questions

**Comment by camiplata** [comment]
Thank you for help @mike-podolski y90, we will be looking forward to the new version to upgrade as soon as possible

**Comment by EstebanMH-SiB** [comment]
We find a resource whit the same problem and it does not work using english as a language. 
It is a new resource (https://ipt.biodiversidad.co/sib/manage/resource?r=dermestidae-colombia) that has not been published so far and gave the same message of error when you try to enter in [Section-citations](https://ipt.biodiversidad.co/sib/manage/metadata-citations.do?r=dermestidae-colombia).

![image](https://user-images.githubusercontent.com/63795703/143303595-d0453def-848f-440e-8f65-09ce6059f2dd.png)

**Comment by mike-podolskiy90** [comment]
Thank you for writing us @EstebanMH-SiB 
that's an issue related to this one https://github.com/gbif/ipt/issues/1655
