### ISSUE TITLE
GBIF logo tooltip can only be modified via HTML and not CSS 

### ISSUE THREAD

**Issue by RicardoOrtizG** [gbif/ipt#1685]
In the personalization of the IPT we are making some changes in the CSS, but have an issue changing the logos because the tooltip persist as "GBIF Logo". (See image below). We achive to change it but only trhough a modification in the .ftl archive. So we suggest to let the Tooltip as "Logo" to avoid to make further changes outsid the CSS.

![imagen](https://user-images.githubusercontent.com/15789737/142554820-29184a93-a6ed-446a-9ebf-d7245b83e328.png)

@camiplata

**Comment by mike-podolskiy90** [comment]
Thank you for spotting this @RicardoOrtizG 
I have changed that to "Logo"

**Comment by peterdesmet** [comment]
I would omit the `title` property from the logo altogether.
