### ISSUE TITLE
Inconsistency related to decimal separator in geographic coverage metadata section

### ISSUE THREAD

**Issue by RicardoOrtizG** [gbif/ipt#1686]
There is an inconsistency in geographic coverage in the IPT metadata section, related to the use of points(.) or commas(,) as a decimal separator in decimal coordinates. When the coordinate is taken with a comma it shows an incorrect position (see image 1), when it changes to a point separator the problem is fixed (image 2).

Image 1:
! [image] (https://user-images.githubusercontent.com/15789737/142555614-a0b663fe-3226-426b-984e-095ef0b1bcb5.png)
Image 2:
! [image] (https://user-images.githubusercontent.com/15789737/142555639-584f8f53-f765-4220-a11e-dcff1c11b7af.png)

In some publications the problem does not appear, it seems like a random error.

**Comment by mike-podolskiy90** [comment]
Thank you for contacting us @RicardoOrtizG 
Coordinates only support dot as separator, I will add a warning to prevent users from using others.

**Comment by RicardoOrtizG** [comment]
Thanks Mike, the warning is a very good idea to avoid this error, but maybe I was not clear enough. The coordinates were well documented, but after the migration the dots changed automaticly to commas in spanish version causing this error, it's not a mistake in the actual documentation of the coordinates. This is why I think is a codification problem.

**Comment by mike-podolskiy90** [comment]
Thanks for the clarification @RicardoOrtizG 
I see now, we will fix it
