### ISSUE TITLE
Using valid Collection ID but still getting Collection Match Fuzzy

### ISSUE THREAD

**Issue by gamblebnmnh** [gbif/ipt#1690]
All of our records imported from the NMNH Extant Specimens Records, NMNH Paleobiology Specimen Records, and NMNH Material Samples data sets are receiving the Collection Match Fuzzy warning.  We have tried sending several of the identifiers to the Collection ID field but they are still showing match fuzzy.  What should we send to get rid of this error or is this an error on the GBIF end.  Thanks so much.

**Comment by ManonGros** [comment]
Thanks @gamblebnmnh we will look into it and let you know if something needs to be updated on your side.

**Comment by ManonGros** [comment]
@gamblebnmnh As far as I can see, the issue has to do with the content of the collectionCode field, it also contains a value that isn't in the codes associated with the collection.

For example this record: https://www.gbif.org/occurrence/3398468302

| Field | Value |
| --- | --- |
| Collection code | `urn:uuid:09c9cf5f-f5d3-48cc-b5c8-cd9b9fbd631f` |
| Collection ID | `urn:uuid:09c9cf5f-f5d3-48cc-b5c8-cd9b9fbd631f` |
| Institution code | `USNM` |
| Institution ID | `urn:lsid:biocol.org:col:34871` |

Matches to [this collection](https://www.gbif.org/grscicoll/collection/fc904fab-a33c-4ca8-bd23-698ddb026f26) where the main code is `Fish` and has `Fishes` as an alternative code. `urn:uuid:09c9cf5f-f5d3-48cc-b5c8-cd9b9fbd631f` isn't one of its codes so our system flags the match as fuzzy.

If the collectionCode for the specimen was `Fish` or `Fishes` or empty, there would be an exact match. Alternatively, if `urn:uuid:09c9cf5f-f5d3-48cc-b5c8-cd9b9fbd631f` was one of the codes associated with the collection, there would also be an exact match.

Note that you can use our lookup service to see the type of match you can get with different values associated with the specimen. See the example with the same institutionCode, institutionID and collectionID but different collectionCodes:
* CollectionCode is `Fish`: https://api.gbif.org/v1/grscicoll/lookup?institutionCode=US&institutionId=urn:lsid:biocol.org:col:15463&collectionId=urn:uuid:09c9cf5f-f5d3-48cc-b5c8-cd9b9fbd631f&collectionCode=Fish `collectionMatch": {"matchType": "EXACT"...`
* CollectionCode is `Fishes`: https://api.gbif.org/v1/grscicoll/lookup?institutionCode=US&institutionId=urn:lsid:biocol.org:col:15463&collectionId=urn:uuid:09c9cf5f-f5d3-48cc-b5c8-cd9b9fbd631f&collectionCode=Fishes `collectionMatch": {"matchType": "EXACT"...`
* CollectionCode is empty: https://api.gbif.org/v1/grscicoll/lookup?institutionCode=US&institutionId=urn:lsid:biocol.org:col:15463&collectionId=urn:uuid:09c9cf5f-f5d3-48cc-b5c8-cd9b9fbd631f `collectionMatch": {"matchType": "EXACT"...`

I hope this helps I will close the issue but let me know if you have any question.

**Comment by ManonGros** [comment]
Thanks @gamblebnmnh 
Just to be clear, the collectionID you used is correct (that's how the system was able to find a match). But it doesn't match the codes associated with the collection found, this is why the match is fuzzy.

Just in case you haven't seen this yet, perhaps you will find this blogpost useful: https://data-blog.gbif.org/post/grscicoll-flags/

You are very welcome to contact me at scientific-collections@gbif.org for more detailed questions.

**Comment by gamblebnmnh** [comment]
Check out this occurrence record https://www.gbif.org/occurrence/2871789405, the collection code urn urn:uuid:18e3cd08-a962-4f0a-b72c-9a0b3600c5ad is a valid code for the Entomology collection which this specimen is a part of yet it still shows collection match fuzzy?

**Comment by ManonGros** [comment]
@gamblebnmnh I think there might be some confusion between Codes and Identifiers.
`urn:uuid:18e3cd08-a962-4f0a-b72c-9a0b3600c5ad` is an identifier but is listed as a code or alternative code. Let me know if the screenshot below helps clarify where to find what:

<img width="977" alt="Screenshot 2021-12-03 at 14 33 59" src="https://user-images.githubusercontent.com/7677271/144611601-b6b076dd-6c20-48f7-839e-888e347a8fde.png">

The system found the match based on the collectionID but put the flag because the value in the collectionCode field for the record didn't match any of the codes for that collection. Does it make sense?
