### ISSUE TITLE
Style URL has no '/' at the beginning

### ISSUE THREAD

**Issue by frafra** [gbif/ipt#1700]
When I open `http://localhost:8080` the CSS styles are not loaded, as their URL is invalid, like: `http://localhost:8080;jsessionid=E163F9875ABEFD36881798E018528CBE/styles/reset.css`

Affected versions: 2.4.1 -> 2.5.4 (not sure about <2.4.1)

```
+ docker exec ipt-dev sh -c 'set -x; curl $(
    curl -sL localhost:8080 |
        grep -Po "(?<=href=\")[^\"]*" |
        head -n1
    )'
+ curl -sL localhost:8080
+ grep -Po (?<=href=")[^"]*
+ head -n1
+ curl http://localhost:8080;jsessionid=E163F9875ABEFD36881798E018528CBE/styles/reset.css
curl: (3) URL using bad/illegal format or missing URL
```

**Comment by MattBlissett** [comment]
This is reproducible in a private window (or with cookies cleared) when using Docker.

@mike-podolskiy90, I think we probably need `<tracking-mode>COOKIE</tracking-mode>` in web.xml's session-config.

**Comment by mike-podolskiy90** [comment]
Thanks @frafra @MattBlissett I added that
