### ISSUE TITLE
identifiedByID is not being parsed

### ISSUE THREAD

**Issue by ymgan** [gbif/ipt#1703]
Hi 

I just published a dataset https://ipt.biodiversity.aq/resource?r=bas-pycnogonida_2007-2019 
The field `identifiedByID` was mapped to occurrence field (in Manage Resources), but I do not see it in the Darwin Core archive generated. 

![Screen Shot 2021-12-14 at 3 34 03 PM](https://user-images.githubusercontent.com/11754081/146018943-7519bfe3-d1a7-4ad9-8bc6-c2d3bf3a0062.png)

Our IPT version is 2.5.4-raf6eaba 

I wonder if this could be a bug? Can you please advise? Thank you so much!

**Comment by rukayaj** [comment]
I've also noticed this in our datasets. recordedByID and identifiedByID are not appearing in the mapping preview. Tagging @dshorthouse so he is aware for Bionomia imports too.

**Comment by rukayaj** [comment]
@MattBlissett

**Comment by mike-podolskiy90** [comment]
Thanks for contacting us, we're looking into this

**Comment by mike-podolskiy90** [comment]
Are there any errors in the IPT logs please?

**Comment by ymgan** [comment]
Hey, thanks for looking into this. I don't see any error from this dataset publication in the IPT logs, please correct me if I am wrong @silenius

**Comment by rukayaj** [comment]
I don't see any related errors in our IPT logs either... But the fact that the recordedByID and identifiedByID fields are not appearing in the mapping preview suggests it's not to do with the data publication process I guess? The fields just aren't getting mapped for some reason. 
<img width="1339" alt="Screenshot 2021-12-16 at 14 38 22" src="https://user-images.githubusercontent.com/9654499/146382251-f9838abd-1480-4fe8-9be2-8417c2030a03.png">

**Comment by ymgan** [comment]
+1 to what @rukayaj mentioned, I encountered the exact same issue

**Comment by dshorthouse** [comment]
Thank you @rukayaj and @ymgan. I too had noticed a significant drop (1M+) in the links that were once present in `identifiedByID` and `recordedByID` in a download from GBIF a week ago, https://www.gbif.org/occurrence/download/0076148-210914110416597 and exceptionally chose to ignore this in favour of retaining what was once present approx. two weeks prior, https://www.gbif.org/occurrence/download/0065455-210914110416597. Ordinarily, I flush all these linkages and rebuild for Bionomia to maintain synchrony with sources. I had not yet investigated what was going on.

**Comment by mike-podolskiy90** [comment]
This is because some of the terms (`recordedByID`, `identifiedByID`, `genericName`) have become tdwg terms instead of GBIF in the most recent version of the dwc-api, so the IPT fails to recognize them.
We're working on bringing new Darwin Core functionality to the GBIF infrastructure and the IPT (https://github.com/gbif/ipt/issues/1653), but that work will be ready in 2022.
Now we can downgrade the dwc-api library in the IPT, and release a new version. This affects only those IPTs that use the terms above.
Sorry for inconveniences

**Comment by silenius** [comment]
> Hey, thanks for looking into this. I don't see any error from this dataset publication in the IPT logs, please correct me if I am wrong @silenius

nop, no errors in the IPT logs
