### ISSUE TITLE
Customization of session time out

### ISSUE THREAD

**Issue by RicardoOrtizG** [gbif/ipt#1710]
Many users and IPT administrators/editors want to have a longer time before the session expired. We are trying to setup the time session, but it has to be done modifying the docker and compiling again. We are wondering if is possible to parametrisize this in a simplier way in a customization file.

**Comment by mike-podolskiy90** [comment]
Thanks @RicardoOrtizG 
It's not possible now, but we can make that thing configurable in the future

**Comment by mike-podolskiy90** [comment]
@RicardoOrtizG How do you customize that please?

**Comment by RicardoOrtizG** [comment]
Hi! @mike-podolskiy90  I'm sorry for taking a lot of time to answer but I needed confirmation from a third-party TI.

In the file AppConfig.java in the folder config https://github.com/gbif/ipt/blob/master/src/main/java/org/gbif/ipt/config/AppConfig.java in line 85 there is a constant named **CSRF_TOKEN_EXPIRATION** whit the value 15*60, equivalent to 15 minutes. 

The TI explains to me that he has to make a change on this value in order to increase the time of the session, and it implies a modification of the IPT that we are trying to avoid. 

The idea of @MattBlissett sounds good to us too.

**Comment by mike-podolskiy90** [comment]
Thanks @RicardoOrtizG 
So let's just increase this property a little? That would be much easier, and more secure I think.
What value do you use please?

**Comment by RicardoOrtizG** [comment]
I made a consultation within SiB Colombia and we consider 60 minutes is enough time for the session to close. Thanks!

**Comment by sylmorin-gbif** [comment]
Hello,

I did a PR (https://github.com/gbif/ipt/pull/1731) to allow the customization of the session timeout in the ipt.properties file.
By default (if nothing is set in the ipt.properties file), the value is set to 1 hour.

We had the same requirement in France, especially for training sessions where it's frustating to loose it's pending work.

@RicardoOrtizG , be careful, the CSRF_TOKEN_EXPIRATION is not the session timeout.
It's the CSRF token timeout, which is used to prevent CSRF attack (before the login is done).

To change the session timeout, you need to change the web.xml file, or by code, use the setMaxInactiveInterval on the session object (https://github.com/gbif/ipt/blob/f45b86c1bb374810a04af7dc4eae128f62ba2191/src/main/java/org/gbif/ipt/action/LoginAction.java#L91)

Cheers,
Sylvain

**Comment by RicardoOrtizG** [comment]
Thanks a lot, @sylmorin-gbif  for the recommendation, we will take this into consideration for further opportunities, for now, I think the 1-hour default configuration will work for us.

**Comment by mike-podolskiy90** [comment]
Thanks @sylmorin-gbif , I merged the PR. Closing this one
