### ISSUE TITLE
Untranslated terms in version 2.5.4.

### ISSUE THREAD

**Issue by RicardoOrtizG** [gbif/ipt#1712]
We are working around the implementation of the IPT's version 2.5.4. and we are seeing that there is an untranslated terms for the publishing type (checklist, occurrence, samplingevent) above each resource title. I look for them in Crowdin and I see is all translated in spanish, and Í cant find this specific terms for translation.

So, I'm wondering if this new terms are not aveible por translation yet, or we have to do something else to have this in spanish.

![imagen](https://user-images.githubusercontent.com/15789737/146972243-d0ddd99a-b400-4a67-9756-be746c928fec.png)

![imagen](https://user-images.githubusercontent.com/15789737/146972284-6c27b9ca-fe8a-49f9-a540-691c503f79da.png)

**Comment by mike-podolskiy90** [comment]
Thank you @RicardoOrtizG 
Those are not available for translation yet indeed. I'll add those in the next release

**Comment by mike-podolskiy90** [comment]
All values taken from https://rs.gbif.org/vocabulary/gbif/dataset_type.xml
It already contains translations for all the IPT languages except russian

**Comment by RicardoOrtizG** [comment]
Great!, but I think the translation for samplingevent is missing in the vocabulary you are sharing, and it is present in the datasets as show below.

![imagen](https://user-images.githubusercontent.com/15789737/147262156-d6d3f3d0-ce45-42e6-8215-e7793239ac64.png)

**Comment by mike-podolskiy90** [comment]
Indeed, there is another vocabulary file https://rs.gbif.org/vocabulary/gbif/dataset_type_2015-07-10.xml

**Comment by EstebanMH-SiB** [comment]
@mike-podolskiy90 I found another bit of text that I coudn't find in Crowdin to translate. Do you know if it is available?

<img width="805" alt="Image" src="https://github.com/user-attachments/assets/505812d0-503f-4b0b-82aa-e3b1e0f66f0d" />

**Comment by mike-podolskiy90** [comment]
Maybe I didn't add a translation for it, I will check
