### ISSUE TITLE
Connection passwords are transmitted to client without [good] reason

### ISSUE THREAD

**Issue by raffael-mnhn** [gbif/ipt#1713]
When editing a Data Source, the server provides the client's form with the real password. This is not necessary as the user should probably not be able to read it from there or incrementally edit it (ie. changing some characters).

The backend could send a fixed sentinel value that would be read by the save controller to check if the password needs to be updated or if no change was done.

The thread that would be mitigated here would be an attacker gaining access to a user's account being able to get the database password which they might use to access the database (often in an unrestricted way). After mitigation as described, the attacker might be able to modify other things but at least they would not be able to recover the password.

![Screenshot from 2021-12-23 14-13-31](https://user-images.githubusercontent.com/95858226/147246221-21ff58ca-05e3-4a17-a85a-7a1ad0270861.png)

**Comment by mike-podolskiy90** [comment]
Thanks @raffael-mnhn , I'll look into that
