### ISSUE TITLE
The EML redirect the page to "manualy" download the file

### ISSUE THREAD

**Issue by RicardoOrtizG** [gbif/ipt#1715]
The EML download doesn't respond like the other downloads options (DwC-A and RTF), It redirects the page to the EML content and the user have to click to download in XML format, It could be a little confusing for people not familiarized with the EML archive and also each web navigator shows it differently (see images below). I'm wondering if is possible that the download button directly makes the download like the other options.

Image of the download in Mozilla.
![imagen](https://user-images.githubusercontent.com/15789737/147482391-72cca5aa-9068-48f7-9243-18c8c08b151c.png)

Image of the download in Chrome
![imagen](https://user-images.githubusercontent.com/15789737/147482608-a16974b9-658e-4758-9f7b-1e4c2b898c34.png)

**Comment by mike-podolskiy90** [comment]
Thank you for reporting this @RicardoOrtizG 
I think it's been working like this for a long time. Do you think it would be better download that?

**Comment by RicardoOrtizG** [comment]
Sorry, I had in my mind that the download was a 'file'.xml, anyway, I think it would be better for the user to download the file directly and avoid the change of formats between Chrome and Mozilla.

**Comment by mike-podolskiy90** [comment]
Thanks, we'll consider changing that
