### ISSUE TITLE
Error window emerge when try to add a vocabulary translate

### ISSUE THREAD

**Issue by RicardoOrtizG** [gbif/ipt#1718]
I'm mapping some datasets to publish but when clicking in the option for translation in the dcterms:type (Just for proving) send the error window I show below:

![imagen](https://user-images.githubusercontent.com/15789737/147792547-dc8a9ada-941b-479c-9e0f-9e4eb2243587.png)

![imagen](https://user-images.githubusercontent.com/15789737/147792698-02c6c63f-8a6c-4def-98d5-943ed2720d19.png)

with the dcterms: description was no problem.

**Comment by mike-podolskiy90** [comment]
Thank you for reporting this bug @RicardoOrtizG. We'll fix it
