### ISSUE TITLE
How to get verbatim identification term?

### ISSUE THREAD

**Issue by ManonGros** [gbif/ipt#1719]
This comes from one of our Node Managers. They are trying to map some values to the `verbatimIdentfication` field but don't see the field in the IPT.
This is from our test IPT:
<img width="828" alt="Screenshot 2022-01-03 at 15 54 49" src="https://user-images.githubusercontent.com/7677271/147945680-451ce353-3c96-4990-b5bd-36552f5b15f4.png">
This is from their IPT:
![CapturaIdDwC](https://user-images.githubusercontent.com/7677271/147945885-22f30e82-09f7-429a-87de-ef7cb936caca.JPG)

They have updated their vocabulary and extensions. What else could they try? Any input?

**Comment by mike-podolskiy90** [comment]
Thanks Marie, I'll check it

**Comment by mike-podolskiy90** [comment]
@MattBlissett is this a recently added term?

**Comment by mike-podolskiy90** [comment]
@ManonGros I've just checked sandbox rs.gbif.org, and found it:
http://rs.gbif.org/sandbox/core/dwc_occurrence_2021-08-16.xml
So it's not supported yet by prod IPTs, but can be used in test ones

**Comment by ManonGros** [comment]
Thank you @mike-podolskiy90 this is really good to know!

**Comment by ManonGros** [comment]
@mike-podolskiy90 any idea when it could be available in prod?

**Comment by mike-podolskiy90** [comment]
Soon I guess. But I don't know the status
