### ISSUE TITLE
Auto publishing doesn't seem to work

### ISSUE THREAD

**Issue by ManonGros** [gbif/ipt#1720]
This concerns this dataset: https://registry.gbif.org/dataset/c8227bb4-4143-443f-8cb2-51f9576aff14/ingestion-history
According to the auto-publishing schedule, the dataset's new version should have been published on the 15th of December (see screenshot below) but it wasn't (see ingestion history above), @deepreef had to trigger it manually yesterday. How can they troubleshoot this issue?
![Unknown](https://user-images.githubusercontent.com/7677271/148201073-c8a77223-75f2-45bd-8358-3236be9c8476.jpeg)

**Comment by mike-podolskiy90** [comment]
Thanks Marie
Is there anything in the logs? Could they send us the log file?

**Comment by mike-podolskiy90** [comment]
they should update their IPT by the way, they use extremely outdated 2.3.6

**Comment by ManonGros** [comment]
I just asked for the log files by email. @deepreef is also on GH if you need to tag him.

**Comment by mike-podolskiy90** [comment]
@ManonGros @deepreef Thank you, I checked the log file, but unfortunately I didn't find anything related to the issue. I would strongly suggest to update the IPT to the most recent version (the 2.3.6 is almost 4 years old). Since then auto-publishing functionality was changed, so it may solve the issue.

**Comment by mike-podolskiy90** [comment]
I don't see any issues with auto-publication in the most recent version so I'm closing this.
Feel free to re-open this, if you have issues with the new version of the IPT
