### ISSUE TITLE
Organization Token VS IPT Password

### ISSUE THREAD

**Issue by ckotwn** [gbif/ipt#1721]
We've been using **IPT Password** to refer to the string that is provided to the data publisher for asking IPT administrators to associate the technical installation with the organization. The term is used in IPT UI, manuals, email as well as verbal communications.

Years gone by, it's very often that perspective data publishers got confused when asked to provide such a _password_ to an IPT Administrator, while they also have an account:password pair to log on to that IPT. Imagine how often we need to explain to a publisher "... oh, that _IPT Password_ is **NOT** your login password but an _organization token_ you need to ..." I think we can do better to consolidate the terminology here.

Since **organization token** is already being used in @ManonGros 's explanation. I propose we work together to use that to globally replace _IPT password_ where it means **organization token**, in our slides, manuals, IPT UI and communications. It can be gradual and I think our network will adapt smoothly.

What do you all think? This of course needs blessings from @ahahn-gbif @laurarussell @mike-podolskiy90.

**Comment by MattBlissett** [comment]
We changed it in the registry for exactly this reason.  Let's wait and see what Laura says, as if there are videos those take much more time and effort to re-record and translate.

**Comment by laurarussell** [comment]
I concur. I much prefer the token terminology as it has always been strange to ask people to share a password they don't even know really exists. I don't think we discuss using the password in any of the basic videos. I'll check the DM course for mentions in the text. We typically only cover it in the course if people as more advanced questions about the IPT.

**Comment by ckotwn** [comment]
<img width="1277" alt="Screenshot 2022-01-20 at 18 11 11" src="https://user-images.githubusercontent.com/637631/150318763-959d5d90-e504-4528-b56b-6f07e45f4c98.png">
As I just finished a call with Cambodian IT introducing adding a publishing organisation on the IPT, this term is exactly where I stumbled upon along with extra explanation. I reckon this is the start of the change to "Organisation token" and it will be followed else where.

**Comment by MattBlissett** [comment]
I've updated the UI and the manual on the dev branch.  It won't be available for translation until it's merged into the master branch.

**Comment by mike-podolskiy90** [comment]
closing this
