### ISSUE TITLE
Published datasets stuck without organization after update

### ISSUE THREAD

**Issue by matdillen** [gbif/ipt#1724]
We updated both our regular and test mode IPT last month to fix the log4j vulnerabilities. Since then, datasets which had previously been registered with GBIF are stuck without an organization in their metadata (see image below). 

After updating, we had to manually re-add our organization to the IPT "GBIF registration options page", something we did not have to do after previous updates. Possibly, this problem is related to some DNS problems we had after the update, which caused most requests to the GBIF registry to fail. These DNS problems have since been resolved, but we are still stuck with all our datasets locked out of publication.

![iptdatasetstuck](https://user-images.githubusercontent.com/37537540/149129766-dea16531-4f44-4ea0-8f85-040b123fa473.jpg)

**Comment by mike-podolskiy90** [comment]
Thank you for contacting us @matdillen, we'll try to find out what happened.
Do you happen to have anything related to it in the logs? Could you send us the log file please?

**Comment by matdillen** [comment]
Attached the log for our test mode IPT:

[iptdevlog.log](https://github.com/gbif/ipt/files/7854227/iptdevlog.log)

**Comment by MattBlissett** [comment]
That log file is from after the organizations had already disappeared, I think.

If you have a backup of the data directory, and haven't made any changes to the data, it is probably simplest to shut down the IPT, restore the data directory from a backup, and restart the IPT.

I suspect your intermittent DNS problem (e.g. half of queries failing, or whatever it might be) could have caused the problem during startup. Mikhail is investigating.

**Comment by mike-podolskiy90** [comment]
Unfortunately, I didn't figure out what exactly happened there. It was most likely a startup issue because of DNS problems, but I couldn't reproduce it. We will keep an eye on this.
@matdillen Have you tried to recover data from backups as Matt suggested please?

**Comment by matdillen** [comment]
@MattBlissett @mike-podolskiy90 My apologies for the delay, but our IT staff were extremely busy the last few weeks. 

As Matt suggested, we have restored an earlier data backup, while retaining the modified DNS settings. This seems to have solved the problem of datasets being locked without an organization. I will now try to make a new publication as soon as possible, but I don't expect any problems anymore.

To reproduce, I think you'd need to do the following:

- Have an older IPT instance with a published (and registered) dataset
- Ensure in your DNS settings that the IPT instance cannot reach the GBIF registry
- Update the IPT instance to a newer version
- See for warnings/check the metadata of the dataset for an organization
- Try to manually add the organization after restoring DNS to see if this fixes the lack of organization problem

But I suspect our DNS problems did not cause all requests to fail, so it may be more tricky than this.
