### ISSUE TITLE
Issue "log4j ManagerFactory unable to create manager" when upgrading the IPT to 2.5.5

### ISSUE THREAD

**Issue by ftheeten** [gbif/ipt#1726]
when I try to point on the previous data folder (version 2.3.5) I receive this error message :
ManagerFactory [org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory@29bb5711] unable to create manager for [/var/ipt_rmca_data/logs/debug.log] with data **_[org.apache.logging.log4j.core.appender.rolling.RollingFileManager$FactoryData@6b57e7fb[pattern=/var/ipt_rmca_data/logs/debug.log.%i, append=true, bufferedIO=true, bufferSize=8192, policy=CompositeTriggeringPolicy(policies=[OnStartupTriggeringPolicy, SizeBasedTriggeringPolicy(size=10485760)]), strategy=DefaultRolloverStrategy(min=1, max=7, useMax=true), advertiseURI=null, layout=%-5p %d{dd-MMM-yyyy HH:mm:ss} [%c] - %m%n, filePermissions=null, fileOwner=null]]_**    

The data folder was previously a 2.3.5 version (the IPT had probably the log4J jars replaced last year).
The data folder has the “tomcat” owner (which is the same owner as for _/var/lib/tomcat/webapps_) and _/var/ipt_rmca_data/logs/debug.log_ is now set with a 777 permission.

**Comment by MattBlissett** [comment]
If you're using Debian or Ubuntu, it could be the security sandboxing settings: https://ipt.gbif.org/manual/en/ipt/2.5/faq#i-get-the-following-error-the-data-directory-directory-is-not-writable-what-should-i-do ("On systems with security sandboxing...").

Check the permissions on `/var/ipt_rmca_data/logs` (the directory itself, e.g. `ls -l /var/ipt_rmca_data`) as the log manager's first action will be to rename debug.log to debug.log.1, then create a new debug.log.

**Comment by mike-podolskiy90** [comment]
related #1616

**Comment by ftheeten** [comment]
Hi, the problem still occurs, even  by putting a 777 permission on the log folder 
![image](https://user-images.githubusercontent.com/13105610/149369405-433838f3-fb43-4b15-97e7-4fe500e4350a.png)

**Comment by MattBlissett** [comment]
Which OS is this? Debian, Ubuntu, Red Hat, CentOS, something else?

**Comment by ftheeten** [comment]
It's an Ubuntu 20.04.3 LTS

**Comment by MattBlissett** [comment]
You probably need to change the security sandboxing settings: https://ipt.gbif.org/manual/en/ipt/2.5/faq#i-get-the-following-error-the-data-directory-directory-is-not-writable-what-should-i-do ("On systems with security sandboxing...").

**Comment by ftheeten** [comment]
Yes, that was the issue. Thanks !
The old datasets are recognized and I can log to it.

I noticed another, minor, issue. For a few minutes after the installation, I couldn't log to the IPT. It was not even displaying the red toolbox mentioning that a wrong password had been entered (like in the image below). But this has been fixed after about 15 to 20 minutes...

![image](https://user-images.githubusercontent.com/13105610/149376816-08ca0e95-4878-413b-8d46-f5c7702e6cc0.png)

**Comment by MattBlissett** [comment]
Glad to hear it. I have split this part of the FAQ into a new question.

https://ipt.gbif.org/manual/en/ipt/2.5/faq#sandboxing

An IPT with many datasets (hundreds) can take a few minutes to start up, but I don't know what would have caused login to be delayed.
