### ISSUE TITLE
Enable correct automapping for terms with the same label (i.e. consider namespace)

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#1739]
Some extensions like Audubon Core have terms with the **same label** (coming from a different namespace). E.g. `type`:
<img width="853" alt="Screenshot 2022-02-11 at 12 27 39" src="https://user-images.githubusercontent.com/600993/153584037-62061d35-5303-45ad-bbe0-16d985b35f0e.png">

Automapping for these terms uses the header as usual, but then maps **to both** terms. So a column with header `type` would be mapped to both:
<img width="852" alt="Screenshot 2022-02-11 at 12 31 38" src="https://user-images.githubusercontent.com/600993/153584361-cbcb2991-8cb7-43aa-90b2-677160fc9fec.png">

I think this is normal behaviour, but a bit annoying, as it might result in incorrect mappings: both terms have different definitions and expect different values (here literal strings vs URIs).

Could it be implemented that one can provide a namespace in the header to force mapping to the correct term, e.g.:

header | maps to | behaviour
--- | --- | ---
`type` | both `dc:type` and `dcterms:type` | current behaviour, keep
`dc:type` | `dc:type` | new behaviour
`eventDate` | `dwc:eventDate` | current behaviour, keep
`dwc:eventDate` | `dwc:eventDate` | new behaviour

**Comment by mike-podolskiy90** [comment]
Thank you @peterdesmet 
That makes sense, we'll try to add this in a future release

**Comment by mike-podolskiy90** [comment]
Done. Deployed to [UAT](https://ipt.gbif-uat.org)

**Comment by mike-podolskiy90** [comment]
@peterdesmet you can check it there if you want. Closing this
