### ISSUE TITLE
To change password, the current one != the login one

### ISSUE THREAD

**Issue by ckotwn** [gbif/ipt#1740]
Trying to change my own password on the Asia IPT.

I logged in with passworda, and would like to change it to passwordb. In the 'Current Password' field, I suppose I should use passworda. But the IPT gives me 'The password provided doesn't match.'

<img width="1298" alt="Screenshot 2022-02-12 at 09 54 49" src="https://user-images.githubusercontent.com/637631/153691993-84a78447-db6d-4104-8582-8882422c24a3.png">

1) The error message can be more explicit. Against what does it try to match?
2) If it indeed should be the login password, which I assume so, then something wrong happened.

**Comment by mike-podolskiy90** [comment]
Thank you @ckotwn I'll check it

**Comment by mike-podolskiy90** [comment]
Thank you for spotting this quickly @ckotwn !
This is fixed now, I re-deployed cloud IPTs.
Since field is called 'Current password', it of course compares with the current login password, but we can improve wording if you find this confusing.

**Comment by ckotwn** [comment]
@mike-podolskiy90 I think the wording does make sense - I was just making logical assumptions.
I've just successfully changed my password. Thank you so much!
