### ISSUE TITLE
editing metadata for an existing dataset: provide visible "back" or "cancel" navigation

### ISSUE THREAD

**Issue by ahahn-gbif** [gbif/ipt#1744]
Entering editing mode for the overview of an existing dataset, the most prominent option at the top is "delete". The button shows a dropdown arrow, but it is a bit scary for a user to try what might happen on selecting it. I would expect some kind of visible alternative to "cancel" editing or navigate "back" out of the editing view.

**Comment by mike-podolskiy90** [comment]
Thank you Andrea for your suggestion
Yes, I think we can an additional button there
