### ISSUE TITLE
Bug introduced with updates to the GBIF registered extensions page

### ISSUE THREAD

**Issue by albenson-usgs** [gbif/ipt#1747]
The two IPTs we oversee have the same error occurring:
"Can't load local extension definition: Can't parse local extension file: Error at line 138 char 27: An error occurred while trying to install vocabulary https://rs.gbif.org/vocabulary/mixs/biotic_relationship.xml." see https://www1.usgs.gov/obis-usa/ipt/. It's because that link has a 404 error. Note that the mixs extension is not installed on the OBIS-USA IPT so I don't know why it would be looking to load it.

**Comment by MattBlissett** [comment]
I'm not sure why you would start to see this now. Would you try restarting the IPT?

Someone reported a problem with that extension this morning: https://github.com/gbif/rs.gbif.org/issues/89 and it's fixed (at 11:44 UTC).

**Comment by albenson-usgs** [comment]
The IPT was restarted today. It didn't show up until the restart. It's also happening here https://bison.usgs.gov/ipt/. That IPT was restarted last night and we noticed the issue this morning. At that time the OBIS-USA IPT did not have an issue and we restarted it and that's when the issue showed up on that one as well.

**Comment by MattBlissett** [comment]
Ah, sorry. Some configuration I thought was only for test/sandbox extensions was also needed for the production DNA extension.  Restarting the IPT should now work, and https://rs.gbif.org/vocabulary/mixs/biotic_relationship.xml does too.

**Comment by albenson-usgs** [comment]
Thanks Matt!
