### ISSUE TITLE
Temporal Coverage doesn't allow for year only or year month only date ranges

### ISSUE THREAD

**Issue by albenson-usgs** [gbif/ipt#1752]
In previous implementations of the IPT I could select a Temporal Coverage that was year only. For instance "1910 - 2018". It doesn't seem possible to include date ranges like this anymore with the addition of the calendar entry.
<img width="372" alt="Capture" src="https://user-images.githubusercontent.com/7586150/157080630-26e3ba83-3492-4518-a24f-6f7d093754ad.PNG">
<img width="529" alt="Capture2" src="https://user-images.githubusercontent.com/7586150/157080645-138a157d-f2fb-4eba-8273-4905da3cc5cd.PNG">
If I try to enter only a year the date defaults to the current date. I would like to be able to type in a date range using ISO format which can be year only or year-month.

**Comment by mike-podolskiy90** [comment]
Thank you for reporting this @albenson-usgs 
We'll fix this
