### ISSUE TITLE
EML maintenanceUpdateFrequency Unknown is mapped to UNKOWN via EmlValidator

### ISSUE THREAD

**Issue by PietrH** [gbif/ipt#1757]
If you set the update frequency to Unknown via the picklist on the IPT, you'll get a value of UNKOWN in the EML, this is a spelling mistake. 

See also: https://github.com/gbif/ipt/blob/1f11fa4dec5e19803e9c93e2b4432ebb650c2c8d/src/main/java/org/gbif/ipt/validation/EmlValidator.java#L244

Reproducible example in R: 

```
> rgbif::datasets(uuid = "b740eaa0-0679-41dc-acb7-990d562dfa37")$data$maintenanceUpdateFrequency
[1] "UNKOWN"
```

In the EML file:
```
      <maintenance>
          <description>
              <para>monthly updates</para>
          </description>
          <maintenanceUpdateFrequency>unkown</maintenanceUpdateFrequency>
      </maintenance>
```

**Comment by mike-podolskiy90** [comment]
In EML 2.2, the correct 'unknown' was added along with the erroneous 'unkown'.
Check this schema out https://eml.ecoinformatics.org/schema/
