### ISSUE TITLE
Change UI to make project contact optional

### ISSUE THREAD

**Issue by ahahn-gbif** [gbif/ipt#1760]
At present, the UI metadata editor enforces to also register a contact person when project information is registered. This is not actually required. ~~Instead, the project identifier should be.~~

--
context: 
~~Manage Resources -> Edit Metadata -> Project Data -> Identifier: should be mandatory (required)~~
Manage Resources -> Edit Metadata -> Project Data -> Project Personnel: should be optional (not required)
(the title remains mandatory, as is)

**Comment by mike-podolskiy90** [comment]
Thanks @ahahn-gbif

**Comment by ManonGros** [comment]
@ahahn-gbif I don't think the project identifier should be mandatory. Many people use the project description for other projects than BID and BIFA. I am afraid that making the identifier field mandatory would "pollute" the project identifiers available on GBIF.

**Comment by ahahn-gbif** [comment]
Good point. Updating the request.
