### ISSUE TITLE
Making pending version private results in Not Authorized

### ISSUE THREAD

**Issue by pieterprovoost** [gbif/ipt#1768]
Making a pending version of a publicly published resource private results in "Not Authorized" when trying to view the resource page, although the resource still shows up on the IPT home page as well as in the RSS feed. ~~For example: https://www1.usgs.gov/obis-usa/ipt/?search=legacy+tissue~~

The issue seems to be with this interceptor which, as opposed to `ResourceAction.detail()`, does not check the version history: https://github.com/gbif/ipt/blob/master/src/main/java/org/gbif/ipt/struts2/PrivateDeletedResourceInterceptor.java#L85

**Comment by mike-podolskiy90** [comment]
Thank you Pieter for reporting this issue

**Comment by pieterprovoost** [comment]
Sure. My assumption is that changes in visibility are not supposed to have any effect until the resource is republished, but maybe I'm wrong.

Steps to reproduce:

1. Create new resource
2. Set visibility to public and publish
3. Change visibility to private without publishing
4. Sign out
5. The resource is now visible on the home page and in the RSS feed (as expected), but trying to view it results in "Not Authorized"

https://user-images.githubusercontent.com/490041/165763810-5abcd954-1fec-4025-9a7d-c2d8bd713134.mov
