### ISSUE TITLE
Failed to load networks from Registry: https://gbrds.gbif.org

### ISSUE THREAD

**Issue by RicardoOrtizG** [gbif/ipt#1769]
On the IPT home page, we are having this alerts related to some network registry. It only happens in one of the IPTs we have (https://ipt.biodiversidad.co/sib/). All of our IPTs are in the 2.5.4. version, so we don't know if it is an issue related to the installation of the IPT or due to some change in the GBIF registry. 

Please let us know if you know how to solve it. For now, we continue publishing data and this problem doesn't seem to affect that.

![imagen](https://user-images.githubusercontent.com/15789737/163893060-747590ac-a14c-4928-a81d-e205170cda07.png)

@MattBlissett @sibcolombia

**Comment by mike-podolskiy90** [comment]
Thanks for reporting this issue @RicardoOrtizG 
This can happen in case of registry connection error. Please try to restart your IPT first, let me know if that helps

**Comment by RicardoOrtizG** [comment]
Thanks, it helps to solve the issue
