### ISSUE TITLE
Error Uploading Excel files

### ISSUE THREAD

**Issue by leo-buitrago** [gbif/ipt#1772]
Hello,

A user from a BID Caribbean project uploaded some excel files on the GBIF IPT Test on [this resource](https://ipt.gbif.org/manage/resource?r=ima_occ), but an error come out reading the files.

![Screen Shot 2022-04-25 at 9 33 21 AM](https://user-images.githubusercontent.com/61566113/165111531-8893c933-1bca-46f5-8e10-d2bfb61515dc.png)

To fix this issue, we were going to upload CSV adjusted instead, but we couldn't delete the old excel files as the next error is showing: 
![Screen Shot 2022-04-25 at 9 42 21 AM](https://user-images.githubusercontent.com/61566113/165113483-89491830-f8d7-4c32-84cd-398fc54855be.png)

I am sending attach the [logfile.txt](https://github.com/gbif/ipt/files/8555591/logfile.txt)

**Comment by mike-podolskiy90** [comment]
Thanks Leo for reporting this
I'll look into this issue

**Comment by mike-podolskiy90** [comment]
@leo-buitrago I checked this out, and unfortunately not much I can do with this.
The file they're trying to attach has a type "Strict Open XML Spreadsheet" which is not currently supported.
There is a long discussion  [here](https://bz.apache.org/bugzilla/show_bug.cgi?id=57699)
I of course will add a proper handling for this exception, so UI can response with an error, and source can be deleted.

p.s. you attached not the log file, but source code of the page
