### ISSUE TITLE
Programming dates for next releases

### ISSUE THREAD

**Issue by RicardoOrtizG** [gbif/ipt#1773]
Hi, @MattBlissett @mike-podolskiy90 

From SiB Colombia we want to update the IPT to the latest version, but we do this installation through an external consultation with a contractor. So, we are wondering about, when will be the next stable release in order to select the perfect timing to make the contract and be sure that there will be not a new major version pending.

Resuming, we are now in version 2.5.4. and we want to know if we can move forward to install version 2.5.7 or if it's better to wait for the next version with a major change release and when this will be. 

Thanks a lot.

**Comment by mike-podolskiy90** [comment]
Thank you @RicardoOrtizG for your question. 
Unfortunately, we don't have a fixed date for the next release, but we're currently working on bringing a new major version of the IPT. I expect we release it within a month, but it may take a little longer.

**Comment by mike-podolskiy90** [comment]
Please contact GBIF helpdesk with questions like this, closing this.
