### ISSUE TITLE
IPT Source Data

### ISSUE THREAD

**Issue by laurarussell** [gbif/ipt#1774]
Was wondering if the source data drop down could be designed to have a blank at the top instead of defaulting to Database. I think it is confusing for most people who will upload files to see Database and the connect button to the left. (I realize the drop-down list is in alpha order).  But I think it would make most sense if there was the blank value and then there is no mismatch between what you see on the add side versus what you see on the edit side.
<img width="1320" alt="IPT-SourceData" src="https://user-images.githubusercontent.com/742537/165485024-00b7f50e-e318-4c5a-8177-4409f63bfb67.png">

**Comment by peterdesmet** [comment]
I agree. If possible, I would set to blank if no source has been chosen yet and to the most selected source type if sources have already been added.

**Comment by mike-podolskiy90** [comment]
Thanks Laura and Peter.
Good idea! I'll do that
