### ISSUE TITLE
Password must be less than 70 bytes....

### ISSUE THREAD

**Issue by mcruz-umich** [gbif/ipt#1776]
Previously I was able to log in with my password which is 100 characters. Now it will not let me log in. See the error message in the attached screenshot.
<img width="905" alt="image" src="https://user-images.githubusercontent.com/36455924/165866046-3387b7e9-9280-446f-8eda-290cb09e9a66.png">

Thank you

**Comment by MattBlissett** [comment]
The IPT is now using the BCrypt hashing algorithm, which is limited to passwords of 71 bytes (often 71 characters).  

There are [workarounds](https://favr.dev/opensource/bcrypt#handling-for-overlong-passwords).

I would prefer the SHA512 workaround, or else limiting the length when the password is set.

**Comment by mcruz-umich** [comment]
Thanks! Turns our we did an update that pulled in that change and so it invalidated my password. Our SysAdmin was able to reset my password.
