### ISSUE TITLE
Getting a 100% offline IPT to load core files + extensions in admin/extensions

### ISSUE THREAD

**Issue by rukayaj** [gbif/ipt#1777]
Hiya, I'm in Armenia doing a BioDATA training course with @laurarussell. We've got a patchy internet connection, so I'm trying to set up a new version of the IPT on our raspberry pi for our students to connect to. 

We've unfortunately got no way of connecting the pi to the internet, so I've downloaded the latest IPT war, then put that on the pi where we have tomcat8, and it's deployed it. I added our students as users and everything is looking fine, but I don't seem to be able to trick it into loading the core files so that our students can actually use it. I copied over the .extensions and .vocabularies directories from the config folder of another online ipt (of the same version) and put them on the pi, but no dice, the error remains -`There are no Core Types installed.` I don't think there's a file permissions problem, I've fiddled with that a bit and still not got it working. Needless to say, I have restarted tomcat maaaaaany times.

Anyway, I'm certain that I've done this before previously with this same raspberry pi in pre-covid times, but I don't remember how I got it working. @laurarussell suggested I drop you guys a line and ask for a bit of help :) @MattBlissett any ideas?

**Comment by MattBlissett** [comment]
Hi,

We haven't tested or planned for a completely offline IPT.

I think you'll need to make a fake gbrds.gbif-uat.org (registry) and possibly rs.gbif.org (schemas and extensions), for example using Apache installed on the Pi.

```
mkdir -p gbrds.gbif-uat.org/registry/organisation
cd gbrds.gbif-uat.org/registry
for i in extensions.json network.json organisation.json thesauri.json; do wget http://gbrds.gbif-uat.org/registry/$i; done
touch organisation/625a5522-1886-4998-be46-52c66dd566c9.json
```

```
wget -r -R '*C=*' -R index.html http://rs.gbif.org
```

```
<VirtualHost *:80>
        ServerName rs.gbif.org
        DocumentRoot /home/matt/offline-ipt/rs.gbif.org

        <Directory /home/matt/offline-ipt/rs.gbif.org>
                   Require all granted
        </Directory>
</VirtualHost>

<VirtualHost *:80>
        ServerName gbrds.gbif-uat.org
        DocumentRoot /home/matt/offline-ipt/gbrds.gbif-uat.org

        <Directory /home/matt/offline-ipt/gbrds.gbif-uat.org>
                   Require all granted
        </Directory>
</VirtualHost>
```

**Comment by rukayaj** [comment]
Thanks @MattBlissett! I tried this with little success, and then we found a way to open up the pi to the internet. And now I have a new error :D 
` An IO error occurred while trying to communicate with the GBIF Registry. [https://gbrds.gbif-uat.org/registry/thesauri.json]`

The server can certainly access https://gbrds.gbif-uat.org/registry/thesauri.json as far as I can tell. I see that it's probably coming up here: https://github.com/gbif/ipt/blob/98c745a7e9e3eeb9f779420ef277ad658ea20467/src/main/java/org/gbif/ipt/service/registry/impl/RegistryManagerImpl.java#L470

I guess there is probably some file permissions problem, I suppose the IPT is trying to download thesauri.json to a temp folder somewhere and it's not been able to. To fix it I've tried reinstalling tomcat and setting 777 permissions on absolutely everything tomcat/ipt related that I come across in the filesystem. But it's still complaining.

This is kind of an academic problem now, the students will just have to (as well as they can with the internet problems) use the online IPT we set up for them on the server in Oslo (the session is up next in 15 minutes).  I'm still sort of interested in finding out what's going wrong though. It's probably something really simple which I should have set up in the tomcat installation that I missed.

**Comment by MattBlissett** [comment]
Is the Pi using a Debian/Ubuntu derivative?  It could be this: https://ipt.gbif.org/manual/en/ipt/2.5/faq#sandboxing

**Comment by rukayaj** [comment]
It is! I will take a look, thanks :)

**Comment by rukayaj** [comment]
Oh dear... It doesn't seem to be that. We're going to nuke it and start over from scratch. Will let you know how it goes! Thanks for your help though, much appreciated :)

**Comment by mike-podolskiy90** [comment]
Is this issue still relevant please?

**Comment by rukayaj** [comment]
No, it can be closed.
