### ISSUE TITLE
Option to add several projects in the Project data metadata page

### ISSUE THREAD

**Issue by SophiePamerlon** [gbif/ipt#1780]
Hi,

Several data publishers asked me why it isn't possible to add project info for several projects in the metadata (especially re: fundings); for now they have resorted to concatenating all project's info into the current sections of the 'Project data' metadata page, but it's not ideal for them... do you think this feature could be added to a future version of the IPT metadata?

Thank you :)
Sophie

**Comment by mike-podolskiy90** [comment]
Thank you for your question @SophiePamerlon 
I don't think it's possible. Under the hood we convert that to the [EML](https://eml.ecoinformatics.org/schema/) format, and it does not support more than one project

**Comment by peterdesmet** [comment]
Related: we have several datasets that are part of the same project and some datasets that are part of multiple projects.

I really like the concept of networks (e.g. https://www.gbif.org/network/2b7c7b4f-4d4f-40d3-94de-c28b6fa054a6), where a network is only defined once (not having to copy/paste metadata across datasets) and in the IPT you can assign a dataset to one or more of these. Zenodo communities work the same (with the option of a network curator to approve an assignment).

Unfortunately, as I have understood, we should not use networks for (shorter lived) projects, as their creation and maintenance is done by the GBIF Secretariat (and thus doesn’t scale). Would it be an option to expand the GBIF registry to support projects that users can create and maintain?

**Comment by timrobertson100** [comment]
> Under the hood we convert that to the [EML](https://eml.ecoinformatics.org/schema/) format, and it does not support more than one project

I'm really not an XSD expert but I think the [EML schema](https://eml.ecoinformatics.org/schema/) has an optional single `dataset/project` as a `ResearchProjectType` as you say. However, it looks like there are a couple of things that might help us:

1. `project/award` is unbounded in number, so multiple funders can be identified if that is the real need
2. `project/relatedProject` is unbounded, so any number of other projects can be included as children. It looks like there would still need to be a "primary" one though.

> Unfortunately, as I have understood, we should not use networks for (shorter lived) projects

It wasn't the original intention at least, which was to help larger international groups working as a sub-community raise the visibility of their work which includes many datasets (e.g. VertNet, OBIS etc). I gather here the intention is really about identifying the related projects within a single aggregate dataset, and ensuring funders are attributed. I'm not sure GBIF wants to get to that level of project registry centrally without some consideration (e.g. expectations of support, consistency across all countries, potentially large scale editing, metadata needs etc)

**Comment by timrobertson100** [comment]
@SophiePamerlon - is it really just multiple funders that you want, please? 
Can you point us to an example of what they are doing now?

**Comment by SophiePamerlon** [comment]
Hi @timrobertson100 
I think the main issue is linked to the 'funding' section indeed, but sometimes the project description and other project sections are limited too (see [this dataset](https://www.gbif.org/dataset/345820cc-a0a8-4d76-b7eb-fba85b21ad08/project), whose occurrences are funded by 2 projects (EI2P & VALLEEBEE - sorry, it's in French only), but the authors chose to describe the first one only as it would have been too confusing otherwise). Another example of concatenated projects will be published soon but it's still in private mode on our IPT so I cannot put the link yet.

**Comment by mike-podolskiy90** [comment]
With new EML 2.2.0 (IPT 3.1.0+) additional project can be added as related projects (many).
Closing this.
