### ISSUE TITLE
Error adding managers permissions to modify resources

### ISSUE THREAD

**Issue by RicardoOrtizG** [gbif/ipt#1781]
After the installation of the IPT's version 2.5.4 we have an issue with one of our [IPTs](https://ipt.biodiversidad.co/iavh/). It doesn't show the "Add" option in the "Resource Manager" section as shown below. So, we can add editors to the resources. 

<img width="1310" alt="imagen" src="https://user-images.githubusercontent.com/15789737/167701522-fcb2eca7-a175-4af6-8f63-f4de593bce0c.png">

We have tried to reinstall the IPT but the issue persists. We have already tried to install the 2.5.7 version and get the same result. We are running out of ideas to solve the issue, so we ask you if you know what can be the cause of the issue or if you have an idea of how to solve it.

If you need it, we can share privately some credentials or a copy of the IPT datadir.

**Comment by mike-podolskiy90** [comment]
Thanks @RicardoOrtizG for contacting us
Do you have managers among the IPT users?

**Comment by RicardoOrtizG** [comment]
Hi @mike-podolskiy90, 

Yes, we have 3 manager users with Admin roles. 
<img width="1191" alt="imagen" src="https://user-images.githubusercontent.com/15789737/167702883-602b5cee-72a9-45dd-8021-88d3f76e5f6e.png">

**Comment by mike-podolskiy90** [comment]
Admins are not present in the list. It should a manager

**Comment by RicardoOrtizG** [comment]
Yeap, that was the problem, all of them have user roles.

<img width="1349" alt="imagen" src="https://user-images.githubusercontent.com/15789737/167704205-03a63f04-0151-4762-8dcf-7027d7ea502f.png">

Thanks, Mike!

**Comment by RicardoOrtizG** [comment]
Maybe as an improvement, it could be more explicit here: https://ipt.gbif.org/manual/en/ipt/2.5/manage-resources#resource-managers. It indicates that only Admin roles could appear in the add label but not that the whole button will disappear if there is non Admin in the IPT users.
