### ISSUE TITLE
HTML description does not render in top snippet

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#1783]
Dataset descriptions now support HTML (#1571), which is rendered at several places:

- ~~[ ] Preview of description on IPT resource page: https://ipt.inbo.be/resource?r=o_westerschelde~~
- [x] Description on IPT resource page: https://ipt.inbo.be/resource?r=o_westerschelde#anchor-description
- [x] Preview of description on GBIF dataset page: https://www.gbif.org/dataset/20bbd36e-d1a1-4169-8663-59feaa2641c0
- [x] Description on GBIF dataset page: https://www.gbif.org/dataset/20bbd36e-d1a1-4169-8663-59feaa2641c0#description

It renders OK everywhere, except in the top preview in the IPT:

<img width="1136" alt="Screenshot 2022-05-20 at 13 18 49" src="https://user-images.githubusercontent.com/600993/169517726-74fd27eb-fbeb-4db4-b5c1-2b096fd4ec70.png">

**Comment by mike-podolskiy90** [comment]
Thanks @peterdesmet for reporting this, I'll fix
