### ISSUE TITLE
http 404 not set

### ISSUE THREAD

**Issue by mdoering** [gbif/ipt#1784]
When a non existing resource is requested the IPT returns a html page with "Resource Does Not Exist".
The http status code is 200 though, making it very hard for programmatic access of archives.
Please set the proper http code.

Example:
http://ipt.museums.or.ke/ipt/archive.do?r=asfbutter2019

**Comment by mike-podolskiy90** [comment]
https://github.com/gbif/ipt/issues/1427
Should be working in 2.5.8

**Comment by mdoering** [comment]
Nice, thanks! Now we just need everyone to update their installations ;)
