### ISSUE TITLE
Misleading warning GGBN permit status

### ISSUE THREAD

**Issue by camiplata** [gbif/ipt#1785]
From @sibcolombia we have been using the GGBN permit extension nevertheless when maping the data we getthe folowing warning indicating that the element permitStatusQualifier is mandatory, nevertheless it is not. Is possible to continue with the mapping and publciation but the warning is misleading for the pulishers.

![imagen](https://user-images.githubusercontent.com/5700527/170507301-02d5d0bb-2c7c-4a01-a1d6-aec1527c2593.png)

**Comment by mike-podolskiy90** [comment]
Thank you @camiplata 
`permitStatusQualifier` is a mandatory field according to the schema, but IPT allows to publish a resource indeed.
I'll check it

**Comment by camiplata** [comment]
Looking at the definition  (Description of why a certain permit was not required or why Permit Status is unknown See also) I don't see the logic of this element been mandatory, for example if the  PermitStatus is Know and documented there is no need to document permitStatusQualifier as it will be againts the element definition.

**Comment by mike-podolskiy90** [comment]
related https://github.com/gbif/portal-feedback/issues/3071

**Comment by mike-podolskiy90** [comment]
I guess we need to correct that in [rs.gbif.org](https://rs.gbif.org/extension/ggbn/permit.xml)

**Comment by mike-podolskiy90** [comment]
@MattBlissett what do you think?
