### ISSUE TITLE
Documentation about the version delete

### ISSUE THREAD

**Issue by RicardoOrtizG** [gbif/ipt#1786]
The option to delete the versions in a dataset is pretty intuitive, but I can't find documentation to reference for other IPT administrators. Maybe a section in the Manual could be helpful to guide about the pros and cons of the version deletes. 

Let me know if maybe I,m looking in the wrong place.

**Comment by mike-podolskiy90** [comment]
Thanks @RicardoOrtizG for the suggestion, I don't see that in the documentation too
