### ISSUE TITLE
Incorrect number of rows and columns read when using an Excel file with multiple sheets

### ISSUE THREAD

**Issue by EstebanMH-SiB** [gbif/ipt#1787]
We have detected a problem with Excel files that have multiple sheets, in the UI you can choose the sheet you want to take the data from, however the number of rows and columns is always of the first sheet, regardless if you choose a different one.

In this example [Plantilla de registros 4.0.xlsx](https://github.com/gbif/ipt/files/8806118/Plantilla.de.registros.4.0.xlsx) we have an Excel document with additional information in several sheets, the data goes in the second one, you can choose that without problems:
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/63795703/171200777-6509c618-9d9c-4e0b-be84-24298f86bb98.png">

But after you choose the data, it only reads 62 rows and 14 columns (the ones used in the first sheet) and it should read 497 rows and 76 columns:
<img width="846" alt="image" src="https://user-images.githubusercontent.com/63795703/171201214-e16d6855-3bbc-4255-a435-dbce6d62dc89.png">

The IPT read the info from the correct sheet but only the number of rows and columns from the first one. It should read the number of rows and columns from the selected sheet and not always the first.
<img width="1267" alt="image" src="https://user-images.githubusercontent.com/63795703/171201710-92344deb-4c5c-4e77-9d92-fe99d531e8f5.png">

Thanks for the help,

**Comment by mike-podolskiy90** [comment]
Thank you @EstebanMH-SiB for reporting this issue

**Comment by mike-podolskiy90** [comment]
@EstebanMH-SiB You need to hit `Analyze` button every time you change excel pages.

**Comment by EstebanMH-SiB** [comment]
Thanks @mike-podolskiy90, using the Analyze button worked perfectly. We should like to see that information included in the manual or maybe a information button in the IPT when you are uploading an Excel, because is not 100% intuitive to use that option instead of just saving.
