### ISSUE TITLE
Include keywords to filter resources

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#1788]
I think `title` and `shortname` are considered when filtering resources in the IPT. Would it be possible to include `keywords` as well?

<img width="1059" alt="Screenshot 2022-06-01 at 14 13 39" src="https://user-images.githubusercontent.com/600993/171402048-d4b37127-7192-4e92-b376-26628d7a63b8.png">

**Comment by mike-podolskiy90** [comment]
Thank you @peterdesmet for your question
I think it's possible, I'll check. Would it be useful?

**Comment by peterdesmet** [comment]
Yes, especially in large IPT it allows me (and others) to filter on datasets for a certain project, topic, etc. (assuming keywords were added).

**Comment by mike-podolskiy90** [comment]
This is implemented, deployed to [UAT](https://ipt.gbif-uat.org/)
