### ISSUE TITLE
Rethink about page

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#1789]
Many IPTs have an empty about page, which isn't helpful for visitors. The reason for this is likely twofold:

- If I remember correctly, the page can only be edited by updating a file on the server, which is quite cumbersome.
- IPT admins don't see the need for the IPT to have an about page.

Note that IPTs also have a "title" and "description" in `/admin/registration.do`. I believe that information is synced with the GBIF registry, e.g. https://registry.gbif.org/installation/9f25fd85-85dc-4dcd-a1b4-b31165442e2b

**Is there a need for IPTs to have an about page?**

If yes:

- Can the option be added to edit it from the administration section (dropping the option to edit a file on the server)?
- Can `About` be removed from the navbar if the About page is empty?

If no:

- Is there a need to add short description at the top of the IPT homepage (above the resources)? Could that be the same description (and title) as what can currently be written in `/admin/registration.do`? That section could also include links to the registered organization.

Crude attempt:

<img width="1153" alt="Screenshot 2022-06-02 at 10 30 37" src="https://user-images.githubusercontent.com/600993/171588940-dedb4e87-6b18-4633-881b-29b562d92bc1.png">

**Comment by mike-podolskiy90** [comment]
Thanks @peterdesmet 
Empty about pages was an IPT bug I recently fixed here https://github.com/gbif/ipt/issues/1751

**Comment by peterdesmet** [comment]
Thanks @mike-podolskiy90. Just curious if there is a need for IPT about pages, given that much of the relevant information can be pulled from existing info.

**Comment by mike-podolskiy90** [comment]
I don't have much of an opinion here. I'd rather leave the page as is (perhaps with a few minor cosmetic changes). But of course it's discussable.
Default IPT about page will look like this https://ipt.gbif-uat.org/about.do

**Comment by albenson-usgs** [comment]
Partially agree with Peter. Where to update the About page is confusing. I can't figure out where I'm supposed to update it. It means that what is on the GBIF page:
![Capture](https://user-images.githubusercontent.com/7586150/171644499-1ef90884-141c-459f-b02e-76a95117646f.PNG)

And what is on the IPT About page:
![Capture2](https://user-images.githubusercontent.com/7586150/171644572-4dbaa265-b1cc-43f2-b7ab-f22e95c59521.PNG)

Are not in sync. I would expect the About page in the IPT to update from the GBIF Registration Options in the Administration section of the IPT but that isn't what happens.

But I can see a use case for the About page as people who come to an IPT first before any aggregators may want to understand what it is. Also there are test IPTs and other IPTs that serve a range of purposes and people may want to understand more about what a particular IPT instance they land on is for.

**Comment by mike-podolskiy90** [comment]
Thank you @albenson-usgs for your comment.
You can synchronize your IPT with the GBIF registry by pressing `Update registration` in the admin/registration options

**Comment by mike-podolskiy90** [comment]
@albenson-usgs Hm, it can be that those values are hardcoded in the custom about page on your server. Could you check it please?

**Comment by albenson-usgs** [comment]
I don't have access to the server. I would have to request time from our IT staff so the answer would be slow but I can ask but I think this has to do with what Peter said above:

> - If I remember correctly, the page can only be edited by updating a file on the server, which is quite cumbersome.

**Comment by mike-podolskiy90** [comment]
I see. To make the page editable for admins would be convenient I guess

**Comment by mike-podolskiy90** [comment]
I have simplified the page as much as possible. All technical information can be viewed on GBIF to avoid sync issues (I've added a link). Example:
https://ipt.gbif-uat.org/about.do

**Comment by mike-podolskiy90** [comment]
Closing this
