### ISSUE TITLE
Right side menu for resource management page?

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#1791]
I notice on https://ipt.gbif-uat.org/ that the resource management page now has a menu (nice 👍 ). @mike-podolskiy90 is there a specific reason this menu is on the left side, and not on the right side, like it is in the metadata editor? If not, would it be possible to have both on the right for consistency?

![Overview-MICA-Muskrat-and-coypu-camera-trap-observations-in-Belgium-the-Netherlands-and-Germany-subsampled-representation-](https://user-images.githubusercontent.com/600993/171799849-f5f1718b-f564-4489-888f-9ecfbd2dfb64.png)
![Basic-Metadata](https://user-images.githubusercontent.com/600993/171799855-12580e72-8791-42db-a6e7-a223b3b158cc.png)

**Comment by mike-podolskiy90** [comment]
Thank you @peterdesmet 
Those side components have different purpose though. Resource page, resource overview, mappings - page navigation; metadata pages - section redirection. It actually used to be like that in the old IPT.

**Comment by peterdesmet** [comment]
Makes sense to have _in page_ navigation on the left (consistent with gbif.org).

I would argue that most users (including myself) would not consider the difference between _in page_ and _across page/section_ navigation, and would prefer to have the menu on the same side for all navigation. Especially since the metadata editor sections largely end up being _in page_ sections on a resource landing page (with a menu on the left).

**Comment by mike-podolskiy90** [comment]
We can try moving this nav to the left for the metadata pages. If we like this option more we can keep it then.

**Comment by peterdesmet** [comment]
Yes! I'm a fan. 😄 

![Basic-Metadata](https://user-images.githubusercontent.com/600993/171849994-64371fcd-d5ad-402e-8b53-724a1e36b33a.png)

**Comment by mike-podolskiy90** [comment]
Great! Closing it then
