### ISSUE TITLE
verbatimIdentificationProperty property unavailable on v2.5.4

### ISSUE THREAD

**Issue by ainsofs** [gbif/ipt#1793]
Hello,

I cannot find this [verbatimIdentification](https://dwc.tdwg.org/terms/#dwc:verbatimIdentification) property in the IPT. 

I am using v2.5.4 with a [docker image](https://hub.docker.com/layers/ipt/gbif/ipt/2.5.4/images/sha256-5eb1275c8ce9979d0a2fee84be8ef261cfb1e0d4228cbaff494a56d383aa0dce?context=explore) 

I have some pending updates for Darwin Core Taxon (24 April 2015) and Darwin Core Occurrence (15 July 2020) but I cant tell if updating them will address my issue.

Cheers,

**Comment by mike-podolskiy90** [comment]
Thank you for contacting us @ainsofs 
This term was introduced here https://rs.gbif.org/core/dwc_occurrence_2022-02-02.xml
So you need to update Occurrence to this version

**Comment by mike-podolskiy90** [comment]
Feel free to reopen it if that doesn't help

**Comment by ainsofs** [comment]
I confirm updating the Occurrence core resolved the issue for me. Thnx again
