### ISSUE TITLE
IPT fails to update registration with 401 Unauthorized

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/ipt#1794]
As per title. Screenshot:

![image](https://user-images.githubusercontent.com/24795387/172776746-a4fb4af6-354e-460a-b6cb-1906e17af218.png)

**Comment by mike-podolskiy90** [comment]
Closing this

**Comment by mike-podolskiy90** [comment]
This still happens on some IPTs

**Comment by mike-podolskiy90** [comment]
Looks like issues with the IPT password. Solution would be to change the password to the correct one
related https://github.com/gbif/ipt/issues/1885

**Comment by mike-podolskiy90** [comment]
Spotted issues on ipt.gbif-uat.org again. IPT may sometimes corrupt passwords somewhere

**Comment by kitelloran** [comment]
Does anyone encountered the same issue in their IPT? Mine was when I started updating my IPT to version Version 2.5.8-r37b18ef it started that error.
