### ISSUE TITLE
DCAT publisher syntax incorrect

### ISSUE THREAD

**Issue by MattBlissett** [gbif/ipt#1798]
At the end of the DCAT feed: https://ipt.gbif.org/dcat we have publishers like this:

```
<https://www.gbif.org/publisher/47a779a6-a230-4edd-b787-19c3d2c80ab5#Organization> a foaf:Agent ;
    foaf:name "Species File Group" ;
    foaf:homepage <[http://software.speciesfile.org]> .
```

The URL shouldn't be enclosed in square brackets, only angle brackets. See example: https://www.w3.org/TR/vocab-dcat-2/#ex-adms-identifier

I don't see why this happens:

https://github.com/gbif/ipt/blob/a8e5d236d0d7c113b15000892bdfc781e83b61b0/src/main/java/org/gbif/ipt/task/GenerateDCAT.java#L157-L167

https://github.com/gbif/ipt/blob/a8e5d236d0d7c113b15000892bdfc781e83b61b0/src/main/java/org/gbif/ipt/task/GenerateDCAT.java#L781-L797

CC @rubenpp7, thanks for reporting this.

**Comment by mike-podolskiy90** [comment]
Thanks Matt. This is because those URL already stored like that in registration2.xml

**Comment by mike-podolskiy90** [comment]
registry response https://gbrds.gbif-uat.org/registry/organisation/0a16da09-7719-40de-8d4f-56a15ed52fb6.json

**Comment by mike-podolskiy90** [comment]
https://github.com/gbif/registry/blob/dev/registry-domain/src/main/java/org/gbif/registry/domain/ws/LegacyOrganizationResponse.java#L72
in the registry `getHomepage` returns list so it's wrapped by square brackets

**Comment by mike-podolskiy90** [comment]
`foaf:name "Test Organization #1" ; foaf:homepage <https://www.gbif.org/>, <https://www.registry.gbif.org/> .`
@MattBlissett Is this right for the case with two URLs please?

**Comment by mike-podolskiy90** [comment]
I tested it on [UAT](https://ipt.gbif-uat.org/dcat) including an option with several homepage URLs.
@MattBlissett

**Comment by MattBlissett** [comment]
Yes, I'm fairly sure this is correct.

It passes on http://www.dcat.be:8080/validator/index.html, although by pasting in the text rather than using the URL. (The content type isn't correct — #1316 seems not to have worked, the content type should be `text/turtle;charset=UTF-8` but following https://struts.apache.org/core-developers/stream-result.html hasn't worked)

**Comment by mike-podolskiy90** [comment]
Closing this
