### ISSUE TITLE
Taxonomic Coverage subsection of the IPT metadata: 'add several taxa' functionality doesn't work

### ISSUE THREAD

**Issue by SophiePamerlon** [gbif/ipt#1800]
Hi all,

We've just been notified a bug in the IPT's 'Taxonomic Coverage' subsection of the metadata, where nothing happens when one tries to add several taxa at once using the 'add several taxa' functionality. I tried replicating the issue on our test IPT and the same thing happens, whether I copy/paste the list of taxa or try to add them manually in the 'add several taxa' text box.
The option to add each taxon individually remains (and works) but it's very time consuming in this case as the taxon list is quite large.

**Comment by mike-podolskiy90** [comment]
Thank you for reporting this @SophiePamerlon
Looking into it

**Comment by mike-podolskiy90** [comment]
We can actually consider removing this functionality since we're currently working on this one https://github.com/gbif/ipt/issues/1564
