### ISSUE TITLE
Update maps in geographic coverage and IPT settings sections

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/ipt#1801]
Update outdated leaflet and related libraries. It is also necessary for actualising geographic names

**Comment by mike-podolskiy90** [comment]
Currently we use [stamen](http://maps.stamen.com/terrain/?request=GetCapabilities&service=WMTS&version=1.0.0#4/48.95/39.20) as a tile layer.

**Comment by EstebanMH-SiB** [comment]
Thanks for updating this. I would like to know if it is possible to update this in an old IPT installation (2.5.4) or we need to install a new version when 2.7.7 is ready

@RicardoOrtizG

**Comment by mike-podolskiy90** [comment]
I'm afraid IPT update to the 2.7.7 would be required

**Comment by mike-podolskiy90** [comment]
I'm going to look into migrating to tile.gbif.org.
