### ISSUE TITLE
Geocoverage metadata has only one coordinate box, but EML allows multiple

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/ipt#1804]
Should we allow multiple coordinate boxes for geographic coverage metadata?

**Comment by peterdesmet** [comment]
My 2 cents: that would align it with the current possibility to add multiple taxonomic coverages (but I have never understood the need for that feature) and allow to indicate e.g. different non-neighbouring countries. On the other hand, bounding boxes are already a very rough estimate (vs e.g. a polygon) so I having the option to add more than one doesn't help much and would only complicate the UI.

**Comment by mike-podolskiy90** [comment]
Thank you very much for your feedback @peterdesmet 
It's a rough estimate indeed. I think that we really don't need it, but I decided I should ask anyway.
