### ISSUE TITLE
Cancel does not work on mapping

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#1806]
1. Upload a source file
2. In Darwin Core Mappings, select any schema from dropdown
3. Select source data from dropdown
4. Click cancel, rather than save

A mapping is created for that source data (same behaviour as clicking save).

Expected behaviour: go back to resource overview page

**Comment by mike-podolskiy90** [comment]
Thanks @peterdesmet for spotting this
Is it something new or it was like that before?

**Comment by peterdesmet** [comment]
I don't know when this error was introduced. 😄

**Comment by mike-podolskiy90** [comment]
Seems like it was always like that. Anyway, I'll fix
