### ISSUE TITLE
Cannot edit mapping on a resource

### ISSUE THREAD

**Issue by ManonGros** [gbif/ipt#1812]
This is an issue reported to on Helpdesk:
> I just modified the Darwin Core Mapping of one of our resources which worked as expected.
Unfortunately, I cannot reopen the mapping now. As soon as I click the EDIT Button, I am redirected to the resource.do page instead of the mapping.do page.

They have two resources on their IPT (https://www.herbarien.uzh.ch/ipt/manage/), the problem concerns only one of them.

**Comment by mike-podolskiy90** [comment]
Thanks Marie for reporting this. We need their IPT logs to figure out what happened and fix it

**Comment by mike-podolskiy90** [comment]
It happens when the database source changes (add new columns/remove columns). IPT (probably) silently swallows error somewhere and just redirects back to the resource page.
