### ISSUE TITLE
Extension mapping interface confusing

### ISSUE THREAD

**Issue by ManonGros** [gbif/ipt#1813]
When testing mapping his identification extension, one our publishers was surprised that most extension fields didn't show in the mapping interface. Like this:
<img width="1365" alt="Screenshot 2022-08-17 at 10 50 04" src="https://user-images.githubusercontent.com/7677271/185076963-7cdf85bf-72c2-4bda-b94b-e4b1f858441a.png">
The fields would show after clicking "Show all classes".
<img width="1345" alt="Screenshot 2022-08-17 at 10 50 12" src="https://user-images.githubusercontent.com/7677271/185077145-0af51704-b596-4849-97cc-755066713942.png">

This is a bit confusing. I assume that the fields were hidden because they were "redundant". What does it mean?
Also, it wasn't clear that the fix was to click "Show all classes".
What is the difference between fields and classes?

**Comment by mike-podolskiy90** [comment]
Thank you Marie for your questions. It is confusing indeed, and I already made some changes in [this one](https://github.com/gbif/ipt/issues/1579).
The IPT suspects a class (group) redundant if it's already mapped for the core extension (Record-level group is an exception).  As you can see [here](https://ipt.gbif-uat.org/admin/extension.do?id=http%3A%2F%2Frs.tdwg.org%2Fdwc%2Fterms%2FOccurrence) - fields usually grouped by groups (classes) - they are on the left.

**Comment by mike-podolskiy90** [comment]
@ManonGros Do we need something else here please?

**Comment by ManonGros** [comment]
Thanks @mike-podolskiy90! I am surprised as most fields from the identification extension aren't in the core. How can it be redundant? Maybe I am missing something.

**Comment by mike-podolskiy90** [comment]
It's not about fields, it's about group names. If names match the IPT considers them as "probably redundant", as I said.
