### ISSUE TITLE
Lost Access to Mappings for Occurrence in Manage Dataset - Version 2.5.5-ra872e56

### ISSUE THREAD

**Issue by gamblebnmnh** [gbif/ipt#1815]
I am attempting to manage one of my datasets and need to make changes to the Darwin Core Mappings.  However, when I click edit I am not sent to the mappings page but the current Manage page is displayed again.  No error message at top.  I've tried this in Edge and Chrome browser.  Thanks!

**Comment by mike-podolskiy90** [comment]
Thank you for contacting us @gamblebnmnh 
We had a similar issue recently. Please make sure all your sources are accessible and readable. You can do that by clicking Analyze button. Let me know if that helps

**Comment by gamblebnmnh** [comment]
Yeah the Analyze doesn't work.  I get the following: The requested URL was rejected. Please consult with your administrator.  Your support ID is: 13569493719438818032.  I'll check with my dbadmin to see if anything has changed on the db server or in the database.  Thanks!

**Comment by gamblebnmnh** [comment]
This resolved itself.  Was some issue with our connection to the database.  Thanks Mike for the lead.
