### ISSUE TITLE
Datasets listed in /dcat are not always described

### ISSUE THREAD

**Issue by frafra** [gbif/ipt#1816]
I tested https://ipt.nina.no/dcat against http://www.dcat.be:8080/validator/index.html by copy-and-pasting the content under the tab "By direct input" (Turtle syntax selected), 6 datasets (out of many) have this error:

`Resource: Dataset class needs to be initialized`

It looks like these datasets have not been described, even if they are listed at the beginning of the file.

I also see that https://ipt.gbif.org/dcat fails (invalid Turtle syntax), but I am uncertain whether that is an error with the tool or not.

**Comment by peterdesmet** [comment]
I notice that for our datasets at https://ipt.inbo.be/dcat, I'm only getting warnings (not errors) with the tool. Might that can help you pinpoint what is different?
