### ISSUE TITLE
`&nbsp;` in taxonomic coverage

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#1818]
I notice that taxa are prepended with `&nbsp;` in [taxonomic coverage](https://ipt.inbo.be/resource?r=mica-agouti-occurrences#anchor-taxanomic):

```html
<tr>
  <th class="col-4">Species</th>
  <td>
    &nbsp;Ondatra zibethicus (muskrat),
    &nbsp;Myocastor coypus (coypu)
  </td>
</tr>
```

Is this necessary? It can lead to odd spacing like this (see alignment on left):

<img width="616" alt="Screenshot 2022-08-30 at 15 09 05" src="https://user-images.githubusercontent.com/600993/187445588-d7b34f3a-c15d-4158-a9cc-87846cf50cbb.png">

**Comment by mike-podolskiy90** [comment]
Thanks Peter. I don't think it's necessary. I'll remove
