### ISSUE TITLE
Use `https://` not `http://` for ORCIDs

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#1819]
See https://support.orcid.org/hc/en-us/articles/360006897674-Structure-of-the-ORCID-Identifier:

> When stored, the ORCID iD should be expressed as a full https URI: https://orcid.org/xxxx-xxxx-xxxx-xxxx, complete with the protocol (https://), and with hyphens in the identifier (xxxx-xxxx-xxxx-xxxx).
> 
> ORCID's current recommended display is a full https URI preceded by the iD icon, both hyperlinked to the https URI

In the IPT however, the `directory` for DOIs is set to `http`:

```xml
<creator>
  <individualName>
    <givenName>Peter</givenName>
    <surName>Desmet</surName>
  </individualName>
  <organizationName>Research Institute for Nature and Forest (INBO)</organizationName>
  <address>
    <country>BE</country>
  </address>
  <electronicMailAddress>peter.desmet@inbo.be</electronicMailAddress>
  <userId directory="http://orcid.org/">0000-0002-8442-8025</userId>
</creator>
```

And they are displayed as http links, both on the IPT (above) and GBIF.org (below)

<img width="279" alt="Screenshot 2022-08-30 at 15 15 21" src="https://user-images.githubusercontent.com/600993/187446397-44413ec7-1ef1-48ba-895d-3ad586908984.png">
<img width="312" alt="Screenshot 2022-08-30 at 15 16 09" src="https://user-images.githubusercontent.com/600993/187446526-b8dc82a9-2b3e-4a52-89d4-f8a76257e4d4.png">

Other than a display recommendation, the http format currently implemented in the IPT is somewhat annoying in providing EML to the IPT, as the IPT does not recognize the (better formatted) `https://orcid.org` directory.

**Comment by mike-podolskiy90** [comment]
Thanks Peter
It is easy to change that, but I'm not sure about the consequences and how it'll affect current orcids

**Comment by peterdesmet** [comment]
Changing from http to https:

- It won't affect currently stored ORCIDs, since the `0000-0002-8442-8025` part is stored separately, so it would just be combined into a https link
- Will change how ORCIDs are displayed (at least on the IPT) but they would link to the same endpoint
- Will change how people (like me) should provide EML to the IPT (e.g. [here](https://github.com/inbo/movepub/blob/acf709b02d80fc5dccd794b43650998653bcf59a/R/write_dwc.R#L125))

So, it's a change that should at least be documented.

@dshorthouse will a change from http to https for ORCIDs in the IPT **metadata** affect your work?

**Comment by dshorthouse** [comment]
> @dshorthouse will a change from http to https for ORCIDs in the IPT **metadata** affect your work?

Not at my end; have not tinkered in the EML. But, thanks for the ping...and +1 for the suggested fix.

**Comment by peterdesmet** [comment]
Excellent, I've made 2 issues for myself once the change is included (and deployed) in the next version of the IPT.
