### ISSUE TITLE
Inconsistency in the field hostedBy in the IPT

### ISSUE THREAD

**Issue by EstebanMH-SiB** [gbif/ipt#1820]
There is a problem with the metadata field HostedBy, it is showing the information of the publisher institution, but it should show SiB Colombia as we are the host of this datasets. 

![image](https://user-images.githubusercontent.com/63795703/189198354-02dba47e-a041-4fe9-99f2-85cec0fd12a1.png)

In the GBIF portal it is show in a correct way, HostedBy: SiB Colombia and PublishedBy:Geopark

![image](https://user-images.githubusercontent.com/63795703/189198491-5d03e92e-118f-4958-9ce4-5591d39d0e94.png)

**Comment by mike-podolskiy90** [comment]
Thank you for reporting this issue @EstebanMH-SiB 
I'll chekc
