### ISSUE TITLE
Enum values not listed on mapping page

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#1824]
_This issue relates to using IPT for publishing [Camtrap DP](https://tdwg.github.io/camtrap-dp/) and is not applicable to production IPTs._

The mapping (`schemaMapping.do`) seems to be aware a term has a controlled vocabulary/enum (e.g. `baitUse`), but doesn't list controlled values (empty dropdown):

<img width="857" alt="Screenshot 2022-09-12 at 15 51 33" src="https://user-images.githubusercontent.com/600993/189671898-ce1e24e7-d06e-4d0e-8d36-815ef89d828d.png">

Those values are present in `constraints$enum`.

**Comment by mike-podolskiy90** [comment]
Just checked, all dropdowns are populated
