### ISSUE TITLE
Problem finding the reason of our IPT going down

### ISSUE THREAD

**Issue by EstebanMH-SiB** [gbif/ipt#1830]
Last week we had some problems with our [IPT](https://ipt.biodiversidad.co/sib/) going down, we try to find the reason but the only think we found was this message of insufficient memory, unfortunately it does not tell the specific resource with the problem:
![image](https://user-images.githubusercontent.com/63795703/189695266-59c6ff4f-cf39-43c7-8136-a609b7182bfc.png)

The only related thing that we found in the log archive, was a problem with this [dataset](https://ipt.biodiversidad.co/sib/resource?r=acz_fototrampeo-mamiferos), but this should not be the issue because this dataset was published last year and have not had any modification since that.
![image](https://user-images.githubusercontent.com/63795703/189695391-e2228ebe-6a1a-4124-81df-b4ee1e65ba52.png)

We do not have the complete log file, just this screenshots of our findings.

We should like to know if you have any suggestion to deal with this problem or to find the reason.

**Comment by mike-podolskiy90** [comment]
Thank you for contacting us @EstebanMH-SiB 
Unfortunately, not much we can do here. Having that `/tmp/hs_err_pid1.log` file would be useful.
It doesn't look like the IPT require too much memory space there (~600MB). Make sure java have enough memory on your server.
