### ISSUE TITLE
Future of requiring basisOfRecord and controlled vocabulary

### ISSUE THREAD

**Issue by albenson-usgs** [gbif/ipt#1831]
[A new recommendation](https://github.com/tdwg/dwc/issues/416) has been put forward to modify `basisOfRecord` which (I believe) would result in changes to the controlled vocabulary currently in place for `basisOfRecord` in the IPT. In order to publish data via the IPT you are required to include `basisOfRecord` and the values in that field must be one of these exactly: PreservedSpecimen, FossilSpecimen, LivingSpecimen, MaterialSample, Event, HumanObservation, MachineObservation, Taxon, Occurrence, MaterialCitation (e.g. "Human Observation" will cause a dataset to be rejected).

Will the IPT continue to require `basisOfRecord`? Will the controlled vocabulary be updated to follow the suggested changes?
@timrobertson100

**Comment by timrobertson100** [comment]
Assuming that recommendation does go through in the next edition of DwC:

> Will the IPT continue to require basisOfRecord? 

Yes, I would expect as the reason it was first made a required field remain valid (i.e. the need to have a basic understanding of what the record actually represents)

> Will the controlled vocabulary be updated to follow the suggested changes?

Yes, although I don't imagine that this would impact things as much as one might think. I'd anticipate that:

- On data publishing, the IPT would handle a spreadsheet containing `preserved_specimen`, `PRESERVED_SPECIMEN`, 'preservedSpecimen' etc and map that onto the correct term.

- When the IPT produces the output archive, the value it puts out for that field might change the format slightly. I doubt many consumers would notice, as it's fairly common to consume this stuff in a case insensitive manner ignoring whitespace and `_` characters.

**Comment by albenson-usgs** [comment]
Thanks Tim!

> On data publishing, the IPT would handle a spreadsheet containing preserved_specimen, PRESERVED_SPECIMEN, preservedSpecimen etc and map that onto the correct term.

The problem is that this is not currently how the IPT works. If you have anything but "PreservedSpecimen" it will be rejected. Meaning you either have to update the file so the data in it matches that exactly or create a translation. 
![basisOfRecordMapped](https://user-images.githubusercontent.com/7586150/191516006-bcfaa71a-0060-4895-86d8-0534e2bafc06.PNG)

![IPTDatasetPublishingFails](https://user-images.githubusercontent.com/7586150/191516028-42fc8275-488f-48f7-a946-2bfd2b2f7c67.PNG)

So will the IPT be updated to handle any of a number of input values?

**Comment by albenson-usgs** [comment]
For thoroughness's sake I also tried "human_observation" with the same result:
![IPTDatasetPublishingFails2](https://user-images.githubusercontent.com/7586150/191517639-18978fce-914d-4b22-b8b3-86a8e3357f35.PNG)

**Comment by timrobertson100** [comment]
Thanks for confirming that Abby. That seems like a nuisance, and something perhaps we should just fix for any vocabulary field on import (ignore whitespace, casing and `_`). Agree?

**Comment by peterdesmet** [comment]
> just fix for any vocabulary field on import

I assume this conversion in the IPT would only be done for those fields that **require** a vocabulary? Or would this also be done for fields where a vocabulary is _recommended_?

**Comment by timrobertson100** [comment]
Thanks @peterdesmet - yes, I think applying only to those fields the IPT requires makes sense.

Basically, it's to stop the IPT failing the publication just because you wrote `presErved_SpeciMen ` instead of `preservedSpecimen` (or whatever format is needed). That is just a nuisance that can be easily handled.
