### ISSUE TITLE
Issue importing from an exported DwC-A

### ISSUE THREAD

**Issue by leo-buitrago** [gbif/ipt#1837]
Hi,

I have problems importing a DwC-A from one IPT to another. This is happening to me in the [LAC IPT](https://cloud.gbif.org/lac), but I detected the same behaviour in other IPTs. See the video https://screen-recorder-bucket.s3.ap-south-1.amazonaws.com/ScreenRecorder_2022-09-29_20e6dfec-5631-47c2-a2bd-3b0456a1c860.mp4

* In case you want to replicate it, I am importing this DwC-A from one of the training IPTs https://training-ipt-c.gbif.org/archive.do?r=pruebaocurrencias&v=1.8

**Comment by mike-podolskiy90** [comment]
@leo-buitrago Thank you for reporting this Leo, I'll check

**Comment by mike-podolskiy90** [comment]
@leo-buitrago [Darwin Core Measurement or Facts](https://cloud.gbif.org/lac/admin/extension.do?id=http%3A%2F%2Frs.tdwg.org%2Fdwc%2Fterms%2FMeasurementOrFact) extension is missing in that IPT. I installed it and upload went successfully.
The 2.5.8 swallows errors there, new 2.6 or higher shouldn't do that anymore:
![Screenshot 2022-09-30 at 10 16 13](https://user-images.githubusercontent.com/24795387/193226660-70d72949-3de6-48ae-9b73-a0643d81bfdf.png)

I removed the resource, so you can re-create it by yourself.
