### ISSUE TITLE
Public dataset not visible from the home page

### ISSUE THREAD

**Issue by ckotwn** [gbif/ipt#1840]
The dataset of concern is https://cloud.gbif.org/asia/manage/resource?r=pfzrc-southluzon.
While the status is public, it's not visible from the home page. Although, the previous published version is accessible with URL param: https://cloud.gbif.org/asia/resource?r=pfzrc-southluzon&v=1.0

I may be wrong, but I suspect the user was working on the dataset when the Asia IPT got upgraded to 2.6.1.

**Comment by mike-podolskiy90** [comment]
@ckotwn Thank you for reporting the issue, I'm checking

**Comment by mike-podolskiy90** [comment]
Only the version 1.0 is present for this resource. I'm not sure what happened there

**Comment by ckotwn** [comment]
It seems like after further updates and publishing, the resource is now visible https://cloud.gbif.org/asia/resource?r=fwcalanoidsslphilippines

**Comment by mike-podolskiy90** [comment]
@ckotwn it's another resource, isn't it?

**Comment by ckotwn** [comment]
Sigh - the publisher deleted the resource. Guess this won't be resolved. :(
