### ISSUE TITLE
request: allow compressed delimited text files as remote URL data sources

### ISSUE THREAD

**Issue by abubelinha** [gbif/ipt#1846]
As I posted in #1673, "The IPT can import **uncompressed** delimited text files directly from a URL" 

But the info icon next to **Source data** header says "You can upload delimited text files either **directly or compressed** (zip or gzip)" ... (with [some issues](https://github.com/gbif/ipt/issues/1294)). 

- So, if compressed files are submitted using the upload button, the IPT can uncompress them.
- But if a file is served from a remote URL, it must be uncompressed.

Why that difference?  
If the IPT is able to uncompress uploaded files, why not allowing it to do the same for those files served from remote URLs?
That would save a lot of space in servers.

Thanks
@abubelinha

**Comment by mike-podolskiy90** [comment]
@abubelinha Thank you for contacting us. We're already planning to do that, see #1632 . Closing this
