### ISSUE TITLE
Do not repeat contacts on the resource page

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/ipt#1850]
There might be many repetitions in the following contact sections:

- Who created the resource
- Who can answer questions about the resource
- Who filled in the metadata

including some cases when there are the only one same contact in all three.

**Comment by abubelinha** [comment]
I'd like to understand the issue you are meaning here:
1. Are you looking for a way to avoid these many repetitions to be visible for users of IPT? (i.e. just changes in the final look of the web page)
2. Or are you meaning to make changes into metadata introduction forms, to avoid having to repeat the stuff there?  

Thanks

**Comment by mike-podolskiy90** [comment]
This is about the first one

**Comment by mike-podolskiy90** [comment]
There is the issue for the second one #1166
