### ISSUE TITLE
Test IPT: user account creation fails at initiation with Freemarker template error

### ISSUE THREAD

**Issue by ahahn-gbif** [gbif/ipt#1852]
Trying to create a user account in the Test IPT (https://ipt.gbif.org/admin/users.do) throws an error, following button click of "Create". The dialogue to enter new user information is not reached.

![image](https://user-images.githubusercontent.com/13435656/195540969-fac88746-562c-4ed9-b3da-7b5073d947b0.png)

**Comment by mike-podolskiy90** [comment]
@ahahn-gbif Thank you Andrea for reporting this issue.
This was fixed here https://github.com/gbif/ipt/issues/1845 (version 2.6.2), ipt.gbif.org needs to be updated to that version.
I'll let you know when it's ready

**Comment by ahahn-gbif** [comment]
Thanks, @mike-podolskiy90! We have a user at helpdesk requesting account creation, so being able to do so sometime before the weekend would be helpful.

**Comment by mike-podolskiy90** [comment]
@ahahn-gbif Yes, of course. Unfortunately, we can't update that right away, since it uses specific RPM package build.
Matt is working on that
