### ISSUE TITLE
Newly installed IPT does not create a new resources directory

### ISSUE THREAD

**Issue by MattBlissett** [gbif/ipt#1853]
At least when installed from the el8 RPM, the IPT does not create a new data directory. It does create config, logs and tmp.

After completing setup2.do, setup3.do reports "Resources directory does not exist: /var/lib/ipt/resources"

(Version 2.6.2, el8 RPM.)

**Comment by mike-podolskiy90** [comment]
Thanks Matt. Have you tried a regular installation?

**Comment by mike-podolskiy90** [comment]
This might be related 37b528fe6782ea998c17df7adb5ed967ed790270

**Comment by mike-podolskiy90** [comment]
This happens indeed when directory path is provided in the datadir.location, but doesn't actually exist.

**Comment by mike-podolskiy90** [comment]
I found what was the issue here. It's UI settings in the wrong place

**Comment by mike-podolskiy90** [comment]
@MattBlissett please check it works when you can
