### ISSUE TITLE
Remove build number from the footer for prod running IPTs

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/ipt#1857]

**Comment by MattBlissett** [comment]
Why? I think it's useful to see if it's our build or something else.

**Comment by mike-podolskiy90** [comment]
@MattBlissett Is it the only purpose for that? I think it's too technical information, we can keep as hidden information or something

**Comment by peterdesmet** [comment]
I don't mind it in the footer, but I guess the version number is sufficient. The hash inspired us for a number of apps we developed 😄 where we link to that commit in the repository: https://alert.riparias.be/

**Comment by mike-podolskiy90** [comment]
Full version can still be viewed on the image in the footer hover

![Screenshot 2022-10-20 at 09 52 53](https://user-images.githubusercontent.com/24795387/196889858-9f85174d-e408-4a86-aeca-1541a9c48682.png)
