### ISSUE TITLE
dataset publication log missing (metadata-only vs DwC-mapped?)

### ISSUE THREAD

**Issue by abubelinha** [gbif/ipt#1858]
I am playing with https://ipt.gbif-uat.org for testing how some datasets will look like once published.
In production IPT we only publish DwC-mapped datasets, but these tests concern only their metadata part (we want to let authors see how these paragraphs will look like before going live). 

So I am mostly testing metadata-only datasets, hoping this will reduce gbif-uat.org server load (and speed up dataset visibility in test portal).
__________
My question is about **_log differences_** in the "_Manage resources - Published versions_" IPT section (manage/resource.do?r=resource-name#anchor-publish). For some resources, it looks like this:

> #### Published versions:
> **Version:**
> **DOI:**
> **Published on:** &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  19 October 2022 19:22
> **Publication log:** &nbsp; &nbsp; &nbsp; [Download](https://ipt.gbif-uat.org/publicationlog.do?r=fake-test)
> **Publication report:** &nbsp;[Show](http://fake-link.because/in.this.dataset.this.line.did.not.exist)

- However, sometimes the last line (Publication report) is missing, and sometimes not. 
- Also sometimes, the penultimate line (Publication log) links to a non-existing log (see above link), and sometimes to a normal log.

When pressing the "Publish" button, and after an apparently successful attempt:
- Sometimes, no detailed log is shown (just the usual top banners telling everything was OK). 
- Whereas some other times, those banners are followed by a "_Continue to [resource overview]()_", plus "_Download the complete [Publication log]()_", and a long list of "_Log Messages_" 

I am guessing those differences are due to something predictable (i.e., no logs for metadata-only resources?).
But in that case, what's the point of linking to a non-existing publication log?

Or might this be instead a symptom of some kind of failure in the last publication attempt? (although the version number increases and the success banners appear).

Thanks
@abubelinha

**Comment by mike-podolskiy90** [comment]
Thank you for reporting this, I'll check
