### ISSUE TITLE
how to know whether dataset portal already matches the last IPT published version

### ISSUE THREAD

**Issue by abubelinha** [gbif/ipt#1859]
Sometimes I feel I wait a lot for republished datasets to show up in the test portal page.
But I never know when to decide "this is taking too long: ask helpdesk". 

I may be testing very subtle metadata changes each time. So I can't tell for sure whether there's a delay in gbif-uat test portal and registry ... or maybe I just don't see any changes reflected because of my misunderstanding of the way portal should have processed them: 
- i.e. an html tag, a `<pre>` section with tabbed strings, could have not been admitted ... so it might have been dropped and I can't see any changes (but the page is already in the portal)
- Or I might be expecting some authors to appear in the automatic citation ... but they won't if portal is doing something different to what I expect
- etc (any aspects or changes in portal design we might not be aware of)

So I prefer to use a more objective way of detecting when my last published version is already live in portal.

If my IPT dataset version number increases, I assume changes passed validation and I would expect it to be published right away in portal (or I think that should be the case for small metadata-only dataset).
But as I keep seeing items in the ingestion queue of the system-health page, it's hard to tell if mine is one of those. 
So **how can I programatically check if a given IPT dataset publication attempt is still queued or has already gone live?**
  
**Is there any infalible way to tell if the current IPT published version matches with the current portal version of a given dataset?**
I'm afraid the IPT dataset version is not being propagated to the API (I couldn't find it)
I hope there is something else in the api.gbif-uat.org/v1/dataset/mydatasetuuid which we can compare against something in ipt.gbif-uat.org/resource?r=mydatasetname 
If not ... would it be possible to implement such a feature?

Thanks in advance
@abubelinha

**Comment by mike-podolskiy90** [comment]
@abubelinha Thank you for your questions.
Unfortunately I can't say for sure about the portal, but you can check that the data/metadata was picked up by GBIF in the registry and in the API.
API:
https://api.gbif-uat.org/v1/dataset/<dataset_UUID>
https://api.gbif-uat.org/v1/dataset/<dataset_UUID>/document
https://api.gbif-uat.org/v1/ingestion/history/<dataset_UUID>

Registry:
https://registry.gbif-uat.org/dataset/<dataset_UUID>/ingestion-history

**Comment by abubelinha** [comment]
Thanks @mike-podolskiy90 for those links.

I understand that registry dataset ingestion-history should show a list of results ... each one corresponding to one publication attempt from the IPT dataset.

So if my test IPT dataset shows 46+5=51 versions (1.0 to 1.45, and 2.0 to 2.4)
... then the ingestion-history should NOT show only one result, like this?:

```lg-json
// https://api.gbif-uat.org/v1/ingestion/history/2adad0d3-6150-4eb7-ac89-b59b71833045/

{
  "offset": 0,
  "limit": 20,
  "endOfRecords": true,
  "count": 1,
  "results": [
    {
      "datasetKey": "2adad0d3-6150-4eb7-ac89-b59b71833045",
      "datasetTitle": "A fake metadata test project",
      "attempt": 1,
      "crawlInfo": {
        "datasetKey": "2adad0d3-6150-4eb7-ac89-b59b71833045",
        "crawlJob": {
          "datasetKey": "2adad0d3-6150-4eb7-ac89-b59b71833045",
          "endpointType": "EML",
          "targetUrl": "https://ipt.gbif-uat.org/eml.do?r=fake-test",
          "attempt": 1,
          "properties": {
            
          }
        },
        "startedCrawling": "2022-10-18T18:39:23.139+00:00",
        "finishedCrawling": "2022-10-18T18:39:23.361+00:00",
        "finishReason": "NORMAL",
        "processStateOccurrence": "EMPTY",
        "processStateChecklist": "EMPTY",
        "pagesCrawled": 1,
        "pagesFragmentedSuccessful": 0,
        "pagesFragmentedError": 0,
        "fragmentsEmitted": 0,
        "fragmentsReceived": 0,
        "rawOccurrencesPersistedNew": 0,
        "rawOccurrencesPersistedUpdated": 0,
        "rawOccurrencesPersistedUnchanged": 0,
        "rawOccurrencesPersistedError": 0,
        "fragmentsProcessed": 0,
        "verbatimOccurrencesPersistedSuccessful": 0,
        "verbatimOccurrencesPersistedError": 0,
        "interpretedOccurrencesPersistedSuccessful": 0,
        "interpretedOccurrencesPersistedError": 0
      }
    }
  ]
}
```
Shouldn't "count" be 51 and shouldn't "results" contain 51 items?

Sorry if I am misunderstanding it

**Comment by mike-podolskiy90** [comment]
@abubelinha They don't necessarily match. There you can just see that your dataset (resource) were processed by GBIF, and by calling API you can confirm that changes are there.

**Comment by abubelinha** [comment]
So what exactly means "count" and "results" ?
I am trying to figure out why that particular metadata-only dataset which I am trying to republish again and again ... keeps on showing the same info in both portal and registry (it does not match IPT since many days ago now)

I am not getting any errors in IPT. Version increases, everything looks normal ... but portal does not change.

**Comment by mike-podolskiy90** [comment]
That's a regular pageable response wrapper. `count` - total amount of available items (objects), `result` - items themselves.
The information you need there is whether it completed successfully and when it completed.
You can start ingestion manually (if it was not fired automatically) in the registry if you are a logged in user and have proper rights. I started it for your resource and it seems updated the metadata in GBIF and the portal picked up the updates in about 5 minutes.

You are also welcome to contact the [GBIF helpdesk](mailto:helpdesk@gbif.org) about that, so they may advise you better than me

**Comment by abubelinha** [comment]
Thanks @mike-podolskiy90  
I knew what are `counts` and `results` mean in gbif api.
What I meant was "what is exactly being counted here?".

I'd like to understand why in this particular dataset IPT publish button did not work. 
Isn't this an IPT issue?

**Comment by mike-podolskiy90** [comment]
You publish your resource in the IPT - it means it was published in the IPT **internally**, and now available for processing at https://ipt.gbif-uat.org/eml.do?r=fake-test . If you check that URL and see metadata is up-to-date - then you published your resource successfully. Rest is out of IPT scope.

Then the publicly available metadata is ready to be processed in order to be available at the GBIF portal. And here you need to make sure your dataset was ingested correctly after publication in the IPT. It may or may not be processed automatically. If not - you start it manually. So `count` here - Ingestion attemps.

After ingestion data is available at the gbif-api and the portal pick it up shortly.

**Comment by abubelinha** [comment]
Thanks.
So if it is successfully published in IPT internally, I can be 100% sure there is nothing wrong with my dataset?

I would like to see other github issues related with having to "start ingestion manually".
For what you say, looks like it is not an uncommon issue?

**Comment by abubelinha** [comment]
Thanks a lot @mike-podolskiy90  
We contacted helpdesk and @ManonGros told us what to do (thanks to you too).

Regarding this issue, I have been checking info in the registry and IPT.
The most straightforward way I could figure out to check the last IPT version is already visible in portal is to somehow compare portal timestamp is later than IPT timestamp.

I do not want to compare metadata between them because that is a more complicated way: the script would need to know which part of the metadata to compare, and this may change from one dataset to another.  Also, what if I don't change metadata but data? I'd prefer a solution valid for any dataset.

I'd rather check the IPT table in /resource?r=my-resource-name#anchor-versions
Then I'd take the first row (latest version) and get the "Published on" column value.
And I would compare that against https://api.gbif-uat.org/v1/dataset/<dataset_UUID> "modified" value (which is a timestamp like "2022-09-26T11:50:01.341+00:00")

The problem is that IPT is not showing a timestamp, but a simple date: "2022-09-26" (and same happens in top header "Publication date: 26 September 2022").
In my scenario, I will do several metadata change tests a day, so it would be great to have the timestamp of the current IPT dataset version.
Is there any other place where I can look, other than that table or the top IPT banner?
If not, **would it be possible to include a timestamp** in each row of the table in #anchor-versions section?
(it's OK if it is a hidden span tag, or any other easy to scrap solution)  
BTW I think it wouldn't hurt the top banner shows also a timestamp in "Publication date".

What do you think?

Thanks a lot for all your help

**Comment by abubelinha** [comment]
> Would it be enough for you?

I guess so. I would include seconds as well. 
(probably they will never matter, but just in case).

Thanks!

**Comment by mike-podolskiy90** [comment]
@abubelinha Deployed to [UAT](https://ipt.gbif-uat.org/resource?r=fake-test)

**Comment by abubelinha** [comment]
That's great.  Thanks a lot !!

BTW ... while reviewing some old scripts, I have just noticed a comment line pointing to this IPT page because it also contains timestamp info (for all resource items served by IPT), but I was not sure what it meant:

https://ipt.gbif-uat.org/rss.do
```lang-xml
<item>
...
<ipt:eml>https://ipt.gbif-uat.org/eml.do?r=fake-test</ipt:eml>
<pubDate>Wed, 19 Oct 2022 23:56:41 +0000</pubDate>
<guid isPermaLink="false">2adad0d3-6150-4eb7-ac89-b59b71833045/v2.4</guid>
</item>
```

Now I guess that `pubDate` is the same timestamp of the last published version (top of the table we were talking about).  Is it?
There is a one second difference between them (which I don't care, but it makes me doubt).

In case I can use that page as well ... is it possible to limit the xml output to a given resource?  (I tried passing `rss.do?r=fake-test` but that didn't work)

**Comment by abubelinha** [comment]
@mike-podolskiy90 I think this can be closed, but I leave that to you 
(you may want to keep it open until you release 2.6.3 version)

Thank you very much again for your great work and wonderful support !!

**Comment by mike-podolskiy90** [comment]
You're welcome. Thank you for your questions! Closing this

**Comment by abubelinha** [comment]
@mike-podolskiy90 
Sorry but I am having again problems to see a test dataset published in ipt.gbif-uat.org.
Could you check why [this one](https://www.gbif-uat.org/dataset/a5c64c25-d0e6-47de-8620-4059d47f3b31) keeps showing 0 records?
Thanks

**Comment by MattBlissett** [comment]
ipt.gbif-uat.org is being used for testing updates to EML, which are not yet supported by the rest of gbif-uat.org. This IPT is for testing the IPT itself, not so much for testing data publishing in general.

Please try ipt.gbif.org, which is the usual test IPT for testing data publishing.

**Comment by abubelinha** [comment]
Thanks @MattBlissett 

For some reason I don't recall we have an account at ipt.gbif-uat.org but not at ipt.gbif.org
Could you create us an account there and send us login credentials? (same user & email).

We are testing dwc csv data prior to real publication (so metadata has no importance here).
We want to check how gbif interprets our provided names in order to double check those which are flagged once published in portal.
