### ISSUE TITLE
Registration issue because of timeout during GBIF Registry call

### ISSUE THREAD

**Issue by sylmorin-gbif** [gbif/ipt#1860]
Hello,

We have reached 10k datasets...

IPT (2.5.8) has issue to register new datasets:
![image](https://user-images.githubusercontent.com/56630013/197420015-7dd4ba98-efa2-4d12-a53c-177abedf186b.png)

The fact is that calling https://gbrds.gbif.org/registry/resource.json?organisationKey=1928bdf0-f5d2-11dc-8c12-b8a03c50a862 took around 40 seconds.

When we had less datasets, it was already an issue since it makes registration really slow (20-25 seconds for each dataset can be long when registering 1K datasets...)

But now, since we are above 30s, we get a timeout, and the registration is failing.

We cannot change the timeout, it's hardcoded (https://github.com/gbif/ipt/blob/master/src/main/java/org/gbif/ipt/config/IPTModule.java#L63)

I compiled my own version with a 2 minutes timeout, and I can now register my datasets.
But maybe, it would be better if we could speed up the https://gbrds.gbif.org/registry/resource.json?organisationKey=1928bdf0-f5d2-11dc-8c12-b8a03c50a862 call...?

Thanks

**Comment by sylmorin-gbif** [comment]
![image](https://user-images.githubusercontent.com/56630013/197422256-3f5c3895-a1fe-4b27-9992-cfd0e6f48d74.png)

36 seconds

**Comment by mike-podolskiy90** [comment]
@sylmorin-gbif Thank you for reporting this.
10k datasets that's a lot! We need to find something there. I think we can do a temporary quick fix like you did, just prevent it from failing, and then find a performance solution

**Comment by mike-podolskiy90** [comment]
@sylmorin-gbif Now it will be much quicker. It doesn't retrieve all datasets anymore and just quickly checks if dataset belongs to the organization.
I'm also currently finalizing more performance improvements which you're probably interested in #1875

**Comment by mike-podolskiy90** [comment]
Registry release is required, but IPT part is done. Closing this
