### ISSUE TITLE
Keywords section of the metadata

### ISSUE THREAD

**Issue by SophiePamerlon** [gbif/ipt#1861]
Hello,
I've been wondering for a while where do the metadata keywords appear on a dataset's GBIF page after publishing? I can see the geographic description & taxonomical keywords (when available) but not the general keywords from the 'Keywords' metadata section.
Thanks for your help!

**Comment by mike-podolskiy90** [comment]
@SophiePamerlon Thank you for your question. I think they aren't displayed at the GBIF portal

**Comment by albenson-usgs** [comment]
Are they used in the [Schema.org representation](https://github.com/gbif/portal-feedback/issues/1669) of the dataset?

**Comment by mike-podolskiy90** [comment]
Unfortunately, I can't answer this, and it's not an IPT scope. Closing this
