### ISSUE TITLE
rss.do r parameter

### ISSUE THREAD

**Issue by abubelinha** [gbif/ipt#1862]
In #1859 I wondered how to limit xml output of `rss.do` page (so you only get the datasource item/s you are interested).  

Now I found something else:

Passing a query `r=resource-name` parameter in the url has no effect in limiting the output to only one item (same output as the page url without parameters):
https://ipt.gbif-uat.org/rss.do
https://ipt.gbif-uat.org/rss.do?r=fake-test

But if you pass it and the name does not match any of the IPT resources ... oddly the IPT returns an error page (404).
https://ipt.gbif-uat.org/rss.do?r=incorrect-fake-test-name

So it seems that `r` parameter is actually being taken into account for something.
 
Probably it was intended to limit the output ... but seems to be an unfinished work.
I don't know if that parameter is documented somewhere or not.
If it is not, then this is not a bug (just a future unfinished feature).

But I wanted to report it, just in case.

BTW ... if this feature is even released, it might be useful letting `r` be a list of resources with some separator string, so you can get them all in just one call.
https://ipt.gbif-uat.org/rss.do?r=resource-1|another-resource

**Comment by mike-podolskiy90** [comment]
@abubelinha Thank you for reporting this. I'll check it
