### ISSUE TITLE
IPT connecting with oracle xe problem

### ISSUE THREAD

**Issue by PMNH** [gbif/ipt#1868]
Hi,
me ubaid, i am facing in configuratuion of IPT of GBIF with oracle.
1.i creared  Source Data.
2.it shows reable (yes) with no of colum but record are displayed.
3.may be i created view for shairing data.
Regards.

**Comment by mike-podolskiy90** [comment]
@PMNH Thank you for contacting us.
I need some clarifications.
First of all, what IPT version do you use please?
As I understood, you created your source and it was successfully saved with readable status. Are you able to preview data at source page? If so, try clicking `Analyze` button it re-calculates number of columns.

**Comment by mike-podolskiy90** [comment]
I've just read your email to the GBIF helpdesk.
Looks like you haven't published your resources yet. Once you publish them, number of records will be displayed correctly.

**Comment by PMNH** [comment]
@mike-podolskiy90  thank you for quick response  
1. IT  Version 2.6.2. 
2. A i analyze it may time.in preview its shows some records but in main resource list it shows 0 record.
3.yes i have not published it yet because it is in test mode. First i will test it  and then finally i will published it.

**Comment by mike-podolskiy90** [comment]
@PMNH Your sources and mappings are fine.
As I said, 0 records at the table will be displayed until you publish the resource.

**Comment by ManonGros** [comment]
@PMNH Publishing doesn't mean that it is made public. If you click on the "publish" button, an archive will be generated. You can publish in test mode.

**Comment by abubelinha** [comment]
Yes, that's a bit confusing.   
Perhaps "compile new version" would be more appropriated? 
(whatever wording which does not look like "public")
