### ISSUE TITLE
wrong contacts order in public IPT web interface

### ISSUE THREAD

**Issue by abubelinha** [gbif/ipt#1874]
Currently, **the order in which you add contacts** (section `/manage/metadata-parties.do?r=resourceId`), does not match the **order in which they are later displayed** in IPT public web interface (`/resource.do?r=resourceId#anchor-contacts`). 

If I revisit and edit section `/manage/metadata-parties.do?r=resourceId`, the order is still correct.
And downloadable EML and RTF metadata files do also correctly follow the original contacts order.

It's only in public IPT web interface where contacts follow an unpredictable sorting pattern.

**EDIT:**
A test dataset where you can look at this:
https://ipt.gbif-uat.org/resource.do?r=fake-test#anchor-contacts

I named contacts fake.0, fake.1, fake.2, fake.3 ... and added them in the same order.

Also, the same issue happens in project section:
https://ipt.gbif-uat.org/resource.do?r=fake-test#anchor-project

**Comment by mike-podolskiy90** [comment]
@abubelinha Thank you for reporting this
I believe it's because of this one https://github.com/gbif/ipt/issues/1850
I'll see how can I fix that

**Comment by abubelinha** [comment]
Thanks @mike-podolskiy90  
I was editing my question above while you answered.
Just to show an example and to add the same issue is happening with "project" section contacts.
