### ISSUE TITLE
Move resource tables functionality to backend

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/ipt#1875]
This can help to dramatically increase performance for IPTs with lots of resources since IPT loads all the resources every time. It'd be better to load only requested number of resources (10, 20 etc.) instead.

For example it takes ~13 seconds to display home page for https://ipt-inpn.gbif.fr/ which has 11K+ resources

**Comment by MattBlissett** [comment]
That would mean the search and sort functions would also need to be moved to the backend.
