### ISSUE TITLE
wrong top "MANAGE" and "ADMINISTRATION" links in IPT installed behind Apache proxy

### ISSUE THREAD

**Issue by abubelinha** [gbif/ipt#1878]
I have just realized there is a wrong link to IPT management in my two IPT installations.

When I look at this url: http://my.server.address/ipt/manage/resource?r=my-dataset I see something like this

> Home - Manage Resources - Administration - About                          `<---(TOP GREEN BAR MENU)`
>
> **_MANAGE_** - OVERVIEW - METADATA
> ## Basic Metadata
> My dataset title

Every link works fine but the "**_MANAGE_**" word in 2nd line links to this wrong URL (notice "/ipt" path missing):
http://my.server.address/manage/

IPT runs Tomcat 9 on port 8080 of a private VM which is behind the public Apache server (both share same LAN), as detailed here:
https://github.com/gbif/ipt/issues/1674#issuecomment-981601022

I run two almost identical installations, both showing the wrong "MANAGE" link: 
- v.2.6.3 in TEST MODE (I am being able to publish datasets, no problem at all) 
- v.2.6.1 intended for production but not yet serving (I only imported data directory from my old IPT 2.3.2 installation ... but [l still didn't click the "update registration" button](https://github.com/gbif/ipt/issues/1674#issuecomment-982593929))

This issue doesn't bother me too much because I still can use top green bar menu (where "Manage resources" links to the correct place).
But I wonder if it can be symptom of other problems.

Thanks in advance
@abubelinha

**Comment by mike-podolskiy90** [comment]
@abubelinha Thank you for spotting this issue.
This is just a small thing. Could you please also check the same thing happens for metadata pages `OVERVIEW` link?

**Comment by abubelinha** [comment]
@mike-podolskiy90  I think I had not answered your previous question about the "OVERVIEW" link.
No, I think that one is correct, if you mean this one:

http://my.server.address/ipt/manage/metadata-additional.do?r=my-dataset

> [MANAGE](http://my.server.address/manage/) - [OVERVIEW](http://my.server.address/ipt/manage/resource?r=my-dataset) - METADATA
> ### Additional Metadata
> [My dataset title](http://my.server.address/ipt/manage/resource.do?r=my-dataset)
 
There I reproduced the MANAGE and OVERVIEW links (in that line, METADATA has no link).

**Comment by mike-podolskiy90** [comment]
Thank you for quick response. I'll fix those links
