### ISSUE TITLE
Autopublished version should have empty "Change summary"

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#1879]
I recently switched to auto-publishing for a resource that was published manually before: https://ipt.inbo.be/resource?r=planten-exoten-natuurpunt-occurrences#anchor-versions

1. For each manual publication, I added a _change summary_, e.g. "Add July 2022 data."
2. For the last manual publication, I updated some metadata and wrote "Enable auto-publishing" as _change summary_
3. It looks like the auto-published versions are using that _change summary_, rather than leaving it empty (`None provided` in the table).

<img width="913" alt="Screenshot 2022-11-16 at 10 16 24" src="https://user-images.githubusercontent.com/600993/202139492-192b7c90-2e9f-4869-84f0-2a4f83a7dc25.png">

**Comment by mike-podolskiy90** [comment]
@peterdesmet Thanks for reporting this issue
