### ISSUE TITLE
Why is basisOfRecord red in the IPT?

### ISSUE THREAD

**Issue by albenson-usgs** [gbif/ipt#1880]
Apologies for putting a question here- I can't find the mailing list address. I never really noticed this before but I'm curious why `basisOfRecord` is red when all the other fields are not? Is there a reason for this? Is it because it's the only required term that also has a required controlled vocabulary?
![thumbnail_image004](https://user-images.githubusercontent.com/7586150/202317947-76f2921a-5f27-4fc5-8b20-862c41bcc569.png)

I tried searching the IPT Manual and didn't find an answer there.

**Comment by mike-podolskiy90** [comment]
@albenson-usgs Thank you for your question. No worries!
That is correct, it meant that basisOfRecord is a required term. I changed it recently and currently it looks like this:
![ipt gbif-uat org_manage_mapping do_r=aves_tanzanian id=http%3A%2F%2Frs tdwg org%2Fdwc%2Fterms%2FOccurrence mid=0](https://user-images.githubusercontent.com/24795387/202384081-4f235da2-e818-40d5-b061-8ae308296871.png)
