### ISSUE TITLE
No tooltip on some User accounts buttons

### ISSUE THREAD

**Issue by sylmorin-gbif** [gbif/ipt#1882]
Hello
I was running the dev version of IPT (2.6.4 snapshot) and I noticed all the new graphical improvements !!! well done !!!

Just a remark on the User Account page.
I can see a tooltip on "delete user" button, but not on Edit and Reset Password.

![image](https://user-images.githubusercontent.com/56630013/202420956-2cf3b741-099a-4c12-ba3e-fcb0db8805a2.png)

**Comment by mike-podolskiy90** [comment]
Thank you very much I appreciate that.
Indeed, those don't have a title property, I'll fix that in the next version
