### ISSUE TITLE
ProjectID not in EML

### ISSUE THREAD

**Issue by ManonGros** [gbif/ipt#1883]
I don't know what is happening here but the projectID for [this dataset](https://www.gbif.org/dataset/11d28533-4dff-467c-943f-121d6bc2f5f9) doesn't seem to be saved in the EML.
It is visible in the IPT UI:
<img width="1293" alt="Screenshot 2022-11-18 at 08 24 45" src="https://user-images.githubusercontent.com/7677271/202645171-af04288c-f4ab-4789-b0a1-70fa4a2ed328.png">
But not in the EML of the DwCA: https://cloud.gbif.org/asia/archive.do?r=spiderindia_fb
I just republished to be sure.

Could you take a look? Thanks!

Tagging @vijaybarve as he is the one who originally raised the issue.

**Comment by mike-podolskiy90** [comment]
Thanks, looking into it

**Comment by mike-podolskiy90** [comment]
@ManonGros Looks like project personnel is required section. If you provide one person there it is displayed

**Comment by mike-podolskiy90** [comment]
https://github.com/gbif/gbif-metadata-profile/blob/master/src/main/resources/templates/eml.ftl#L274
Should we change that?

**Comment by ManonGros** [comment]
Thanks @mike-podolskiy90!
I don't think the project personal should be mandatory. Could you change that? Thanks!

**Comment by mike-podolskiy90** [comment]
Fix will be included in the next release
