### ISSUE TITLE
413 error - entity too large - for relatively small datasets

### ISSUE THREAD

**Issue by ManonGros** [gbif/ipt#1886]
One of our publishers is getting the following message when trying to create a new dataset “413 error - entity too large” but the datasets aren’t very big (one is less than 10 MB)
https://www.gbif.org/installation/240e89bc-4985-4468-aa2f-aaba905a8be4

**Comment by mike-podolskiy90** [comment]
Thanks Marie. Can they provide their logs please? 
I can't also access the IPT https://ipt.pnwherbaria.org/rss.do

**Comment by ManonGros** [comment]
I asked them for their logs, I will put them here when they send them.

**Comment by mike-podolskiy90** [comment]
Any updates here?

**Comment by ManonGros** [comment]
They wrote back that they are trying to put their server online and that they will be in touch with us. I haven't heard since. I will follow up them in January if there is still no news.

**Comment by EstebanMH-SiB** [comment]
We had the same problem in our IPT and it gave us the same message. Turns out it was a configuration problem in our server, we actualize the NginX parameters to increase the file size that you can upload.
Not sure if is the same problem, but maybe it can be helpful.

**Comment by abubelinha** [comment]
I wonder if this error message may also appear for url-based data sources.
I mean, what if you create a dataset which autopublishes (i.e. weekly) and your remote data source keeps growing. Eventually, it could grow beyond some limit.

Has the IPT any way to notify about errors raised by unattended publications?
Or we should just permanently look into IPT logs?

Thanks
@abubelinha

**Comment by mike-podolskiy90** [comment]
@abubelinha Thanks for you question 
No, unfortunately, we don't have such functionality yet

**Comment by mike-podolskiy90** [comment]
Closing this. Feel free to reopen if the issue occurs again
