### ISSUE TITLE
Could not publish dataset on test IPT Version 2.6.2-rbc8c0ba 

### ISSUE THREAD

**Issue by ManonGros** [gbif/ipt#1889]
From Helpdesk:

>  I tried to publish a test dataset on GBIF test IPT (https://ipt.gbif.org/) today, but nothing seems to happen when I click on the “yes” for publishing the dataset. The health status indicates that everything is operational.
I tried that with both Safari and Firefox and had the same results. 

> Can you please have a look at it? This is the dataset (https://ipt.gbif.org/manage/resource?r=mapppd)

I encountered the same issue while trying to publish another resource.

**Comment by mike-podolskiy90** [comment]
Thanks Marie. Looking into it

**Comment by mike-podolskiy90** [comment]
That's the problem https://github.com/gbif/ipt/issues/1854
I've fixed it for the 2.6.3, but we haven't updated ipt.gbif.org yet

**Comment by mike-podolskiy90** [comment]
I've published that resource by switching off 'Infer metadata automatically'

**Comment by ManonGros** [comment]
@ymgan FYI

**Comment by ymgan** [comment]
Thank you so much!! Really appreciate it!!
