### ISSUE TITLE
Scan results for trivy shows potential container vulnerabilities

### ISSUE THREAD

**Issue by ainsofs** [gbif/ipt#1891]
32 detected

https://trivy.dev/results/?image=gbif/ipt

**Comment by mike-podolskiy90** [comment]
@ainsofs Thank you for reporting this

**Comment by mike-podolskiy90** [comment]
related #1892

**Comment by mike-podolskiy90** [comment]
most of the issues will be fixed in the upcoming version (2.7.0 and higher)
