### ISSUE TITLE
Should we allow users to set their dataset version in the UI?

### ISSUE THREAD

**Issue by ManonGros** [gbif/ipt#1900]
This question comes following a request forwarded to helpdesk.
Right now there is no way to do this via the UI.

**Comment by peterdesmet** [comment]
Users can define a version in Zenodo.org, but there you can publish much more than datasets. Personally, I wouldn't allow users to set a version in the IPT, except perhaps the choice of a major vs minor version. That choice requires good guidelines and might have implications for the DOI assignment.

**Comment by ymgan** [comment]
Thank you Marie and Peter~ To give a bit of context:

We have a data provider who releases some data the format of [R package](https://github.com/CCheCastaldo/mapppdr). He made a Darwin Core version of the data and wanted to publish it through GBIF as well. He wishes to have the R package's release version match with the Darwin Core version. 

If manually setting version is not recommended, then what is the recommended way to do this?

Thank you so much!!

**Comment by peterdesmet** [comment]
I would point to the R package version as an **alternative identifier**. I have done [something similar](https://ipt.inbo.be/resource?r=o_assen#anchor-additional) for pointing to the source of animal movement data. Ideally the identifier is an URL, which is easy to make if the package is released on GitHub. See for example
https://github.com/frictionlessdata/frictionless-r/releases/tag/v1.0.2 which is a URL for version 1.0.2 of the frictionless R package. It wouldn't hurt to also mention the fact that the data originate from an R package in the **description**.

@gbif/informatics can alternative identifiers be used for this?

**Comment by mike-podolskiy90** [comment]
Alternative identifier looks like a good solution to me.

There is also an option to set version to the resource - to upload an EML with that version (Overview -> Metadata -> Upload). IPT will automatically pick it up.

**Comment by peterdesmet** [comment]
@mike-podolskiy90 @ymgan I guess this issue can be closed?

**Comment by ymgan** [comment]
Yes I think so! We are going for the alternative identifier approach! Thank you very much Peter and Mike!
