### ISSUE TITLE
Support reading .gz compressed source files

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#1903]
The IPT currently supports reading from `.zip` compressed files, but not `.gz` compressed files.

Our source files are often created in R and written to disk using [readr::write_csv()](https://readr.tidyverse.org/reference/write_delim.html). That function supports writing as `.gz` not `.zip`, so it would be nice if the IPT could read those files too.

**Comment by mike-podolskiy90** [comment]
Thank you Peter. IPT is actually able to read `.gz` files, but by default assumes it's `.tar.gz`. I'll fix
