### ISSUE TITLE
Error al subir datos al SIBs Colombia

### ISSUE THREAD

**Issue by jhoyosa1988** [gbif/ipt#1908]
#error al momento de subir datos a SIBs Colombia
![Imprimir](https://user-images.githubusercontent.com/87579828/205961418-ddbb6d25-8d18-4866-8e75-0dc45cae0e25.png)

**Comment by mike-podolskiy90** [comment]
Thank you for contacting us @jhoyosa1988 
What exact actions caused the error? 
Also to be able to analyze the error we need the IPT log files.

**Comment by mike-podolskiy90** [comment]
Is this the same error please https://github.com/gbif/ipt/issues/1907 ?

**Comment by mike-podolskiy90** [comment]
It basically says that resource's EML is invalid and can't be parsed. Feel free to re-open this if this still happens and please provide log files
