### ISSUE TITLE
Geographic coverage: false precision added

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#1912]
If I add `West: 2.53` to geographic coverage, the interface updates this to `2.530000000000001`. Is there a way to prevent this?

<img width="896" alt="Screenshot 2022-12-08 at 16 32 48" src="https://user-images.githubusercontent.com/600993/206488150-fce7b4b0-e156-468b-822f-14c785c91d9c.png">

**Comment by mike-podolskiy90** [comment]
Thank you @peterdesmet for your question
What IPT version is that?
I believe that was fixed recently. I don't see that at ipt.gbif-uat.org (2.7.0-snapshot) and ipt.gbif.org (2.6.3)
