### ISSUE TITLE
JVM is crashing at startup with Docker images >= 2.6.0

### ISSUE THREAD

**Issue by sylmorin-gbif** [gbif/ipt#1918]
We switched from 2.5.8 to a more recent version (issue reproducible on any version >= 2.6.0)

The IPT is no more starting, the JVM is crashing right away.
We only updated the IPT docker image version in the docker-compose - no other modification.
(I will copy paste the full JVM crash log below)

2 additional info:

- I didn't have the issue when I replace the base docker image by `tomcat:8.5.83-jdk8-corretto-al2`
https://github.com/gbif/ipt/blob/master/package/docker/Dockerfile#L17

- We can also fix the startup crash by adding:
```
    security_opt:
      - seccomp:unconfined

``` 

Both are solving the crash, but I can't explain why for the 1) one, and don't know the impacts for the 2) one, but I don't like it.

**Comment by sylmorin-gbif** [comment]
Here are the logs at startup...

[log.txt](https://github.com/gbif/ipt/files/10247919/log.txt)

**Comment by sylmorin-gbif** [comment]
It was reproducible on our VMs, but also on my laptop

![image](https://user-images.githubusercontent.com/56630013/208158713-3347cf74-cc49-481e-b9f6-ca6405fed34d.png)

**Comment by sylmorin-gbif** [comment]
I just ran the docker image:

`docker run -ti gbif/ipt:2.6.0 /bin/bash
`
Then, inside the container, a simple java -version is crashing...

![image](https://user-images.githubusercontent.com/56630013/208159560-0719bde3-f16a-4360-9394-33b174682c65.png)

**Comment by sylmorin-gbif** [comment]
Here is the result when I switch the tomcat docker images:

![image](https://user-images.githubusercontent.com/56630013/208160170-4bf6df4d-db0f-4b5a-ba6b-c4a3f9aa6190.png)

**Comment by mike-podolskiy90** [comment]
Thank you @sylmorin-gbif 
This was fixed in the last version a couple of months ago, which is the 2.6.3

**Comment by mike-podolskiy90** [comment]
I'm not quite sure though. Could you check the last version please?

**Comment by sylmorin-gbif** [comment]
It's reproducible since 2.6.0, but we first found the issue with 2.6.3

**Comment by sylmorin-gbif** [comment]
BTW, the issue is reproducible without the IPT... just by using the base image you are using in the dockerfile :

FROM tomcat:8.5-jdk8

**Comment by mike-podolskiy90** [comment]
@MattBlissett could you check this please when you can

**Comment by sylmorin-gbif** [comment]
Clearly, this tomcat:8.5-jdk8 base image is not working on my 2 envs (local and cloud)
With another tomcat image, no issue
So it's really not related with IPT, but with the base image you are using

![image](https://user-images.githubusercontent.com/56630013/208161879-31f288c6-7c65-4b6d-a288-d5ab654620ff.png)

I really can't explain why - I still haven't found any clue...

**Comment by sylmorin-gbif** [comment]
I updated my docker version on all the VMs, and my laptop, and I don't have the issue anymore with tomcat:8.5-jdk8, so with recent IPT version...

phew.... :)
