### ISSUE TITLE
Loading from existing dwca fails with no error message when extensions not loaded

### ISSUE THREAD

**Issue by albenson-usgs** [gbif/ipt#1921]
I have discovered when loading from an existing dwca that the IPT fails without telling the user why when trying to import from an archived resource. It reloads the create.do page without creating the new resource but are not told why. If possible, it would be nice if the IPT informed the user that a necessary extension is not loaded.

**Comment by mike-podolskiy90** [comment]
@albenson-usgs Thank you, I'll check it next year

**Comment by albenson-usgs** [comment]
Yes please no rush on this. Just wanted to document it while it was in my head. Happy new year!

**Comment by mike-podolskiy90** [comment]
I've just checked it's no longer the case for the new versions 2.6+
There were no issue for that, it was fixed in the version 2.5.8 though (I guess you're using 2.5.7)

**Comment by albenson-usgs** [comment]
Thank you Mike! Apologies for the ticket based on an outdated version.

**Comment by mike-podolskiy90** [comment]
No worries! I've updated the 2.5.8 milestone
