### ISSUE TITLE
Allow much larger file uploads

### ISSUE THREAD

**Issue by MattBlissett** [gbif/ipt#1928]
I can upload multi-gigabyte files to Box, Google Drive etc through a web browser.  These services use Javascript to show upload progress, and probably do a lot more.

It would be useful to have this in the IPT.  10GB seems a good target (does anyone need bigger? @albenson-usgs?). If possible, checking the server's disk space won't be exhausted would be very sensible.

**Comment by albenson-usgs** [comment]
That would definitely be big enough for me!

**Comment by albenson-usgs** [comment]
@peterdesmet @ckotwn or any other data managers out there- do you ever have datasets that are too big to upload and you have to find weird workarounds to get them in? Would it help to be able to upload larger files? Can you comment here if so?

**Comment by peterdesmet** [comment]
I occasionally bump into the file size limit, but have always been able to work around that by compressing the data (e.g. `.gz`), which also saves me on bandwidth. The real test is in publishing the data, where the validation of foreign keys between core and extension (especially on an extended measurement or fact) can take a long time (e.g. over an hour), but typically works in the end.

**Comment by albenson-usgs** [comment]
Makes sense. I have datasets that even once they are zipped are still to large to upload like [this one](https://www.gbif.org/dataset/721a99a4-71f4-4466-b346-83c367889238) and [this one](https://ipt-obis.gbif.us/resource?r=wod_2009). I imagine that in the future datasets will only get larger and so this may become more of an issue then.

**Comment by DanBIF** [comment]
We (Danish node) have also reached limits with uploading, having to split the data set, so yes, we would welcome to be able to upload larger files

**Comment by ckotwn** [comment]
Sorry for missing the mention. Yes, I agree a larger allowance will be more often needed in the future.
Though, reading the top post, does this request also include UI components (progress bar or else)?

**Comment by mike-podolskiy90** [comment]
Yes, it includes UI improvements.

Currently working on that, would be something like this:
![Screenshot 2023-06-16 at 10 55 29](https://github.com/gbif/ipt/assets/24795387/cc23af00-038f-428d-bf56-a2746f5da071)

**Comment by CecSve** [comment]
Helpdesk has been in contact with publishers who want to share 20-64 GB source files and are hesitant to split the files before upload. I will update this comment if I learn why splitting the source files can be an issue.
