### ISSUE TITLE
Tab issue on Create User page

### ISSUE THREAD

**Issue by laurarussell** [gbif/ipt#1933]
After completing the last field on the user entry page (verify password), the keyboard tab option should go to the Save button (at the top of the page), instead of the About the IPT link in the footer.

It would also be nice if you could see that the Save button has focus when you have tabbed to it. (When you mouse over it, the color goes slightly darker).

**Comment by mike-podolskiy90** [comment]
@laurarussell Thank you Laura. I've deployed to [ipt.gbif-uat.org](https://ipt.gbif-uat.org/)
