### ISSUE TITLE
Cannot add resources if Spanish is selected

### ISSUE THREAD

**Issue by vjrj** [gbif/ipt#1939]
A js exception rises in this line:

![image](https://user-images.githubusercontent.com/180085/216261872-88f1f9c3-5119-4fe0-8c45-ed79be4cb1c4.png)
because the translation has an extra `\n`.

So the "Add" button of data resources does not open the dialog.

The workaround is to remove the `\n`  (in our case in `/var/lib/tomcat9/webapps/ipt/WEB-INF/classes/ApplicationResources_es.properties`):

![image](https://user-images.githubusercontent.com/180085/216262700-04ce6502-9bfd-4f5a-a50e-704c9d383bd3.png)

or use English. I'm requesting access to crowdin to try to fix it.

This happens in `2.7.1`.

**Comment by mike-podolskiy90** [comment]
Thank you for reporting this bug @vjrj 
I'll release fix shortly
