### ISSUE TITLE
Advertise the availability of the OBIS DQ validator

### ISSUE THREAD

**Issue by timrobertson100** [gbif/ipt#1944]
OBIS have a very nice validation tool [here](https://rshiny.lifewatch.be/BioCheck/).

When a publisher selects the OBIS network, we should notify the user of the existence of this tool.

**Comment by rubenpp7** [comment]
Hi, 

currently users could build an URL that already outputs the validation of a specific dataset by concatenating the following:

'http://rshiny.lifewatch.be/BioCheck/?baseurl=' + <URL to your IPT> + '&resource=' + <shortname of the resource>

Example:
http://rshiny.lifewatch.be/BioCheck/?baseurl=http://ipt.vliz.be/training&resource=biofun_2009

Current open issue that affects this usage of the Biocheck tool in https://github.com/EMODnet/EMODnetBiocheck/issues/34

**Comment by mike-podolskiy90** [comment]
@timrobertson100 Thanks Tim, I'll do
