### ISSUE TITLE
HTTP 500 error for ipt3.gbif-uat.org

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#1951]
@mike-podolskiy90 the IPT used to test Camtrap DP functionality currently shows a HTTP 500 error for any resource management page, e.g. https://ipt3.gbif-uat.org/manage/resource?r=camtrap-test Is it possible to debug this?

![Apache-Tomcat-7-0-76-Error-report](https://user-images.githubusercontent.com/600993/221198753-29d095ca-fa77-4b34-9104-4fb53f43996a.png)

**Comment by mike-podolskiy90** [comment]
@peterdesmet Thank you for reporting this.
That's not an IPT issue, we just have to install a newer Tomcat version on UAT. Camtrap IPT works only for Tomcat 8 or higher

**Comment by mike-podolskiy90** [comment]
@MattBlissett looking into it

**Comment by peterdesmet** [comment]
Great! On what branch is his developed? Do you foresee a merge to pull in the recent updates from `master` (and I assume solve the Tomcat 8 dependency)?

**Comment by mike-podolskiy90** [comment]
@peterdesmet Current code is in the master-3.0 branch (if I remember correctly). What Matt is doing is basically just installing a fresher Tomcat.
Yes, I'll be merging the master branch soon, but it won't solve Tomcat issues whatsoever. Tomcat 8 will be a requiremet for IPTs 3.0+

**Comment by MattBlissett** [comment]
https://ipt3.gbif-uat.org/health.do

It's now Tomcat 9 and Java 11, which seem to be the defaults for Ubuntu 22.04.1 LTS.
