### ISSUE TITLE
Freemarker issue in ipt3.gbif-uat.org

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#1952]
The Camtrap DP schemas are not available when trying to map data (empty dropdown for `file`):

<img width="714" alt="Screenshot 2023-02-24 at 18 16 49" src="https://user-images.githubusercontent.com/600993/221244972-6b6b7ed3-86e5-4117-b105-75a660399fac.png">

Navigating away from this page (not clicking cancel) resulted in a freemarker error:

<img width="924" alt="Screenshot 2023-02-24 at 18 12 44" src="https://user-images.githubusercontent.com/600993/221244562-9eb1f6af-e500-4299-a0cd-e57ed0fcaaa6.png">

This also prevents me from removing the mapping.

@mike-podolskiy90 the Camtrap DP schemas were updated from 0.4 to 0.6 by @timrobertson100 and me, but maybe we broke something. 😅

**Comment by mike-podolskiy90** [comment]
Thanks, looking into it

**Comment by mike-podolskiy90** [comment]
Yes, something wrong with the schemas structure in rs gbif

**Comment by mike-podolskiy90** [comment]
I believe this will fix the issue e3ef461b5d9ee8ccef681aebb8dd3c9d2b148c32
