### ISSUE TITLE
What schemas to refer to for Camtrap DP

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#1955]
When publishing a Camtrap DP on ipt3.gbif-uat.org, the `profile` property is set to the generic `data-package` and the Table schemas are included verbosely (referring to the GBIF ones):

```
schema/
  http_rs_gbif_org_schemas_camtrap-dp_deployments.json
  http_rs_gbif_org_schemas_camtrap-dp_event-observations.json
  http_rs_gbif_org_schemas_camtrap-dp_media-observations.json
  http_rs_gbif_org_schemas_camtrap-dp_media.json
datapackage.json
deployments.csv
event-observations.csv
media-observations.csv
media.csv
```

This is a valid Data Package, but looses its relation with Camtrap DP (e.g. metadata won't be validated against Camtrap DP specs, but Data Package specs). @mike-podolskiy90, @timrobertson100 is this a deliberate design choice? It could be, to make a published data package a self-containing combination of data and validation (except for the Data Package specs).

I would argue to not include the Table Schemas verbosely, but rather to refer to a specific version by URL. This could either be to the Camtrap DP ones (e.g. `https://github.com/tdwg/camtrap-dp/blob/0.6/deployments-table-schema.json`), but a rs.gbif.org URL would be valid too (as long as the URL contains the version number). The IPT already makes sure that all columns not populated by the user _are_ included in the CSV, so that the CSV columns match the schema . 👍 

Additionally, I would use:

```
"profile": "https://raw.githubusercontent.com/tdwg/camtrap-dp/<version>/camtrap-dp-profile.json",
```

So that any validation happens against Camtrap DP and not generic Data Package.

**Comment by timrobertson100** [comment]
I think my concern would be that the archives could outlive the schema repository URLs. Perhaps an approach of additionally including them in a `/schemes` directory would be sensible.

**Comment by peterdesmet** [comment]
Yes, that could work: including them in `/schemes`, but not linking to it.

Another approach would be to include them verbosely in the `datapackage.json` in a custom property, e.g. `schemaVerbose`, `schemaAsObject`, ...

```
{
  "name" : "deployments",
  "profile" : "tabular-data-resource",
  "format" : "csv",
  "schema" : "schema/http_rs_gbif_org_schemas_camtrap-dp_deployments.json",
  "schemaVerbose": { ... },
  "path" : "deployments.csv"
}
```

The advantage would be a strong link between the resource and `schemaVerbose` (which is only implied by the name with `/schemes`). The disadvantage is that `datapackage.json` gets a bit more clunky to navigate.

**Comment by mike-podolskiy90** [comment]
@peterdesmet I got issues with the json schema here https://github.com/tdwg/camtrap-dp/blob/main/camtrap-dp-profile.json

Fixed them by replacing `$defs` with `definitions`, and `"$ref": "#$defs/version"` with `"$ref": "#/definitions/version`

See https://rs.gbif.org/sandbox/experimental/camtrap-dp/0.6/profile/camtrap-dp-profile.json

**Comment by peterdesmet** [comment]
Where is it that `$defs` does not work? The use of `$defs` was borrowed from https://json-schema.org/understanding-json-schema/structuring.html#defs

**Comment by mike-podolskiy90** [comment]
Data package fails to generate and error is displayed:

```
Reference #$defs/version cannot be resolved
```

**Comment by peterdesmet** [comment]
I have logged an issue to make use of `definitions` not `$defs` in Camtrap DP.

@mike-podolskiy90 are you still planning to include the verbose schemas for each resource as `schemaVerbose` (see https://github.com/gbif/ipt/issues/1955#issuecomment-1446448527)? This would address @timrobertson100 concern "I think my concern would be that the archives could outlive the schema repository URLs."

**Comment by mike-podolskiy90** [comment]
Thanks. I am not actually. `datapackage.json` doesn't really look good with verbose schemas, I'd prefer no to include it.
