### ISSUE TITLE
Metadata file for Camtrap DP

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#1958]
[ipt3.gbif-uat.org](https://ipt3.gbif-uat.org/resource?r=camtrap-dp-0-6) currently supports a **metadata file** for Camtrap DP. It is a file named `datapackage-camtrap-dp-0-6-v2.0.json` that includes all metadata (single line, not prettified) with an empty `resources` array:

```json
...,
"resources":[],
...
```

This is the equivalent of the **Metadata as an EML file** and **Metadata as an RTF file** for Darwin Core Archives, but I'm not sure what use case it supports. I would remove it.

A good use case would be to have a valid `datapackage.json` that links to (compressed) data files, cf. how this is done in https://doi.org/10.5281/zenodo.5653311. The user can then read the relatively small `datapackage.json` and get all the pointers to the data files. But I don't think it is possible to point to data files _in_ an archived directory though.

**Comment by mike-podolskiy90** [comment]
Thanks, I removed it
