### ISSUE TITLE
Implement preview of Camtrap DP

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#1959]
Previewing a pending version of a Camtrap DP does not work on ipt3.gbif-uat.org.

It indicates the resource does not exist:
<img width="348" alt="Screenshot 2023-02-27 at 15 54 15" src="https://user-images.githubusercontent.com/600993/221597032-e04e8392-d998-4d53-afd5-28f37dd2a94e.png">
<img width="512" alt="Screenshot 2023-02-27 at 15 53 40" src="https://user-images.githubusercontent.com/600993/221596874-90ef8e08-2059-4623-82a4-cecbe0eddf56.png">

**Comment by mike-podolskiy90** [comment]
Thanks for spotting that. Turns out it was not implemented for data packages
