### ISSUE TITLE
List Camtrap DP resources in preferred order

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#1960]
In https://rs.gbif.org/sandbox/experimental/schemas.json the Camtrap DP schemas are listed as:

```
deployments
media
media-observations
event-observations
```

 That is the preferred order.

In the IPT (dropdown when mapping) and the published datapackage.json, the resources are listed as:

```
event-observations
media-observations
deployments
media
```

Can the preferred order by maintained?

**Comment by mike-podolskiy90** [comment]
@peterdesmet Thank you
Why is it important please?

**Comment by peterdesmet** [comment]
That order is the logical flow from the data model:

<img width="378" alt="Screenshot 2023-03-02 at 10 04 11" src="https://user-images.githubusercontent.com/600993/222382062-0f6f846f-13e2-4ca8-a9d6-47c3bd0fb3ae.png">

So it will be more convenient for publisher to map it as such and for consumers to see the resources listed as such.

**Comment by mike-podolskiy90** [comment]
To make it work at ipt3.gbif-uat.org we need to re-install (delete and install) Camtrap schema.
