### ISSUE TITLE
Unable to edit and/or delete mapping from a resource

### ISSUE THREAD

**Issue by rondlg** [gbif/ipt#1968]
Hi,

for some reason since the new ipt version we are unable to edit or delete the dwc  mapping on this resource:

https://fmipt.fieldmuseum.org/ipt/manage/resource.do?r=fmnh_mammals_sightings

![image](https://user-images.githubusercontent.com/702709/223841534-8c02aad9-021a-47ee-ad90-a2f52efe05e7.png)

Has anyone else reported this?

Thanks

Sharon

**Comment by mike-podolskiy90** [comment]
Thank you for contacting us.
Just click on the element itself it'll open the mapping/source detail page.

**Comment by mike-podolskiy90** [comment]
related #1946

**Comment by mike-podolskiy90** [comment]
Are you not able to delete the mapping as well?

**Comment by rondlg** [comment]
Hi Mike,

when I click the "box" to try and edit nothing happens, the same when I click delete. 

S.

**Comment by mike-podolskiy90** [comment]
@rondlg Something failed with this resource. Would it be possible to create an admin account for me in your IPT please? I'll try to diagnose the problem

**Comment by rondlg** [comment]
You should have an email from me now.
