### ISSUE TITLE
Improve IPT setup: thematic steps

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/ipt#1969]
Instead of setup part 1, 2, and 3, break down the IPT installation steps thematically into the following topics:

1. Disclaimer (License agreement)
2. IPT data directory
3. IPT default administrator
4. IPT mode
5. Public URL (including proxy URL if needed)
6. All step completed

and add UI stepper component

**Comment by mike-podolskiy90** [comment]
![Screenshot 2023-03-13 at 11 15 13](https://user-images.githubusercontent.com/24795387/224672779-28b67f81-3baf-430b-9011-5e85668af6ac.png)

**Comment by MattBlissett** [comment]
I'm reopening this as I need to check it works correctly when the data directory is supplied through environment config, i.e. as in https://ipt.gbif-uat.org/manual/en/ipt/latest/installation#tomcat

**Comment by mike-podolskiy90** [comment]
@MattBlissett Have you tried it?

**Comment by MattBlissett** [comment]
It didn't seem to work when I looked last week, but I didn't spend much time on it.  I will try it later.

It is this code that's relevant: https://github.com/gbif/ipt/blob/master/src/main/java/org/gbif/ipt/config/IPTModule.java#L86

**Comment by MattBlissett** [comment]
On deployment the IPT can read the context parameter for the data directory location:

```
Jul 18 10:55:04 uattomcat-vh.gbif.org server[21483]: INFO  [org.gbif.ipt.config.IPTModule] - Using context parameter IPT_DATA_DIR for data directory location: /var/lib/tomcat/ipt-data-matt
Jul 18 10:55:04 uattomcat-vh.gbif.org server[21483]: INFO  [org.gbif.ipt.config.DataDir] - IPT Data Directory configured at /var/lib/tomcat/ipt-data-matt
```

But the second setup step, to choose a data directory, is still shown.  This step should be skipped, as a data directory as already known.

example: http://uattomcat-vh.gbif.org:8080/matt/ and `/etc/tomcat/Catalina/localhost/matt.xml`.

**Comment by mike-podolskiy90** [comment]
@MattBlissett Thanks, I see. I'll fix

**Comment by mike-podolskiy90** [comment]
Can't reproduce it on mac (Tomcat/Jetty). If datadir is provided in any of the three ways, the setup is skipped. The second step actually checks if datadir is already configured:
https://github.com/gbif/ipt/blob/master/src/main/java/org/gbif/ipt/config/SetupAction.java#L247
I don't know what can be wrong

**Comment by mike-podolskiy90** [comment]
I think I've reproduced it

**Comment by mike-podolskiy90** [comment]
Should be fixed now

**Comment by mike-podolskiy90** [comment]
I've removed the disclaimer step

**Comment by mike-podolskiy90** [comment]
@MattBlissett Can you try it again?
