### ISSUE TITLE
basisOfRecord mapping does not allow you to select the correct dwc values.

### ISSUE THREAD

**Issue by rondlg** [gbif/ipt#1970]
We are the process of building logic into our data exports to include the correctly formatted basisOfRecord values, however in the meantime we would like to use the value override to get the correct value mapped. The lookup on this field however, forces the wrong values. 

For example "Preserved Specimen" instead of "PreservedSpecimen" (https://fmipt.fieldmuseum.org/ipt/manage/vocabulary.do?id=http://rs.tdwg.org/dwc/dwctype/)

![image](https://user-images.githubusercontent.com/702709/224847477-1110ecd9-6cb7-4a25-8fa3-b05501dffc75.png)

**Comment by albenson-usgs** [comment]
I believe based on this ticket https://github.com/gbif/ipt/issues/1831 that the IPT is supposed to be more forgiving in how `basisOfRecord` values are provided but I admit I haven't tested this myself but that might be why the options are provided as you see them.

**Comment by mike-podolskiy90** [comment]
Thank you for contacting us.
That's right, now it allows a wider range of values. So `Preserved Specimen` will end up as `PreservedSpecimen` in the result archive.
