### ISSUE TITLE
How to update organization alias in resource overview table?

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#1971]
I noticed that names in the `Organization` column of the [resource overview table](https://ipt.inbo.be/?sort=organisation&order=asc):

> Agentschap voor Natuur en Bos

Can differ from the `Published by` associated with a [resource](https://ipt.inbo.be/resource?r=anb-crayfishes-occurrences):

> Agency for Nature and Forests (Flemish Government)

The latter is also the official name in the [registry](https://www.gbif.org/publisher/d2b220bd-5701-4fe4-ba06-a1e3fc6288fe).

It looks like the name in the resource overview table is pulled from the `alias` as defined in the `Admin > Associated organizations`. However, when I update the alias name there, it is not reflected in the resource overview table. Does it only get updated when republishing the resource? Would it be possible to pull that `alias` name live, so resources don't need to be updated to fix e.g. a typo?

**Comment by peterdesmet** [comment]
Thanks, I'll close this issue and mark it as duplicate then, since it will be resolved when #1964 is fixed.

**Comment by mike-podolskiy90** [comment]
I don't think it's duplicate actually. 
The #1964 implies implementing a button/link which user can click and sync with the registry (get organizations in the IPT updated). And here it's internal data (not from the registry) that supposed to be sync automatically

**Comment by peterdesmet** [comment]
Oh, my mistake, I thought the button was to sync the internal data.
