### ISSUE TITLE
Copy Resource Contact Information to Creator and Metadata Provider

### ISSUE THREAD

**Issue by albenson-usgs** [gbif/ipt#1972]
Did we lose the ability to copy from the resource contact in the basic metadata section? It now seems like we can only copy from another existing resource?
![Capture](https://user-images.githubusercontent.com/7586150/225374996-867d6534-8a8a-4db3-aabe-4dce0465c6c0.PNG)

I like this new functionality but I also used the "Copy from Resource Contact" functionality from before because frequently the Contact, Creator, and Metadata provider are all the same person and it's nice not to have to retype all that information 3 times.

Alternatively [this suggestion](https://github.com/gbif/ipt/issues/1166#issuecomment-1369561107) would also resolve this issue.

**Comment by mike-podolskiy90** [comment]
Thank you for contacting us @albenson-usgs 
It is possible to copy if you save the resource contact. Then it'll be available in the list. But it requires more actions from the user. Let's add a link to the modal window which will replicate previous functionality.

About that suggestion, I already mentioned somewhere that it doesn't really work with the current IPT and EML implementation. Those are different entities under the hood in the EML xml, so it would be a bit complicated to split it up/aggregate every time

**Comment by albenson-usgs** [comment]
Ok thanks!

**Comment by mike-podolskiy90** [comment]
There are issues with search

**Comment by mike-podolskiy90** [comment]
Fixed https://github.com/gbif/ipt/commit/c68134f5a76a40c0de37da7f367d0b42904f69d7

**Comment by mike-podolskiy90** [comment]
@albenson-usgs There will be a search option, I thought that would be enough?

**Comment by albenson-usgs** [comment]
Oh yes that seems like it would solve the problem. Thanks!

**Comment by albenson-usgs** [comment]
Hi Mike- I'm trying to use this functionality right now and I don't know how to accomplish "It is possible to copy if you save the resource contact." I have two completely new people (meaning they are not saved in any other resource) and I input their information into the Resource Contacts section and what I would like to be able to do is not have to write again all that information in the Resource Creator section. I don't see a way to "save the resource contact" because when I try to do that I get an error message that states "At least one creator is required". How do I save a resource contact that I need the information for in the resource creator and they are not part of any other resource?

**Comment by albenson-usgs** [comment]
Ah I see, I'm going to leave my comment but left to work on something else for a bit and when I came back to it the new resource- the contact information is saved and I can search for this new resource in the dialog box to select it for the creator. Thank you for all your hard work!

**Comment by mike-podolskiy90** [comment]
@albenson-usgs Thank you for suggesting improvements! I'm glad you sorted it out. Otherwise I'm here to help
