### ISSUE TITLE
Update registration failed

### ISSUE THREAD

**Issue by kitelloran** [gbif/ipt#1974]
Does anyone here experience the same issue? 
I've updated my IPT but after the process all Organization content was gone.

![image](https://user-images.githubusercontent.com/12725462/225780751-686e9979-278b-4d05-ad04-01a0b75f0f2d.png)

**Comment by mike-podolskiy90** [comment]
Thank you for contacting us.
This is your issue https://github.com/gbif/ipt/issues/1794. You need to upgrade your IPT to the most recent version (currently 2.7.3) and update IPT tokens at the GBIF registration options page.

**Comment by mike-podolskiy90** [comment]
Feel free to contact us if this is still a problem
