### ISSUE TITLE
Check whether a Camtrap DP `data` license is a valid GBIF license

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#1976]
In Camtrap DP, one can indicate two licenses: one for the data and one for the media files. This is currently implemented as such in the IPT:

<img width="741" alt="Screenshot 2023-03-24 at 16 33 10" src="https://user-images.githubusercontent.com/600993/227571004-743df042-7e05-4f32-8941-689571743455.png">

The IPT _does_ currently check whether the license for the scope `data` is one of the following `CC0, CC-BY, CC-BY-NC`. That is good! The values are incompatible however. IPT requires `CC0, CC-BY, CC-BY-NC`, while Frictionless requires an [Open Definition license ID](https://licenses.opendefinition.org/licenses/groups/all.json), i.e. `CC0-1.0, CC-BY-4.0, CC-BY-NC-4.0`

I would update the interface a bit:

- [x] Rather than a list of licenses, provide 2: Data license and Media license
- [x] Remove the `Title` field, it can only lead to conflicting information
- [x] For `Data license`:
  - [x] Make it a required field
  - [x] Offer a dropdown with the 3 GBIF licenses
- [x] For `Media license` we need to assess if we want to set requirements, but imo:
  - [x] ~Don't make it required~ Make it required for now
  - [x] Offer a dropdown with all Creative Commons licenses
- [x] Decide whether GBIF services want to use `name` (CC0-1.0, CC-BY-4.0, CC-BY-NC-4.0) or `path` for importing, exporting and interpreting `datapackage.json` information. I would opt for `name` as those values are controlled. Camtrap DP could be adapted to require `name` (rather than `name` or `path`)

**Comment by peterdesmet** [comment]
Oh, I forgot about that! 😄 Good to have decisions coded in specs, let's make both licenses required, it's the proper thing to do anyway.

**Comment by mike-podolskiy90** [comment]
I assume using `name` would be more convenient
