### ISSUE TITLE
Explore ColDP support

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/ipt#1979]
https://github.com/CatalogueOfLife/coldp

**Comment by mike-podolskiy90** [comment]
@mdoering Col-dp is similar to frictionless-data, but not exactly the same. Tim suggests we can produce two in one: it would be valid col-dp and frictionless package so it would contain both datapackage.json and metadata.yaml files (and datafiles of course). What do you think?

**Comment by mdoering** [comment]
Adding a datapackage.json is fine and might be useful. The big different from ColDP over a regular DP is the various implementations of [reference data](https://github.com/CatalogueOfLife/coldp/blob/master/README.md#reference). These can come in 3 flavors: a csv, bibtex or csl-json file.

I don't expect the IPT to produce bibtex or CSL Json from mapping a source, but it would be very good to be able to upload such a data file manually and produce a reference.csv by regular mapping.

**Comment by mdoering** [comment]
Another non standard datapackage option in ColDP is support for a logo.png or logo.jpeg file which could be added by uploading it to the IPT - and which stays for every version unless it is replaced?

**Comment by peterdesmet** [comment]
@mdoering note that Frictionless Data Package has the property `image`: https://specs.frictionlessdata.io/data-package/#image Would that not support your use case?

**Comment by mdoering** [comment]
The use case is to have a binary logo image as a local file in the archive, not a URL. For this to happen one needs to be able to upload an image file in the IPT. I actually think it would be a great addition to the IPT to be able to upload any number of binary files, e.g. pdfs or other raw data files that are simply included in the archive, potentially even organised in a subfolder.

Secondary to that the ColDP specs define the name of the file to be logo.png or jpeg.

**Comment by peterdesmet** [comment]
@mdoering note that `image` property accepts URLs and local files. The ColDP specs could expand on that and require it to be a local `logo.png` file. The use case sound similar enough to "An image to use for this data package. For example, when showing the package in a listing.", but you could of course have your own property.

Other binary files sound like another topic/issue altogether. 🙂
