### ISSUE TITLE
Allow multiple email addresses per contact

### ISSUE THREAD

**Issue by timrobertson100** [gbif/ipt#1981]
Requested from Arctos via email:

> allows for only one email address for creator contacts (and probably others, but this is the one we ran into). Many of our agents in Arctos have more than one email address and we pull from there to complete the publisher metadata EML. Our strategy was to list them as comma-separated values, but the IPT will not accept that. Could it? 

As far as I can see in EML `electronicMailAddress ` can be multivalue everywhere and contacts in the GBIF API [can have multiple email addresses](https://github.com/gbif/gbif-api/blob/dev/src/main/java/org/gbif/api/model/registry/Contact.java#L87) so I think this might be possible without too many breaking changes.

Relates to https://github.com/gbif/eml-profile/issues/1

**Comment by mike-podolskiy90** [comment]
This is going to be a part of the EML 2.2.0 update
