### ISSUE TITLE
Taxon core vernacular name and distribution invalid

### ISSUE THREAD

**Issue by rukayaj** [gbif/ipt#1982]
We've got a dataset (https://www.gbif.org/dataset/88d487cb-9049-47dd-a2b4-f8da0d45870a), and the records have been tagged with Vernacular name invalid and Distribution invalid, e.g. https://www.gbif.org/species/209474045. 

The mapping:
<img width="1284" alt="Screenshot 2023-04-04 at 10 16 28" src="https://user-images.githubusercontent.com/9654499/229731032-f0d06fdc-75d3-46ea-a4dd-bfab08170fe3.png">
And e.g. for vernacular names:
<img width="926" alt="Screenshot 2023-04-04 at 10 17 13" src="https://user-images.githubusercontent.com/9654499/229731179-b2e458d9-c5dc-4dcf-b1f8-9db50349f3f4.png">

Are these in an incorrect format or something maybe?

**Comment by rukayaj** [comment]
Ok maybe we figured it out. The guy doing this dataset said last night he checked the codes more closer. Not all were exactly as in the standard format for language and countries, he will correct and try again.

**Comment by mike-podolskiy90** [comment]
@rukayaj Is this still an issue please?

**Comment by rukayaj** [comment]
I didn't hear back so I think this one can get closed. Thanks.
