### ISSUE TITLE
duplicated information from case sensitivity in Agent's email

### ISSUE THREAD

**Issue by ymgan** [gbif/ipt#1985]
Hi, 

I realized that when I put the same email but with first letter of the name capitalized in the email of Resource Creators, the information is duplicated in the metadata (see screenshot below) but it did not appear as Originator in this page: https://ipt.biodiversity.aq/resource?r=mna_planktonic-benthic-sympagic-copepod&v=1.0 

![Screenshot 2023-04-11 at 15 46 44](https://user-images.githubusercontent.com/11754081/231183787-a9295802-4247-401e-b06f-955ae12a7b6d.png)

Once I corrected the email to all lowercase, it looks fine here (Agent is now listed as Originator): https://ipt.biodiversity.aq/resource?r=mna_planktonic-benthic-sympagic-copepod&v=1.1
![Screenshot 2023-04-11 at 15 54 38](https://user-images.githubusercontent.com/11754081/231185598-6892e3fe-e3f5-4fd0-bc12-5567ddb5727b.png)

I believe that this could be a bug. The IPT version is 2.7.3. Can you please have a look at this? Thank you very much!

**Comment by mike-podolskiy90** [comment]
@ymgan Thank you I'll have a look
