### ISSUE TITLE
IPT version 2.7.3 does not include recordedByID and identifiedByID

### ISSUE THREAD

**Issue by rukayaj** [gbif/ipt#1986]
<img width="516" alt="Screenshot 2023-04-12 at 11 45 38" src="https://user-images.githubusercontent.com/9654499/231420755-414bf4f7-9e33-42e7-a1d2-5cbfc64d9a7b.png">
<img width="238" alt="Screenshot 2023-04-12 at 11 46 07" src="https://user-images.githubusercontent.com/9654499/231420867-00340cd3-e76f-46dc-aa8b-3fd10470e6b4.png">

Did it perhaps get moved somewhere?

**Comment by mike-podolskiy90** [comment]
@rukayaj Thank you for contacting us
No, it was not moved. I assume your IPT loaded wrong vocabulary file for the occurrence. You can check that in the Administration -> Darwin Core Types and Extensions -> Darwin Core Occurrence. It supposed to be the version issued on 02-02-2022.
This one looks similar https://github.com/gbif/ipt/issues/1980
