### ISSUE TITLE
Add support for Plausible analytics

### ISSUE THREAD

**Issue by MattBlissett** [gbif/ipt#1988]
GBIF will soon stop using Google Analytics and use Plausible analytics instead.

It would be useful to be able to configure the IPT in a similar way to Google Analytics.  For Plausible, there needs to be a "Data domain" option, which can accept a single domain like `gbif.org`, or a list like `ipt.gbif.org,gbif.org`.

Pages should then include the following HTML:

```
<script defer data-domain="#{data_domain}" src="https://plausible.io/js/script.file-downloads.js"></script>
```

(It is already present in the manual, stats at https://plausible.io/ipt.gbif.org as well as rolled in to https://plausible.io/gbif.org)

**Comment by mike-podolskiy90** [comment]
Thanks Matt

**Comment by MattBlissett** [comment]
This isn't a feature GBIF need, so there's no need to implement it unless someone else shows interest.
