### ISSUE TITLE
 Recognition of geodeticDatum Field by IPT

### ISSUE THREAD

**Issue by marcelooyaneder** [gbif/ipt#1989]
Hello, recently we have published biodiversity data in GBIF using the georeferencing process recommended by the publication ([georeferencing best practices](https://docs.gbif-uat.org/georeferencing-best-practices/1.0/en/)), using the georeferencing Calculator tool. In addition to the field "coordinateUncertaintyInMeters", this tool provides other data such as the datum. For our publication, we used the datum "WGS84" and it was published in our database as it is delivered by the Calculator, "(WGS84) World Geodetic System 1984". However, when analyzing our data later in GBIF under "Issues and Flags", we found that this datum is not recognized by the IPT.

While the solution is to change the datum to "WGS84" or "EPSG:4326", would it be possible to add the value "(WGS84) World Geodetic System 1984" to the allowed dictionary in IPT? The georeferencing Calculator is recognized as one of the official tools that add quality to databases related to the georeferencing process. Additionally, we believe that it would be useful to disseminate this information to the nodes, as we stumbled upon this issue while generating a quality report for our data published in GBIF.

Best regards,

Marcelo Oyaneder Labarca - [marcelo.oyaneder@usach.cl](mailto:marcelo.oyaneder@usach.cl)
Paulette Naulin Gysling - [pnaulin@uchile.cl](mailto:pnaulin@uchile.cl)

**Comment by mike-podolskiy90** [comment]
@marcelooyaneder Thank you for contacting us

@fmendezh @muttcg It's pipelines scope I guess

**Comment by MattBlissett** [comment]
parsers-0.61 now includes the required values.  I don't know if you want to update dev or master.

These two issues are also handled, and can be closed once this is deployed: https://github.com/gbif/portal-feedback/issues/4610, https://github.com/gbif/portal-feedback/issues/4388
