### ISSUE TITLE
Data package record filter

### ISSUE THREAD

**Issue by mdoering** [gbif/ipt#1994]
In some cases it would be useful to exclude/skip records when some field is empty.
For example a scientificName might be required and a record without it rather useless. 
If the mapping page could have a check box with "NonEmpty" or sth alike next to the field that is being mapped and then skip the entire record if there is no value that would be great.

**Comment by mike-podolskiy90** [comment]
Thanks Markus.
It's basically filtering functionality we already have for DwCs, it's just not implemented for data packages.
