### ISSUE TITLE
Missing field in the Trait measurement score (v20140515) extension

### ISSUE THREAD

**Issue by SophiePamerlon** [gbif/ipt#1995]
Hi, I noticed an issue with the Trait measurement score (v20140515) extension on the IPT: when it is installed, I cannot find the "measurementMethod" term after selecting it in the mapping section of a resource page, whereas it is listed as a term from this extension in this extension's page in the Administration tab (see attached file)
Thanks for your help :)
![Screenshot 2023-04-19 at 12-34-19 Darwin Core Extension](https://user-images.githubusercontent.com/19349253/233049252-89b3fa7d-cd04-4514-b38e-3fa1bcb9bdce.png)

**Comment by mike-podolskiy90** [comment]
@SophiePamerlon Thank you for contacting us
Yes, I've just tested, and it's not present indeed. I'll figure out why.
