### ISSUE TITLE
How/why is `id="uuid"` for Camtrap DP

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#1999]
_First reported [here](https://github.com/gbif/ipt/issues/1829#issuecomment-1483024758)_

I noticed id is assigned (e.g. with fb2fb39c-3a11-437c-8e60-aa50c5e5172b). How is this value assigned?

**Comment by mike-podolskiy90** [comment]
Thanks Peter
I answered it there a while ago https://github.com/gbif/ipt/issues/1829#issuecomment-1485135651

**Comment by peterdesmet** [comment]
My mistake. That should work.
