### ISSUE TITLE
Support `image` property for resource logo

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#2000]
First mentioned [here](https://github.com/gbif/ipt/issues/1829#issuecomment-1483024758):

Should we support the [image property](https://tdwg.github.io/camtrap-dp/metadata/#image) as a resource logo? I'm not a big fan of resource logos, as the chosen image is often refers to the publisher rather than project or dataset.

And further discussed [here](https://github.com/gbif/ipt/issues/1979#issuecomment-1513514903).

**Comment by mike-podolskiy90** [comment]
Thanks Peter. Should it be a file upload or just an input for URL?

**Comment by peterdesmet** [comment]
The `image` property in Frictionless supports both. I would support what makes the most sense for the IPT.

**Comment by mike-podolskiy90** [comment]
To begin with I've created a regular input

**Comment by mike-podolskiy90** [comment]
Help text is taken from here https://specs.frictionlessdata.io/schemas/data-package.json

**Comment by peterdesmet** [comment]
- [ ] I notice this property is named `imagePath` in `datapackage.json`. It should be named `image` (to follow Frictionless spec).
- [ ] Is it possible to display the image on the resource page (cf. DwC-A datasets)?
