### ISSUE TITLE
Camtrap DP: add metadata by uploading `datapackage.json`

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#2001]
In addition to starting a resource with data (see #1993), it should be possible for the user to add metadata by uploading the `datapackage.json` file. This is supported in the interface:

<img width="882" alt="Screenshot 2023-04-21 at 11 30 36" src="https://user-images.githubusercontent.com/600993/233601356-1c8d085f-6bfd-44fc-b6ce-8d0482c37ac6.png">

But when I try it, I get:

> Failed to replace the metadata file!

**Comment by mike-podolskiy90** [comment]
Thanks Peter
It's supposed to be working, I used it before I started implementing ColDP. I'll check

**Comment by peterdesmet** [comment]
FYI: it has never worked for me, even in earlier tests.

**Comment by mike-podolskiy90** [comment]
That's odd actually. We need to figure it out, because I've just downloaded metadata from your resource at ipt3.gbif-uat.org, created new resource and successfully uploaded metadata. What is your file you're trying to upload please?

**Comment by peterdesmet** [comment]
The file I want to upload is https://github.com/tdwg/camtrap-dp/blob/main/example/datapackage.json. The issue might be caused by the `$defs` variable, will test.

**Comment by peterdesmet** [comment]
Update: the `$defs` is a property of the `profile`, not the `datapackage.json`, so that should not be the issue. Currently I still get an error when trying to upload https://github.com/tdwg/camtrap-dp/blob/main/example/datapackage.json

**Comment by mike-podolskiy90** [comment]
Thanks Peter. I guess that problem can be in the resources. I'll exclude them from de-serialization and validation, they'll be anyway overridden upon publication.

**Comment by peterdesmet** [comment]
Tested and it works for both an IPT generated datapackage.json and an external one. 🎉 

It is unclear to me what the `validate` checkbox does, because even an invalid datapackage makes it through. Personally, I would remove the checkbox.

<img width="489" alt="Screenshot 2023-04-27 at 16 07 50" src="https://user-images.githubusercontent.com/600993/234887686-a5bfe934-65ff-4b77-b7a5-400e8f17140b.png">

**Comment by mike-podolskiy90** [comment]
We probably miss something in validation. It does work actually - just tested it by removing `project` field. What is your file please?

**Comment by peterdesmet** [comment]
I notice that these contributor properties are set to an empty string by the IPT. It would be better to consider them `NULL` and not include them in the datapackage. Note: I have not tested if this only occurs when uploading datapackage.json.

```
{
    "title" : "Research Institute for Nature and Forest (INBO)",
    "path" : "https://inbo.be",
    "email" : "",
    "organization" : "",
    "role" : "rightsHolder"
  }
```

**Comment by peterdesmet** [comment]
Items that will fail upload:

- [ ] contributor has `role` that is not in enum
- [ ] project has `captureMethod` role that is not in enum
- [ ] `description` is an array rather than a string

I think that can be frustrating to debug for users. I'm wondering if it wouldn't be better to not set those properties (e.g. collaborator without role, empty description). If they are required, the user will be warned to populate them in the editor.

**Comment by mike-podolskiy90** [comment]
Thanks Peter. 
I'm concerned about `captureMethod`. Let's say we have a couple of capture methods and one of them is invalid. We can skip an invalid value but then we end up with a valid result object without one of the values

**Comment by peterdesmet** [comment]
For `captureMethod` I would indeed not upload any of the values if one of them is not in the enum.

I think the upload should be a bit lenient when uploading `datapackage.json`, i.e. set properties to NULL rather than outright reject the upload. This makes it easier for users to debug, because the editor will indicate if a required property is missing. They can correct this directly in the editor or in their source file and upload again.

And here the `validate` checkbox comes in handy: if that one is checked, you could refuse uploading an invalid data package. This helps users once they have done some debugging and want to be sure all is ok.

**Comment by peterdesmet** [comment]
- [x] Uploading data with missing properties as described in https://github.com/gbif/ipt/issues/2001#issuecomment-1525867551 is now possible
- [x] contributor.path is set to NULL
- [ ] contributor.email is still `""`
- [ ] contributor.organization is still `""`
- [ ] bibliographicCitation is still `""`
- [ ] project.path is still `""`
- [ ] taxon.kingdom, and other ranks are still `""`

**Comment by mike-podolskiy90** [comment]
@peterdesmet In what cases those fields are empty please?

**Comment by peterdesmet** [comment]
Those fields are empty in the IPT created `datapackage.json` when the user did not set them in the metadata editor.

**Comment by mike-podolskiy90** [comment]
I've excluded those empty/null values from serialization, should be fine now

**Comment by peterdesmet** [comment]
@mike-podolskiy90 indeed, there are no more `""` values, except for `image`. Can you remove that one too?

**Comment by peterdesmet** [comment]
Confirmed fixed, no empty `""` or `[]` remain. Those properties are correctly not included in `datapackage.json`.
