### ISSUE TITLE
Cannot edit/remove mappings after creating resource from file

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#2004]
@mike-podolskiy90 I created a resource from this Camtrap DP ([agouti-resource.zip](https://github.com/gbif/ipt/files/11352502/agouti-resource.zip)). It is not created by the IPT and contains missing fields, incorrectly named fields, missing relations, etc. ... The IPT warns for those, but the resource is apparently good enough to pass uploading:

<img width="1131" alt="Screenshot 2023-04-28 at 12 22 32" src="https://user-images.githubusercontent.com/600993/235122712-1574fb92-700f-49f1-a41f-14792722a928.png">

1. The particular yellow messages are odd, because it mentions terms that _do_ exist in event-observations

2. The mapping of the resources shows 0 terms:

<img width="872" alt="Screenshot 2023-04-28 at 12 23 24" src="https://user-images.githubusercontent.com/600993/235122818-62fa58b7-200a-47f1-a7f7-c552e7dda13a.png">

3. When I want to open one of the mappings to edit, I get a `Automapped 16 columns ...` message, but I remain on the resource page:

<img width="1134" alt="Screenshot 2023-04-28 at 12 24 02" src="https://user-images.githubusercontent.com/600993/235122953-a73c2a36-85da-441c-99cb-51ed1b9b83b2.png">

4. When I want to remove one of the mappings to start over, I get the same `Automapped 16 columns ...` message (on the resource page), and the mapping is not removed.

It seems something is blocking accessing or editing the mappings. It is still possible to remove a source (and thus its mapping).

---

An important question is whether we want to support creating resources from (invalid) packages or if users should do this process in steps: create, add sources, add mappings, upload `datapackage.json` ...

**Comment by mike-podolskiy90** [comment]
Thanks Peter. Looking into it

**Comment by mike-podolskiy90** [comment]
That was due to small internal issues with automapping, fixed now.

**Comment by peterdesmet** [comment]
Confirmed fixed.
