### ISSUE TITLE
create color blind friendly palette

### ISSUE THREAD

**Issue by sformel-usgs** [gbif/ipt#2006]
I'm curious if the default colors in the IPT (e.g. GBIF green) are colorblind friendly? My immediate use case is that we were asked to ensure that the two IPTs managed by USGS are accessible with respect to color blindness, in compliance with government policy. However, it seems like a good thing to be mindful of, or document if it has already been discussed.  

Here are a few things I found while I was searching:
1.  I couldn't find a way to learn the values of the default colors myself (RGB or hexadecimal) through the IPT, so I couldn't confirm it on my own. 
1. The [IPT manual](https://ipt.gbif.org/manual/en/ipt/latest/administration#ui-management) doesn't explicitly mention it.
1. I only found [one issue in github](https://github.com/gbif/ipt/issues/414) that seemed tangentially related, but isn't asking the same question.

**Comment by MattBlissett** [comment]
Hi,

The colours should be chosen from the GBIF palette here: https://www.gbif.org/logos#_gbif-colours

I don't think we rely on colours for meaning, they are supplemental to text labels, so the problem would be low-contrast combinations.  I don't see a problem using an [online tester](https://www.color-blindness.com/coblis-color-blindness-simulator/), but maybe @kcopas knows if colour blindness was taken into account when creating the palette.

**Comment by peterdesmet** [comment]
Note that it is also possible to customize the colours of an IPT (in Administration > UI Management). We did so for our IPT to align it with the brand colours of our institute: https://ipt.inbo.be/resource?r=hg_oostende

**Comment by mike-podolskiy90** [comment]
@sformel-usgs Thank your time testing this.
Let's keep it open for now

**Comment by mike-podolskiy90** [comment]
@sformel-usgs Just in case, https://ipt-obis.gbif.us/ is 2.7.1 which is not the most recent version (which is 2.7.3). Since then, we changed type/subtype badges and visibility indicators.
The most recent snapshot version is deployed here https://ipt.gbif-uat.org/

**Comment by MattBlissett** [comment]
I've upgraded ipt-obis.gbif.us and ipt.gbif.us, they were missing from the upgrade script.

**Comment by albenson-usgs** [comment]
Thank you Matt!

**Comment by sformel-usgs** [comment]
I just noticed the changes, thanks for doing so! I'll do another review with ANDI when I have a spare moment.

**Comment by mike-podolskiy90** [comment]
@sformel-usgs Thank you very much for testing the IPT and providing suggestions to improve IPT accessibility.
I do like those more contrast colors but aren't they a little too dark?
@javiesgm Would like to hear from you

**Comment by sformel-usgs** [comment]
They might be a little dark.  I was just reporting what the ANDI tool was automatically suggesting.

**Comment by mike-podolskiy90** [comment]
@sformel-usgs  I've adjusted the colors and added title to languages.
https://ipt.gbif-uat.org/

**Comment by sformel-usgs** [comment]
Excellent!  There are two more contrast flags.  I must have overlooked them before. 

1. The text at the top describing the number of available resources.  The ANDI tool suggests changing it from #61a861 to #3e853e
2. The RSS feed link at the bottom.  Suggested change from #4ba2ce to #277eaa.

**Comment by mike-podolskiy90** [comment]
@sformel-usgs Thanks Stephen. Those are configurable in the admin menu (primary and link colors) so one can set whatever color they want.
