### ISSUE TITLE
Show ColDP metadata.yaml problem if upload fails

### ISSUE THREAD

**Issue by mdoering** [gbif/ipt#2011]
The metadata.yaml taken from Donalds [archive](https://github.com/gbif/ipt/files/11380633/dataset-2207.zip) results in:

> Failed to replace the metadata file!

**Comment by mdoering** [comment]
It is because the metadata file indeed wrongly contains a list for the contact instead of a single object.
Would be good to log the problem so it can be fixed easier.

**Comment by mike-podolskiy90** [comment]
@mdoering Would be an error log enough or we should also display an error message on UI? It might be too technical for UI

**Comment by mike-podolskiy90** [comment]
![Image](https://github.com/user-attachments/assets/64d3721d-cff5-4fc6-853f-027f911ae3bc)

**Comment by mike-podolskiy90** [comment]
We already log the error, actually
