### ISSUE TITLE
ColDP value translation "vocabulary required"

### ISSUE THREAD

**Issue by mdoering** [gbif/ipt#2013]
The links exist, but the vocabulary and values are not loaded apparently:
https://ipt3.gbif-uat.org/manage/dataPackageFieldTranslationReload.do?r=donaldscoldp&field=code&mid=0

**Comment by mdoering** [comment]
Actually one can enter translations and it works. Just the initial screen with "Property code. Vocabulary required" looks like a vocabulary is missing. I did not understand what to do on first glance.

**Comment by mike-podolskiy90** [comment]
Thanks Markus. I guess, we can just remove that
