### ISSUE TITLE
ColDP registration fails due to license

### ISSUE THREAD

**Issue by mdoering** [gbif/ipt#2014]
>The resource cannot be registered because the current published version was not assigned one of the licences that GBIF supports. To enable registration, assign one of these licences and publish a new version.

The ColDP metadata has it as CCO though. I assume its not understood by the IPT?
Does the registry even support ColDP endpoints?

**Comment by peterdesmet** [comment]
@mdoering what literal value is ColDP using for `CC0`? For Camtrap DP we opted to follow frictionless and use the [Open Definition license ID](http://licenses.opendefinition.org/) to refer to licenses. These are now understood by the IPT. Example:

```json
"licenses": [
  {
    "name": "CC0-1.0"
  }
]
```

**Comment by mdoering** [comment]
It is basically the same, but without a version: 
`cc0`, `cc-by`, `cc-by-nc`, etc.

**Comment by mdoering** [comment]
I guess that's not impossible. Though I always wondered what to do with the versioning. Do we really want 4 different ccby licenses and how do they relate?

**Comment by peterdesmet** [comment]
While the intent might be the same, license conditions can change slightly between licenses (e.g. [4.0 vs 3.0 no longer requires to cite the title](https://wiki.creativecommons.org/wiki/License_Versions#Detailed_attribution_comparison_chart)). In the IPT, I think it's fine to only offer the latest license (4.0). If a ColDP is uploaded with 3.0 then it won't be recognized and the user has to reassign it, which I don't think is a bad thing.

**Comment by mdoering** [comment]
Yes, that would be fine. And clearly there are subtle differences, otherwise you wouldn't version them. But what would GBIF or other consumers really be doing with these various versions? Would you not treat them the same anyways when trying to understand what you can do with them? As far as I am ware GBIF maps them all to the latest v4 anyways.
