### ISSUE TITLE
IPT LAC warning messages

### ISSUE THREAD

**Issue by leo-buitrago** [gbif/ipt#2015]
Hi @mike-podolskiy90 ,

Could you help me to check why these warning messages are displaying on the [LAC IPT](https://cloud.gbif.org/lac/)?

Apparently, this is affecting the publishing process on this IPT.

![Screen Shot 2023-05-04 at 2 04 27 PM](https://user-images.githubusercontent.com/61566113/236311367-d46b22a2-5c1d-4404-9034-24ecd91a59af.png)

**Comment by ManonGros** [comment]
There is a similar issue on another IPT from one of our Nodes. I looked at the log and it suggests a firewall issue. It looks like it might be more generic. Maybe a problem with the registry?

**Comment by mike-podolskiy90** [comment]
Hi @leo-buitrago 
It's nothing serious, all is fine, we just need to restart tomcat. We'll be ready shortly
