### ISSUE TITLE
Columns shown in quotes

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#2016]
1. Upload source data
2. Set Field Quotes to `"`
3. Go to the mapping page
4. Open the dropdown to map a column
5. The first column is shown in quotes (unexpected), the rest is not:

<img width="273" alt="Screenshot 2023-05-05 at 11 19 31" src="https://user-images.githubusercontent.com/600993/236424358-f66d38aa-9723-4761-a47f-9f2d629c0b55.png">

**Comment by mike-podolskiy90** [comment]
Thanks Peter. It happened because the file has a byte order mark (BOM). We need to discard it when reading the file

**Comment by peterdesmet** [comment]
It looks like this has been resolved?

**Comment by mike-podolskiy90** [comment]
No, I haven't deployed anything related to this. This is a quite rare case though, for regular files with UTF-8 encoding without BOM it works just fine

**Comment by peterdesmet** [comment]
Then I take we can close this issue. Your call.

**Comment by MattBlissett** [comment]
It is rare on Mac and Linux, which assume Unicode, but some Microsoft Windows tools used to add BOMs.  Maybe Excel, maybe Notepad.  Do you have a Windows computer to hand which you can check?

**Comment by peterdesmet** [comment]
No, I do not have a Windows computer.
