### ISSUE TITLE
Cannot set value for boolean field in mapping

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#2017]
## Issue

1. I uploaded media data that is missing the required field `filePublic`
2. This field is a boolean, but presents a text box to set a single value for all:

    <img width="866" alt="Screenshot 2023-05-05 at 11 16 49" src="https://user-images.githubusercontent.com/600993/236425189-9ad03997-5f81-4633-951f-54d2a7de3e39.png">

3. Writing `TRUE` will fail validation when publishing

## Solution

For boolean fields a dropdown should be presented, with values:

```
(empty = unmapped)
TRUE
FALSE
```

Alternatively, radio buttons could be shown, but users should always have the option to deselect their choice (i.e. empty), which is not straightforward with radio buttons.

**Comment by mike-podolskiy90** [comment]
Thanks. I've made a dropdown for boolean values and corrected validation

**Comment by peterdesmet** [comment]
Great. Minor suggestion: values are currently listed as `false`, `true`. I think the order `true`, `false` would be more intuitive.
