### ISSUE TITLE
Associated Organizations registry problems - IPT LAC

### ISSUE THREAD

**Issue by leo-buitrago** [gbif/ipt#2026]
Hi @mike-podolskiy90 ,

I I have problems adding new organizations to the [LAC IPT](https://cloud.gbif.org/lac/). Specifically, I am trying to add this new organization https://www.gbif.org/publisher/ffa83b77-6b8c-4c35-807c-d56e1fce7ae3, using the token of the organization https://registry.gbif.org/organization/ffa83b77-6b8c-4c35-807c-d56e1fce7ae3. When I click on the "Save" button the IPT reload but nothing happens. I tried a lot of times but I got the same result every time.

![Screen Shot 2023-05-11 at 2 09 59 PM](https://github.com/gbif/ipt/assets/61566113/5b544a88-ca23-410e-bdc9-5139d70ea2a6)

**Comment by mike-podolskiy90** [comment]
Thank you @leo-buitrago 
This is the same issue #1996
