### ISSUE TITLE
More Excel file related crashes

### ISSUE THREAD

**Issue by MattBlissett** [gbif/ipt#2030]
GBIF-hosted IPTs crashed twice this week from Excel files, the second time with the file `ipt-data-asia/resources/liliopsida/sources/liliopsida_published.xls`, which LibreOffice also reports a problem with ("too many columns").

I think the solution might be the streaming reader, e.g. https://github.com/pjfanning/excel-streaming-reader or see https://poi.apache.org/components/spreadsheet/limitations.html

Although the file in this case is not large, just 8MB, the formatting seems to be applied to the whole spreadsheet, perhaps 16 billion cells.

**Comment by MattBlissett** [comment]
Unless it's been changed, ipt-data-asia/resources/liliopsida/sources/liliopsida_published.xls is one example.

**Comment by mike-podolskiy90** [comment]
This seems fine to me now, but I'd like someone else to test it
