### ISSUE TITLE
IPT 3 - extension doesn't show in drop down mapping

### ISSUE THREAD

**Issue by ManonGros** [gbif/ipt#2031]
I installed the resource relationship extension in the https://ipt3.gbif-uat.org but I don't find it in the drop down mapping interface:
<img width="531" alt="Screenshot 2023-05-23 at 10 50 12" src="https://github.com/gbif/ipt/assets/7677271/c26857f0-93cd-48c9-a27d-373f9af1854e">

**Comment by mike-podolskiy90** [comment]
Thanks Marie.
Darwin Core Resource Relationship has keywords `dwc:Occurrence dwc:Event dwc:Taxon` but does not have `dwc:MaterialEntity`. IPT deems extension unsuitable and exclude it. 
All extensions without keywords should be present.

**Comment by ManonGros** [comment]
can the keyword be added? I think we need the extension for the workshop next week

**Comment by mike-podolskiy90** [comment]
We need to issue a new version of the extension I guess. Or maybe change that logic somehow.
@MattBlissett @timrobertson100

**Comment by timrobertson100** [comment]
https://github.com/gbif/rs.gbif.org/issues/110

Is what needs to be done I think?

**Comment by timrobertson100** [comment]
Following a discussion in the office, @mike-podolskiy90 will enable all extensions suitable for Occurrence to be suitable for material as well in the IPT3 (to be revisited when/if the MaterialEntity core work nears production)

**Comment by mike-podolskiy90** [comment]
Thanks Tim. I'll deploy it shortly
