### ISSUE TITLE
Make it possible to change a registered metadata resource to core resources

### ISSUE THREAD

**Issue by CecSve** [gbif/ipt#2034]
In [the technical support hour for nodes in April](https://discourse.gbif.org/t/april-technical-support-hour-for-gbif-nodes/3881), a node was inquiring whether it would be possible to change a registered metadata-only dataset to for example occurrence or sampling event core. Currently it is not possible, but it would be great if the possibility could be added in the future, since projects occasionally use metadata-only datasets as placeholders (for example https://www.gbif.org/dataset/d882e391-10f9-43f6-b0f9-29636396ba9e) and nodes are interested in the option.

**Comment by mike-podolskiy90** [comment]
Thanks Cecilie

**Comment by albenson-usgs** [comment]
Yes this would be a nice enhancement from the US node perspective.

**Comment by mike-podolskiy90** [comment]
The most recent snapshot version allows doing that ([ipt.gbif-uat.org](https://ipt.gbif-uat.org/))
We don't disable type in the basic metadata for metadata resources, one just need to change resource type to occurrence.
