### ISSUE TITLE
Admin Password in FAQ is incorrect

### ISSUE THREAD

**Issue by rockliffelewis** [gbif/ipt#2035]
I was trying to reset the admin password for my IPT instance, and I followed the example on the FAQ which suggests that `$2a$12$sI48l9ZdW8pvxbxE8GygZe5CXU/dFFj1UrCSP0vEh7rkk8csMPTt6` is the bcrypt hash for `Ga_1bxiedrvNHSyK `

I checked this using another implementation of bcrypt, and the compare is failing.

I ended up generating my own bcrypt hash, putting it into the `config/users.xml` which allowed me to login.

**Comment by mike-podolskiy90** [comment]
Thank you for reporting the issue. I've updated FAQ manual.
