### ISSUE TITLE
Update warning message for Data Packages

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#2037]
When publishing a Data Package that has no mappings, the IPT issues a warning:

> Source data or Darwin Core mappings missing. No data archive generated. Please note that this is perfectly normal if you are publishing a metadata-only resource.

I think this should at least be updated to:

> Source data or **Data** mappings missing. No data archive generated. Please note that this is perfectly normal if you are publishing a metadata-only resource.

Note: "Data Mappings" is name we gave the heading. The last sentence could maybe be removed too.

**Comment by mike-podolskiy90** [comment]
Thanks Peter.
I think we have to forbid publishing datapackage resources without mappings.

**Comment by mike-podolskiy90** [comment]
Deployed

**Comment by peterdesmet** [comment]
Confirmed fixed.
1. When trying to publish without any resources, you are stopped and get:
> Before you can publish a resource you must provide data mappings.
3. When trying to publish with some but not all resources, the publication starts but fails with:
> Publishing version #4.0 of resource test failed: Archive generation for resource test failed: All required schemas must be present: [deployments, media, observations]
