### ISSUE TITLE
Make title and description required for Camtrap DP

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#2038]
The Camtrap DP specs don't require a `title` and `description`. As a result, datasets can be published without those properties in the IPT. I assume those properties are expected by the GBIF registry? Similar to `licenses` (which are not required by Camtrap DP but are by the IPT), it might be good to make `title` and `description` required in the IPT?

Note that `name`, `id`, `created`, and `version` are automatically set by the IPT

**Comment by mike-podolskiy90** [comment]
Deployed

**Comment by peterdesmet** [comment]
Confirmed fixed.
