### ISSUE TITLE
Uploading `datapackage.json` with `version` affects versioning

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#2039]
It looks the the versioning of Camtrap DP publications gets messed up if you upload a `datapackage.json` that specifies a version. I haven't been able to trace down the exact issue, but when it resulted in publishing version `2.0` and `3.0` multiple times. I think the `version` property should be completely ignored when uploading a `datapackage.json`, so that the IPT can have full control over the versioning.

**Comment by mike-podolskiy90** [comment]
Thanks for the suggestion. Yes, I guess it makes sense to preserve versioning. Deployed

**Comment by peterdesmet** [comment]
Confirmed that uploading a `datapackage.json` with `"version": "1.0"` does not break the version chain (it continued nicely from 3.0 to 4.0).
