### ISSUE TITLE
Mapping interface can be confusing

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#2041]
When clicking `Add` to create a mapping between source data and a Table Schema for a Data Pacakge, the following screen is presented:

![Mapping-Source-Data](https://github.com/gbif/ipt/assets/600993/b2f8cd70-d210-40e0-b4df-e7e72bcd2979)

When I read `File` I always assume that is my source file, not the output file. 😅 I also noticed that Darwin Core Archives use a two step approach (at least in IPT 2.7.3), with a modal and then a selection screen. There also, it is a bit confusing what is presented first (output or input), especially since the title mentions "Mapping **Source** Data". I can only tell these are output files, because the dropdown mentions `Darwin Core`:

<img width="508" alt="Screenshot 2023-06-02 at 10 45 55" src="https://github.com/gbif/ipt/assets/600993/6a4a9cff-0ad5-4868-b1f6-3626db432b1a">

## Suggestion

I think the single screen with two dropdowns (as used for the Data Packages) is more efficient, but the first dropdown should get a different label, incorporating the **resource type shortname**:

- Darwin Core Archive
- Camtrap DP
- Material Entity

![Mapping-Source-Data (1)](https://github.com/gbif/ipt/assets/600993/cc247cc2-70f7-42d8-b123-aa139a3cb872)

**Comment by mike-podolskiy90** [comment]
Thanks Peter. Deployed

**Comment by peterdesmet** [comment]
Confirmed fixed, much more intuitive.

<img width="835" alt="Screenshot 2023-06-07 at 09 08 35" src="https://github.com/gbif/ipt/assets/600993/73ad8c26-531b-4616-9182-85063237f3a4">

The sentence "Before you can start mapping concepts, please select your source." sounds a bit odd (since you select a schema and a source), but can likely remain.
