### ISSUE TITLE
Data Package Profile updates require update of IPT

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#2043]
When a Data Package schema (Camtrap DP, Col DP, etc.) releases a new version, the workflow is as follows:

1. The Data Package **Profile** and **Table Schemas** get deposited on rs.gbif.org
2. IPT admins have the choice to update their local **Table Schemas** to that version, in `/admin/schemas.do`
3. Any updates in the **Profile** cannot be updated by the IPT admins. It often requires an update of the metadata editor and thus an update of the IPT itself.

This has two downsides:

- IPTs need to be updated to make use of a new Profile
- The version of the Profile can be out of sync with the version of the Table Schemas.

We should think how to tackle this.

---

As mentioned by @mike-podolskiy90 at https://github.com/gbif/ipt/issues/2036#issuecomment-1578075020:

> I have concerns about how this will work in the future.
> 
> In essence, we have two "entities" - schemas and a metadata profile. Schemas can be updated through the interface and saved in xml. On the other hand, the profile and metadata cannot be updated automatically (these are java classes that need to be changed manually in case of any metadata change and therefore a new version of IPT must be released).
> 
> We need to think about how we can deal with this.

And @peterdesmet at https://github.com/gbif/ipt/issues/2036#issuecomment-1578115983

> Yeah, that part is not ideal. Automatically building a metadata editor from the specs does not seem realistic either ...

**Comment by mike-podolskiy90** [comment]
This has to be implemented for the release to avoid issues.
As I currently see it - IPT should allow update schema if schema is marked as compatible. If the latest version is not compatible - IPT display that to the admin.

Types of changes that can be in the package or schema:

1. Adding new file(s)
2. Remove file(s)
3. File(s) are re-organised or renamed
4. New property or properties in the existing file(s)
5. Remove property or properties from the existing file(s)
6. Property type change in the existing file(s)
7. Metadata change

@peterdesmet What types of changes above are breakable (non-compatible) you think? Did I miss something?

**Comment by mike-podolskiy90** [comment]
Or we can just forbid (temporarily?) updating/deleting schemas. One can only update them with the IPT itself

**Comment by mike-podolskiy90** [comment]
> That sounds like a good approach, but it will probably be hard to detect changes that are breaking to the IPT. You won't be able to detect from the semantic versioning alone (e.g. 1.1 could introduce a new metadata field, which requires an IPT update). It also puts a burden on admins to keep both in sync.

Since we store all schemas in the rs.gbif.org we can add an additional field there that will indicate supported IPT versions. Something like:
```
...
supportedIptVersions: "[3.0,3.1]"
...
```
or
```
...
supportedIptVersions: {
    minimum: "3.0",
    maximum: "3.1"
}
...
```

**Comment by mike-podolskiy90** [comment]
If disabling schema updating/deletion is fine I guess we should do that. It'd be easiest and safest solution for now, and if we want to implement schema update/delete functionality in the future we can easily do so.

**Comment by mike-podolskiy90** [comment]
I've deployed first version to ipt3.gbif-uat.org
Seems fine for now. How it works:

1. All supported packages and its versions are now fixed to the IPT. IPT install them on setup stage
2. Update/Delete is no longer available and removed from the UI (I keep backend though if we want it in the future)
3. If package schema is outdated, warning message is displayed

**Comment by peterdesmet** [comment]
> 3. If package schema is outdated, warning message is displayed

Can you explain in what instance and where this would happen?

**Comment by mike-podolskiy90** [comment]
In admin/schemas. If current (supported) version of the package in IPT is not the latest one

**Comment by mike-podolskiy90** [comment]
Correct. If those schemas are published to rs.gbif.org
