### ISSUE TITLE
Differentiate published from pending version

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#2044]
Under the section publication, I find it difficult to differentiate between the published and pending version, since the text to discern the difference is quite small:

<img width="865" alt="Screenshot 2023-06-07 at 09 16 52" src="https://github.com/gbif/ipt/assets/600993/e7b6fd56-a14f-4e89-b805-f513ed866e97">

Can I suggest colours to differentiate the two:

<img width="871" alt="Screenshot 2023-06-07 at 09 23 15" src="https://github.com/gbif/ipt/assets/600993/2b0b2625-0ec6-4d68-b6fa-65cb4a4bc977">

**Comment by mike-podolskiy90** [comment]
Thank you for the suggestion. It's confusing sometimes indeed.
@javiesgm what do you think please?

**Comment by javiesgm** [comment]
I agree, It is difficult to differentiate them. 
I had already tried some options: 

https://xd.adobe.com/view/931c4ba3-dc73-4df9-9956-ebfd26dfe277-c64f/ 

@mike-podolskiy90 I'm inclining towards using a colored chip for alerts. What do you think?

**Comment by peterdesmet** [comment]
Nice, I prefer the top version (gives less weight to `public` visibility):

<img width="988" alt="Screenshot 2023-06-08 at 09 24 45" src="https://github.com/gbif/ipt/assets/600993/39ce7487-0bd2-4256-a687-b5dae8e601ee">

**Comment by mike-podolskiy90** [comment]
Visibility looks like out of place. I think like this it would be better:
![Screenshot 2023-09-22 at 18 16 48](https://github.com/gbif/ipt/assets/24795387/e2e943c1-2ed3-4633-9005-2b79bbae30b1)

**Comment by javiesgm** [comment]
I'm sorry for not getting back to you sooner, but I couldn't do it on the weekend. It still looks confusing. It could work if the pending ship and the red circle on the version 1.16 example were yellow. As it is, I think it is still confusing.

**Comment by mike-podolskiy90** [comment]
Thanks @javiesgm and sorry for closing this a bit too fast. I've just released I've commented on Friday night.

Tbh I don't understand this issue with two versions. It always has been the published one to the left and the pending one to the right. If there is only one - it means resource was never published.

I guess we can make it yellow but yellow is normally a warning color in the IPT indicating something is not quite right. The next version is absolutely fine it's just not been released yet.

**Comment by mike-podolskiy90** [comment]
I suggest one of these:
![Screenshot 2023-09-25 at 11 03 40](https://github.com/gbif/ipt/assets/24795387/43b1f6b9-0778-4e87-8c48-2ab88c3af99c)
![Screenshot 2023-09-25 at 11 03 29](https://github.com/gbif/ipt/assets/24795387/758f3007-c8b6-428a-a3d5-5ac0a805dfa5)

We may also introduce a new color instead of the primary green for the published version.

**Comment by mike-podolskiy90** [comment]
Thanks Javier
Circle represents visibility (deleted - red, private - grey unfilled, public - green unfilled, registered - green filled)

**Comment by javiesgm** [comment]
Oh, nice. Does leaving the pending version grey/unfilled (including the chip and the licence) make sense?

**Comment by mike-podolskiy90** [comment]
Yes, it does. And the current one green/unfilled?

**Comment by javiesgm** [comment]
Well, it makes sense to me that green/filled (circles and chips) should be the most public (is it registered the most public?), so if that is the case, yes.

**Comment by mike-podolskiy90** [comment]
Registered is "more public" because it's registered with GBIF and available via GBIF portal and/or registry.
