### ISSUE TITLE
Publication failed for large Camtrap DP dataset on IPT3

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#2045]
I tried to publish a sizeable Camtrap DP dataset on IPT3 (`mica-full`) with:

- 1,516 deployments
- 3,698,903 media
- 179,334 observations

But got this error:

> Publishing version #1.0 of resource mica-full failed: Archive generation for resource mica-full failed: Java heap space

Is this a limit on the IPT3 server? The publication log seems to indicate that publication was successful:

```
Data package generation started for version #1.0
Metadata added
Start writing data file for deployments
No lines were skipped due to errors for mapping Camera Trap Data Package (Camtrap DP) in source deployments
No lines were skipped due to errors for mapping Camera Trap Data Package (Camtrap DP) in source deployments
No lines with fewer columns than mapped for mapping Camera Trap Data Package (Camtrap DP) in source deployments
All lines match the filter criteria for mapping Camera Trap Data Package (Camtrap DP) in source deployments
Data file written for deployments with 1516 records and 23 columns
Start writing data file for media
No lines were skipped due to errors for mapping Camera Trap Data Package (Camtrap DP) in source media
No lines were skipped due to errors for mapping Camera Trap Data Package (Camtrap DP) in source media
No lines with fewer columns than mapped for mapping Camera Trap Data Package (Camtrap DP) in source media
All lines match the filter criteria for mapping Camera Trap Data Package (Camtrap DP) in source media
Data file written for media with 3698903 records and 11 columns
Start writing data file for observations
No lines were skipped due to errors for mapping Camera Trap Data Package (Camtrap DP) in source observations
No lines were skipped due to errors for mapping Camera Trap Data Package (Camtrap DP) in source observations
No lines with fewer columns than mapped for mapping Camera Trap Data Package (Camtrap DP) in source observations
All lines match the filter criteria for mapping Camera Trap Data Package (Camtrap DP) in source observations
Data file written for observations with 179334 records and 29 columns
All data files completed
```

**Comment by peterdesmet** [comment]
The data are uploaded at https://ipt3.gbif-uat.org/manage/resource?r=mica-full

**Comment by mike-podolskiy90** [comment]
There are issues with the data:
- media.captureMethod - value [motion detection] violates enum constraint
- observation.lifeStage - value [unknown] violates enum constraint
- observation.sex - value [unknown] violates enum constraint
- observation.eventStart - value [+02:00] violates ISO 8601
- observation.eventEnd - value [+02:00] violates ISO 8601

**Comment by mike-podolskiy90** [comment]
By fixing those issues above I managed to publish the resource locally. We need to analyze how much memory is needed for publication

**Comment by mike-podolskiy90** [comment]
I've deployed an updated version. But it fails with the following error:
```
Publishing version #1.0 of resource mica-full failed: Archive generation for resource mica-full failed: java.lang.IllegalStateException: IOException reading next record: java.io.IOException: (line 79273) invalid char between encapsulated token and delimiter
```

**Comment by mike-podolskiy90** [comment]
@peterdesmet It's now possible to publish large packages

**Comment by peterdesmet** [comment]
Excellent! I assume you have tested this with the `mica-full` dataset and that this issue can be closed?

**Comment by mike-podolskiy90** [comment]
Yes. You can try it yourself. I've changed some mappings though (see comments above) to make publication work, but haven't changed source files.

**Comment by peterdesmet** [comment]
I'll test it once we have updated our export format in Agouti to Camtrap DP 1.0-rc.1 (so I don't need to convert it manually).
