### ISSUE TITLE
Remove GBIF Analytics

### ISSUE THREAD

**Issue by MattBlissett** [gbif/ipt#2049]
We no longer use or need the "GBIF Analytics" feature, which adds tracking with Google Analytics.  The option is enable in the Administration screen.

It should be removed for the next release.

**Comment by mike-podolskiy90** [comment]
Thanks Matt. Should we just remove the input field "Your Google Analytics Key" please?

**Comment by MattBlissett** [comment]
Sorry, no, the intention here is to remove the **GBIF** analytics feature.  GBIF_ANALYTICS / gbif.analytics etc.

The Google analytics in #2050 needs to be updated, and the configuration key should be retained for people continuing to use Google analytics.

**Comment by mike-podolskiy90** [comment]
Oh, sorry. I'll fix

**Comment by mike-podolskiy90** [comment]
@MattBlissett Done
