### ISSUE TITLE
allow publishing organization to be changed after the dataset is published

### ISSUE THREAD

**Issue by ymgan** [gbif/ipt#2057]
Hello,

We would like to request for this feature as we have some datasets with old publishing organizations that are no longer in use. We would like to transfer the datasets from the old publishing organizations to the ones that we are currently using but we cannot change that at the web interface.

Thanks a lot!

@Antonarctica

**Comment by MattBlissett** [comment]
There are workarounds here: https://ipt.gbif.org/manual/en/ipt/latest/faq#how-do-i-change-the-publishing-organization-of-my-resource-the-drop-down-on-the-basic-metadata-page-is-disabled

but it may be something we should integrate into the UI.

**Comment by abubelinha** [comment]
Would this affect occurrence gbifIDs or they could remain stable after such a change?

Thanks
@abubelinha

**Comment by muttcg** [comment]
@abubelinha
gbifIDs are a combination of datasetKey (UUID given by the registry) and occurrenceID, so that the publishing organization doesn't affect gbifIDs.

**Comment by ymgan** [comment]
@MattBlissett Thank you very much! It will be super helpful if it can be integrated into the UI, we will very much appreciate it!
@abubelinha Thank you for asking!
@muttcg Thank you for clarifying - good to know!

**Comment by mike-podolskiy90** [comment]
In new IPTs publishing organization can be directly changed at the overview page. I'll update the manual
