### ISSUE TITLE
setting a default network for a specific IPT instance

### ISSUE THREAD

**Issue by rubenpp7** [gbif/ipt#2058]
Hi, 

I manage the EurOBIS IPT instance (https://ipt.vliz.be/eurobis/). Since all the IPT resources in this IPT instance belong to the OBIS network, I would like to have an option to set the OBIS network in this IPT instance as a default for all the datasets, so I don't have to worry about it for each dataset.

Does something like that exist, and if not, could it be implemented?

Thank you

**Comment by mike-podolskiy90** [comment]
Thank you for contacting us @rubenpp7 
There is no such functionality in the IPT right now. It could be implemented if there is a demand for it

**Comment by ManonGros** [comment]
I can imagine that this functionality could be helpful for networks like OBIS, VertNet and DISSCo
What do you think?
@dbloom
@ymgan

**Comment by ymgan** [comment]
Thank you Marie!! Yes, it will be helpful for [SCAR Network](https://www.gbif.org/network/8534dd20-c368-4a1f-bdaf-e6b390710f89) too! All of the datasets that we published at our IPT are added to SCAR Network :)

**Comment by mike-podolskiy90** [comment]
I'm wondering where we can place this? Maybe Admin -> IPT settings?

**Comment by MattBlissett** [comment]
Perhaps Admin → GBIF Registration Options?

**Comment by mike-podolskiy90** [comment]
If we remove association with network should it be removed from all datasets as well?

**Comment by ymgan** [comment]
> If we remove association with network should it be removed from all datasets as well?

From data publisher's point of view, I do not think so. Take our node as example, we publish antarctic datasets to SCAR Network. If for some reasons I remove this default association later on from the IPT settings, it probably means that I will publish datasets for other network (that should NOT be SCAR Network), but the previous datasets I published should still belongs to SCAR Network. I hope that makes sense :) 

Thank you so much for putting this much thoughts in this, I really appreciate it!

**Comment by mike-podolskiy90** [comment]
Thanks for the quick reply! And vice versa, all existing datasets should be tied to the network once it's associated? Or only new ones?

**Comment by mike-podolskiy90** [comment]
Maybe IPT should ask users what they want (modal window)? Or checkbox "apply to existing datasets". For both cases adding\removing network
