### ISSUE TITLE
Geographical coverage: bounding box is not saved when using IPT in multiple languages

### ISSUE THREAD

**Issue by katiagbif** [gbif/ipt#2066]
We have identified an issue related to establishing geographical coverage when attempting to set the geographic bounding box for the area covered by the resource by either dragging the markers or filling in the fields. We have noticed that this problem arises when using IPT at least in Spanish, Portuguese, Russian, and French, as the selected area fails to display.

The **temporary workaround is to use IPT in English**.

We hope this information is helpful, and we trust that the issue will be resolved in future IPT updates : )

**Comment by mike-podolskiy90** [comment]
Thank you for reporting the issue.

**Comment by mike-podolskiy90** [comment]
There are template errors
