### ISSUE TITLE
IPT fail to publish resource after metadata upload

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/ipt#2070]
From @sformel-usgs

Resource https://ipt-obis.gbif.us/manage/resource?r=drytortugasreefvisualcensus2014

Here's what I did:

1. Resource was working fine.
2.  I uploaded the EML file
3. double checked that the metadata looked as expected (i.e. in the IPT: metadata > edit)
4. Returned to main editing screen and clicked publish
5. It allowed me to enter a comment, as expected.  However, after approving the comment, it returned to the resource screen instead of the publishing log screen.
6. After this, the [landing page says 'resource does not exist.'](https://ipt-obis.gbif.us/resource?r=drytortugasreefvisualcensus2014) However, you can still find the resource in the IPT, and still manage it as an editor.

**Comment by mike-podolskiy90** [comment]
I reverted the resource back to the 1.8. The issue is with the EML, missing `<citation>` in the gbif section (additionalMetadata -> metadata -> gbif -> citation). If you add it should be working fine. 
This is a bug, I'll fix it for the next version.

**Comment by sformel-usgs** [comment]
Thanks for taking the time to figure this out, it's very appreciated.
