### ISSUE TITLE
Minor: trim whitespace on login form

### ISSUE THREAD

**Issue by timrobertson100** [gbif/ipt#2071]
Discovered when helping a user struggling to log in.

Logging in with e.g. "trobertson@gbif.org " doesn't work. I suggest to `trim()` both username and password (presumably passwords can't have whitespace, right?) on login.

**Comment by MattBlissett** [comment]
A password can have whitespace, although it would be unusual for it to begin or end with a space.

**Comment by mike-podolskiy90** [comment]
Thanks Tim, I'll fix it up
