### ISSUE TITLE
Remove irrelevant DOI related stuff from IPT

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/ipt#2075]
- [x]  "If there have been scientifically significant changes to the resource since the last publication, you should cancel, assign this resource a new DOI, and then publish again" when publishing
- [x] "Reserve DOI" button - hide or remove

**Comment by mike-podolskiy90** [comment]
@ManonGros @MattBlissett

**Comment by mike-podolskiy90** [comment]
What else please? "Reverve DOI" icon-button as well?

**Comment by ManonGros** [comment]
yes, ideally the "reserve DOI" button should be hidden if there is no data cite account associated with the organisations.
