### ISSUE TITLE
Sort newest published instead of last published

### ISSUE THREAD

**Issue by albenson-usgs** [gbif/ipt#2077]
This is a small wish and perhaps it would be good to hear from other IPT managers if they have a similar wish. When I have just published a new resource in the IPT I usually want to find it immediately to get the link to GBIF. To do this I need to leave the manage view and go to the resource view (Home). I then need to find the newly published dataset so I usually click the Last Publication section on Home but it (understandably) puts the last published dataset at the top. I would rather this functionality put the newest publication at the top instead of the last. I'm almost never looking for the last published dataset and instead looking for the most recent publication.

**Comment by mike-podolskiy90** [comment]
Should we include a GBIF link at the publication page?

**Comment by albenson-usgs** [comment]
That could be another fix. I do have other times where I'm sorting (e.g. to figure out how many datasets we've published this fiscal year) and still I want it to be newest -> last but it's ok to click twice.

**Comment by mike-podolskiy90** [comment]
No problem at all, we can do both

**Comment by mike-podolskiy90** [comment]
Done. Can be tested here [UAT](https://ipt.gbif-uat.org/)
