### ISSUE TITLE
Toggle between view/edit resource

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#2079]
Related to #2077. When managing/publishing resource, I often find myself wanting to see the public resource page. It is possible to do so, but it's all the way down under `Publication > Version`:

<img width="726" alt="Screenshot 2023-08-21 at 12 22 08" src="https://github.com/gbif/ipt/assets/600993/470efc83-4a02-4da6-988f-cfcdcef2989c">

In the other direction (from a public resource page), it is a lot easier, since there is an `Edit` button at the top (for logged in users):

![public](https://github.com/gbif/ipt/assets/600993/3674a099-3347-4925-a246-2dae7fd1fd40)

I think it would be helpful to have a similar `View` button on the resource management page:

![manage](https://github.com/gbif/ipt/assets/600993/4d8c713e-e3e4-4015-ab94-5ef1da7543d8)

**Comment by mike-podolskiy90** [comment]
Thanks Peter for the suggestion. It makes sense adding that button I think
