### ISSUE TITLE
Delete version button does not show for resource managers

### ISSUE THREAD

**Issue by ktotsum** [gbif/ipt#2090]
Delete version button does not show for resource managers under "Manager with registration rights" role (admin can see it).
![image](https://github.com/gbif/ipt/assets/138471170/dec2c220-00f1-4797-bfab-3d3487663b7b)

Resource managers can delete versions of a dataset according to [the IPT manual](https://ipt.gbif.org/manual/en/ipt/latest/home#deletion-of-a-version).

IPT Version: 2.7.4

**Comment by mike-podolskiy90** [comment]
@ktotsum Thank you for spotting the issue
Yes, only admins can delete versions at the moment. I'll fix it.
