### ISSUE TITLE
Not possible to publish datasets with MaterialCitation of basisOfRecord (GBIF training IPT)

### ISSUE THREAD

**Issue by ManonGros** [gbif/ipt#2099]
This was reported by one of our Nodes. They can't publish this dataset: https://training-ipt-c.gbif.org/manage/resource.do?r=suelo2 because the basis of record is MaterialCitation. Could it be related to this issue? https://github.com/gbif/ipt/issues/1980

**Comment by mike-podolskiy90** [comment]
Thanks Marie.
It looks completely like that issue, let me see what's going there

**Comment by mike-podolskiy90** [comment]
There were two vocabularies loaded. I've removed the older one and it should be working now. 
I'm not sure why the IPT did not load the most recent version of the vocabulary though, need to figure that out

**Comment by ManonGros** [comment]
Hi @mike-podolskiy90 could you also fix the issue for that IPT? https://cloud.gbif.org/lac/ Thanks!

**Comment by mike-podolskiy90** [comment]
@ManonGros Done

**Comment by mike-podolskiy90** [comment]
There is a failing test, need to fix
