### ISSUE TITLE
Publishing version #1.3 of resource anopheles_stephensi_occurrence_1985_2019 failed: An unexpected error occurred while writing RTF file: null

### ISSUE THREAD

**Issue by pshimabukuro** [gbif/ipt#2105]
![A0C5E79C-8C07-41BC-B51B-06651FB20F6C](https://github.com/gbif/ipt/assets/122034060/2b2a8208-08bf-425e-be0f-613c16bd8b38)

**Comment by mike-podolskiy90** [comment]
Thanks. They're all related to issued with metadata inferring. I'll release fix shortly

**Comment by mike-podolskiy90** [comment]
Issues with metadata now fixed and released. That release can't be published though, there is another error:
`Each line must have a occurrenceID, and each occurrenceID must be unique (please note comparisons are case insensitive)`
