### ISSUE TITLE
Can't edit Darwin Core Mappings

### ISSUE THREAD

**Issue by edalcin** [gbif/ipt#2111]
Dear folks,

Running the version 2.5.8-r37b18ef I'm having issues with editing "Darwin Core Mappings". Looks like that IPT does not allow that a mapping (Darwin Core Occurrence, Darwin Core Identification History or Simple Multimedia), once edited, be edited again.

When I click in "Edit", nothing happens. I'll try to delete the "Source Data" related to the mapping, and remap again. But it is frustrating.

Any thoughts? Maybe related to an outdated version of IPT?

I'll try the source deletion and report here.

Thanks in advance. 

Cheers,

Dalcin

**Comment by edalcin** [comment]
That's it. I had to delete the Source Data. Re-do the Source Data, to be able to recreate the Simple Multimedia Map. Would be better to just edit the  mapping.

**Comment by mike-podolskiy90** [comment]
@edalcin Thank you for contacting us.
The 2.5.8 is quite outdated. We addressed similar issues in recent releases (e.g. this one #1968)
Please make sure you use the latest version (currently 2.7.6)

**Comment by edalcin** [comment]
> @edalcin Thank you for contacting us. The 2.5.8 is quite outdated. We addressed similar issues in recent releases (e.g. this one #1968) Please make sure you use the latest version (currently 2.7.6)

Thanks @mike-podolskiy90 . I'll try to do this.
