### ISSUE TITLE
Allow configuration of the default language

### ISSUE THREAD

**Issue by MattBlissett** [gbif/ipt#2121]
The manual describes a way to edit a configuration file to specify the default language for the IPT: https://ipt.gbif.org/manual/en/ipt/latest/faq#how-can-i-change-the-ipts-default-language

It would be really useful to allow this to be configured somewhere in the Administration settings of the IPT. (Then also update the FAQ item in the manual.)

CC @rukayaj.

**Comment by mike-podolskiy90** [comment]
Thanks Matt.
Can be added to the IPT settings I think
