### ISSUE TITLE
Use correct HTML titles for metadata section in Camtrap DP

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#2122]
The metadata editor has different pages/sections (Basic Metadata, Geographic Scope, etc.). For a Camtrap DP, those all have the HTML title (`<head><title>`) "Basic Metadata".

This might also be the case for ColDP and Material DP. The sections for a DwC-A have the correct title.

**Comment by mike-podolskiy90** [comment]
Thanks Peter, I'll fix.
