### ISSUE TITLE
Allow custom objects as geographic and taxonomic scope

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/ipt#2123]
By default metadata will be inferred from the source data. Otherwise user can upload a custom object.

See #2047

**Comment by EstebanMH-SiB** [comment]
I don't find the option to upload a file for Taxonomic or Temporal scope in the Version 3.0.6 of the IPT and version v1.0 of Camtrap DP.
![image](https://github.com/user-attachments/assets/c061d620-a505-4b28-a590-3a1300134d84)
![image](https://github.com/user-attachments/assets/e713d945-ff15-4f3a-88d0-6dac9b229460)

If this is by desing, maybe the information message can be changed to explain that only inferred information is valid and add that those scopes are mandatory

**Comment by mike-podolskiy90** [comment]
Thank you @EstebanMH-SiB 
We need to change the message. There is no plans to add such functionality

**Comment by EstebanMH-SiB** [comment]
The message for taxonomic and temporal scope for CamtrapDP resources is broken in IPT Version 3.1.5:
<img width="455" alt="Image" src="https://github.com/user-attachments/assets/14616b70-b29e-4976-a330-3d591a4dcc08" />

Also, it would be useful in the message to say from wich file the information is retrived in the temporal scope, if it is from deployment or media
