### ISSUE TITLE
Remove geometry and bbox fields from default GeoJson

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/ipt#2126]
Currently geographic scope's GeoJson is too complicated with `geometry` and `bbox`. Essentially, the coordinates are duplicated three times. Those should be removed

**Comment by mike-podolskiy90** [comment]
As part of https://github.com/gbif/ipt/issues/2123

**Comment by peterdesmet** [comment]
I notice the exported `spatial` property is now:

```
{
    "type": "Polygon",
    "coordinates": [
      4.468157,
      51.256753,
      4.501468,
      51.269946
    ]
  }
```

That is not valid geojson. I think it should be:

```
{
    "type": "Polygon",
    "coordinates": [
      [
        [lon1, lat1],
        [lon2,lat1],
        [lon2,lat2],
        [lon1,lat2],
        [lon1,lat1]
      ]
    ]
  }
```

**Comment by mike-podolskiy90** [comment]
Yes, it is wrong indeed

**Comment by mike-podolskiy90** [comment]
We need to validate custom objects too

**Comment by mike-podolskiy90** [comment]
Deployed to UAT.
Now it validates GeoJSON upon saving. Should be a valid object.

**Comment by peterdesmet** [comment]
- [x] Result is now indeed valid GeoJSON. 👍 
- [x] The input field allows to write, validate and save custom GeoJSON. 👍 
- [ ] When invalid, it clears the input field. Note a huge issue, but maybe the value can be retained for adapting?
- [ ] The placeholder text should likely be `Input custom GeoJSON object` (no space Geo JSON)
- [ ] It is unclear to me what the `Upload file` is supposed to do? Clicking it has no effect, dragging a file there doesn't work either:

<img width="483" alt="Screenshot 2023-11-17 at 16 08 23" src="https://github.com/gbif/ipt/assets/600993/6880ecce-3a1b-4c01-b236-d646f779b0c7">

**Comment by mike-podolskiy90** [comment]
You can upload a file by clicking `Upload file`. It was broken, should be fine now.

**Comment by mike-podolskiy90** [comment]
deployed to UAT

**Comment by peterdesmet** [comment]
Tested and confirmed fixed. Really useful that invalid uploaded input stays there to correct.
