### ISSUE TITLE
Unmapped columns section does not apper in Camtrap DP mapping

### ISSUE THREAD

**Issue by EstebanMH-SiB** [gbif/ipt#2128]
We think it would be nice to have the "Unmapped columns" sections at the end of mapping section, it helps the process when not all columns have the correct header and to check how many elements are left without mapping.

We do not know if this was left out for a specific reason, so sorry if the topic has been arranged before. Thanks in advance,

@SiBColombia

**Comment by mike-podolskiy90** [comment]
Thank you @EstebanMH-SiB 
I think we just overlooked it since it's not a crucial part of the mapping. I'll add that
