### ISSUE TITLE
Inquiry regarding Stamen message: Basemap tiles no longer available

### ISSUE THREAD

**Issue by EstebanMH-SiB** [gbif/ipt#2129]
The message in the image has been appearing in the "Geographic Coverage" section, we want to know if after October 31 we need to update something in our IPTs or if there is no effect and we can just continue using our IPT normally.

Thanks in advance!

<img width="985" alt="image" src="https://github.com/gbif/ipt/assets/63795703/930749e5-a970-4cac-bdd5-d64f2a1412b8">

**Comment by mike-podolskiy90** [comment]
Thank you for reporting the issue.
Map tiles libraries have to be update, see here #1801
