### ISSUE TITLE
Session Loss When Clicking "Manage Resources" in an IPT Instance

### ISSUE THREAD

**Issue by ymatheus95** [gbif/ipt#2177]
**Problem Description:**

I am encountering a specific issue with one of the three instances of IPT operating in my environment, each running in separate Docker containers. I use a Docker Compose file to manage these instances. The problem at hand occurs only in one of the instances, where the Admin user loses their session upon clicking on "Manage Resources."

**Step-by-step description of the problem:**

The Admin user logs in successfully.
The Admin user can perform any administrative task without issues.
However, upon clicking "Manage Resources," the page is redirected to https://example/instance1/manage/?. The session is not abruptly terminated, but when the user clicks on any other function or link, they are redirected to the login page.
Additional Information:

IPT Version in use: 2.7.6
This problem is adversely affecting user experience and system functionality, and I am seeking assistance in resolving this specific issue in one of the IPT instances.

**This is recorded at the moment when the session is terminated:**
![image](https://github.com/gbif/ipt/assets/32114803/ca344762-f5e1-4db5-a79e-453789318b39)

**Comment by mike-podolskiy90** [comment]
Thank you for contacting us and for the detailed description of the problem.
It is very strange that the problem occurs only in one IPT. I'll look into what could be causing this problem and get back to you.

**Comment by mike-podolskiy90** [comment]
Does this happen for every admin user every time you try?

**Comment by mike-podolskiy90** [comment]
@ymatheus95 One of the possible issues is a session timeout. Please check it out in your IPT data directory (config -> ipt.properties -> session.timeout). It's set in minutes, so please make sure you have a reasonable value there, e.g. 60

**Comment by edalcin** [comment]
The problem happening:

https://youtu.be/kyfJ7F-vzcE?si=a6rFkiO5Zy8uGKQb

**Comment by ymatheus95** [comment]
> Isso acontece com todos os usuários administradores sempre que você tenta?

Yes, this issue affects all users. We have reset the passwords, but the problem still persists.

**Comment by ymatheus95** [comment]
> Isso aconteceu no meu servidor de teste esta semana. Recriei o docker do zero e o problema desapareceu.
Good morning, yes, I rebuilt the instance, but the issue persists.

pt-br: Bom dia, sim, reconstruí a instância, mas o problema continua.

**Comment by ymatheus95** [comment]
> azoável, por exemplo, 60

**Comment by ymatheus95** [comment]
I just clicked closed by mistake.

**Comment by ymatheus95** [comment]
> @ymatheus95 One of the possible issues is a session timeout. Please check it out in your IPT data directory (config -> ipt.properties -> session.timeout). It's set in minutes, so please make sure you have a reasonable value there, e.g. 60

I believe it's not a timeout issue, as the problem doesn't occur when using other administrative functions, only when clicking 'Manage Resources.' In advance, thank you for your response.

![image](https://github.com/gbif/ipt/assets/32114803/5d256587-ced5-4e9b-881a-de911af08356)

**Comment by mike-podolskiy90** [comment]
@ymatheus95 Would it be possible to create an admin account for me?

**Comment by ymatheus95** [comment]
> @ymatheus95 Would it be possible to create an admin account for me?

Certainly, I will reach out to my client and request permission. Would it be possible for us to schedule a Teams call?

**Comment by edalcin** [comment]
> @ymatheus95 Would it be possible to create an admin account for me?

@mike-podolskiy90 , email me at edalcin@jbrj.gov.br. I work together with @ymatheus95, and I'll open your account and send details by email.

**Comment by mike-podolskiy90** [comment]
@edalcin Thank you for the account.

@ymatheus95 After some debugging I found the reason of the issue. It's this resource: https://ipt.jbrj.gov.br/jabot/manage/resource?r=ufrn
This resource has a logo that refers to another IPT: https://ipt.jbrj.gov.br/reflora/logo.do?r=ufrn_herbarium and this call triggers session change in the browser. I removed the logo from the resource in the Additional metadata section and the manage section is working fine now. Please don't add URLs to other IPTs, upload logo file instead. You also need to republish this resource, otherwise problems will persist if the resource's home page is open.

Let me know if you have questions

**Comment by ymatheus95** [comment]
> @edalcinObrigado pela conta.
> 
> @ymatheus95Após alguma depuração, descobri o motivo do problema. É este recurso: https://ipt.jbrj.gov.br/jabot/manage/resource?r=ufrn Este recurso possui um logotipo que faz referência a outro IPT: [https://ipt.jbrj.gov.br/reflora/ logo.do?r=ufrn_herbarium](https://ipt.jbrj.gov.br/reflora/logo.do?r=ufrn_herbarium) e esta chamada aciona a mudança de sessão no navegador. Removi o logotipo do recurso na seção Metadados adicionais e a seção de gerenciamento está funcionando bem agora. Por favor, não adicione URLs a outros IPTs; em vez disso, carregue o arquivo do logotipo. Você também precisa republicar este recurso, caso contrário, os problemas persistirão se a página inicial do recurso estiver aberta.
> 
> Deixe-me saber se você tem perguntas


**Incredible!! I'm very grateful for the help.**

**Comment by ymatheus95** [comment]
> @edalcin Thank you for the account.
> 
> @ymatheus95 After some debugging I found the reason of the issue. It's this resource: https://ipt.jbrj.gov.br/jabot/manage/resource?r=ufrn This resource has a logo that refers to another IPT: https://ipt.jbrj.gov.br/reflora/logo.do?r=ufrn_herbarium and this call triggers session change in the browser. I removed the logo from the resource in the Additional metadata section and the manage section is working fine now. Please don't add URLs to other IPTs, upload logo file instead. You also need to republish this resource, otherwise problems will persist if the resource's home page is open.
> 
> Let me know if you have questions



> @edalcin Thank you for the account.
> 
> @ymatheus95 After some debugging I found the reason of the issue. It's this resource: https://ipt.jbrj.gov.br/jabot/manage/resource?r=ufrn This resource has a logo that refers to another IPT: https://ipt.jbrj.gov.br/reflora/logo.do?r=ufrn_herbarium and this call triggers session change in the browser. I removed the logo from the resource in the Additional metadata section and the manage section is working fine now. Please don't add URLs to other IPTs, upload logo file instead. You also need to republish this resource, otherwise problems will persist if the resource's home page is open.
> 
> Let me know if you have questions

**Incredible!! I'm very grateful for the help.**
