### ISSUE TITLE
Starting Camtrap DP resource from zip does not recognize observationID

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#2189]
1. Start a Camtrap DP resource from a zip. I used [the Camtrap DP example dataset](https://download-directory.github.io/?url=https://github.com/tdwg/camtrap-dp/tree/1.0/example) (link will generate and download a zip)
2. Resource is created, metadata is populated, but one warning appears:

<img width="1160" alt="Screenshot 2023-11-10 at 14 25 50" src="https://github.com/gbif/ipt/assets/600993/003d231c-84ab-4e54-b299-6a695360fa34">

3. Go to the mapping for observations:

<img width="1172" alt="Screenshot 2023-11-10 at 14 29 19" src="https://github.com/gbif/ipt/assets/600993/a89d2ea0-93a7-48a9-84da-adf482b41613">

I'm not sure what could be wrong, since the field `observationID` is present in the source data, so it should be possible to automap.

**Comment by mike-podolskiy90** [comment]
An invisible character in the beginning of the file? BOM probably

**Comment by peterdesmet** [comment]
Oh right, I notice:

<img width="977" alt="Screenshot 2023-11-10 at 14 38 23" src="https://github.com/gbif/ipt/assets/600993/59e97ffe-8f05-4690-9d85-d7a7fb794b0d">

**Comment by peterdesmet** [comment]
Do you think these two errors are related? Is it possible to search for that invisible character?

**Comment by peterdesmet** [comment]
It looks like the two issues are not related, I'm also getting the publication error for another dataset. Will create separate issue.

**Comment by peterdesmet** [comment]
Indeed, the reason why observationID was not mapped is because of a BOM character. Removing it fixes this issue. Issue @2190 remains.
