### ISSUE TITLE
Generated taxonomic scope has empty `vernacularNames`

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#2192]
A published Camtrap DP with an generated `taxonomic` scope currently adds `vernacularNames` for every taxon. That property contains an empty list.

```json
[
  {
    "scientificName" : "Muntiacus reevesi",
    "vernacularNames" : { }
  }, {
    "scientificName" : "Canis lupus familiaris",
    "vernacularNames" : { }
  }
]
```

Can the `vernacularNames` property be removed if it is empty (i.e. generated), cf. other properties with empty lists?

**Comment by mike-podolskiy90** [comment]
Deployed to UAT

**Comment by peterdesmet** [comment]
Confirmed fixed
