### ISSUE TITLE
Update `Field quotes` interpretation + help text

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#2193]
The `Field quotes` help text is currently the following:

<img width="344" alt="Screenshot 2023-11-13 at 12 22 59" src="https://github.com/gbif/ipt/assets/600993/aa1a2882-9b82-4fcb-93af-89d01bab7b37">

- [x] Can the parser really not deal with quoted and unquoted columns and/or mixed use within a column? This is very common behaviour in CSV writers. **It seems it can handle mixed situation if `fieldQuotes` is set to `"`, see below**
- [x] The newline and carriage returns should probably not have the parenthesis, as the character is not visible.
- [x] ~Bug: Clicking any of the options does not populate the field (in contrast with `Multi-value Delimiter`, which does work)~
- [x] ~Why not use a dropdown to set this field? This also avoids users setting double characters.~
- [x] Why not set this field to `"` by default for csv files?

**Comment by peterdesmet** [comment]
I uploaded this file: https://github.com/tdwg/camtrap-dp/blob/1.0/example/deployments.csv

- It has a mixture of quoted and unquoted values across columns (all are unquoted, except for `habitat` and `deploymentComments`)
- It has a mixture of quoted and unquoted values within the `habitat` and `deploymentComments` column (only values with `,` are quoted)
- I set `fieldQuotes` to `"`

This publishes fine, so it seems the help text is to strict.

**Comment by mike-podolskiy90** [comment]
> Bug: Clicking any of the options does not populate the field (in contrast with Multi-value Delimiter, which does work)

I don't see that in any test IPT

> Why not use a dropdown to set this field? This also avoids users setting double characters.

Dropdown would restrict choice to those three. I think we should just leave it as is

**Comment by peterdesmet** [comment]
If not dropdown, than perhaps the field should be restricted to a single character?

**Comment by peterdesmet** [comment]
And indeed, I cannot replicate the issue with "Clicking any of the options". Seems to work fine now

**Comment by mike-podolskiy90** [comment]
> If not dropdown, than perhaps the field should be restricted to a single character?

Don't want to add additional validation there. I think we're fine, the field will be set automatically most of the time anyway
