### ISSUE TITLE
Inferred temporal scope incorrect

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#2195]
The inferred temporal scope for the Camtrap DP example package is:

```
"temporal" : {
    "start" : "2020-05-30",
    "end" : "2020-07-01"
  },
```

The end date is correct. It looks like it is the `deploymentEnd` of the first deployment, while it should be the maximum `deploymentEnd` across deployments, which is `2021-04-18`.

The `spatial` coordinates are correct (min max across deployments)

**Comment by mike-podolskiy90** [comment]
There were issues with date types. I've deployed a fixed version to UAT

**Comment by peterdesmet** [comment]
Seems to work now.
