### ISSUE TITLE
Inferred taxonomic scope incomplete

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#2196]
The inferred taxonomic scope for the Camtrap DP example package is:

```
"taxonomic" : [ {
    "scientificName" : "Ardea cinerea"
  }, {
    "scientificName" : "Rattus norvegicus"
  }, {
    "scientificName" : "Homo sapiens"
  }, {
    "scientificName" : "Anas platyrhynchos"
  } ],
```

The observations.csv however contain many more taxa. The taxa above are not the taxa in the first records either.

**Comment by mike-podolskiy90** [comment]
Is it on ipt3 UAT? Can you point me out to the resource please?

**Comment by peterdesmet** [comment]
Yes, see https://ipt3.gbif-uat.org/resource?r=camtrap-dp-example&v=1.0#anchor-taxonomic. I have since updated the resource to use the original (not inferred data)

**Comment by mike-podolskiy90** [comment]
Oh, I see. It's limited to 200 lines now. Fixing

**Comment by mike-podolskiy90** [comment]
Deployed to UAT

**Comment by peterdesmet** [comment]
Tested, confirmed fixed.
