### ISSUE TITLE
Published dataset indicated as Never published

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#2197]
I notice that published Camtrap DP datasets are indicated as `never been published`:

https://ipt3.gbif-uat.org/resource?r=camtrap-dp-example&v=2.0

<img width="994" alt="Screenshot 2023-11-13 at 14 54 16" src="https://github.com/gbif/ipt/assets/600993/59052677-3cc7-4fce-bbe6-df38d5143b11">

**Comment by peterdesmet** [comment]
What is the behaviour for Darwin Core Archives? I would use the same approach for both.

**Comment by mike-podolskiy90** [comment]
It's a bit weird there. The publishing organization is a part of the basic metadata, even though it's actually not. I'm planning to remove it from the basic metadata page.

**Comment by peterdesmet** [comment]
> It's an issue with the check. It checks whether the resource has a publishing organization. I guess we should prohibit publishing without an organization?

This would be a substantial change, since the behaviour of the IPT so far has been that a dataset doesn't need to be registered with GBIF to be a valid. OBIS relies on that behaviour (but that might change if they make use of the same registry as GBIF). Others might use the IPT (e.g. in test) without registration.

So I think it should likely still be possible to publish without a registered publisher (i.e. publish without registration) and the dataset should then not be indicated as "Never published".

**Comment by mike-podolskiy90** [comment]
deployed to UAT

**Comment by peterdesmet** [comment]
Confirmed fixed.

**Comment by EstebanMH-SiB** [comment]
We are getting this same problem in Version 3.0.6, it let us publish an index to GBIF normallym but it showns the message:
<img width="1290" alt="image" src="https://github.com/user-attachments/assets/8c42c7c7-ceef-47bb-90e8-193f5de68967">

From the IPT it doesn't let me edit the organization, neither here 
<img width="1046" alt="image" src="https://github.com/user-attachments/assets/1c3179bb-81e5-4b77-9658-9e48dbf41f29">
Not here were is blocked:
<img width="969" alt="image" src="https://github.com/user-attachments/assets/cf104a37-297f-4f02-a561-2862ad028d50">

Is there an easy solution to this? Thanks in advance,
