### ISSUE TITLE
Publication fails for values containing escaped quotes and comma

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#2198]
For a source with `fieldQuotes = "`, **publication will fail if the field contains quoted values (escaped by double `""`) _and_ a comma**. This is the actual cause of the error reported in #2190 (that issue has since changed scope).

> Publishing version #7.0 of resource camtrap-dp-example failed: Archive generation for resource camtrap-dp-example failed: java.lang.IllegalStateException: IOException reading next record: java.io.IOException: (line 5) invalid char between encapsulated token and delimiter

Note that only the combination of quoted values _and_ comma break publication:

Input csv | Output csv | Preview | Publication
--- | --- | --- | ---
`"Contains comma, wrapped in quotes"` | `"Contains comma, wrapped in quotes"` | ✅ | ✅ 
`Contains "quoted value" not wrapped in quotes` | `"Contains ""quoted value"" not wrapped in quotes"` | ✅ | ✅ 
`"Contains ""quoted value"" wrapped in quotes"` | `"Contains ""quoted value"" wrapped in quotes"` | ✅ | ✅ 
`"Contains ""quoted value"" and comma, wrapped in quotes"` | - | ✅ | ❌

The preview is fine:
<img width="290" alt="Screenshot 2023-11-13 at 15 28 52" src="https://github.com/gbif/ipt/assets/600993/ee5b9c76-8465-4a29-9f58-3845c161ab7d">

It is important to support this combination, since some values (`media.exifData`, but also `dwc:dynamicProperties`) suggest to use of JSON, which will contain both:

```
{"key_1": 1, "key_2": "value"}
```

Example file to test (field `habitat`): [deployments.csv](https://github.com/gbif/ipt/files/13335766/deployments.csv)

**Comment by mike-podolskiy90** [comment]
Deployed to UAT

**Comment by peterdesmet** [comment]
Tested on UAT. The file referenced above still fails publication: [deployments.csv](https://github.com/gbif/ipt/files/13335766/deployments.csv)

> Publishing version #8.0 of resource camtrap-dp-example failed: Archive generation for resource camtrap-dp-example failed: java.lang.IllegalStateException: IOException reading next record: java.io.IOException: (line 5) invalid char between encapsulated token and delimiter

**Comment by mike-podolskiy90** [comment]
Looks like I deployed a wrong version. Don't have issues with the file when creating a new source and a mapping.

However, it doesn't seem to be working correctly when creating from the archive.

**Comment by mike-podolskiy90** [comment]
I think I've figured it out. Deployed to UAT

**Comment by peterdesmet** [comment]
Confirmed, the file referenced above can be published without error now.
