### ISSUE TITLE
Simplify scope pages

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#2201]
Camtrap DP scope pages were simplified in #2132 to from datapackage.json or inferred. I think the layout of the pages can be simplified further:

- [x] All scopes: Remove `... coverage of the package` (redundant with title)
- [x] All scopes: Combine boxes for `Current saved metadata` and `Last inferred metadata` into one. It is currently confusing what will be saved. I think the box should always show what will be saved when clicking `Save`. It can revert to the original content when the user doesn't save.
- [x] All scopes: Make `Infer metadata automatically` first line on page
- [x] Taxonomic scope: Use table with columns `Scientific name` and `Taxon ID`

## Geographic scope

- [x] From datapackage.json:

<img width="901" alt="Screenshot 2023-11-16 at 09 46 58" src="https://github.com/gbif/ipt/assets/600993/8971fbf3-8e29-4854-baaf-6d58c595148d">

- [x] Inferred:

<img width="921" alt="Screenshot 2023-11-16 at 09 52 05" src="https://github.com/gbif/ipt/assets/600993/529756d2-461c-437d-a422-bef9d283ab01">

## Taxonomic scope

- [x] From datapackage.json:

<img width="910" alt="tax-before" src="https://github.com/gbif/ipt/assets/600993/7466341c-07c4-4eb8-b9fe-971229cae03a">

- [x] Inferred:

<img width="910" alt="tax-after" src="https://github.com/gbif/ipt/assets/600993/cd680bf0-cc3a-436d-a89c-f129410471e5">

## Temporal scope

- [x] From datapackage.json:

<img width="898" alt="tem-before" src="https://github.com/gbif/ipt/assets/600993/b9f1e04f-c73a-478a-8b3a-3bfc98b82619">

- [x] Inferred:

<img width="898" alt="tem-after" src="https://github.com/gbif/ipt/assets/600993/b456fca7-09ce-4378-9d0c-94be504a6468">

**Comment by mike-podolskiy90** [comment]
Got a couple of questions/doubts:

- Should we also display vernacular names (and, maybe, other taxonomic fields) for custom taxonomic view?
- Long list of scientific names with an always empty taxon ID column looks really awkward.

**Comment by mike-podolskiy90** [comment]
Deployed to UAT.
Let's just figure the taxonomic page out

**Comment by peterdesmet** [comment]
I like all the improvements! Much easier to work with!

One minor issue:

1. Upload datapackage.json
2. Go to geo/tax/temp coverage
3. Click `Infer metadata` (but don't save yet)
4. The timestamp (very useful to see it is inferred) and `Re-infer` appears
5. Clicking the `Re-infer` brings the page back to its original unsaved form.

I think that is fine (user should save first), but optionally that `Re-infer` link is only shown once saved first?

> Should we also display vernacular names (and, maybe, other taxonomic fields) for custom taxonomic view?

In my opinion, the current implementation is sufficient. Showing everything would almost require showing the verbose JSON.

> Long list of scientific names with an always empty taxon ID column looks really awkward.

Agree. One could argue to display the custom metadata the same way as the inferred metadata, but the fact that the layout is different makes it easier to see the difference.

**Comment by mike-podolskiy90** [comment]
deployed to UAT

**Comment by peterdesmet** [comment]
Tested:

Step 5 in https://github.com/gbif/ipt/issues/2201#issuecomment-1816630686 now displays the inferred data (rather than reverting), but the checkbox for `Infer metadata automatically` disables. Is that the expected behaviour?

**Comment by mike-podolskiy90** [comment]
I think it makes sense to display inferred metadata when `Re-infer` clicked?

**Comment by peterdesmet** [comment]
Yes it does, but I'm wondering why the checkbox is checked of when clicking `Re-infer` (before saving).

**Comment by mike-podolskiy90** [comment]
Oh, I see now. `Infer automatically` should be preserved? I've just deployed the fix.

**Comment by peterdesmet** [comment]
Confirmed fixed.
