### ISSUE TITLE
Cannot add myself as dataset manager

### ISSUE THREAD

**Issue by andrejjh** [gbif/ipt#2204]
I have some old datasets created with an old user(email=aheugheb@ulb.ac.be).
eg [Fruitly checklist](https://www.gbif.org/dataset/bd25fbf7-278f-41d6-bc17-9f08f2632f70)
When I try to add myself as manager of this dataset, my new admin account(email=a.heughebaetr@biodiversity.be) does not appear in the user list.
I can add somebody else, but not me... very strange.

**Comment by andrejjh** [comment]
It seems that non of the admins appear in the list.

**Comment by timrobertson100** [comment]
Hi @andrejjh - this is expected. 
It's implemented as a hierarchical authorization list where admins have management permission on all datasets (plus other aspects). Admins can then appoint other users as data managers (with or without registration rights) in a more fine-grained manner.
