### ISSUE TITLE
Preview page is not showing the Geographic Scope

### ISSUE THREAD

**Issue by ktotsum** [gbif/ipt#2216]
Creating a test Camtrap DP dataset on https://ipt3.gbif-uat.org/

Bounding coordinates are shown in the Geographic Scope of metadata, but it becomes blank in the preview page after publishing. Coordinates seem to be included in the datapackage.json properly.
![image](https://github.com/gbif/ipt/assets/138471170/c313bff3-ce88-440d-abee-9e1c8f64e3bb)
![image](https://github.com/gbif/ipt/assets/138471170/31c0486a-8218-4c9e-a892-51d5034b16bc)

**Comment by mike-podolskiy90** [comment]
Thanks Kumiko, I'll fix it

**Comment by mike-podolskiy90** [comment]
I'll deploy the fix in the next version
