### ISSUE TITLE
Schema update/synchronization

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/ipt#2227]
Some time ago we decided to disable manual schema updates through the admin interface. Currently IPT updates them automatically on startup and the versions are hardcoded. See https://github.com/gbif/ipt/issues/2043

This is not the best solution. We need to find a solution to allow administrators to update schemas. There is also a known case when some small things were changed in the scheme (typos, description, etc.) without releasing a new version. In this case, synchronization (reinstallation) should be available.

I suggest adding a new date field to rs schemas: `compatible`. All schemas with a release date after the compatibility date can be updated manually. Otherwise, IPT reinstallation is required.

**Comment by mike-podolskiy90** [comment]
`compatible` is working fine only to check the latest version. If the latest one is incompatible, but there are newer compatible version somewhere behind - we need to iterate back to find one, which is not very convenient.

Alternatively, we can store a file in the rs.gbif.org, next to schema.json, which will indicate what the latest supported version is. Example:
![Screenshot 2023-11-30 at 10 43 21](https://github.com/gbif/ipt/assets/24795387/b4040668-7ceb-4f7e-9df3-78d77c4c4c3a)

Inside:
```
{
  "version": "1.0",
  "latestCompatibleVersion": "1.1"
}
```

However, this property `latestCompatibleVersion` must be updated for each version whenever a new version is released.

@peterdesmet

**Comment by mike-podolskiy90** [comment]
With the IPT-version approach you'll need to compare versions of IPT and it's not obvious what version of Camtrap you can install. Example: let's say you have an IPT of version `3.1.2` - how do you quickly find the latest supported version of Camtrap?

So essentially IPT installs Camtrap, and not the other way around. At the moment I see this approach:
- Some version of Camtrap is installed in IPT
- IPT queries the registry: I have this version and would like to update it. Which version will be the latest for me?

**Comment by peterdesmet** [comment]
Can you explain how the IPT iterates over the registry looking for new versions? Is this from a single registry file with all the versions or does it iterate over all the directories looking for a specific `_schema/version.json` file?

**Comment by mike-podolskiy90** [comment]
I directly asks the registry (rs): "I have `x` version installed, what would be the latest version for this?":

```
https://rs.gbif.org/sandbox/experimental/camtrap-dp/x/_schema/version.json
```

**Comment by EstebanMH-SiB** [comment]
We are wondering if this error is related to the update of this schemas. We have a Version 3.0-RC1 installed and it used to be possible to review all schemas availables, but now I am getting this error:
<img width="1251" alt="image" src="https://github.com/gbif/ipt/assets/63795703/00efcba2-77f0-4b0e-8f29-88794b99542c">

We want to know if it is normal or how we can solve this. Thanks!

**Comment by mike-podolskiy90** [comment]
Thank you for your comment. Unfortunately, the 3.0-RC1 does not work anymore due to recent changes to the GBIF rs and schemas. You need to install one of the latest snapshots or use IPT3 on GBIF UAT environment
