### ISSUE TITLE
Excel file issue - cannot generate archive

### ISSUE THREAD

**Issue by ManonGros** [gbif/ipt#2231]
This is something that two users reported separately on two different files and dataset.
They upload and map their excel files in the IPT but when they click on the publish button, they get an error message.

This is the error message:

`Publishing version #1.16 of resource griis-brunei-norway failed: Archive generation for resource griis-brunei-norway failed: Error writing data file for mapping Darwin Core Taxon in source griisgbif_norway_2023, line 99`

If the data is exported to CSV and that CSV file is uploaded to the IPT, there is no issue.
See the examples here:

- I cannot publish the dataset here (excel): https://cloud.gbif.org/griis/manage/resource.do?r=griis-brunei-norway 
- but I can publish it here (CSV): https://ipt.gbif.org/manage/resource.do?r=test-marie-norway-checklist-griis

**Comment by ktotsum** [comment]
This is the other example: https://ipt.gbif.no/resource?r=conflux

You also get an error message on the preview of Darwin Core Mappings with Excel files.
![image](https://github.com/gbif/ipt/assets/138471170/102d0bde-a061-4480-9548-c2423c9e4ee3)

**Comment by SophiePamerlon** [comment]
Hi, I've had this issue several times too: it seems to be solved by saving the excel file into another format but it can be really troublesome (this morning i had to import the file into Openrefine, export it as a Google sheet, then save it locally from Google sheet as a csv file in order for it to be accepted by the IPT...). Direct converting in Excel/other table managers from xlsx to csv/tsv/txt files didn't work.

**Comment by mike-podolskiy90** [comment]
Yes, current implementaion can't process binary excel files `.xls`, only more modern XML-based `.xlsx`. I'm not sure whether we should support both? `.xlsx` works fine

**Comment by mike-podolskiy90** [comment]
There were performance issues and IPT crashes related to that https://github.com/gbif/ipt/issues/2030

**Comment by mike-podolskiy90** [comment]
Oh, I see now, it's another thing. Looking into it

**Comment by mike-podolskiy90** [comment]
This should be fine now, deployed to [ipt.gbif-uat.org](https://ipt.gbif-uat.org/)
