### ISSUE TITLE
Align naming conventions with Frictionless standards

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/ipt#2234]
Currently there are some inconsistencies with the names. Needs to be aligned

Entities:

-  **Schema** - main descriptor for the "entity", contains all the information about the package
- **Subschema** - descriptor for "sub-entities" (e.g. `media` or `observation` for camtrap)
- **DataSchemaField** - descriptor for properties (e.g. `locationName` in `deployments`)

**Comment by peterdesmet** [comment]
In Frictionless those entities are:

- Schema -> **[Data Package](https://specs.frictionlessdata.io/data-package/)** (typically referred to as `package` in Frictionless software): All information about a dataset, i.e. it's metadata and its resources
- Subschema -> either:
  - **[Data Resource](https://specs.frictionlessdata.io/data-resource/)** (`resources` in json): All information about a **file** (or collection of files with the same format), including path(s), format, encoding and (for tabular data) schema
  - **[Table Schema](https://specs.frictionlessdata.io/table-schema/)** (`schema` in json): Description of fields in **tabular data** as well as missing value representation, primary keys and foreign key relationships with other resources.
- DataSchemaField -> An element in the array [`fields`](https://specs.frictionlessdata.io/table-schema/#field-descriptors) of a Table Schema

**Comment by mike-podolskiy90** [comment]
Thanks Peter.

We call the result as "Data Package", whereas this "Schema" is only a descriptor of the future result. We need something not to confuse those two.

**Comment by mike-podolskiy90** [comment]
@peterdesmet Do you think this will work?

- DataPackageSchema
- DataPackageTableSchema
- DataPackageField

**Comment by mike-podolskiy90** [comment]
This will affect a lot of things and also break current data package resources. I'll re-create them on IPT3

**Comment by mike-podolskiy90** [comment]
Also we need to decide on the camtrap data package identifier, currently `http://rs.gbif.org/schemas/camtrap-dp`. We can still change it

**Comment by peterdesmet** [comment]
Decided on the following name conventions:

Directory structure and file names:

```ini
rs.gbif.org/
  data-packages/
    index.json # previously schemas.json
    camtrap-dp/
      1.2/
        profile/
          camtrap-dp-profile.json
        table-schemas/
          deployments.json # moved down
          media.json # moved down
          observations.json # moved down
        version.json # moved up
        index.json # previously _schema/schema.json
```

JSON structure for a `rs.gbif.org/data-packages/<name>/<version>/index.json`:

```ini
{
    "identifier"
    "url"
    "profile" # previously metadataProfile
    "name"
    "version"
    "tableSchemas": [] # previously subSchemas
      "tableSchemasRequirements": {} # previously subSchemaRequirements
}
```

JSON structure for `rs.gbif.org/data-packages/index.json`:

```ini
{
  "dataPackages": [ # Optionally, remove this property and start array at root
    {
      "identifier" # etc, same as above
    }
  ]
}
```
