### ISSUE TITLE
API for resources

### ISSUE THREAD

**Issue by edalcin** [gbif/ipt#2236]
Dear folks,

I'm moving forward with the project https://github.com/edalcin/DarwinCoreJSON, including occurrence data from IPT. The project "DarwinCoreJSON" will accept any IPT Resource, "core" independent, and convert the data to JSON.

At this point, I have to enter [manually the list of resources on IPT ](https://github.com/edalcin/DarwinCoreJSON/blob/main/referencias/sources.json)that I want to convert to JSON and aggregate on MongoDB.

What would be great would be to have some kind of  "resources.do" that will list all the resources, better, exposing the "EML" of all and each resource, to be read and processed by machine.

Please let me know if it makes sense.

Thanks in advance.

**Comment by mike-podolskiy90** [comment]
Thank you, we'll consider implementing this feature

**Comment by mike-podolskiy90** [comment]
I think you can do that via `https://ipt.gbif.org/rss.do`. It lists all IPT datasets in XML format. There you can find `ipt:eml` - EML endpoint and `ipt:dwca` - DwC archive.

**Comment by mike-podolskiy90** [comment]
There is also https://ipt.gbif.org/inventory/dataset
