### ISSUE TITLE
IPT set the profile field to `data-package` instead of actual one

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/ipt#2254]
Example:

```
{
  "version": "1.0",
  "profile": "data-package",
  "name": "camtrap-resource",
...
}
```

**Comment by peterdesmet** [comment]
@mike-podolskiy90 is this a value that will be set in published Data Packages?

**Comment by mike-podolskiy90** [comment]
We migrated data packages in rs recently and IPT stopped to set the profile properly. Should be an actual value

**Comment by peterdesmet** [comment]
👌 And the actual value is going to be a URL to the versioned profile at rs.gbif.org?

**Comment by mike-podolskiy90** [comment]
Must be this one for UAT:

```
https://rs.gbif.org/sandbox/data-packages/camtrap-dp/1.0/profile/camtrap-dp-profile.json
```

and this one for prod:

```
https://rs.gbif.org/data-packages/camtrap-dp/1.0/profile/camtrap-dp-profile.json
```

**Comment by mike-podolskiy90** [comment]
it still has `experimental` in the profile URL on UAT for some reason.. need to fix that
