### ISSUE TITLE
allow a "description" for taxonomic coverage when using auto infer from source data feature on IPT

### ISSUE THREAD

**Issue by ymgan** [gbif/ipt#2255]
IPT version 2.7.6

It is not possible to include a brief description for taxonomic coverage when I checked "Automatically infer from source data". 

![Screenshot 2024-01-05 at 12 38 41](https://github.com/gbif/portal-feedback/assets/11754081/7a802dd6-0c13-4d34-a629-54cd2912770b)

GBIF populated the field with "N/A"

dataset page on GBIF: https://www.gbif.org/dataset/081daea5-fe6a-4303-bcc3-126b65d0adeb#taxonomicCoverages

![Screenshot 2024-01-05 at 13 41 56](https://github.com/gbif/portal-feedback/assets/11754081/14a72715-4278-4208-8d49-12ea812987b5)

eml: https://api.gbif.org/v1/dataset/081daea5-fe6a-4303-bcc3-126b65d0adeb/document

```xml
<taxonomicCoverage>
    <generalTaxonomicCoverage>N/A</generalTaxonomicCoveragegeneralTaxonomicCoverage>
```

Is it possible to have the "description" field enabled when using "Automatically infer from source data" please? It will be very helpful for us as this is a recommendation from the data audit we received from Pensoft.

Thank you so much!!

**Comment by mike-podolskiy90** [comment]
Thank you for contacting us.

Yes, we'll fix that
