### ISSUE TITLE
Replace `data file` with `resource` when reporting on the publishing page

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/ipt#2258]
<img width="640" alt="Screenshot 2024-01-08 at 11 03 06" src="https://github.com/gbif/ipt/assets/24795387/2a302055-528b-4698-85d3-f7b4f0ffca4d">

**Comment by mike-podolskiy90** [comment]
<img width="630" alt="Screenshot 2024-01-08 at 11 09 50" src="https://github.com/gbif/ipt/assets/24795387/f39c8607-8ab9-4269-b96a-883a7e3f0c86">

**Comment by mike-podolskiy90** [comment]
@peterdesmet I guess it would make more sense? Otherwise we can leave it as it is

**Comment by peterdesmet** [comment]
Yeah, `resource` is more correct, but can clash with an IPT resource ( = dataset). Maybe you can opt to use the full names `Data Package` (title case) and `Data Resource` (title case). And then also use "creating" over "writing"

> Data Package generation started for version #1.0
> Metadata added
> Start creating Data Resource deployments
> Data Resource deployments created with 1539 records and 24 columns

> Processing record 365999 for Date Resource _media_

**Comment by mike-podolskiy90** [comment]
Deployed to UAT
