### ISSUE TITLE
Number of records for data packages resources

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/ipt#2262]
Currently we don't display total number of records for data package resources. Should we start doing that?
@peterdesmet 

What needs to be done:

- [x] Store data about how many records were published in the version history (including partition by table schema)
- [x] Display actual number of records in the home and manage tables (number of observations for camtrap)
- [x] Add "Data Records" section to the resource page
- [x] Display actual number of records in the versions table

**Comment by peterdesmet** [comment]
Yes, think that would be useful.

**Comment by peterdesmet** [comment]
No, the number of records per resource (cf. core + extensions of Darwin Core Archives).

**Comment by mike-podolskiy90** [comment]
Sorry, not sure what you mean..
What would be displayed in the home table? https://ipt3.gbif-uat.org/
I though something like: 3967747 ( combined of 1539 deployments, 3782401 media, 183807 observations)

**Comment by peterdesmet** [comment]
Oh, right, I forgot the homepage also shows a single number. For Camtrap DP specifically, I would opt to show the number of **observations**. The sum of the resources is not relevant.

**Comment by mike-podolskiy90** [comment]
I see. There is also a versions table, I guess similar to home page.
And what place did you have in mind?

**Comment by peterdesmet** [comment]
I had the Data Records section in mind: https://ipt.inbo.be/resource?r=meetnetten-abv2-occurrences#anchor-dataRecords:

<img width="638" alt="Screenshot 2024-01-09 at 14 30 38" src="https://github.com/gbif/ipt/assets/600993/b6e4f32c-d4ab-4a88-8ec8-468da5d55c1b">

**Comment by mike-podolskiy90** [comment]
Oh, I see. We don't have that section currently

**Comment by peterdesmet** [comment]
Great! Cool to see https://ipt3.gbif-uat.org/resource?r=mica-full#anchor-dataRecords

Could the resources be sorted (in their default order): deployments, media, observations?

**Comment by mike-podolskiy90** [comment]
Yes, sure, I can use that order
