### ISSUE TITLE
IPT3 functional testing

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/ipt#2283]
## IPT installation and setup

- [x] Latest version on Tomcat (the latest supported Tomcat is 9, version 10 and higher won't work because of https://github.com/gbif/ipt/issues/2118)

## Data Package administration

- [x] Data Package schemas are installed and displayed (Expected 4 packages: Camtrap DP, ColDP, Material DP, Interaction DP)
- [x] Data Package view is displayed
- [x] Source file for the Data Package can be viewed in options
- [x] All navigations, links and buttons work as expected

#### Creation

- [x] Empty Camtrap DP resource creation
- [x] Camtrap DP resource from an archive
- [x] Camtrap DP resource from an IPT folder
- [x] Camtrap DP resource from a metadata file (datapackage.json)

#### Overview: source data

- [x] Create a new source of any type (File, URL, SQL)
- [x] Create several sources at one by multiple file upload
- [x] Source overwrite (file with the same name)?
- [x] Action icons are functional (Edit, Download, Delete)
- [x] Correct info is displayed (size, columns, rows, modification date etc.)

#### Source page

- [x] Source details page is displayed
- [x] Save works
- [x] Options are functional (Analyse, Preview, Delete)
- [x] Download source log works
- [x] Help icons and their functionality work
- [x] All navigations, links and buttons work as expected

#### Overview: mappings

- [x] Create a new mapping
- [x] Create multiple mappings at time
- [x] Action icons are functional (Edit, Delete) (Preview function is missing - #2304)
- [x] Correct info is displayed (fields, modification date etc.)

#### Mapping page

- [x] Mapping page is displayed
- [x] Save works
- [x] Automapping works
- [x] Filtering works
- [x] Translation works
- [x] Required fields are marked with *
- [x] Help icons and their functionality work
- [x] Unmapped fields are displayed (if present)
- [x] Options are functional (Hide/Show unmapped fields, Delete)
- [x] All navigations, links and buttons work as expected

#### Overview: metadata

- [x] Metadata edit works, opens Basic metadata page
- [x] Metadata upload works (with or without validation)
- [x] Chip displays valid info: Complete/Incomplete
- [x] Correct info is displayed (modification date, metadata validity)

#### Metadata pages

- [x] Basic metadata
- [x] Geographic Scope
- [x] Taxonomic Scope
- [x] Temporal Scope
- [x] Keywords
- [x] Project
- [x] Citation
- [x] Other metadata

#### Overview: visibility

- [x] Visibility change works

#### Overview: publication

- [x] Change publishing organization works
- [x] Publication modal is displayed when Publish is clicked, valid info is displayed
- [x] Publication works

#### Overview: registration

- [x] Registration works
 
#### Resource home page

- [x] Resource view page works, correct data displayed

**Comment by CecSve** [comment]
This is my overview of the test. I will check each test as I go along and create separate issues (if any) for each. My test is based on the MICA dataset.

## IPT installation and setup

- [ ] Latest version on Tomcat

## Data Package administration

- [ ] Data Package schemas are installed and displayed (Expected 4 packages: Camtrap DP, ColDP, Material DP, Interaction DP)
- [ ] Data Package view is displayed
- [ ] Source file for the Data Package can be viewed in options
- [ ] All navigations, links and buttons work as expected

## Data Package management

### Camtrap DP

#### Creation

- [ ] Empty Camtrap DP resource creation
- [ ] Camtrap DP resource from an archive
- [ ] Camtrap DP resource from an IPT folder
- [ ] Camtrap DP resource from a metadata file (datapackage.json)

#### Overview: source data

- [ ] Create a new source of any type (File, URL, SQL)
- [ ] Create several sources at one by multiple file upload
- [ ] Source overwrite (file with the same name)?
- [ ] Action icons are functional (Edit, Download, Delete)
- [ ] Correct info is displayed (size, columns, rows, modification date etc.)

#### Source page

- [ ] View page is displayed
- [ ] Save works
- [ ] Options are functional (Analyse, Preview, Delete)
- [ ] Download source log works
- [ ] Help icons and their functionality work
- [ ] All navigations, links and buttons work as expected

#### Overview: mappings

- [ ] Create a new mapping
- [ ] Create multiple mappings at time
- [ ] Action icons are functional (Edit, Delete)
- [ ] Correct info is displayed (fields, modification date etc.)

#### Mapping page

- [ ] Mapping page is displayed
- [ ] Save works
- [ ] Automapping works
- [ ] Filtering works
- [ ] Translation works
- [ ] Required fields are marked with *
- [ ] Help icons and their functionality work
- [ ] Unmapped fields are displayed (if present)
- [ ] Options are functional (Hide/Show unmapped fields, Delete)
- [ ] All navigations, links and buttons work as expected

#### Overview: metadata

- [ ] Metadata edit works, opens Basic metadata page
- [ ] Metadata upload works (with or without validation)
- [ ] Chip displays valid info: Complete/Incomplete
- [ ] Correct info is displayed (modification date, metadata validity)

#### Metadata pages

- [ ] Basic metadata
- [ ] Geographic Scope
- [ ] Taxonomic Scope
- [ ] Temporal Scope
- [ ] Keywords
- [ ] Project
- [ ] Citation
- [ ] Other metadata

#### Overview: visibility

- [ ] Visibility change works

#### Overview: publication

- [ ] Change publishing organization works
- [ ] Publication modal is displayed when Publish is clicked, valid info is displayed
- [ ] Publication works

#### Overview: registration

- [ ] Registration works

**Comment by ManonGros** [comment]
And that's the thinks I am testing

## IPT installation and setup

- [ ] Latest version on Tomcat

## Data Package administration

- [ ] Data Package schemas are installed and displayed (Expected 4 packages: Camtrap DP, ColDP, Material DP, Interaction DP)
- [ ] Data Package view is displayed
- [ ] Source file for the Data Package can be viewed in options
- [ ] All navigations, links and buttons work as expected

## Data Package management

### Camtrap DP

#### Creation

- [ ] Empty Camtrap DP resource creation
- [ ] Camtrap DP resource from an archive
- [ ] Camtrap DP resource from an IPT folder
- [ ] Camtrap DP resource from a metadata file (datapackage.json)

#### Overview: source data

- [ ] Create a new source of any type (File, URL, SQL)
- [ ] Create several sources at one by multiple file upload
- [ ] Source overwrite (file with the same name)?
- [ ] Action icons are functional (Edit, Download, Delete)
- [ ] Correct info is displayed (size, columns, rows, modification date etc.)

#### Source page

- [ ] Source details page is displayed
- [ ] Save works
- [ ] Options are functional (Analyse, Preview, Delete)
- [ ] Download source log works
- [ ] Help icons and their functionality work
- [ ] All navigations, links and buttons work as expected

#### Overview: mappings

- [ ] Create a new mapping
- [ ] Create multiple mappings at time
- [ ] Action icons are functional (Edit, Delete)
- [ ] Correct info is displayed (fields, modification date etc.)

#### Mapping page

- [ ] Mapping page is displayed
- [ ] Save works
- [ ] Automapping works
- [ ] Filtering works
- [ ] Translation works
- [ ] Required fields are marked with *
- [ ] Help icons and their functionality work
- [ ] Unmapped fields are displayed (if present)
- [ ] Options are functional (Hide/Show unmapped fields, Delete)
- [ ] All navigations, links and buttons work as expected

#### Overview: metadata

- [ ] Metadata edit works, opens Basic metadata page
- [ ] Metadata upload works (with or without validation)
- [ ] Chip displays valid info: Complete/Incomplete
- [ ] Correct info is displayed (modification date, metadata validity)

#### Metadata pages

- [ ] Basic metadata
- [ ] Geographic Scope
- [ ] Taxonomic Scope
- [ ] Temporal Scope
- [ ] Keywords
- [ ] Project
- [ ] Citation
- [ ] Other metadata

#### Overview: visibility

- [ ] Visibility change works

#### Overview: publication

- [ ] Change publishing organization works
- [ ] Publication modal is displayed when Publish is clicked, valid info is displayed
- [ ] Publication works

#### Overview: registration

- [ ] Registration works
