### ISSUE TITLE
Adding users with Admin role as Resource Managers

### ISSUE THREAD

**Issue by JamesDMSpeed** [gbif/ipt#2294]
IPT v 2.7.7

When adding a Resource Manager to an existing resource, the dropdown list does not include users who are Admins. 

![image](https://github.com/gbif/ipt/assets/33656875/7ac91b02-10d6-4d17-9b53-c701bacf2662)

**Comment by mike-podolskiy90** [comment]
Thank you for contacting us.
Yes, because admins by default have rights for all resources, you don't need to add them

**Comment by mike-podolskiy90** [comment]
Similar request https://github.com/gbif/ipt/issues/2204

**Comment by mike-podolskiy90** [comment]
Same request https://github.com/gbif/ipt/issues/1251

**Comment by mike-podolskiy90** [comment]
We should probably consider implementing it based on recurring user interest.

**Comment by mike-podolskiy90** [comment]
Not planning to implement this feature yet, see https://github.com/gbif/ipt/issues/2204
