### ISSUE TITLE
Basic metadata: License - media license error

### ISSUE THREAD

**Issue by ahahn-gbif** [gbif/ipt#2295]
The dropdown for "Media license" comments the selection of any value with an error message of "Name and/or path required". Filling this field is marked as mandatory; saving works regardless. The meaning of the error message is not quite clear.

**page link**: https://ipt3.gbif-uat.org/manage/camtrap-metadata-basic.do?r=more_camtrap
**screenshot**:
![image](https://github.com/gbif/ipt/assets/13435656/bbd4ca23-884c-4b9b-8585-c4ad9a2a58c7)

**Comment by mike-podolskiy90** [comment]
Thanks Andrea

It's a backend validation so error message does not disappear when you select the license.
Yes, message is confusing indeed, we hid rest of the license fields under the hood. I'll find a better error message

**Comment by mike-podolskiy90** [comment]
Fixed, deployed to UAT
