### ISSUE TITLE
Require protocol for `path`

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#2297]
Similar to homepage https://github.com/gbif/ipt/issues/2290, I would return an error if a provided `path` does not have a protocol. Currently the IPT allows them without http(s).

## Homepage

> A URL for the home on the web that is related to this data package.

**Require protocol** (already implemented)

## Image

> The value of the image property MUST be a string pointing to the location of the image. The string must be a url-or-path ...

Can technically be a local path (and could at a later point be supported by image upload in ipt), so fine without protocol.

## contributor.path

> A fully qualified http URL pointing to a relevant location online for the contributor.

**Require protocol**.

## sources.path

> A [url-or-path](https://specs.frictionlessdata.io/data-resource/#url-or-path) string, that is a fully qualified HTTP address, or a relative POSIX path ...

Can be a local path, but I'm not sure when that would be the case. I think it is safer to **require a protocol** and maybe update the help text.

## project.path

> Project website. (expected to be a uri: https://github.com/tdwg/camtrap-dp/blob/188d285a3765f379f7c16ac2f542090cc1dfc86a/camtrap-dp-profile.json#L202)

**Require protocol**.

**Comment by mike-podolskiy90** [comment]
Thanks, I'll fix

**Comment by mike-podolskiy90** [comment]
deployed

**Comment by mike-podolskiy90** [comment]
Oh, I require protocol for image too

**Comment by peterdesmet** [comment]
> Oh, I require protocol for image too

Up to you, depends on what implementation you envision in the future. Technically, could also be a local path to an image in the zip file.

**Comment by mike-podolskiy90** [comment]
Note: check empty value

**Comment by mike-podolskiy90** [comment]
I removed a protocol requirement from `image`. Deployed to UAT
