### ISSUE TITLE
Improve Source Analyze function

### ISSUE THREAD

**Issue by CecSve** [gbif/ipt#2298]
In the source page of a resource, when you click 'options' --> 'Analyse' you do not get any result. There appears to be something running for a couple of seconds, but the page remains the same. Are you supposed to see some analytics here?

**Comment by mike-podolskiy90** [comment]
Thanks Cecilie

No, it's actually not supposed to show anything. This is to ping the source to make sure it's readable

**Comment by CecSve** [comment]
what happens if it is not readable? @ahahn-gbif and I agree it would be nice with some visible outcome, otherwise, it seems almost like it does not do anything

**Comment by ahahn-gbif** [comment]
As a user, I had expected something like a breakdown of results of tests, similar to the publish button dialogue, or at least a feedback message showing something like "source can be read" (or maybe rather "source structurally correct" or similar - "readable" does not mean a lot to many users)

**Comment by mike-podolskiy90** [comment]
It's old IPT functionality. I agree it'd be useful to improve it in the future
