### ISSUE TITLE
Publish resource: typecast error message (wish for more concrete guidance on the source of the error)

### ISSUE THREAD

**Issue by ahahn-gbif** [gbif/ipt#2301]
On publication, the log reports a typecast error and a fail (see screenshot)

Base reason: a value translation from a numeric value to a string (4 values) in one table (deployments/cameraHeight); removal of the translations gets rid of this error.
The error message is not very informative for tracing the source of the error. If typecasts (understandably) are an issue, would they be better intercepted at the place they occur (adding translations)?

**screenshot**:
![image](https://github.com/gbif/ipt/assets/13435656/955d44da-e14b-43dd-a32e-5a3e95b48dd8)

**Comment by mike-podolskiy90** [comment]
Improvement for `tableschema-java` project to display meaningful error messages https://github.com/gbif/tableschema-java/commit/6593d4fca47bbeb7d9b93c0fe5523eb8c520274e

**Comment by mike-podolskiy90** [comment]
It's fine now. I've added some validation for the translations and also improved error messages.

**Comment by mike-podolskiy90** [comment]
Deployed to UAT
