### ISSUE TITLE
Can't do bulk publication - metadata missing when it looks like no metadata is missing

### ISSUE THREAD

**Issue by ManonGros** [gbif/ipt#2305]
I am using a local version of the IPT 3 [org/gbif/ipt/3.0-RC2-SNAPSHOT/ipt-3.0-RC2-20240124.165554-116.war](https://repository.gbif.org/repository/gbif/org/gbif/ipt/3.0-RC2-SNAPSHOT/ipt-3.0-RC2-20240124.165554-116.war)

I uploaded this archived https://download-directory.github.io/?url=https://github.com/tdwg/camtrap-dp/tree/1.0/example to the IPT.
and this one to the IPT: https://download-directory.github.io/?url=https://github.com/tdwg/camtrap-dp/tree/188d285a3765f379f7c16ac2f542090cc1dfc86a/example.
I added the license information. The IPT interface seems to show the metadata are complete for all my datasets:
<img width="1028" alt="Screenshot 2024-01-25 at 13 49 11" src="https://github.com/gbif/ipt/assets/7677271/0a9e9a41-ee22-4aff-9074-d2d3845b5f74">
But I can't seem to do any bulk publication. Clicking on the administration menu, "Bulk publication" then "Republish all resources" gives me these messages:
<img width="1320" alt="Screenshot 2024-01-25 at 13 49 01" src="https://github.com/gbif/ipt/assets/7677271/f13e007c-0c3d-4e41-a248-ccaee7c62eff">

**Comment by mike-podolskiy90** [comment]
It works now. Deploy to UAT
