### ISSUE TITLE
 IPT3 functional testing -> Mapping page -> Translation works -> do not allow translations that does not fit within constraints

### ISSUE THREAD

**Issue by CecSve** [gbif/ipt#2306]
As an example, in camtrap-dp/media, the `fileMediatype` values are constrained to (from the info button)
![billede](https://github.com/gbif/ipt/assets/54532645/6b3c46f2-91b6-4f79-ba9e-a8005c1a5568)

However, it is currently possible to add a translation that does not fit within the constraints without an error prompt, for example 
`image/jpeg` --> `jpeg`

Ideally, only translations for allowed values, or construction of allowed values, should be allowed.

**Comment by mike-podolskiy90** [comment]
Thanks!

**Comment by mike-podolskiy90** [comment]
This is fixed
