### ISSUE TITLE
Add more information about field on the translation page

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/ipt#2309]
Add info about type, constraints and examples if present.

**Comment by peterdesmet** [comment]
FYI, see [this template](https://github.com/tdwg/camtrap-dp/blob/188d285a3765f379f7c16ac2f542090cc1dfc86a/_layouts/tables.html#L39-L50) on how I retrieved type, constraints, examples from the Table Schemas to display at https://camtrap-dp.tdwg.org/data/
