### ISSUE TITLE
Manager (withour registration rights) not allowed to publish new versions after registering the resource

### ISSUE THREAD

**Issue by spalp** [gbif/ipt#2319]
Hi there, 

As regards the following dataset: https://cloud.gbif.org/eca/manage/resource?r=atlas_breeding_birds_bulgaria_2007, the author (a manager without registration rights) stopped being able to publish new versions after the source has been registered.
![image](https://github.com/gbif/ipt/assets/11872373/8bb33525-5ca3-43e8-88a9-2d5716e718db)

Even stranger, two days ago, when the dataset was not yet registered, each time he refreshed the resource page, a new version was published even though the auto-publication setting was off. This behaviour has now stopped but, as described above, now he cannot publish anymore (but I - as admin - can).

We tested with another resource that he created for a testing purpose: he could publish new versions of that new source (at least before registration) but still not of the other one. I am not sharing the link because we did not register the test resource but deleted it instead.

Any idea why this strange behaviour?

@ManonGros removed the same manager and then re-assigned him again. He logged out and deleted the browser's cash but the same error still appeared.

**Comment by mike-podolskiy90** [comment]
Thank you for reporting the issue. I'll have a look

**Comment by mike-podolskiy90** [comment]
That's actually an expecting behaviour. IPT manual https://ipt.gbif.org/manual/en/ipt/latest/manage-resources#publication

```
Once the resource is registered only users with the role "Manager with registration rights" can publish, since the resource’s registration gets updated during each publication
```

**Comment by spalp** [comment]
Thanks, Mikhail. I suspected this but wasn't sure. Apologies for not checking thoroughly in advance before posting here.


============

Salza Palpurina

GBIF Europe and Central Asia Regional Support Team

***@***.*** | skype hecksa

https://www.gbif.org<https://www.gbif.orgo>

<https://aka.ms/AAb9ysg>
________________________________

**Comment by mike-podolskiy90** [comment]
I'll have a look why new version may publish on update.
I'm closing this one.
