### ISSUE TITLE
Message before publication

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/ipt#2321]
Since we changed versioning for Data Package resources I think we should also change the message:

You are about to publish a new minor version of this resource. If there have been scientifically significant changes to the resource since the last publication, you should cancel, asdign this resource a new DOI, and then  publish again.

To:

You are about to publish a new version of this resource.

@peterdesmet Thoughts?

**Comment by peterdesmet** [comment]
> You are about to publish a new version of this resource.

Sounds good.
