### ISSUE TITLE
IPT reports no public access to ipt.gbif.org and cloud.gbif.org

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/ipt#2335]
Check probably doesn't work

**Comment by MattBlissett** [comment]
Ah, I've forgotten to deploy that service on the new server.

**Comment by MattBlissett** [comment]
It looks like https://github.com/gbif/validurl-ws might need some updates.

**Comment by mike-podolskiy90** [comment]
I'll update dependencies there

**Comment by MattBlissett** [comment]
You can deploy it as ws-validurl.war on the prod Tomcat server.

**Comment by mike-podolskiy90** [comment]
Deployed.
