### ISSUE TITLE
Automatic email with credentials sent to users when first registered

### ISSUE THREAD

**Issue by rubenpp7** [gbif/ipt#2350]
Hi,

I'm admin of a number of IPT instances.

Therefore I create accounts for users on request with some frequency. Sometimes I have had to create several tens of accounts.
What I have done in the past is sending an email to each user with their credentials but this can be very time consuming so I was looking for a more automated way of doing this.

Would it be possible to automatically send an email with the credentials and IPT instance to the email linked to a newly created account?

Thanks

**Comment by mike-podolskiy90** [comment]
Thank you for contacting us.

What version of IPT are you using please?

**Comment by mike-podolskiy90** [comment]
#2091 was implemented recently

**Comment by rubenpp7** [comment]
Ohhh you are a life saver!! :)
I hadn't notice it hahaha I have Version 2.7.6 so I'm fine

Thanks a lot!!
