### ISSUE TITLE
Asia IPT about page update

### ISSUE THREAD

**Issue by ckotwn** [gbif/ipt#2359]
We've changed the BIFA IPT to Asia IPT, though the "about" page still seems to merit an update. It reads:

> This IPT is hosted by GBIF to publish datasets from countries in Asia, who prefer not to run their own IPT. Some of those datasets were originally published in the context of the Biodiversity Fund for Asia: https://www.gbif.org/programme/82629/bifa-biodiversity-information-fund-for-asia For more information about BIFA, please contact the GBIF BIFA team: bifa@gbif.org

I suggest to edit it as:
`This IPT is hosted by GBIF to support data publishers in Asia. Some datasets were originally published in the context of the <a href="https://www.gbif.org/programme/82629/bifa-biodiversity-information-fund-for-asia">Biodiversity Fund for Asia</a>. For inquiries about using this IPT, please contact [asia_support@gbif.org](mailto:asia_support@gbif.org).`

See https://cloud.gbif.org/asia/about.do.

**Comment by mike-podolskiy90** [comment]
Thanks Chihjen, I've update the page.
