### ISSUE TITLE
Registration options' update registration is very slow

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/ipt#2360]
It takes too much time, make sure it works properly

**Comment by abubelinha** [comment]
I have not this issue, but I wonder if it is related.

I am migrating an old IPT in testing mode to a new server (different IP address).
I just did the same with our production server, clicked the "UPGRADE REGISTRATION" button and it just worked.

But the testing mode IPT fails with this message:

A bad request was issued. Please contact the GBIF Helpdesk (helpdesk@gbif.org) for help [https://gbrds.gbif-uat.org/registry/ipt/update/586ccccd-44a5-4c64-a414-43892f84f6f5]

IPT registration update failed! Update IPT registration failed: HTTP/1.1 400 Bad Request


I wonder if it is a bug, or perhaps the testing registry does not support upgrades at all.

**Comment by mike-podolskiy90** [comment]
Thank you, I'll have a look

**Comment by mike-podolskiy90** [comment]
Closing this
