### ISSUE TITLE
IPT test mode

### ISSUE THREAD

**Issue by melinalou** [gbif/ipt#2367]
Hi!
We 've faced an issue trying to publish dataset in the ipt test mode in order to test them through BioCheck.
It keeps giving us this message for 2 different datasets. And when I tried to delete rows until line 99 it says that has empty lines and then again the same problem when the datasets do not seem to be in incorrect format.Let me know if you have any idea!

![image](https://github.com/gbif/ipt/assets/117156896/855c000b-541f-4b16-9316-6cb5418acfab)

Also, do you know in which term of DWC terms should be the "station number"? Is it ok to be placed as verbatim locality?
Thank you very much!

**Comment by mike-podolskiy90** [comment]
Thank you for contacting us.
Looks like this issue https://github.com/gbif/ipt/issues/2231

**Comment by mike-podolskiy90** [comment]
The issue has been fixed in the 3.0.1. In prior versions you could use text files or URL data sources instead of Excel as a workaround
