### ISSUE TITLE
Automatically infer from source data

### ISSUE THREAD

**Issue by vidarbakken** [gbif/ipt#2368]
I have problems to automatically infer from source data in the metadata section. I get the message "No data mappings! Please create data mapping and try again". It is the same for Geographic Coverage, Taxonomic Coverage and Temporal Coverage. What kind of data mapping is this?

The tables are imported and mapped to DwC. We have IPT version 3.01. Earlier these functions worked.

**Comment by mike-podolskiy90** [comment]
Thank you for contacting us.
This might be a bug. Can I have the IPT logs please?

**Comment by vidarbakken** [comment]
Thanks for following up this! Here is the log:
https://www.dropbox.com/scl/fi/o0x9ekb4uwmdljgx5yq28/Log.txt?rlkey=nl4xyusgpk1levw8axf9vdy33&dl=0

**Comment by mike-podolskiy90** [comment]
Btw, have you tried to do `Re-infer`? Doesn't it help?

**Comment by vidarbakken** [comment]
Sorry, how do we re-infer?

**Comment by mike-podolskiy90** [comment]
There is a button, see example:
![Screenshot 2024-03-08 at 14 16 08](https://github.com/gbif/ipt/assets/24795387/c58d7d74-ecb5-4556-a57d-647b531a1282)
![Screenshot 2024-03-08 at 14 16 17](https://github.com/gbif/ipt/assets/24795387/b75f265a-5016-436c-ae99-e5d0975bd577)

**Comment by vidarbakken** [comment]
Yes, several times. When I tick it I get: No data mappings! Please create data mapping and try again

**Comment by vidarbakken** [comment]
Yes, that worked. Thank you!

**Comment by mike-podolskiy90** [comment]
Good. I'll create an issue to make it more obvious that that option exists
