### ISSUE TITLE
Do not display broken page when IPT has a wrong baseURL property

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/ipt#2371]
For example: IPT is misconfigured with the wrong `ipt.baseURL` property, but is accessible from a public URL. Then the IPT pages load but the styles are not available and don't work (broken page). IPT should warn about problems with the base URL property and probably render a simplified page instead.

**Comment by MattBlissett** [comment]
If it can detect this, then printing the current baseURL, a suggested baseURL using window.url from Javascript, and a link to the manual would be useful.

**Comment by mike-podolskiy90** [comment]
@MattBlissett What do you think please?

<img width="1296" alt="Screenshot 2024-03-19 at 18 35 09" src="https://github.com/gbif/ipt/assets/24795387/459e7142-9c4c-4334-859a-a794c175bcda">
