### ISSUE TITLE
ArrayIndexOutOfBoundsException after uploading multiple files

### ISSUE THREAD

**Issue by Kydae** [gbif/ipt#2381]
I wanted to replace the csv files because I have made correction. So I deleted the old ones and tried to upload the new ones but I got an error and I'm not able to manage this resource anymore. Here is the link of the dataset : "https://ipt.vliz.be/upload/resource?r=geochemical_data_on_otoliths_of_chaetodon_speculum_from_new_caledonia_2002-10"

**Comment by mike-podolskiy90** [comment]
@Kydae Thank you for contacting us

I need to know what your error is so I can help. Could you send me the log files and describe the problem in more detail?

**Comment by mike-podolskiy90** [comment]
Thank you for the explanation. So you tried to upload multiple files at once, right? Would it be possible to send me those files? Also, if it displays the error page, what's the stacktrace of the exception?

**Comment by Kydae** [comment]
Sorry I'm not sure i corrctly understand what you mean about 'stacktrace'. But here is a picture of the error page.
![image](https://github.com/gbif/ipt/assets/118560141/09e1f1b0-558b-468a-bf8a-a08c52ffda9d)
Yeah exactly and since I assumed the problem was due to the uploading of multiple files at once, I don't do it anymore and I have not encounter this issue again. I'm very sorry but I created another resource and kept working on those files so I didn't kept a backup of the version related to this error, it's my bad.

**Comment by mike-podolskiy90** [comment]
Is that all that is displayed please? There may be more detailed information just below the exception.

**Comment by Kydae** [comment]
Yeah that was everything that was displayed. I just tried to go back to the resource page (link in my first comment) to take another screenshot for you but now I can manage the resource again and I doesn't display an error page anymore. Did you fix the issue ?

**Comment by Kydae** [comment]
Since I've created another resource and I don't need this one anymore, can I delete it ? Or you still need it to identify where the issue came from ?

**Comment by mike-podolskiy90** [comment]
No, I'm not able to fix that remotely. Yes, you can delete the resource if you have another one.

**Comment by Kydae** [comment]
Ok thank you for you help. If you have any other questions, feel free but I think I've explained everything I could

**Comment by mike-podolskiy90** [comment]
Thank you

**Comment by Kydae** [comment]
![image](https://github.com/gbif/ipt/assets/118560141/72874130-0efc-41eb-ba62-a8e040e7f4e3)
My bad I was just viewing the resource but when i want to manage it the error page is still here. Sorry for the confusion.

**Comment by mike-podolskiy90** [comment]
I see it's a test installation. Would it be possible to update to the latest version (3.0.1) to make sure the error is still there?

**Comment by Kydae** [comment]
I'm not sure I'm allowed too, I will ask next week because I just left the work now

**Comment by Kydae** [comment]
I can't make the update myself but it will be done by the IT service at some point in time (I can't give you a precise date, sorry). I will add a comment here as soon as it's done.

**Comment by mike-podolskiy90** [comment]
Is this still an issue please? Otherwise, let's close it

**Comment by Kydae** [comment]
I think you can close it. Thank you for your time and your help !
