### ISSUE TITLE
Do not display the "Reserve DOI" button for resources with a publishing organization without an affiliation with DataCite.

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/ipt#2383]
Functionality should be hidden if:

- [x] There is no organizations associated with DataCite
- [x] Current user has no registration rights
- [x] Current publishing organization is not set or does not have DataCite association

@MattBlissett @CecSve did I miss anything?

**Comment by CecSve** [comment]
Sorry that I am late in following up. Just to make sure I understand.

Would the functionality be hidden if (keep in mind the original question was coming from a publisher on a cloud IPT:

- one or more organizations associated with the IPT has a DataCite account
- the user has registration rights
- the user (wrongly) choose the publishing organization with the DataCite association

@ymgan does this sound like the scenario you were highlighting, please?

**Comment by mike-podolskiy90** [comment]
Users without registration rights won't see the DOI button.

**Comment by ymgan** [comment]
Yes exactly as you highlighted @CecSve , thank you!! I can share the screenshot if it is clearer! The scenario I hope that this bug fix could prevent is: Reserved DOI button should be hidden from organization without DataCite account.

![image002](https://github.com/gbif/ipt/assets/11754081/686159bf-edfe-4d3e-98e3-72f7842b388e)

The Italian National Antarctic Museum does not have an associated DataCite account, so the "Resolve DOI" button should be hidden in the screenshot below.
![image003](https://github.com/gbif/ipt/assets/11754081/e9fd8667-dd68-4ac2-902d-66ca689f5b65)

**Comment by CecSve** [comment]
Ok thank you both - that seems to be resolved in the next version then.

**Comment by mike-podolskiy90** [comment]
The 3.0.2 already deployed to cloud.gbif.org
