### ISSUE TITLE
how to configure google analytics (GA4) for ipt?

### ISSUE THREAD

**Issue by CarmenLujano** [gbif/ipt#2389]
how to configure google analytics (GA4) for ipt?
GA4 does not finish configuring for ipt.gbif.es, has anyone managed to do it? You have to choose an option but I don't know which one is correct
![image](https://github.com/gbif/ipt/assets/14233154/20d5bce3-37eb-4bd3-9a6c-450018007838)

**Comment by vechocho** [comment]
Hola Carmen, 

A mí me salía en el proceso instalación manual arriba a la derecha

![image](https://github.com/gbif/ipt/assets/13081080/7a31de4f-2c37-4159-ae4e-29c675d9007e)

Luego copia el tag de google : G-5NZYRJXXXX, el que se coloca en el IPT

**Comment by CarmenLujano** [comment]
Muchas gracias!
