### ISSUE TITLE
IPT public access: Failed

### ISSUE THREAD

**Issue by vechocho** [gbif/ipt#2390]
We upgraded our IPT to version 3.x, since that we have the following error on our health status:

![image](https://github.com/gbif/ipt/assets/13081080/3e732297-bb99-4a59-beac-18fc6a4860b8)

This happens on all our installations.

IPT URL: https://patrimonio.ambiente.gob.ec/iptmae/health.do?request_locale=en

![image](https://github.com/gbif/ipt/assets/13081080/c0b7facb-3ee1-4fb9-b8fa-14bb9c075513)

**Comment by mike-podolskiy90** [comment]
@vechocho Thank you for contacting us

Our service reports that it's unable to access the IPT.
I checked your URL online here: https://whatsmychaincert.com/?patrimonio.ambiente.gob.ec/iptmae and it also reports problems.

Please check certificates on your end

**Comment by vechocho** [comment]
The certificate is valid for *.ambiente.gob.ec, so we don't know if there an additional configuration missing.

We generate a certificate for the ambiente.gob.ec domain and all subdomains

https://whatsmychaincert.com/?ambiente.gob.ec

**Comment by vechocho** [comment]
Was a problem with the provider. Its fixed now.
Thank you Mike
