### ISSUE TITLE
IPT / dataset

### ISSUE THREAD

**Issue by ninacourlee** [gbif/ipt#2398]
Dear IPT support,

I have a problem with my dataset publishing:

When Saving the metadata, it says "Oops" and shows this log message (attached),

but the main problem that it didn't Publish the update (it creates 0 records while there are about 6K in a new Pending version),

it seems that this dataset encountered some issues "without me doing anything", because i found it with zero metadata (they were removed somehow) a few days ago, then i tried to update the metadata, but Save button opens this "Oops" message any time (while still saving the changes.

![image](https://github.com/gbif/ipt/assets/90766905/28b2d92a-3c25-486b-8372-54aff4c529fb)

[IPT_issue.txt](https://github.com/gbif/ipt/files/14954494/IPT_issue.txt)

Nina

**Comment by ninacourlee** [comment]
Our IPT administrator initiated an update (now we are will on 2.5.6 version from 2022), i will let you know if this would help!

**Comment by mike-podolskiy90** [comment]
@ninacourlee Thank you for contacting us

Yes, let's have a look how it goes after update

**Comment by ninacourlee** [comment]
Thank you Mike, the issue was solved after update! Sorry for my fault.

**Comment by mike-podolskiy90** [comment]
Glad it solved!
