### ISSUE TITLE
Not possible to assign your own DOI (datacite)

### ISSUE THREAD

**Issue by katiagbif** [gbif/ipt#2399]
In the latest version 3.0.2, is not possible to assign your DOI. Our organization (GBIF Spain) has permission to do this and DATACITE is configured correctly. I can't find the old icon or alternative option to assign a new DOI.

**Comment by mike-podolskiy90** [comment]
@katiagbif Thank you for contacting us

Related issue https://github.com/gbif/ipt/issues/2383. We might made restrictions too strict. Could you please check you have these:

- Current publishing organization for the resource is associated with DataCite
- Current user has registration rights

**Comment by vjrj** [comment]
Hi @mike-podolskiy90, thanks for your fast response as usual:

![image](https://github.com/gbif/ipt/assets/180085/3da4be30-4bf6-4d0e-82e9-fb3364e49f5c)
![image](https://github.com/gbif/ipt/assets/180085/bdcf26ed-354e-4f2c-9d41-2bb8488145aa)

**Comment by mike-podolskiy90** [comment]
Is the publishing organization of the resource is GBIF Spain?

**Comment by vjrj** [comment]
It seems is not ![image](https://github.com/gbif/ipt/assets/180085/962d2d00-91c1-4d45-a6de-2653cdf9c820)

**Comment by mike-podolskiy90** [comment]
So the request was to disable functionality for organizations without DataCite association.
Ping @CecSve

**Comment by CecSve** [comment]
So in this case, GBIF Spain cannot assign DOIs on behalf of it s associated organizations because the publishing organization is not associated with a DataCite account?

**Comment by mike-podolskiy90** [comment]
@CecSve Correct. Maybe we should allow admins to do that

**Comment by CecSve** [comment]
I think allowing the admin to assign DOIs might fix the issue, yes. The feature was requested because users with registration rights on cloud IPTs could reserve DOIs even though their organization was not associated with a DataCite account (but because another oraganization also using the cloud IPT was, as far as I understand).

But this would mean that publishers on cloud IPTs would have to request their admin to assign the DOI, right?

**Comment by mike-podolskiy90** [comment]
Yes, requesting DOI actions every time doesn't sound convenient. So, we need a new function to enable DOI registration for not primary DataCite organizations. Temporal fix would be admins without restrictions.

**Comment by CecSve** [comment]
Would it be possible to allow for IPT admins to enable DOIs reservation for specific publishers? This way it could be a one time thing, ticking of which publishing organization could assign themselves.

**Comment by mike-podolskiy90** [comment]
@CecSve something like this? Organisation will be able to assign DOIs even though it's not associated with the DataCite directly

<img width="720" alt="Screenshot 2024-04-17 at 10 44 47" src="https://github.com/gbif/ipt/assets/24795387/d752bd9d-7756-46b8-b563-386ff6df7d0f">

**Comment by CecSve** [comment]
I had missed that an IPT can only be associated with one DataCite account. It seems not to be an issue currently, but could we foresee a scenario where more than one organization on a cloud IPT is associated with a DataCite account and want to be able to use their specific prefix - @dnoesgaard maybe you have an idea?

**Comment by dnoesgaard** [comment]
Only a few nodes have their own Datacite credentials for now, but this might change in the future.

**Comment by RicardoOrtizG** [comment]
Colombia is one of the countries that has the option to assign DOIs in the IPT. A lot of organizations don't have their own Datacite agreement and it's something that we offer as an advantage of mobilizing data through GBIF. I'm wondering based on the last post from @dnoesgaard  if there will be a change in the DOI assignations that impacts our current procedure. It will also allow us to move on with the IPT update to version 3.0.2. in which we are doing tests at the moment.

**Comment by katiagbif** [comment]
Spain is another country that has the option to assign DOIs in the IPT, offering this service to its publishers. The recent update impacts our current publishing process, so for now, we've reverted to the version that allows us to assign DOIs, pending further updates :)

**Comment by CecSve** [comment]
> Colombia is one of the countries that has the option to assign DOIs in the IPT. A lot of organizations don't have their own Datacite agreement and it's something that we offer as an advantage of mobilizing data through GBIF. I'm wondering based on the last post from @dnoesgaard if there will be a change in the DOI assignations that impacts our current procedure. It will also allow us to move on with the IPT update to version 3.0.2. in which we are doing tests at the moment.

In the IPT version 3.0.2 it is not possible to assign DOIs as a node. We made the change to fix an issue in the cloud IPT, but it unfortunately had this effect on the nodes who assign DOIs through their IPT. As mentioned [above](https://github.com/gbif/ipt/issues/2399#issuecomment-2068580561), the temporary fix would be to revert back to version 3.0.1, until 3.0.3 is released. Be aware [these issues](https://github.com/gbif/ipt/milestone/54?closed=1) will then not be fixed in version 3.0.1. we are very sorry for the inconvenience!

**Comment by CecSve** [comment]
Version 3.0.3 is released and nodes requiring the DOI fix can now update to the latest version https://ipt.gbif.org/manual/en/ipt/latest/releases. IPT admins now have to check a box that allows the publishing organization to assign DOIs to the datasets they publish through the IPT.

**Comment by katiagbif** [comment]
Thank you all very much. I've successfully assigned DOIs with this new version :)
