### ISSUE TITLE
After IPT update, there isn't any more organisation registered

### ISSUE THREAD

**Issue by ManonGros** [gbif/ipt#2401]
I am logging this issue from Helpdesk. 
When publishers updated their IPT, the datasets were migrated (and show as registered in the IPT) but there is no publishing organisation: neither on the administration of organization side nor on the dataset "publishing organisation" field. They also checked the resource.xml files and couldn't find the organisation keys either.

**Comment by mike-podolskiy90** [comment]
Thanks Marie

**Comment by mike-podolskiy90** [comment]
@ManonGros Do they have backups please? They also need to make sure `config/registration2.xml` is present and contains organizations.

**Comment by ManonGros** [comment]
Thanks @mike-podolskiy90 I will ask.

**Comment by mike-podolskiy90** [comment]
`registration2.xml` file is actually present (it's stated in the logs). So the only I can guess that resources were corrupted somehow. They need to re-create resources from backups (if they have them).
