### ISSUE TITLE
MIxS terms broken

### ISSUE THREAD

**Issue by thomasstjerne** [gbif/ipt#2404]
We are trying to import a DWC archive from the eDNA tool into [ipt.gbif.org](http://ipt.gbif.org/).
We get these error messages:
Skipped mapped term https://w3id.org/mixs/0000050, which is unknown to extension http://rs.gbif.org/terms/1.0/DNADerivedData
Skipped mapped term https://w3id.org/mixs/0000092, which is unknown to extension http://rs.gbif.org/terms/1.0/DNADerivedData
The source archive uses the unmapped terms, which correspond to the xml definition of the extension:
<field default="Environmental DNA metabarcoding differentiates between micro-habitats within the rocky intertidal" term="https://w3id.org/gensc/terms/MIXS:0000092"/>
Recently, Matt added some mapping mechanism from
ttps://w3id.org/mixs/0000092 => https://w3id.org/gensc/terms/MIXS:0000092
It seems the IPT knows this mapping, but that somehow it breaks the use of the DNA derived data extension.

**Comment by mike-podolskiy90** [comment]
@thomasstjerne I suppose after releasing a new version of the extension we can close this one
