### ISSUE TITLE
no background tiles loaded in IPT geographic range metadata editor

### ISSUE THREAD

**Issue by PietrH** [gbif/ipt#2406]
In the IPT metadata editor, under geographic range, a leaflet interactive map is rendered. This map uses Stamen background tiles. 

![image](https://github.com/gbif/ipt/assets/48065851/efc9b34b-7c9d-40c4-bbb7-56c26c620776)

I believe Stamen no longer provides free tiles ever since they got merged/aquired by Stadia, more information here: https://maps.stamen.com/stadia-partnership/

A possible solution would be to switch to a different background tile provider, or to start paying Stadia.

**Comment by mike-podolskiy90** [comment]
Please update to the latest version. Closing this.
