### ISSUE TITLE
IPT publication fails when basisOfRecord is MaterialEntity

### ISSUE THREAD

**Issue by dbloom** [gbif/ipt#2408]
@mike-podolskiy90 I have several collections on the Vertnet IPT that have begun to use "MaterialEntity" as the basisOfRecord per the recommended vocabulary, https://dwc.tdwg.org/terms/#dwc:basisOfRecord.  These collections all fail with the expected error "X line(s) have basisOfRecord that does not match the Darwin Core Type Vocabulary (please note comparisons are case insensitive)".

Is this vocabulary going to be updated in 3.1 or earlier or is this update something that will proceed in parallel with the data model implementation? If the latter, it would be good for you to know that there are terms in that vocabulary that are unavailable within the IPT and also in the search U/I of the GBIF portal. Many thanks for your recommendation.

**Comment by mike-podolskiy90** [comment]
Hi David! I've just checked the IPT and discovered it uses outdated versions of the Occurrence extension and Darwin Core Basis of Record Vocabulary. Those should be updated to support `MaterialEntity`. If you don't mind I'll update them or you can update them yourself.

**Comment by dbloom** [comment]
Thanks @mike-podolskiy90. I suppose those much have been carried over when we moved to GBIF's cloud infrastructure. Probably a poor assumption on my part that everything would update. If you feel like an easy win and are able to update, it would be amazing to sit down on Monday morning my time with that one already off of my plate. If you can't do it, please let me know.

**Comment by mike-podolskiy90** [comment]
It seems everything has been updated there now. This shouldn't be a issue anymore

**Comment by dbloom** [comment]
@mike-podolskiy90 What was I thinking and why am shrinking from the responsibilities as a node manager? I've updated and republished all resources successfully. Not sure why I assumed everything would update after the change of infrastructure. Just a lazy bag of bones, I suppose. Thank you for the support and the reminder to be sure I am up-to-date.

**Comment by mike-podolskiy90** [comment]
It's good that everything works now! 
I've been thinking about email notifications in case of using outdated extensions. Maybe we should implement that

**Comment by dbloom** [comment]
That could be helpful, but would that notification go to all Admins or can specific Admins be selected? We have multiple Admins, but not all of them need to, or should, receive a notice like this.

**Comment by mike-podolskiy90** [comment]
@dbloom This can be easy configurable. I think we need to create a task for that to start discussion
