### ISSUE TITLE
Metadata Geographic Coverage: bounding box crossing the dateline not possible

### ISSUE THREAD

**Issue by ahahn-gbif** [gbif/ipt#2412]
For a dataset whose coordinates fall into a band both west and east of the dateline (-180/180), it is not possible to express the bounding box in a way where both (a) the box displays correctly and also (b) the coordinates underneath get accepted at saving. The related support case (helpdesk, May 2, 2024) has these coordinate values: South West [48.665, -178.644], North East [69.794, 179.429]

Example (a) - the coordinates express the values, but the bounding box misrepresents them and covers the inverse range of longitudes:

![image](https://github.com/gbif/ipt/assets/13435656/6112ac91-c4ce-4271-bcec-c3e539219bc0)

Example (b) - here, the bounding box shows the correct location, but the coordinates now fall outside of validation range, preventing saving:

![image](https://github.com/gbif/ipt/assets/13435656/c3567db7-5f1b-4999-bac7-a785c4604de6)

The

**Comment by mike-podolskiy90** [comment]
Thanks Andrea.
