### ISSUE TITLE
Is the last step of the resource migration redundant now?

### ISSUE THREAD

**Issue by CecSve** [gbif/ipt#2417]
Feedback on [Manage Resources Menu](https://ipt.gbif.org/manual/en/ipt/latest/manage-resources) ([Github source for this page](../blob/master/docs/en/modules/ROOT/pages/manage-resources.adoc))

Helpdesk no longer need to update the endpoint in the registry [when a resource is migrated following the guide ](https://ipt.gbif.org/manual/en/ipt/latest/manage-resources#migrate-a-resource) since the endpoint is updated automatically (old IPT -> new IPT). Would it make sense to remove step 10 of the guide? Or maybe only keep point 10C, as I think we would still need to do that.

**Comment by mike-podolskiy90** [comment]
Thanks Cecilie.
We can also keep it, but add a note that it only applies to older versions of IPT.

**Comment by CecSve** [comment]
Yes, that could work too.

**Comment by mike-podolskiy90** [comment]
You can submit a pull request for any solution you like best. I'm fine with any.
