### ISSUE TITLE
Split EML basic metadata page

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/ipt#2419]
The basic metadata page is becoming more and more cumbersome. There will be three more large text inputs for the `gettingStarted`, `introduction` and `acknowledgements`. Apart from that there will be many changes to contact blocks.

Therefore, I suggest splitting the page into a couple (at least two) pages. Then `Resource contact`, `Resource creators` and `Metadata Providers` will have a separated page (`Contacts`? Name TBD). Alternatively, contacts/creators/providers can be moved to the Associated party page (then the page should be renamed?).

**Comment by mike-podolskiy90** [comment]
@gbif/dataproducts @laurarussell

**Comment by EstebanMH-SiB** [comment]
I think that having a Contacts and Associated Parties sections can be confusing for the publishers. Can they be merged in one section? Being explicit what contacts will be part of the Resource Citation and which ones will only be associated parties?

I am not familiar with EML 2, so sorry if this question is redundant

**Comment by mike-podolskiy90** [comment]
@EstebanMH-SiB Thank you for your comment

It might be a good idea to merge them. EML 2.2.0 is not that different than EML 2.1.1

**Comment by CecSve** [comment]
> Being explicit what contacts will be part of the Resource Citation and which ones will only be associated parties?

+1 - if possible, then also have the different contact fields listed in the order they would appear in the citation. I think `Contacts` would be a fitting name for the page.

What kind of information could go in the associated parties page? Is it person-specific or could it be organizations etc. as well? Sorry if this is documented elsewhere but I could not find that specific information.

**Comment by ManonGros** [comment]
I think that having the contacts on a separate page (called `contacts`) and having some visual cue to emphasise the contacts that will appear in the citation is a very good idea.

Would it make sense to have `acknowledgements` as a separate tab? or does it need to be with the rest of the basic metadata?

**Comment by mike-podolskiy90** [comment]
Thanks @CecSve 

I believe we already preserve the order of the people in the citation. There are some differences between IPT and portal though.

Data stored into EML's `associatedParty`, description:

```
The 'associatedParty' element provides the full
            name of other people, organizations, or positions who should be
            associated with the resource. These parties might play various
            roles in the creation or maintenance of the resource, and these
            roles should be indicated in the "role" element.
```

**Comment by mike-podolskiy90** [comment]
Thanks @ManonGros 

Do you mean a dedicated page please? If so, then yes, of course we can do that.

**Comment by mike-podolskiy90** [comment]
> having some visual cue to emphasise the contacts that will appear in the citation

Sounds good, just wondering what it would look like in the UI

**Comment by mike-podolskiy90** [comment]
Maybe some sort of a visual marker? I'll try a couple of options and will share examples here.

**Comment by mike-podolskiy90** [comment]
@CecSve @ManonGros What do you think of this placement:

![Screenshot 2024-06-25 at 16 42 07](https://github.com/gbif/ipt/assets/24795387/71f7dbd3-46e8-4c2a-b58d-0786a3a4d865)

We can change color/wording/form of the badge.

This is going to be a new page, that will replace the Associated parties one.

**Comment by ManonGros** [comment]
Thanks Mikhail, I think the badge is easy to spot (which is nice). Should we specify that it is the `suggested citation on GBIF.org`? Or is it too long of a sentence?

**Comment by mike-podolskiy90** [comment]
Maybe a bit too long?

![Screenshot 2024-06-26 at 10 10 43](https://github.com/gbif/ipt/assets/24795387/627c7733-cce2-4a16-a53c-38df6ed0ff84)

**Comment by ManonGros** [comment]
Yes it looks too long, maybe let's keep the previous text. If we get a lot of confused users, we can always change it.

**Comment by mike-podolskiy90** [comment]
This is done, but not deployed to test yet. I'll deploy it later for testing when the rest of the env(registry, crawler etc.) will be ready.
