### ISSUE TITLE
Add new inputs for `relatedProject` and `projectAward` to the project metadata section

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/ipt#2420]

**Comment by mike-podolskiy90** [comment]
Both multi-valued

**Comment by dbloom** [comment]
@mike-podolskiy90 Will this upgrade permit multiple funders and identifiers (e.g., a GBIF BID ID as well as a project ID that comes from an additional funder)?

Please excuse me if this issue is intended in another way.

**Comment by mike-podolskiy90** [comment]
Thanks David

Multiple identifiers are not allowed by the EML schema as far as I know.
