### ISSUE TITLE
Add new rich-text inputs for `gettingStarted`, `introduction`, `acknowledgements`

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/ipt#2422]

**Comment by CecSve** [comment]
Would this replace the description field or added as separate fields? I would be in favour of replacing but maybe this has been discussed elsewhere.

**Comment by mike-podolskiy90** [comment]
Thanks Cecilie.
It does not. There will be new inputs.

**Comment by CecSve** [comment]
Ok - I wonder if publishers might get confused about what to include where when it comes to describing their dataset. But if the descriptions of the fields as laid out [here](https://github.com/gbif/eml-profile/issues/5#issue-1839276298) can be included as a fact/help box, then it would be good.
