### ISSUE TITLE
Apply changes to agent blocks(`contact`, `creator`, `metadata provider`, `associated party`, `project personnel`)

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/ipt#2423]
New input:

- salutation

Changes:

- position multi-value
- email multi-value
- phone multi-value
- homepage multi-value
- address multi-value
- identifiers multi-value

For project personnel add a `salutation` input.

**Comment by mike-podolskiy90** [comment]
![Screenshot 2024-05-22 at 11 39 18](https://github.com/gbif/ipt/assets/24795387/c7d20a72-4b74-48c9-b2d0-d7d7048b9cd7)

**Comment by CecSve** [comment]
For `salutation`, is the plan to show it on the GBIF UI of the dataset? Salutions go different places (before or after the name) depending on what the salutation is e.g., `Cecilie Svenningsen, PhD` or `Dr. Cecilie Svenningsen` so it may be difficult to show correctly.

**Comment by mike-podolskiy90** [comment]
Thanks, that's a good question. I assume we'd like to display them. Currently, we have salutations in the directory as far as I know. Maybe @MortenHofft has something to say

**Comment by mike-podolskiy90** [comment]
But I suppose we're going to have before-name salutations since they're the most common ones in most cases.
