### ISSUE TITLE
IPT allows publication of the resource with a project with no personnel

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/ipt#2425]
At least one personnel is required according to EML schema (both 2.1.1/2.2.0)
Although IPT saves the data without any issues and allows to publish it.

**Comment by mike-podolskiy90** [comment]
Initially it wasn't like this, was changed here #1760 
@gbif/dataproducts I'm afraid we need to revert it. Otherwise, we produce invalid EML.

**Comment by ahahn-gbif** [comment]
We need to evaluate possible work-arounds. BID and BIFA (and other projects in the past) were never required to provide a project contact, and may not always be able to provide one when metadata updates fail for that reason.
Suggest to:
- explore whether to enable and support use of a default value
- provide easy-to-interpret error messages when dataset metadata cannot be saved/updated for that reason

**Comment by mike-podolskiy90** [comment]
@gbif/dataproducts I'm going to start testing the EML update this week including this one. I don't think we can find a default value suitable for everyone here. So, I suppose, we just need to display a comprehensive error message. 
Do you have any ideas/suggestions please?

**Comment by ManonGros** [comment]
How about a message like "At least one project contact is now mandatory. Please add a contact person to the project tab." would that be ok? Maybe @ahahn-gbif has some better suggestion.

**Comment by mike-podolskiy90** [comment]
Thanks Marie.

Do you want to display this message somewhere other than the project metadata page itself? Otherwise, we probably don't need to mention "to the project tab" if we're already on that page.

**Comment by ManonGros** [comment]
@mike-podolskiy90 I am thinking of these cases where publishers have a dataset with a projectID and no project contact. They might just want to add records to their dataset and republish the archive without changing the metadata. In that case, I imagine that they won't be on the project tab when the error appears. They will likely be on the page that comes after pressing the publish button.

**Comment by mike-podolskiy90** [comment]
I see. Yes, we need to display that on the resource overview page then.
