### ISSUE TITLE
File format being changed

### ISSUE THREAD

**Issue by pcrjoana** [gbif/ipt#2426]
Hello,

I'm trying to publish to IPT and I've encountered an issue. I publish an EMOF table in csv format file, and this particular file has a quite long line. When I try to publish, I get the error that not all lines in emof have an eventID, which is not true. What's happening is that the tool is converting my csv file to text, removing line numbers, and separating the long line into two. I've tried uploading also with a tab separator, and I get the same issue. Can someone help me with this, please? Just to summarise, I have no issues opening my file before upload to the IPT tool, but if I then upload and consequently download the file from the tool, it becomes scrambled.

Thank you in advance.
Kind regards,
Joana

**Comment by mike-podolskiy90** [comment]
Thank you for contacting us.
If you send me a file I'll have a look

**Comment by mike-podolskiy90** [comment]
Do you use the latest IPT please? The 3.0.4 currently

**Comment by rubenpp7** [comment]
Hi, version used is Version 2.7.6

**Comment by pcrjoana** [comment]
Just sent you the file via email. :-)

**Comment by mike-podolskiy90** [comment]
@pcrjoana Recieved, thank you!

**Comment by mike-podolskiy90** [comment]
@pcrjoana Are you trying to publish it as the Darwin Core Event please? Apart from being present, `eventID` must also be unique, which is not the case for your data.

**Comment by mike-podolskiy90** [comment]
When downloaded the file looks odd indeed, but it the data itself is still valid

**Comment by pcrjoana** [comment]
It's not an event, it's an extended measurements or facts file. So the EventID doesn't need to be unique. I still can't publish it, and the error given is that not all lines in the emof file have an eventID. This is because it's separating one long line into two.

**Comment by mike-podolskiy90** [comment]
I think I need to see your mappings

**Comment by rubenpp7** [comment]
Hi @mike-podolskiy90 

I've made an account for your in the IPT instance where the issue happens, let me know if you can see/edit the IPT resource
IPT resource url is https://ipt.vliz.be/upload/resource?r=ices-vme

**Comment by mike-podolskiy90** [comment]
Thank you. I'm not authorised to edit the resource

**Comment by mike-podolskiy90** [comment]
Thank you for the access. I've tested a couple of options. With the current IPT versions (the 3.0.4) it works fine when you use the source data in `.xlsx` format. So I'd suggest you to update the IPT and use that.

I'll try to address this issue in one of the upcoming releases.

**Comment by mike-podolskiy90** [comment]
There are some cells with the data like this:

```
Ruhl. H.A.. 2012. RRS James Cook Cruise 62. 24 Jul-29 Aug 2011. Porcupine Abyssal
Plain â€“ sustained observatory research. National Oceanography Centre Southampton.
Southampton. UK. pp. 119 (National Oceanography Centre Cruise Report 12).
```

with line breaks and it does not work properly. Should be fine in Excel.
