### ISSUE TITLE
Unable to use some URL as a data source

### ISSUE THREAD

**Issue by MichalTorma** [gbif/ipt#2432]
I found this issue with the URL data source when the URL has GET parameters containing dot `.` after the last `/`
IPT throws an error `not supported extension`
An example URL is one for the postgREST server: https://geoserver.ibot.cas.cz/rest/gbif_export?project=eq.10000
The data is loaded normally when you hide the URL behind bit.ly

Pull request coming soon

**Comment by mike-podolskiy90** [comment]
Thank you!

**Comment by mike-podolskiy90** [comment]
PR merged, closing this.
