### ISSUE TITLE
Non exiting resource returns 200 ok

### ISSUE THREAD

**Issue by mdoering** [gbif/ipt#2437]
This IPT returns a 200 OK http response for a non existing resource:
http://www.csbg.nsc.ru:8080/ipt/archive.do?r=coenoflora_lsas1

it gives an html page, but it should really return an http 404 so it can be easily handled by software

**Comment by mdoering** [comment]
version IPT Version 2.3.6-r3985b6a

**Comment by mike-podolskiy90** [comment]
Thanks Markus

I believe this was fixed a while ago, Matt did that as far as I remember.

**Comment by mdoering** [comment]
ah, so its just an old IPT. I was wondering about that already

**Comment by mike-podolskiy90** [comment]
Resolved here https://github.com/gbif/ipt/issues/1427
Seems working as expected on new IPTs
