### ISSUE TITLE
IPT couldn't update a vocabulary without `issued` date

### ISSUE THREAD

**Issue by rondlg** [gbif/ipt#2439]
Hi,

We were trying to update a sightings resouce by mapping basisOfRecord to a field in our csv however, we include the values that are required by dwc (and recommended by the ipt)

- MaterialEntity
- PreservedSpecimen
- FossilSpecimen
- LivingSpecimen
- MaterialSample
- Event
- HumanObservation
- MachineObservation
- Taxon
- Occurrence
- MaterialCitation

![image](https://github.com/gbif/ipt/assets/702709/350f84d2-7c02-4309-99d1-8dbf2ddf07e3)

however the ipt seems to actually want (and only works with) values with spaces.

- Human Observation
- Fossil Specimen
- Living Specimen
- Machine Observation
- Preserved Specimen
- (MaterialSample and Occurrence) are correct.

![image](https://github.com/gbif/ipt/assets/702709/4fa74123-ec06-4555-bfe8-adcbede9e0dc)

At the moment the dataset only includes Human Observations so we were able to use the override for now.

Mammal Sightings is the resource that we tested with: https://fmipt.fieldmuseum.org/ipt/manage/resource?r=fmnh_mammals_sightings

Would be great to get this fixed.

**Comment by mike-podolskiy90** [comment]
Thank you for contacting us.

This might be a misunderstanding. Values ​​with spaces are display values ​​only. The actual values ​​in the results archive will be as expected, with no spaces.

**Comment by rondlg** [comment]
Thanks - when we try to publish the dataset with basisOfRecord from the csv we get a fail. Switching to the mapped field publishes.

***

16:35:28 Archive generation started for version #1.6
16:35:28 Start writing data file for Darwin Core Occurrence
16:35:28 Data file written for Darwin Core Occurrence with 1422 records and 59 columns
16:35:28 Start writing data file for Audubon Media Description
16:35:28 Data file written for Audubon Media Description with 16 records and 40 columns
16:35:28 All data files completed
16:35:28 EML file added
16:35:28 meta.xml archive descriptor written
16:35:28 Validating the core file: occurrence.txt. Depending on the number of records, this can take a while.
16:35:28 ? Validating the core basisOfRecord is always present and its value matches the Darwin Core Type Vocabulary.
16:35:28 ? Validating the core ID field occurrenceID is always present and unique. Note: the core ID field is required to link core records and extension records together.
16:35:28 ✓ Validated each line has a occurrenceID, and each occurrenceID is unique
16:35:28 140 line(s) have basisOfRecord that does not match the Darwin Core Type Vocabulary (please note comparisons are case insensitive)
16:35:28 Archive validation failed, because not every row in the occurrence file(s) has a valid basisOfRecord (please note all basisOfRecord must match Darwin Core Type Vocabulary, and comparisons are case insensitive)
16:35:28 Restored version #1.5 of resource fmnh_mammals_sightings after publishing failure

**Comment by mike-podolskiy90** [comment]
I think the issue is with the Darwin Core Type Vocabulary, it could not be updated in the IPT. The vocabulary in your IPT does not have the issued date. I'll address it so IPT can handle such a case.

**Comment by rondlg** [comment]
Thankyou. Let me know when I should try again.

**Comment by mike-podolskiy90** [comment]
I've fixed the issue but it'll require a new version release. I'll let you know when it's ready.

**Comment by rondlg** [comment]
Many thanks - we have it in our queue to update. Will let you know when that's done and we've republished.
