### ISSUE TITLE
Your IPT manual examples of the metadata 

### ISSUE THREAD

**Issue by kmexter** [gbif/ipt#2442]
Feedback on [GBIF Metadata Profile – How-to Guide](https://ipt.gbif.org/manual/en/ipt/latest/gbif-metadata-profile) ([Github source for this page](../blob/master/docs/en/modules/ROOT/pages/gbif-metadata-profile.adoc))

The example in the link in the sentence
An example EML complying with v1.1 of the GBIF Metadata Profile can be found [here](https://cloud.gbif.org/griis/eml.do?r=global&v=2.0). Note this file has been generated by the [GRIIS IPT](https://cloud.gbif.org/griis/).

is a dead link

**Comment by mike-podolskiy90** [comment]
Thank you, we'll fix the link

**Comment by mike-podolskiy90** [comment]
I've removed the section.
