### ISSUE TITLE
Source data file upload issue

### ISSUE THREAD

**Issue by mikaelhedblom** [gbif/ipt#2443]
I have a problem uploading a new version of source data in the test IPT.

This is how I always have been uploading new versions of the datasets, however now when trying it does not work anymore.  

I want to upload a file in .zip format. The upload is competed however the files in the IPT is not changing. Image attached below is from yesterday (2024-06-12) however files are dated 2024-05-13. I have also tried deleting the files in the IPT before uploading new files however it does not work either and now I don't have any files in the IPT as well as I have lost the mapping.

Any suggestions of what the problem could be?

<img width="832" alt="upload2" src="https://github.com/gbif/ipt/assets/105280806/626863fe-dec0-460b-80f8-7b4d56b8d794">

**Comment by rubenpp7** [comment]
IPT resource affected: https://ipt.vliz.be/upload/resource?r=shark-epibenthos-nat

**Comment by mike-podolskiy90** [comment]
I think I need access to your IPT to figure that out. I've tried this on my local IPT and our test one and it seems working fine.

**Comment by rubenpp7** [comment]
Hi @mike-podolskiy90 
I've added you as a manager for the IPT resource

**Comment by mike-podolskiy90** [comment]
Thank you. Would it be possible to grant me admin rights? I need to check the logs

**Comment by mike-podolskiy90** [comment]
It seems it works for me too at ipt.vliz.be

**Comment by rubenpp7** [comment]
@mike-podolskiy90 admin rights granted

**Comment by mike-podolskiy90** [comment]
@mikaelhedblom I can't reproduce your issue. Maybe it was something wrong with the data?

**Comment by mikaelhedblom** [comment]
@mike-podolskiy90 thank you for troubleshooting! I got it to work now and what I did was: first trying to upload another file (different dataset), and that worked well. I then deleted these files and tried again with the file I had issues with, and now it did go through. not sure why this happened... :sweat_smile:

**Comment by mike-podolskiy90** [comment]
Good it works now!
