### ISSUE TITLE
Taxonomic Scope Description automatically repeats contents

### ISSUE THREAD

**Issue by dbloom** [gbif/ipt#2445]
An addition to the wonderful oddities of the IPT.  In this VertNet resource, when any description is added into the Taxonomic Coverage Description field, it is automatically duplicated over and over (tens or hundreds of times) after Save.

This happens in both Metadata-only an Occurrence Core settings. We have attempted to clear the field and re-enter the single sentence by typing and via cut/paste from multiple different apps (Notes, BBEDdit, Word, etc). We have also attempted to "Remove this taxonomic Coverage" and start fresh, but the result is always the same.

The intended sentence is simply "We captured 4,278 individual bats of 40 species belonging to nine families, which represents nearly half of all bat species distributed across the seven focal countries." I have left this in it's current state for your review. I haven't seen this behavior before.

Should I export the EML and start a new resource? It would be a shame to have to re-enter all of the metadata manually.

**Comment by mike-podolskiy90** [comment]
That's something new, never seen this behaviour before. I'll have a look tomorrow morning

**Comment by mike-podolskiy90** [comment]
I downloaded the resource from the IPT and I think I found the issue.
I couldn't manage to fix it on UI in the current version, so new release will be required. I'll try to it next week.

**Comment by dbloom** [comment]
Thanks @mike-podolskiy90 

I am always happy to break things in order to keep you employed. We'll keep an eye out for the update.

**Comment by mike-podolskiy90** [comment]
@dbloom I've managed to fix the resource on the Vetnet IPT (I suppose this one https://ipt.vertnet.org/manage/metadata-taxcoverage.do?r=eha_wabnet right?)
The problem is that IPT sends two descriptions instead of one, it is duplicated since there is one for the case when "Automatically infer from source data" is selected. I'll address it soon. Currently, if you have any similar issues with other resources - just let me know.

**Comment by ManonGros** [comment]
We have a similar issue on this dataset: https://cloud.gbif.org/lac/manage/resource.do?r=aves_del_palmar (LAC IPT). The taxonomic description is repeated and I cannot delete it either. See this recording:

https://github.com/gbif/ipt/assets/7677271/9095bf0d-81b2-46f6-bb6c-b71f79333adc

**Comment by mike-podolskiy90** [comment]
Thanks Marie. I'll release a new version soon

**Comment by dbloom** [comment]
Thank you @mike-podolskiy90. I appreciate the individualized correction on this one. We were able to publish as a metadata-only resource. By the time we're ready to convert to occurrences you'll have this fixed and updated. I'll let you know if other resources experience that same.

**Comment by mike-podolskiy90** [comment]
FYI, this is deployed to cloud.gbif.org

**Comment by EstebanMH-SiB** [comment]
Dear @mike-podolskiy90 , I would like know if you could share the steps to correct this problem in an specific dataset, we have one[dataset](https://ipt.biodiversidad.co/sibm/resource?r=crinoidea_pacifico#anchor-taxanomic) that a publisher wants to fix as soon as possible.
We will evaluate if we migrate our IPT to 3.0.6 but that will take time, so if you could share the steps to solve it in the meantime that would be great, thanks!

**Comment by mike-podolskiy90** [comment]
The problem is that there are two inputs with the same id on the page (one of them is hidden). One should be deleted/disabled. That can be done via browser web tools. I can share more details tomorrow.

**Comment by peterdesmet** [comment]
😅 this issue got us dumbfounded too. Good to see it has been reported and resolved in 3.0.6. For future reference: in IPT 3.0.5 the taxonomic description retains old info with no possibility to remove. For example:

1. Open Taxonomic description and save: empty description box appears
2. Save again: description contains `,`
3. Save again: description contains  ` , ,`
4. Replace content with `My description.` and save: description contains `My description., , , , `
5. Replace content with `Second attempt at my description.` and save: description contains `Second attempt at my description., My description., , , , `
6. Etc.

Resulting in:

<img width="912" alt="Screenshot 2024-09-13 at 10 44 20" src="https://github.com/user-attachments/assets/355e110c-8112-4004-8a2a-1d0093faccb0">
