### ISSUE TITLE
Additional logging of account change operations

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/ipt#2448]
We have a case where someone demoted the role of an administrator to a manager without approval. It would be useful to have information about which admin performed the operation.

Also, I have concerns about usage systems@gbif.org user on production (cloud) IPTs. I think we should use our dedicated accounts instead, otherwise it's unclear who is behind systems@gbif.org.

Any thoughts @gbif/dataproducts @MattBlissett

**Comment by ManonGros** [comment]
Yes, I agree that if we want to track changes, we should using individual admin accounts
