### ISSUE TITLE
Cannot update auto-publishing time

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#2463]
For one of our resources we have an auto-publication set to Wednesday at 12:00:

<img width="477" alt="Screenshot 2024-07-12 at 12 09 05" src="https://github.com/user-attachments/assets/95bd3bd0-a840-42a8-a1ff-4f848761781d">

1. Try to update the time to `14:00` and save
2. I see the resource overview page
3. I go and open the auto-publication page
4. The time is still set to `12:00` and was not updated.

Note: if I update the day from `Wednesday` to `Tuesday, that is saved. It is only the time part that does not work.

**Comment by mike-podolskiy90** [comment]
Thank you Peter, I'll fix

**Comment by peterdesmet** [comment]
Note: even if I remove the auto-publishing and re-enable it, I cannot set the timestamp to anything other than `12:00` 😄
