### ISSUE TITLE
Problema al descargar el listado de Hongos de Chile

### ISSUE THREAD

**Issue by zenonmardones** [gbif/ipt#2465]
Al intentar abrir el archivo ZIP, aparece un error, el cuál no permite abrirlo, al parecer el archivo se encuentra corrupto.

Favor de revisar. Gracias

https://gbif-chile.mma.gob.cl/ipt/resource?r=checklist_fungilab

**Comment by mike-podolskiy90** [comment]
Thank you for contacting us. We'll have a look

**Comment by mike-podolskiy90** [comment]
@zenonmardones The URL is inaccessible

**Comment by mike-podolskiy90** [comment]
Please reopen this issue if it's still relevant
