### ISSUE TITLE
EML 2.2.0 testing

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/ipt#2473]
This will be a parent task for testing @gbif/dataproducts

**Comment by mike-podolskiy90** [comment]
https://github.com/gbif/eml-profile/issues/5

**Comment by mike-podolskiy90** [comment]
@gbif/dataproducts  Let's decide about `introduction` and `gettingStarted` inputs - should we move them to a separated page (Additional description, what would be the best name?) after the temporal coverage, as Marie suggested? Alternatively, we can move them to Additional Metadata or leave as they are.

**Comment by CecSve** [comment]
@mike-podolskiy90 will you set up an IPT instance so we can check the new layout? And would you prefer we just comment in this master issue or want us to link issues to this parent issue?

**Comment by mike-podolskiy90** [comment]
I'll try to deploy the updates to the UAT env and see how it works there. Otherwise, a local [IPT](https://repository.gbif.org/repository/gbif/org/gbif/ipt/3.0.7-SNAPSHOT/ipt-3.0.7-20240805.110930-49.war) installation needed

**Comment by mike-podolskiy90** [comment]
@CecSve I'd suggest creating new issues and link them to this one. Similar to https://github.com/gbif/ipt/issues/1975

**Comment by mike-podolskiy90** [comment]
Let me know when you start testing please. Others are testing on dev, so there might be a wrong war deployed to dev.

**Comment by CecSve** [comment]
> Let me know when you start testing please. Others are testing on dev, so there might be a wrong war deployed to dev.

I will begin testing today.
