### ISSUE TITLE
Unable to update metadata in a camtrap resource after updating an IPT

### ISSUE THREAD

**Issue by EstebanMH-SiB** [gbif/ipt#2474]
We created a camtrap [resource](https://ipt.biodiversidad.co/sibm/manage/resource.do?r=panthera_camtrap) when our IPT was in 3.0.3 version, we updated to 3.0.6 and now when we try to update the metadata it shows an unforeseen error (log information in the file).

[Unforeseen_error.txt](https://github.com/user-attachments/files/16515557/Unforeseen_error.txt)

Camtrap DP was in v1.0 in both instances of our IPT, so we do not know the reason for this problem

**Comment by mike-podolskiy90** [comment]
Thank you for contacting us.
I think this is similar https://github.com/gbif/ipt/issues/2414
I'll fix it

**Comment by mike-podolskiy90** [comment]
It's been fixed already actually https://github.com/gbif/ipt/issues/2457 but it has not been released yet

**Comment by mike-podolskiy90** [comment]
I'll make a new release shortly
