### ISSUE TITLE
A dedicated metadata page for `introduction`, `gettingStarted` and `purpose`

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/ipt#2475]

**Comment by CecSve** [comment]
I think the idea of having a dedicated tab for this makes sense. The additional description sounds fine to me, but I think it should be under the basic metadata tab since the content goes together with the description. It should be more clear somehow which content belongs where.

**Comment by ManonGros** [comment]
@CecSve should we also add `purpose` under the same "additional description" group?

**Comment by mike-podolskiy90** [comment]
That's exactly what I was thinking. If we move those two (I already deployed to UAT) we should also move `purpose`. They're grouped together in EML.
