### ISSUE TITLE
More user-friendly information on or integration of HTML tags?

### ISSUE THREAD

**Issue by CecSve** [gbif/ipt#2477]
Feedback for https://github.com/gbif/ipt/issues/2473.

Currently, the help button/information button (?) lists the available HTML tags but if users are unfamiliar with HTML, then it can be a bit tricky to structure the text with it. I wonder if it could be possible to integrate buttons (like the code view button that currently exists) so the selected text can be structured within a more understandable tag, like clicking a small image with a list will create a list in code view

```
 <ul>
  <li>Coffee</li>
  <li>Tea</li>
  <li>Milk</li>
</ul> 
```

but the user will see the text view

- Coffee
- Tea
- Milk

and not have to bother with understanding HTML.

**Comment by mike-podolskiy90** [comment]
Yes, a regular rich-text editor would be better, but because of conversion to DocBook I did not manage to make it work stable.

**Comment by mike-podolskiy90** [comment]
We can try to implement that in the future as an improvement. I did not manage to make it work stable with all the conversions.
