### ISSUE TITLE
Description of fields as greyed out text in the text box prior to text input?

### ISSUE THREAD

**Issue by CecSve** [gbif/ipt#2478]
Feedback for https://github.com/gbif/ipt/issues/2473.

Since the new EML profile will have `Description`, `Introduction` and `Getting Started` which may have overlapping content (or at least this can confuse the publisher with what goes where), would it be possible to have the first lines of the ? text (where the content is described) as greyed-out text within the text box before data input? Then the explanation would be visible to users when they try to sort out what content to put in which field.

might be relevant for this issue as well https://github.com/gbif/ipt/issues/2475.

**Comment by mike-podolskiy90** [comment]
I've deployed a new version with simple text descriptions. I suppose you'd like it to have a bit of styling. If so, please point me out how it's supposed to look like.

**Comment by CecSve** [comment]
Maybe smaller text, grey text color and in italics? Just to reduced the amount of space it takes up and make it nice-to-read and not need-to-read.

**Comment by mike-podolskiy90** [comment]
Deployed
