### ISSUE TITLE
Salutation not copied over to resource creators

### ISSUE THREAD

**Issue by CecSve** [gbif/ipt#2479]
Feedback for https://github.com/gbif/ipt/issues/2473.

Currently, the salutation is not copied if you copy contact information to the resource creators section. Should it?
It should of course not be included in the citation text for the roles that get included in the citation.

It is possible to list one salutation in the resource creator and another in the contact info. Would it not be better if it was consistent across sections?

**Comment by mike-podolskiy90** [comment]
Thanks Cecilie.
Yes, salutation should be copied.
Yes, it's possible to have different salutation, it's up to users to decide I suppose.
