### ISSUE TITLE
Project data - related projects: should it be possible to add identifier of related projects?

### ISSUE THREAD

**Issue by CecSve** [gbif/ipt#2480]
Feedback for https://github.com/gbif/ipt/issues/2473.

Would it be possible to include an identifier field in the `related projects` section of `project data`? If a publisher keeps these identifiers stable, it might be a valuable way to link projects/datasets in GBIF.

**Comment by mike-podolskiy90** [comment]
Yes, thnaks. I've missed that

**Comment by mike-podolskiy90** [comment]
Thanks. Deployed
