### ISSUE TITLE
EML file cannot be replaced

### ISSUE THREAD

**Issue by rubenpp7** [gbif/ipt#2483]
Hi, 

I'm trying to replace the metadata file in https://ipt.vliz.be/upload/resource.do?r=2010_phd_reubens

But I get the following Error message:
`Failed to replace the metadata file: Validation failed org.xml.sax.SAXParseException; lineNumber: 6; columnNumber: 16; cvc-complex-type.3.2.2: Attribute 'xsi:schemaLocation' is not allowed to appear in element 'eml:eml'.`

File I'm trying to add:
https://www.vliz.be/en/imis?module=dataset&dasid=5846&show=eml

is this related to a bad formatting of the EML file or to the IPT?

Thank you for checking!!

**Comment by mike-podolskiy90** [comment]
Thank you for contacting us @rubenpp7 
I'll have a look

**Comment by mike-podolskiy90** [comment]
It seems this one is wrong:
```
xmlns:xsi="https://www.w3.org/2001/XMLSchema-instance" 
```

should be `http` instead:
```
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
```

Apart from that, I think EML is invalid, some required fields are missing (it failed validation at https://knb.ecoinformatics.org/emlparser/)

**Comment by rubenpp7** [comment]
Thanks a lot @mike-podolskiy90 I'll close the issue and take it from here :)
