### ISSUE TITLE
EML 2.2.0 testing - Pasting text from website keeps formatting

### ISSUE THREAD

**Issue by ManonGros** [gbif/ipt#2495]
If I am pasting something I found online that's formatted with html into one of the "description" fields, the formatting is kept (with all the HTML tags) and then I get and error when trying to save the metadata.

For example:
pasting this:

<img width="1037" alt="Screenshot 2024-08-20 at 11 54 24" src="https://github.com/user-attachments/assets/04dbbb6e-5916-4dcf-999b-c0bbc47dfc90">
<img width="1055" alt="Screenshot 2024-08-20 at 11 54 29" src="https://github.com/user-attachments/assets/3eba9293-6169-42e5-877b-5f31b2f2b958">

I would have expected that pasting a text would be stripping it of its formatting. Maybe it should? I guess it relates to https://github.com/gbif/ipt/issues/2482

Also: https://github.com/gbif/ipt/issues/2473

**Comment by mike-podolskiy90** [comment]
I think we need to add a better explanation that HTML should be simplified without additional styling and elements etc. It would be quite time consuming to process/clean everything.

**Comment by mike-podolskiy90** [comment]
Closing for now.

**Comment by mike-podolskiy90** [comment]
related #2473
