### ISSUE TITLE
EML 2.2.0 testing - Unforeseen error

### ISSUE THREAD

**Issue by ManonGros** [gbif/ipt#2497]
When I try to save the project data of this dataset: https://eml-ipt.gbif-uat.org/manage/metadata-project.do?r=another-test-marie, I get this error:
> Index 1 out of bounds for length 1

**Comment by mike-podolskiy90** [comment]
Thanks. This is a bug, fixing

**Comment by mike-podolskiy90** [comment]
related #2473
