### ISSUE TITLE
EML 2.2.0 testing - comparing EML from IPT to EML accessible from API

### ISSUE THREAD

**Issue by ManonGros** [gbif/ipt#2498]
For this dataset https://www.gbif-uat.org/dataset/d2013cd8-ebeb-4320-90c3-d57469369d87
The API adds a role to the contact of the related project.
In the EML coming from the IPT we have:

```
            <relatedProject id="TEST2">
                <title>Hello</title>
                <personnel>
                    <individualName>
                        <surName>another test</surName>
                    </individualName>
                    <role></role>
                </personnel>
            </relatedProject>

```

While the EML accessible via the API shows

```
                    <relatedProject id="TEST2">
                        <title>Hello</title>
                        <personnel>
                            <individualName>
                                <surName>another test</surName>
                            </individualName>
                            <role>ADMINISTRATIVE_POINT_OF_CONTACT</role>
                        </personnel>
                    </relatedProject>
```

Another difference I noticed (and I think it isn't very important) is that the IPT puts country codes in the EML and the API spells out the country names. For example, `<country>FR</country>` in the IPT-generated EML and <country>FRANCE</country> in the API one.

**Comment by mike-podolskiy90** [comment]
`FR` vs. `FRANCE` doesn't matter I think, both are valid values.

**Comment by mike-podolskiy90** [comment]
Dataset's EML is invalid though, I thought I added a validation when publishing. Odd.

**Comment by mike-podolskiy90** [comment]
This seems fine, closing

**Comment by mike-podolskiy90** [comment]
related #2473
