### ISSUE TITLE
Updating a dataset failed due to "An error of type REGISTRY"

### ISSUE THREAD

**Issue by fujiokae** [gbif/ipt#2514]
While updating multiple datasets, one of the datasets failed due to "An error of type REGISTRY". The others were successful, so not sure why only one dataset didn't get updated successfully. I tried deleting this dataset from our IPT and GBIF but it failed as well. Then, I tried deleting this dataset from our IPT only then republished it. But the same problem with the same key.

Log messages:

    10:42:21 Archive generation started for version #6.7
    10:42:21 Start writing data file for Darwin Core Occurrence
    10:42:22 Data file written for Darwin Core Occurrence with 3 records and 85 columns
    10:42:22 All data files completed
    10:42:22 EML file added
    10:42:22 meta.xml archive descriptor written
    10:42:22 Validating the core file: occurrence.txt. Depending on the number of records, this can take a while.
    10:42:22 ? Validating the core basisOfRecord is always present and its value matches the Darwin Core Type Vocabulary.
    10:42:22 ? Validating the core ID field occurrenceID is always present and unique.
    10:42:22 ✓ Validated each line has a occurrenceID, and each occurrenceID is unique
    10:42:22 ✓ Validated each line has a basisOfRecord, and each basisOfRecord matches the Darwin Core Type Vocabulary
    10:42:22 Archive validated
    10:42:22 Archive has been compressed
    10:42:22 Archive version #6.7 generated successfully!
    10:42:23 An error of type REGISTRY was encountered during publishing: There was an error in GBIF Registry update – Update resource registration failed [shortname=zd_767_1deg, key=bf446a9b-11ac-4c57-b863-90a6bef9745c]: HTTP/1.1 400 Bad Request.

**Comment by fujiokae** [comment]
While updating multiple datasets, one of the datasets failed due to "An error of type REGISTRY". The others were successful, so not sure why only one dataset didn't get updated successfully. I tried deleting this dataset from our IPT and GBIF but it failed as well. Then, I tried deleting this dataset from our IPT only then republished it. But the same problem with the same key.

Log messages:

    10:42:21 Archive generation started for version #6.7
    10:42:21 Start writing data file for Darwin Core Occurrence
    10:42:22 Data file written for Darwin Core Occurrence with 3 records and 85 columns
    10:42:22 All data files completed
    10:42:22 EML file added
    10:42:22 meta.xml archive descriptor written
    10:42:22 Validating the core file: occurrence.txt. Depending on the number of records, this can take a while.
    10:42:22 ? Validating the core basisOfRecord is always present and its value matches the Darwin Core Type Vocabulary.
    10:42:22 ? Validating the core ID field occurrenceID is always present and unique.
    10:42:22 ✓ Validated each line has a occurrenceID, and each occurrenceID is unique
    10:42:22 ✓ Validated each line has a basisOfRecord, and each basisOfRecord matches the Darwin Core Type Vocabulary
    10:42:22 Archive validated
    10:42:22 Archive has been compressed
    10:42:22 Archive version #6.7 generated successfully!
    10:42:23 An error of type REGISTRY was encountered during publishing: There was an error in GBIF Registry update – Update resource registration failed [shortname=zd_767_1deg, key=bf446a9b-11ac-4c57-b863-90a6bef9745c]: HTTP/1.1 400 Bad Request.

**Comment by ManonGros** [comment]
@fujiokae it looks like the dataset that you are trying to publish is deleted on GBIF's side: https://www.gbif.org/dataset/bf446a9b-11ac-4c57-b863-90a6bef9745c. I could restore it and you could try again. Should we try?

**Comment by ManonGros** [comment]
Hi @fujiokae I forgot to notify you that I have restored the dataset. Could you try clicking on the publish button? Thanks!

**Comment by fujiokae** [comment]
I was able to republish it successfully. Thank you for your support!
