### ISSUE TITLE
Add logo for Camtrap DP resources

### ISSUE THREAD

**Issue by EstebanMH-SiB** [gbif/ipt#2524]
It would be nice if ww could add a logo for the publishing organizations in hte new data models, to keep consistency with the other resources 
![image](https://github.com/user-attachments/assets/47fc433d-dc5c-42d3-b320-e47d2fbc1ef1)

**Comment by peterdesmet** [comment]
There is a property for it in the metadata (`image`), which is available via Basic Metadata:

<img width="445" alt="Screenshot 2024-09-19 at 16 24 46" src="https://github.com/user-attachments/assets/f9a7d9ee-e3b5-4651-9171-da89c15d2004">

However:

- It currently requires an URL, without the possibility to upload a logo
- I don't know if it is used as the resource logo in the overview

@mike-podolskiy90 if this is supported, please use the `image` property.

**Comment by mike-podolskiy90** [comment]
Thank you @EstebanMH-SiB and @peterdesmet 
I'll check it out

**Comment by mike-podolskiy90** [comment]
Just checked - we already use the image property. If you add a resolvable URL it will be displayed at the home and the resource pages.
