### ISSUE TITLE
Rewrite introduction to sampling event data 

### ISSUE THREAD

**Issue by CecSve** [gbif/ipt#2525]
Feedback on [Sampling Event Data](https://ipt.gbif.org/manual/en/ipt/latest/sampling-event-data) ([Github source for this page](../blob/master/docs/en/modules/ROOT/pages/sampling-event-data.adoc))

The [introduction](https://ipt.gbif.org/manual/en/ipt/latest/sampling-event-data#introduction) of sampling event is not very clear and parts of it are technically not correct.

I propose to change most of the text to the first paragraph on [this page](https://www.gbif.org/sampling-event-data).

**Comment by mike-podolskiy90** [comment]
Thanks Cecilie
Feel free to submit a pull request if you think the documentation is not clear or incorrect. Here's the page https://github.com/gbif/ipt/blob/master/docs/en/modules/ROOT/pages/sampling-event-data.adoc
