### ISSUE TITLE
Inferring coverage with multiple mappings

### ISSUE THREAD

**Issue by ManonGros** [gbif/ipt#2548]
One of our publishers recently reported on helpdesk the following issue.

They changed a dataset from occurrence to sampling event by remapping the data. After doing so, they tried to infer the geographic coverage but they get this error:
![Image](https://github.com/user-attachments/assets/f26f5944-9e6a-43d4-8742-486147bee9eb)

The coordinates are mapped to the event core.

**Comment by mike-podolskiy90** [comment]
Thanks Marie. I'll have a look

**Comment by mike-podolskiy90** [comment]
I haven't managed to reproduce the issue, it seems fine on test IPTs
Let's try to get their IPT logs

**Comment by mike-podolskiy90** [comment]
So the problem is they have both Event and Occurrence mapped (Event as core and Occurrence as extension). Coordinates mapped only in Event, but not in Occurrence.

**Comment by mike-podolskiy90** [comment]
Quick fix is to map the coordinates in the occurrence mapping.
I'll add a fix to the IPT to properly handle this situation in the next release.

**Comment by mike-podolskiy90** [comment]
There are also similar issues for taxonomic and temporal coverages. I'll address them here.
