### ISSUE TITLE
can't login with my admin user/password..

### ISSUE THREAD

**Issue by guti181** [gbif/ipt#2560]
I'm trying to login with my configured admin user/password, but it fails.. (See below the configuration from users.xml)
Have also tried to add new user, and also - failed to login
I've restarted my Tomcat properly (admin privilege)

Pls advise. Thx !

```
<users> <user email="yaelgut@savion.huji.ac.il" password="****" firstname="Yael" lastname="Gutreich" role="Admin" lastLogin="2024-09-11 12:56:17.106 UTC"/> </users>

**Comment by mike-podolskiy90** [comment]
Thank you for contacting us.

Password is encrypted in users.xml, please make sure you use this https://ipt.gbif.org/manual/en/ipt/latest/faq#how-do-i-reset-the-admin-password

**Comment by guti181** [comment]
Thx Mike !
I've just manage..  totally forgot it's encrypted . . 
Have encrypted me a new one and it's working now
