### ISSUE TITLE
DP schema enumeration order lost

### ISSUE THREAD

**Issue by mdoering** [gbif/ipt#2568]
When mapping vocabularies from DP schemas the ordering is lost.
E.g. ranks in NameUsage ColDP

**Comment by mike-podolskiy90** [comment]
Thanks.
Should we preserve the order from the source vocabulary? Or sort alphabetically?

**Comment by mike-podolskiy90** [comment]
I suppose we should just preserve the initial order

**Comment by mdoering** [comment]
please preserve the original order

**Comment by mike-podolskiy90** [comment]
deployed
