### ISSUE TITLE
Published ColDP resource shows as not published

### ISSUE THREAD

**Issue by mdoering** [gbif/ipt#2571]
https://ipt.gbif-uat.org/resource?r=clements
![Image](https://github.com/user-attachments/assets/11f962ff-d567-4d9a-b8b1-22d82d3ebde1)

Also says no records, maybe that's related:
![Image](https://github.com/user-attachments/assets/b4a355de-6db0-4a9e-96af-9519f14f1091)

I think we should just sum up all published records no matter what entity they were for a global count.

**Comment by mike-podolskiy90** [comment]
How do we count records for a ColDP resource?

**Comment by mdoering** [comment]
I would suggest to count the total records of all data files as the default for any DP resource. There is no core any longer...

**Comment by mike-podolskiy90** [comment]
Okay, thanks. For Camtrap we take the number of observations

**Comment by mike-podolskiy90** [comment]
deployed
