### ISSUE TITLE
Unforseen error when trying to publish a dataset (EML parsing)

### ISSUE THREAD

**Issue by ahahn-gbif** [gbif/ipt#2575]
see https://ipt.sibbr.gov.br/sibbr/resource?r=pab-eta-pirai

The publisher writes:
"We published the dataset with a license correctly. Choosing a license is mandatory. So, the dataset is public with a license but not able to register through gbif - https://ipt.sibbr.gov.br/sibbr/resource?r=pab-eta-pirai. And also I can't download the eml. 

ERROR 31-Oct-2024 14:48:42 [org.gbif.ipt.action.portal.ResourceAction] - EML file version #1.14 for resource pab-eta-pirai couldn't be parsed
ERROR 31-Oct-2024 14:49:49 [org.gbif.ipt.action.portal.ResourceAction] - EML file version #1.14 for resource pab-eta-pirai couldn't be parsed
ERROR 31-Oct-2024 14:53:04 [org.gbif.ipt.action.portal.ResourceAction] - Invalid contact: fullname and/or organization not present. Check the metadata
ERROR 31-Oct-2024 14:53:24 [org.gbif.ipt.action.portal.ResourceAction] - EML file version #1.14 for resource pab-eta-pirai couldn't be parsed

Original email trail on helpdesk - forwarding latest email to @mike-podolskiy90 to enable direct contact.

**Comment by mike-podolskiy90** [comment]
Thanks Andrea, I'll have a look

**Comment by mike-podolskiy90** [comment]
IPT is not the latest, 3.0.1. So it's not related to the EML update at least

**Comment by mike-podolskiy90** [comment]
The problem is with the presence of the Unicode symbol U+0002 (Start of text). After removing it, the resource works fine.
