### ISSUE TITLE
how to improve preview tables readability (desktop)

### ISSUE THREAD

**Issue by abubelinha** [gbif/ipt#2576]
This happens to me in at least two different situations:

- ipt_url/manage/source.do?r=dataset_name&id=datasource_name
  Then I click dropdown Options and select "Preview"

- ipt_url/manage/resource.do?r=dataset_name#anchor-mappings
  Then I click the "eye" (Preview) icon of a mapping (i.e. DwC occurrences)

In both cases, a table pops up but usually it has many more columns than those fitting in my browser window.
So I miss many of them which are supposed to be hidden towards the right side of the table.

When I click on the table it closes. So I have no idea of how to drag the table in order **to browse those hidden columns**.
Well, **there is a way but it is rather useless**:
1. There is a right side vertical scroll bar which lets me drag towards the end of the table. 
   But as soon as I start this dragging, all column headers disappear.
2. That way I can go down to the end of the table, and there I can see a horizontal scroll bar
3. Then I can navigate towards right columns of the table, but this is useless because I can't see the column headers anymore.

#### Are there any solutions for this? **Some ideas:**
- Is there any mouse-keys combination which lets me move towards right side of the table without clicking it or using the bottom scroll bar?   (so I don't need to go down and loose headers). Maybe this is already possible but I don't know how to do it.
- Another possibility would be having a **fixed header** (which does not disappear when scrolling down).
- Perhaps if I could **preview only one a few rows**, I would see the bottom scroll bar without having to scroll down first.
- Perhaps if the div size (I mean the container for that table) fits browser window limits and has its own **scrolling bars visible at any time**? (no idea of css, just wondering)
- In any case, **repeating all headers as footers** would be a quick solution with current design (so at least we can see column names when reaching step 3 above).  

And for readability, when browsing a big table I find helpful having some **tiny** column and row **boundaries**. 

Thanks !
@abubelinha

**Comment by mike-podolskiy90** [comment]
Thank you for the suggestions. I'll adjust stylings to make to more useful.
