### ISSUE TITLE
IPT public access: Failed

### ISSUE THREAD

**Issue by vechocho** [gbif/ipt#2591]
We have three IPT instances and in all the IPT public access appears as failed

![Image](https://github.com/user-attachments/assets/fdf689b5-c3fd-4612-b427-794146d1e862)

The URL's for the IPT installations are:

- https://patrimonio.ambiente.gob.ec/iptmae/
- https://patrimonio.ambiente.gob.ec/iptmae_test/
- https://patrimonio.ambiente.gob.ec/iptmae_permisos/

Someone has a similar problem?

**Comment by MattBlissett** [comment]
The site appears down from here, and from https://downforeveryoneorjustme.com/

https://check-host.net/check-http?host=patrimonio.ambiente.gob.ec shows it working in the USA and Brazil, but nowhere else.  It could be an issue with your institution's firewall or network.

**Comment by vechocho** [comment]
I just check the IPT and the server is up here and there is no firewall for the webpage.

**Comment by MattBlissett** [comment]
Unfortunately the server is still not accessible from most of the world, including Denmark.  This is probably something your IT department or network team will need to investigate.

See https://check-host.net/check-http?host=patrimonio.ambiente.gob.ec or https://www.uptimia.com/website-availability-test/141e8f6f or https://www.site24x7.com/tools/check-website-availability.html

**Comment by vechocho** [comment]
We don't have any block from here, we don't know what else to do.

**Comment by MattBlissett** [comment]
I can access http://mail.ambiente.gob.ec, though it redirects to https://mail.ambiente.gob.ec which is blocked by a firewall.

I cannot access either http://patrimonio.ambiente.gob.ec or https://patrimonio.ambiente.gob.ec

This is nothing to do with the IPT, it is a network problem. You need to ask your IT department or network administrators; the people who control your IP range 190.152.46.0/24, for help. That might be cnt.gob.ec.

GBIF's servers are in 130.225.43.0/24, which is present on the internet as part of Denmark's academic network, [AS1835](https://ipinfo.io/AS1835)

**Comment by vechocho** [comment]
I just talk with my IT and they told me that they dont have any special firewall for the domain and it is published and propagated. 

 ![Image](https://github.com/user-attachments/assets/56af2dd6-3551-4849-a6fc-2342e846f91f)
![Image](https://github.com/user-attachments/assets/dd835ea2-56bf-4676-ba54-f313c692648b)

I dont know what else to do.

**Comment by MattBlissett** [comment]
Have you shown them the public testing page I've been using, for an HTTP connection (port 80) https://check-host.net/check-http?host=patrimonio.ambiente.gob.ec ? It clearly has many red entries for your server.

I can connect to an Alfresco service running on http://patrimonio.ambiente.gob.ec:8080/, but I cannot connect to http://patrimonio.ambiente.gob.ec/ (port 80) or https://patrimonio.ambiente.gob.ec/ (port 443).

The public checker also reports being able to connect on port 8080: https://check-host.net/check-http?host=patrimonio.ambiente.gob.ec%3A80 but not port 80.

**Comment by MattBlissett** [comment]
https://downforeveryoneorjustme.com/patrimonio.ambiente.gob.ec also reports the site is down.

**Comment by vechocho** [comment]
Can you have a look to the SSL certificate? the only thing that change is that te ssl certificate was updated on November 5.

**Comment by MattBlissett** [comment]
I cannot connect at all, so I don't see any certificate.

I'm sorry, but there is nothing more I can do. This is not a problem with the IPT, it is a problem with your institution's network, or your ISP, or a very strange setting that's on your server (TTL, net.ipv4.ip_default_ttl?).

Please show https://check-host.net/check-http?host=patrimonio.ambiente.gob.ec to your IT people and work with them to see why most locations show  "Connection timed out" errors.

![Image](https://github.com/user-attachments/assets/b28e5669-75f6-48d8-ae04-698b48a74481)

**Comment by vechocho** [comment]
I just take off the SSL from the webpage and it works normally. I'll try to see what happen whit the SSL next year.

**Comment by vechocho** [comment]
@MattBlissett There is a way to share with you my ssl certificate or something so you can take a look and see if there is some problem, as we cannot been acceded outside our country.

**Comment by vechocho** [comment]
It appear that the regsitry knows that a change was made on the metadata but is not updating the information: 

See: https://www.gbif.org/dataset/7482c011-1692-412d-a87c-220a579ccfd2

**Comment by ManonGros** [comment]
@vechocho as far as I can tell, the archive is still not accessible for our system. Which metadata changes can you see?

**Comment by vechocho** [comment]
I updated the whole resource 

[dwca-aves-pambilar-v2.3.zip](https://github.com/user-attachments/files/18522273/dwca-aves-pambilar-v2.3.zip)

**Comment by dnoesgaard** [comment]
Came across this issue following a DOI of dataset: https://doi.org/10.60545/z1ri5q

This redirects to http://patrimonio.ambiente.gob.ec/iptmae/resource?r=checklist-pnll

Which in turn requires authentication for access :(

I will need to review the DOI agreement if this persists...

**Comment by mike-podolskiy90** [comment]
@vechocho

**Comment by vechocho** [comment]
It's a problem with the https that I can't not make people for the it department to fix. 

If you put http://patrimonio.ambiente.go b.ec/iptmae/r esource?r= checklist-pnll without the https it let you go to the ipt .

**Comment by dnoesgaard** [comment]
I think it was a browser issue for me as it was enforcing https. I'm able to get to the IPT via https://doi.org/10.60545/z1ri5q if I try an alternative browser.
