### ISSUE TITLE
Not able to upload a source data

### ISSUE THREAD

**Issue by spalp** [gbif/ipt#2593]
A strange new behaviour of the IPT: https://cloud.gbif.org/eca 
Browsers: Mozilla Firefox 132.0.2, Google Chrome 130.0.6723.117 (Official Build) (64-bit)

If within a single session, I delete a resource data and then try to upload a new dataset, the new dataset is not uploaded. I have to log in and log (and sometimes many times) before I get the file successfuly uploaded and visible.
The resouce is the following: https://cloud.gbif.org/eca/manage/resource.do?r=podujeva_wwtp

_Update_: And after a second deletion of the resource data, now I cannot upload anything anymore.

**Comment by mike-podolskiy90** [comment]
Thanks Salza for reporting the issue.

Could you clarify "upload a new dataset" does it mean a new file?

**Comment by spalp** [comment]
![Image](https://github.com/user-attachments/assets/ea4cbf55-0d4e-408a-a0e6-4fb535d0cde2)
Yes, clicking on the Add button, selecting the file, and then clicking on Upload does not upload a new file.

**Comment by mike-podolskiy90** [comment]
Thanks, I see. I don't have any issues in those browsers with uploading or deleting any types of the sources. So I am not sure what's wrong for you. Are there errors in the browser console please? (In Chrome F12 -> console)

**Comment by mike-podolskiy90** [comment]
Please try to restart your computer this often solves issues

**Comment by spalp** [comment]
In the end I found that it was the very single file I was trying to upload that 'did not want' to upload: [gbifdatasheet_Rexport_1-10,18-21,23.txt](https://github.com/user-attachments/files/17771742/gbifdatasheet_Rexport_1-10.18-21.23.txt).
I have no problems other .txt files, it is only this one.

**Comment by mike-podolskiy90** [comment]
I see. I'm wondering what could be wrong with it

**Comment by spalp** [comment]
What is even more interesting... That the excel that I created based on this .txt ([gbifdatasheet_UTF8_noinvisible_space_locality.xlsx](https://github.com/user-attachments/files/17772220/gbifdatasheet_UTF8_noinvisible_space_locality.xlsx)), can be uploaded and results in a complete DwC core archive: https://cloud.gbif.org/eca/resource?r=podujeva_wwtp&v=1.1 

However, a second version of the same .txt that the publisher sent (and I just slightly modified [gbifdatasheet_v2_UTF8_no-inv-space.txt](https://github.com/user-attachments/files/17772361/gbifdatasheet_v2_UTF8_no-inv-space.txt)) can be  uploaded and mapped correctly but results in a DwC without the occurrences (only with a metadata): https://cloud.gbif.org/eca/resource?r=podujeva_wwtp&v=1.2

**Comment by spalp** [comment]
[like]  Salza Palpurina reacted to your message:
________________________________

**Comment by spalp** [comment]
[like]  Salza Palpurina reacted to your message:
________________________________

**Comment by mike-podolskiy90** [comment]
I've added a UI check and a warning message. See https://ipt.gbif-uat.org/
I will include this issue in the next release.

**Comment by spalp** [comment]
[celebrate]     Salza Palpurina reacted to your message:
________________________________
