### ISSUE TITLE
Line breaks in description result in invalid archive

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#2612]
When the user adds a line break in a Camtrap DP description:

![Image](https://github.com/user-attachments/assets/1f164edc-07f6-4fc4-8f1a-949d8afe2bd9)

It is exported as an array in datapackage.json:

```json
"description": [
  "... reported at <a href=\"https://github.com/inbo/camera-trap-datasets/issues\">https://github.com/inbo/camera-trap-datasets/issues<\/a>.",
  "We have released this dataset to the public domain under a Creative Commons Zero waiver. We would appreciate it if ..."
],
```

This is invalid, since `description` needs to be a string value (see https://datapackage.org/standard/data-package/#description).

It is fine to retain empty lines in the description, but it should not create an array.

**Comment by mike-podolskiy90** [comment]
Thank you Peter, noted. I'll fix

**Comment by sannegovaert** [comment]
This might not be an IPT bug, we will research this and update this issue.

**Comment by mike-podolskiy90** [comment]
@sannegovaert Thank you, I'm closing then
