### ISSUE TITLE
IPT connection to Google Fusion Tables

### ISSUE THREAD

**Issue by kbraak** [gbif/ipt#693]
```
What feature would like to see being added to the IPT?

I use Google Fusion Tables to visualize and manage a dataset I have. It allows me to
geocode/georeference, map, filter and search, some of which are not dissimilar from
what the original IPT portal could do.
I'd like to publish this dataset as a Darwin Core Archive through IPT, and republish
it without remapping for updates.

Would it be possible to support a connection to Google Fusion Tables, next to text
uploads and database connections? The Google Fusion Tables API supports JDBC.
```

Original issue reported on code.google.com by `peter.desmet.cubc` on 2011-05-26 18:13:40

**Comment by peterdesmet** [comment]
Is any one using Google Fusion tables anymore? Is this still a desired feature? cc-ing @tucotuco @mdoering, would thought - just like me - that this would be a good idea.

**Comment by tucotuco** [comment]
We use Fusion Tables for some project management for VertNet, but we don't have any data sources that would end up being published through IPT from Fusion Tables.

**Comment by peterdesmet** [comment]
@kbraak I this could be marked as a `wontfix` until someone complains. 😄

**Comment by kbraak** [comment]
Thank you. I have done so now.
