### ISSUE TITLE
Improve import of existing DwcA when uninstalled extension

### ISSUE THREAD

**Issue by kbraak** [gbif/ipt#718]
```
What feature would like to see being added to the IPT?

For the moment, you can just create a resource by uploading an existing DwcA file into
an IPT instance that refers to extensions that are not installed in that instance.
You receive a warning message, but it does not make it very clear that without installation
of this extension, there will be a data loss between the original DwcA and the one
that will be published.

Could we imagine a message box saying that propose to automatically install the required
extension, and if the user refuse, make sure (s)he clearly understands that all the
source data will not be published. A more radical approach could be to simply refuse
the import as long as the needed extensions are not installed... Anyway, I just thing
we should have this debate at some point.

I don't know if these suggestions could bring unwanted complexity (for example, what
about extensions that have been updated between the creation of the original DwcA source
file and the import into another instance) ?

What do you think ?

Nicolas
```

Original issue reported on code.google.com by `niconoe` on 2011-06-21 14:25:46

**Comment by kbraak** [comment]
@peterdesmet with respect to this issue are you in favor of keeping things flexible, or making things more strict (e.g. rejecting the import if it includes an extension that hasn't been installed). Thanks for your opinion.

**Comment by peterdesmet** [comment]
@kbraak, did you mean to include @niconoe?

I agree with what you write at https://github.com/gbif/ipt/issues/718#issuecomment-100179868: refuse if extensions are not installed: that's the task of the administrator.

**Comment by kbraak** [comment]
Thanks Peter, I asked for your input on purpose. Of course if Nicolas wants to add anything more he is welcome.

**Comment by kbraak** [comment]
Change implemented: create resource via archive import will now be refused if archive refers to an extension that hasn't been installed yet. A warning is provided to the user recommending they seek help from the IPT admin to resolve the problem. Closing issue.

**Comment by kbraak** [comment]
After refusal, resource configuration folder and sources remain persisted - they should be cleaned up. Reopening.

**Comment by kbraak** [comment]
Issue verified.
