### ISSUE TITLE
Administration notes

### ISSUE THREAD

**Issue by kbraak** [gbif/ipt#791]
**What feature would like to see being added to the IPT?**

It would be useful to have a place to store administration notes and guidelines per resource. This would especially be useful for a a hosted IPT with one admin and a lot of managers, and where a resource has to be updated regularly.

The section could appear at the top of manage resource (see screenshot), and can contain guidelines and/or reminders. The field can be edited by any manager of the resource and is not visible to the public (only for admin purposes, not part of the published resource).

Clicking the edit button would change the text into a text area that can be edited. A save and cancel button would appear. The data could be stored in a IPT or resource properties file.

Original issue reported on code.google.com by `peter.desmet.cubc` on 2011-10-01 21:02:04

**Comment by mike-podolskiy90** [comment]
@peterdesmet would this feature be useful please? Or it's not relevant anymore?

**Comment by peterdesmet** [comment]
Adding (private) notes about a resource for collaborators seems like a nice to have feature, but I've not missed it either. So, I think this issue can be closed.
