### ISSUE TITLE
Download source file

### ISSUE THREAD

**Issue by kbraak** [gbif/ipt#818]
```
What feature would like to see being added to the IPT?

Currently, you can download the log file from the source page (/ipt/manage/source.do
- see screenshot), but it would be nice if you could download the source file itself
as well. It's path is already available. As it is on the management page, it would
only be accessible to logged in managers.
```

Original issue reported on code.google.com by `Peter.Desmet` on 2011-11-25 00:17:12

<hr>
- _Attachment: download-source.png<br>![download-source.png](https://storage.googleapis.com/google-code-attachments/gbif-providertoolkit/issue-818/comment-0/download-source.png)_

**Comment by MattBlissett** [comment]
Implemented in #1546 / #1488.
