### ISSUE TITLE
Write field occurrenceID/taxonID in generated DwC-Archive 

### ISSUE THREAD

**Issue by kbraak** [gbif/ipt#978]
```
John I have tried to capture your requirements below. Please revise what I have written,
and correct me if I am wrong.

What is the issue?
The DwC-Archive generated by the IPT never populates field occurrenceID or taxonID,
to avoid duplicating the content in the ID field ( <id index="0" /> ) which always
represents the occurrenceID or taxonID anyways.

What change is being proposed?
John, if I understand you correctly, you are simply asking for the field occurrenceID/taxonID
to be populated in the DwC-Archive. This is the simplest case, whereby the IPT's mapping
page would not have to change. For example, there would still only be a single occurrenceID/taxonID
field to map to, not 2 separate fields: occurrenceID/taxonID and ID. 

In the more complicated case, however, the mapping page would have to be adapted to
include 2 separate fields for the occurrenceID/taxonID and ID, allowing users to map
separate columns for both fields. 

Additional information?

We should double check the behavior of the dwca-reader library, specifically when importing
a DwC-Archive having both the ID and occurrenceID/taxonID mapped. Are both columns
preserved, or is the occurrenceID/taxonID overwritten?

What version of the provider software are you using? 
v2.0.5

```

Original issue reported on code.google.com by `kyle.braak` on 2013-05-24 14:54:05

**Comment by godfoder** [comment]
This behavior is broken for the case of importing data from externally generated darwin core archives into IPT.

Specifically the case where the "id" and "coreid" columns contains primary key values used exclusively to link the extensions to the core file, and the occurenceID field contains a proper GUID value.

The only way such archives can be imported into IPT is by dropping the extension files, or by manually munging the data, despite the fact that they are standards compliant and pass the GBIF DwC-A validator.

An example of such a dataset is attached.
[ASU-Seeds_DwC-A.zip](https://github.com/gbif/ipt/files/280322/ASU-Seeds_DwC-A.zip)

**Comment by kbraak** [comment]
Thanks for this comment Alex. 

In the IPT, the core record identifier always maps to the coreID and must be used to link source rows together. Indeed a DwC-A like the one you attached, that uses a coreID different to its core record identifier to link its source rows together, will not import properly. 

I'm sorry if the [GBIF DwC-A Validator](http://tools.gbif.org/dwca-validator/) gave you the impression this archive is valid, because it's not. There is this [open issue](http://dev.gbif.org/issues/browse/TOOL-5) to ensure it uses the latest extension versions. And I just opened [this issue](http://dev.gbif.org/issues/browse/TOOL-8) to ensure it reports the EML file isn't valid XML. 

As an apology for the faulty validator, please find my manual validation of this archive below where I name some of the problems I could spot. Hopefully this helps you clean other archives you are publishing. 

* The eml.xml does not validate
* Assuming the eml.xml is intended to use the GBIF Metadata Profile, it uses the wrong schema definition file: it uses [eml.xml](http://rs.gbif.org/schema/eml-gbif-profile/1.0.1/eml.xsd) but it should use [eml-gbif-profile.xsd](http://rs.gbif.org/schema/eml-gbif-profile/1.0.1/eml-gbif-profile.xsd). 
* The eml.xml uses an out of date schema version ([v1.0.1](http://rs.gbif.org/schema/eml-gbif-profile/1.0.1/) vs [v1.1](http://rs.gbif.org/schema/eml-gbif-profile/1.1/eml-gbif-profile.xsd) - the latest)
* The Occurrence mapping uses deprecated term dc:rights. [This](http://rs.gbif.org/core/dwc_occurrence_2015-07-02.xml) is the latest version of the Occurrence extension, with deprecated terms removed, and new terms added. The IPT allows you to update extensions automatically to the next version in case you weren't aware. 
* There are a suite of terms that don't exist in the extensions (see attached screenshot)
* The [Image extension](http://rs.gbif.org/extension/gbif/1.0/images.xml) is deprecated in favor of [Multimedia extension](http://rs.gbif.org/extension/gbif/1.0/multimedia.xml). This is explained in the extension description. 
* The identifications file has no records. 

![screen shot 2016-05-25 at 10 21 47](https://cloud.githubusercontent.com/assets/5981100/15534996/bfcadc64-226b-11e6-8421-2788ecc41158.png)

**Comment by danstoner** [comment]
@kbraak 

Could you divide your list of problems into true errors vs. warnings?

For example, I would expect 

> The eml.xml uses an out of date schema version (v1.0.1 vs v1.1 - the latest)

to be a warning or recommendation.


I can see a data provider taking actions on errors but not necessarily having the ability to immediately shift from deprecated extensions, for example.

Thanks.

**Comment by kbraak** [comment]
Hi Dan, 

The errors include XML that doesn't validate, and wrong XSD file used. 

This case demonstrates how difficult it is to manually create DwC-As and keep them up to date with the latest DwC terms. 

More information about how the IPT's update extensions feature works can be found [here](https://github.com/gbif/ipt/wiki/IPT2ManualNotes.wiki#update-extension) in the IPT User Manual. 

Thanks
