### ISSUE TITLE
Allow a dataset to be registered as part of a network

### ISSUE THREAD

**Issue by kbraak** [gbif/ipt#986]
```
In the GBIF registry, a dataset can be associated to a network. Currently, GBIF admins
add the dataset belongs-to<network> relationship. E.g. http://gbrds.gbif.org/browse/agent?uuid=7ddd1f14-a2b0-4838-95b0-785846f656f3

It would be better to automate this. Ideally, the IPT resource manager would be able
to add the belongs-to<network> during (or after) registration.  

I envision the IPT managing a list of networks, similar to how it manages a list of
organizations right now. 

Furthermore, we would need clear explanations guiding managers so that they know when
it is appropriate to associate their resource to a network.  

Additional information:

http://dev.gbif.org/issues/browse/PF-77 

Blocked on release of new registry API 


```

Original issue reported on code.google.com by `kyle.braak` on 2013-07-12 08:55:06

**Comment by jlegind** [comment]
With OBIS and SCAR looking to get in on the 'network' market, this could soon become a hot property.

**Comment by Antonarctica** [comment]
Hi Is ther any advancement on this?

This would indeed be an important advancement of network that go beyond country boundaries: SCAR, OBIS (of which I'm part) definitely, but I imagine others as well such as CAFF

**Comment by ManonGros** [comment]
Hi @Antonarctica, the Networks can now be curated from the GBIF Registry (which can accommodate for external editors).

As you might already know, we have one for OBIS: https://www.gbif.org/network/2b7c7b4f-4d4f-40d3-94de-c28b6fa054a6
If you would like to see some updates to this network, please contact us at helpdesk@gbif.org

Regarding other network: not everyone can request the creation of a new network. For more information, please contact helpdesk@gbif.org

**Comment by peterdesmet** [comment]
One issue with the helpdesk@gbif.org approach is that it is not well known and requires action separate from publishing the dataset. When publishing a dataset on Zenodo, you can search for communities (similar to GBIF networks) under which your dataset should appear. These trigger a request to the curators of those communities to either refuse or accept that dataset as part of their community. With the GBIF registry, I think a similar approach is possible directly from the IPT.

Example: https://zenodo.org/record/4299976, part of `Research Institute for Nature and Forest (INBO)`, `Open science lab for biodiversity` and `Tracking Invasive Alien Species (TrIAS)` networks (right hand sidebar)

**Comment by Antonarctica** [comment]
@ManonGros Thank you for the update as well as per e-mail. I agree with @peterdesmet that a system where data providers can somehow self-identify as belonging to a network would be a great appraoch. as a user, the Zenodo examples work very well, but as a person managing a community and publishing items belonging to different communities.

**Comment by dbloom** [comment]
I like this possibility. As a Node Manager and someone who helps
organizations publish their datasets, it would be more efficient to be able
to identify that dataset as a part of a network rather than having to
publish and then update the registry. I will admit that doing both is
neither time consuming nor difficult, but i'm always happy to reduce the
number of steps I need to take if I can.

Further, as a responsible party for the VertNet vertebrate network, it
would be amazing if publishers could opt-in to the vertebrate network if
they wish to do so, especially if we are not working with the publisher
directly. We plan to contact as many publishers with vertebrate data as
possible, but an opt-in possibility would be a time-saver for us moving
forward, especially if we were to receive a notification that a new dataset
has been added to the network - but I won't ask for unicorns and rainbows
just yet. I'll leave that up to @peterdesmet
<https://github.com/peterdesmet>.

**Comment by timrobertson100** [comment]
This was discussed again and seen as highly desirable by participants in the OBIS session of the GBIF global nodes meeting last night.

I'm adding this to the 2.5 stream so it will be explored for the 2.5.1 release (missed 2.5.0 now)

**Comment by timrobertson100** [comment]
@mike-podolskiy90  
Can you please explore the feasibility of getting this in the next IPT release, please? (i.e. the release this/next week)

I could imagine this be implemented in one of two ways:

1. On the resource management page, the user is presented with a form to (multi)select which networks the dataset participates in. When the DwC-A is generated, the keys of the chosen networks are added in the EML (´<additionalMetadata/>´ perhaps?) and this is linked up as we ingest.

2. The user is presented with the same form, prefilled with the existing state from the registry but any change hits the Registry API and makes the link immediately. This would only be enabled after the dataset is registered.

The benefit of 2, is that we'd always have strong consistency when external edits are applied and we wouldn't face the case of drift and need to reconcile edits in two places. A publisher _may_ link to a network, that the network "owner" challenges resulting in admin edits. A network may be created and we bulk assign datasets etc. I don't see any real benefit of having the GBIF network keys in EML. My feeling is 2. would be the simpler option.

CC @ahahn-gbif and @pieterprovoost

**Comment by peterdesmet** [comment]
I also support option 2. It is truly part of the registration process and should not require the dataset to be republished.

The multi is important, as datasets can be part of multiple networks.

**Comment by Antonarctica** [comment]
In Favour of option 2 as well. 

Also, networks may be formed after the dataset is published so would be good to be able to update that without republishing. 

+1 for multi-option, I'd even say it is essential.

**Comment by pieterprovoost** [comment]
Also in favour of option 2, thanks!

**Comment by mike-podolskiy90** [comment]
Draft version is deployed to https://ipt.gbif-uat.org/

**Comment by mike-podolskiy90** [comment]
closing this
